### ISSUE TITLE
Use PirateBay proxy site from list of sites instead of normal proxy services like hideme.nl

### ISSUE THREAD

**Issue by emzero** [SiCKRAGETV/sickrage-issues#1001]
TPB is blocked in my country and I find using proxy sites like hideme.nl pretty unreliable to access it.

I think it would be better to grab one TPB proxy site that's running, test if it works, if not, try another one, etc.

Here's the site I use: https://proxybay.info/
I don't know if it has some kind of API to get the sites, but if not, scrapping the HTML should be pretty straightforward.

**Comment by fernandog** [comment]
@abeloin can't we add a {provider}.proxy_custom setting in config.ini and an input in provider options so user can manually input a specific proxy for that provider? I couldn't make it work because I don't know how add the custom name and custom url "on the fly" to the "dropdown list". Or is there a better solution?

**Comment by abeloin** [comment]
@fernandog I think enabling the option to edit some provider hardcoded url maybe a good idea

**Comment by fernandog** [comment]
@abeloin like i said above or a list box with alternative urls from the provider?

**Comment by abeloin** [comment]
Will see if I can automate the list

**Comment by uskyrt** [comment]
That'd be helpful. At the moment I have to SSH and modify the provider files manually every time SR updates

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1381
