### ISSUE TITLE
Edit show: Unable to force an update on wanted episode

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#1025]
```
SR Version: 	BRANCH: (production-stage) / COMMIT: (0d137d62c2b8a5166c47ecc6c58643cadc76bea6)
Python Version:	2.7.5 (default, Nov 3 2014, 14:26:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]
```

When edit and save a show, I get this error notification:
`1 error while saving changes: Unable to force an update on wanted episode`

I don't use trakt, but SR don't do the check and end up running sickbeard.traktRollingScheduler.action.updateWantedList() in webserve.py#L1507.

This result in an notification error

**Comment by fernandog** [comment]
@gborri

**Comment by abeloin** [comment]
Problematic commit: https://github.com/SiCKRAGETV/SickRage/commit/6562e1149629806c83fb8eb83e296762c7f79fb4

**Comment by abeloin** [comment]
Also ended show are now shown active: https://github.com/SiCKRAGETV/SickRage/commit/6562e1149629806c83fb8eb83e296762c7f79fb4#diff-299def7cc64d1e463b2759b06a183432R615

**Comment by gborri** [comment]
@abeloin the behaviour is correct if rolling download is enabled. i will provide a fix in order to manage different behaviour if rolling download is enabled or not. 
The concept is that a show is active or paused not depending if ended or not. 
If the show is active rolling download feature is enabled on that showm otherwise if it is paused it is disabled.

**Comment by gborri** [comment]
@abeloin fixed. SiCKRAGETV/SickRage#1640

**Comment by abeloin** [comment]
@gborri Ok good to know
