### ISSUE TITLE
[Feature Request] Add progess bar when updating/scanning shows

### ISSUE THREAD

**Issue by cyberundertaker** [SiCKRAGETV/sickrage-issues#1044]
Is it possible to add a small progress bar when updating shows (either manually or automatically).
This would be nice especially when forcing full update on tv show so we don't have to press F5 to find out when it's done updating.
Something like this but with the name of the show currently being updated:
![bar](https://cloud.githubusercontent.com/assets/11670746/6857698/f6260516-d408-11e4-87ce-0e9e593716ca.png)

Also is it possible to have multiple shows updating at once instead one by one

**Comment by markheloking** [comment]
You can update multiple shows under manage->mass update.

I would also like to see a visual indicator showing the progress in updating since it can take such a long time.

If I'm correct, I believe echel0n already made the updating multithreaded, but I can be mistaken. I only discussed the implementation of such multithreading, and thread syncing between updating, searching, grabbing/snatching, etc. with echel0n and I believe he implemented some parts of it already, though I'm not entirely sure which parts.

**Comment by abeloin** [comment]
One of the problem with updating multiple show at the same time is that we might run into some api limitation(query per sec) from the indexer. We don't want to end up banned because we were hammering their system.

Also it's worth mentioning that because of the GIL(global interpreter lock) in cPython, you can't have more than 1 thread running byte-codes at the same time. This limit Python code to 1 CPU. So if SR use the CPU to 100% already when updating, you won't see any improvement. The way to overcome this is to use multiprocessing instead for cPython. I think Jpython and IronPython aren't limited by this because they don't use GIL.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
