### ISSUE TITLE
Error with Add Show Trending 

### ISSUE THREAD

**Issue by ticker18** [SiCKRAGETV/sickrage-issues#1059]
I have the same issue as https://github.com/SiCKRAGETV/sickrage-issues/issues/274

When I use "Add Show / Add Trending Show" it return this : Trakt API did not return any results, please check your config.

BRANCH: (master) / COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718) 

Line from the log
2015-03-29 09:09:18 WARNING  Thread-26 :: Could not connect to Trakt service: error 405 Client Error: Method Not Allowed

**Comment by fernandog** [comment]
@gborri confirm trakt changed method and needs to use Oauth or is it another error?

**Comment by gborri** [comment]
@fernandog i've tried either with develop or master and both are working correctly.

**Comment by Thraxis** [comment]
I was having the same error for over a week, which is why I wrote the OAuth code.  Looks like a wasted effort as I just tested this again in my code and after increasing the timeout it did start returning results.  Changed the API URL to the https://api-v2launch.trakt.tv URL and changed the timeout back to 30 seconds as the default and everything is working correctly.

**Comment by Thraxis** [comment]
@fernandog @gborri I can confirm Develop is working for trending shows I changed the API URL to the V2 URL and it is working fine.

I am getting one error in tracktChecker

2015-03-29 14:14:15 DEBUG    TRAKTCHECKER :: Syncing Trakt.tv show library
AA
AATypeError: int() argument must be a string or a number, not 'NoneType'

Which I already have the fix for in my Oauth code, going to fix that and let this shake out for a while to see if any other errors show up.  If not then the Oauth code might need to just be archived possible future reference.

**Comment by TagForce** [comment]
@Thraxis @fernandog @gborri Trakt is migrating the api to the new URL and deprecating the old V1 API calls... Apparently they are messing stuff up while doing this causing weird issues with calls that worked before... Everything should be done using the V2 url from now on.

**Comment by abeloin** [comment]
PR will be merge on Sunday

**Comment by Thraxis** [comment]
I just updated https://github.com/SiCKRAGETV/SickRage/pull/1676 final changes barring anything that shows up on my system between now and Sunday.

TracktChecker.py got a massive re-write but it now operates much faster and now does the collection  sync as well as the watchlist.

**Comment by abeloin** [comment]
@ticker18 Master updated, please test

**Comment by ticker18** [comment]
It's working now on my end after the update.
BRANCH: (master) / COMMIT: (c9a102608e37c4c6e24c595297af1add5677ef79)
