### ISSUE TITLE
Series with lots of blank episode titles has stopped updating

### ISSUE THREAD

**Issue by REDdimension** [SiCKRAGETV/sickrage-issues#1157]
In the python window I see:

"This episode has no name in TheTVDB
The episode was deleted, skipping the rest of the load."

This just started occurring in the last week or so, so must have been a recent change.
Running BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 
Python Version:	2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]

This is easy to replicate if you add "The Dr. Phil Show" from TVDB.  Lots of the earlier seasons are just blank, and this used to be no trouble fetching updates for the most recent episodes.  A recent modification to the code, though, has caused me to no longer get any updates even if I force a full update.

**Comment by fernandog** [comment]
@REDdimension screenshot? Did you checked tvdb data in their website?

**Comment by T-2000** [comment]
@fernandog I've asked about this on the TheTVDB forum section regarding their policies about episode information, what i received was the following answer:

> Our policy is to only have real information. Unless the episode is actually named Episode 1 it shouldn't be named that. Same goes for TBA, if the proper name isn't known the field should be blank. We'd rather no information over incorrect information. If a program doesn't work because of that the program should be adjusted to allow for it. If fake names like episode 1 are preferred a program can put them in automatically, there is no need to add fake information to the site.

TheTVDB forum topic can be found [here](https://forums.thetvdb.com/viewtopic.php?f=41&t=23086)

**Comment by miigotu** [comment]
These two issues are unrelated. This issue is due to a policy change on theTVDB, whereas "TBD" and "Episode #" used to be tolerated as episode names in the DB, and they have recently disallowed this.

The best solution would be for you to contribute to theTVDB by adding the episode names, rather than fixing it in SR.

Although, SR SHOULD still snatch and process episodes that have an unknown title. I will have a look at it sometime soon.

Do you think it acceptable for the episode title to appear in SR (and Kodi) as "Unknown" when it is blank on theTVDB?

**Comment by T-2000** [comment]
I'm thinking it would, the episodes have their numbering for identifying them. I do wonder if the post processor allows for episode renaming once files have been imported and the episode name has actual information. All related content would need renaming as well, thinking of nfo and episode thumbnail files.

**Comment by fernandog** [comment]
Unknown its fine to me

**Comment by Thraxis** [comment]
I've had "TBA", "Episode x" and I think "Unknown" before they made the policy change.  Of the three I lean towards "Episode x" as that at least differentiates between episodes.

**Comment by miigotu** [comment]
I still would like to do some testing to confirm that this is not just happening with episodes that are not released yet. Before, whenever I saw TBD in the show list, it was an unreleased episode. If it only happening with episodes that are not released yet, SR is acting as it should.

**Comment by fernandog** [comment]
@Thraxis agree. Also we have the episode number so no problem setting as "Episode x"

**Comment by fernandog** [comment]
@miigotu did you do any tests with this? thanks!

**Comment by miigotu** [comment]
@fernandog I didn't have time to work on anything yesterday, I'll try and look into it tonight.

**Comment by fernandog** [comment]
@miigotu can I add this to this sunday milestone or to Apr 28 milestone?

**Comment by miigotu** [comment]
@fernandog I would say at least Apr 28. SR is correct to "Skipping the rest of the load" as there is no more information to load anyways.  The problem is that if we process it, the file name ends up being without a title, and gets added to the kodi db, and then when the info is added to tvdb later it is more difficult to change the name of the files.

I still think the best policy here would be to direct affected users to add the missing information to tvdb themselves, rather than doing a hacky workaround in SR. It isn't too much to ask because anyone can do it and it benefits theTVDB and everyone who uses it and it gives them a way to contribute back.

**Comment by fernandog** [comment]
@TagForce thoughts on this one?

**Comment by TagForce** [comment]
@fernandog I'm with miigotu on this one... It's not a problem within SR, or with the user, it's a problem that exists in a 3rd party tool that we happen to use... If users have a way of fixing it themselves, why not have them do it. Generates income for the guys at TVDB because they get more hits (even if it's only a couple) and it makes the data provided by it more consistent. win win win situation, I think. We don't need to code a workaround, and they get more complete data and more unique visitors, and the users can fix their issue for themselves and anyone else watching that show.

**Comment by fernandog** [comment]
@TagForce but what about the user's issue that show is not being update all the other's episodes?

**Comment by TagForce** [comment]
@fernandog If it's actually skipping all episodes after finding one without a name, then yes, that should be addressed. I think @miigotu said as much. SR should skip the episode without an episode, but it should still process the remaining episodes that DO have a name.

**Comment by miigotu** [comment]
Yeah it doesn't skip the load for ones that have a name on theTVDB afaik, or we would have many more reports of this. Episodes without a name are usually episodes just aired in the past half hour (rarely) or are not yet aired. The case reported in this issue is when a show is really old or not popular enough for people to have added the info to theTVDB, which is why I think the answer is to have the OP, and others affected simply add the correct info to theTVDB to help further theTVDB progress.
