### ISSUE TITLE
SickRage recently ignoring torrents

### ISSUE THREAD

**Issue by rcodddow** [SiCKRAGETV/sickrage-issues#1163]
Quality of Backstrom.S01E10.HDTV.x264-ASAP is SD TV
Ignoring Backstrom.S01E10.HDTV.x264-ASAP because its not a valid scene release that we want

**Comment by Thraxis** [comment]
### SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)<br />
Please include the following when opening a new ticket:
 - Branch
 - Commit hash
 - Your operating system and python version
 - What you did
 - What happened
 - What you expected
 - Link to a copy/paste of your logfile with clear debug info of the error on [GIST](http://gist.github.com)

**Comment by rcodddow** [comment]
Sorry about that 

Branch : master
Commit Hash : 669046ea40a7a26a6121a1b07721f3c1c3cf5b10
operating system and python version: OSX 10.10.2 & 10.10.3, Python 2.7.9
What I did: Upgrade to newest version
What happened: After upgrading, torrents are no longer downloaded for any list show
I expected : That these torrents pass the validation process
Gist: no gist, because this is unexpected behaviour

**Comment by TagForce** [comment]
@rcodddow We need debug logs...
The message "Ignoring Backstrom.S01E10.HDTV.x264-ASAP because its not a valid scene release that we want" is only generated in one point in the code:
```
if not show_name_helpers.filterBadReleases(cur_result.name, parse=False):
            logger.log(u"Ignoring " + cur_result.name + " because its not a valid scene release that we want, ignoring it",
                       logger.INFO)
```
Seeing as filterBadReleases is called using parse=false, the only checks left are for Ignore words, and require words.
```
if sickbeard.IGNORE_WORDS:
        ignore_words.extend(sickbeard.IGNORE_WORDS.split(','))
    word = containsAtLeastOneWord(name, ignore_words)
    if word:
        logger.log(u"Invalid scene release: " + name + " contains " + word + ", ignoring it", logger.DEBUG)
        return False

    # if any of the good strings aren't in the name then say no
    if sickbeard.REQUIRE_WORDS:
        require_words = sickbeard.REQUIRE_WORDS
        if not containsAtLeastOneWord(name, require_words):
            logger.log(u"Invalid scene release: " + name + " doesn't contain any of " + sickbeard.REQUIRE_WORDS +
                       ", ignoring it", logger.DEBUG)
            return False
```
If either case is true, it will log which of the tests was positive by adding a line to the debug log.
So, it's safe to say that it's either ignore or required words that causes stuff to be rejected. At least check those in your setup. If that doesn't fix it, show us the logs from the entire search (20+ lines before and after the rejection message), so we can look for a cause of this.
