### ISSUE TITLE
[Feature Request] Improve Process method: symlink and hardlink

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#1179]
Both method need to be change to better handle error(eg: moveAndSymlinkFile the try block check both move and symlink so we don't know which one failed)
This way we detect link failure before doing any copy or move

**Comment by rjrudman** [comment]
Thinking about this; we might be able to be a bit more efficient with our moves and copies.  

Is it correct to assume that most people using symlinks would be doing so over separate partitions (otherwise hardlink is a better choice?).

I'd propose the way symlinks works is as follows (as default or if we detect that the source and destination are on separate partitions);
1. Copy the file to the new destination
1a. If copy fails, operation fails
2. Move source to source_temp (or randomly generated name)
2a. If move fails, operation exits (as a success with warning)
3. Make a symlink from destination to source
3a. If symlink fails, rename temp file back to source. Operation exits with success and warning
4. Remove temp file. Success.

This process eliminates the need for a second copy if the link/move fails, which is not extremely unlikely, as many torrent applications lock their files.

Further, we can have a check to see if source and destination are on the same partition. In that case, we can do what we have already; Move (copy on fail), symlink (copy back on fail). 

Any thoughts or something I've missed?

**Comment by abeloin** [comment]
And don't forget it most work on Linux, Mac and Windows

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
