### ISSUE TITLE
Issue submitter open issues with NONE in title

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1282]
How to reproduce:
- New SR install
- Configure GIT user, pass and path
- Don't change any other setting
- Open log page
- Submit error:
```
ERROR    SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickrage config for daily searches. Please check your settings.
```
- Issue is created with None in title

**Comment by fernandog** [comment]
@TagForce can you help me debug this one? Can find the reason why its not working

**Comment by fernandog** [comment]
@abeloin @TagForce I give up on this one. Can't find the problem.

https://github.com/SiCKRAGETV/sickrage-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+author%3Afernandog+None

**Comment by TagForce** [comment]
@fernandog I'll have a look tomorrow

**Comment by TagForce** [comment]
@fernandog The title is extracted as follows:

```self.title = sys.exc_info()[-2]```
sys.exc_info() will return the last encountered exception.
However... The No NZB/Torrent providers found error (or indeed any other error that is handled by SR, rather than throwing an exception, like configuration errors, no git.exe found, invalid naming patterns, etc, etc) will not throw an exception.
This results in an empty title...

I'm fixing it now, by changing that line to read:
```self.title = sys.exc_info()[-2] or message```
causing it to use the message for the title if there's no exception. This happens at the moment the UIError is created, not at the time the error is submitted.
That should fix it...

**Comment by fernandog** [comment]
@tagforce Thanks!

**Comment by fernandog** [comment]
merged in develop

**Comment by TagForce** [comment]
Needs more logic. Empty titles still occur when the message is an empty string.

**Comment by miigotu** [comment]
Ew, I had it finding a dupe issue, and commenting instead of creating a new one, and now i broke it -.-

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1820

**Comment by miigotu** [comment]
@fernandog I think that error is not an actual error and thats why you have no title. The log line that spits out that error should be set to something like info or debug, or bypassed in the issue submitter.

ei: it isnt created by an exception, so it shouldnt be an 'ERROR'

**Comment by fernandog** [comment]
@miigotu are you talking about this one?

https://github.com/SiCKRAGETV/sickrage-issues/issues/1302

**Comment by miigotu** [comment]
OK that one is created after an exception.

**Comment by miigotu** [comment]
@fernandog I got a way around it, I pushed a commit, but I have to add a regex to it and split off the type and thread and provider strings. Ill squash a regex in and let you know when to check it out.
