### ISSUE TITLE
Failed download processing failed

### ISSUE THREAD

**Issue by bobbyware** [SiCKRAGETV/sickrage-issues#1320]
Some episodes of Arrow are failing on news groups:

2015-04-19 17:13:32 WARNING  Thread-55 :: Failed Download Processing failed: (scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.nzb, /home/roland/Downloads/incomplete/scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1): 
2015-04-19 17:13:32 INFO     Thread-55 :: Using nzb_name for release name.
2015-04-19 17:13:32 INFO     Thread-55 :: Failed download detected: (scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.nzb, /home/roland/Downloads/incomplete/scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1)

I guess it's because the name contains episode information twice (304 and S03E04).

SR Version:	BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4) 

This bug is I've highlighted a while ago on sickrage.tv, without response. It's still present in current build   
https://sickrage.tv/forums/forum/help-support/general-support/9571-failed-download-processing-failed

**Comment by abeloin** [comment]
Can you provide the whole log from SR and sabnzbd script?

**Comment by bobbyware** [comment]
Sabnzbd:

Opening URL: http://localhost:8081/home/postprocess/processEpisode
Processing folder /home/user/Downloads/incomplete/scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1
TV_DOWNLOAD_DIR: /mnt/Download/transmission/completed/tv_shows
PostProcessing Path: /home/user/Downloads/incomplete
PostProcessing Dirs: [u'scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing folder scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1
Failed download detected: (scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.nzb, /home/user/Downloads/incomplete/scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1)
Error: unable to parse release name scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv into a valid show
Failed Download Processing failed: (scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.nzb, /home/user/Downloads/incomplete/scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1):
Successfully processed
I did encounter some unprocessable items:
[scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv.1 : Failed download]

**Comment by bobbyware** [comment]
Sorry but Sickrage logs are no longer there (too long ago). But above should give enough information. I've did some debugging as well, and found out that the regex to extract the show information fails.
This is probably caused by the fact that the episode number is duplicated (S03E04 and 304). I've tried to implement a fix, but didn't work...
The original NZB name does not have the season information duplicated, it did not have the "304" part in it.
Hope this helps! If I need to replicate the issue again, to get SR logs, please let me know.

**Comment by fernandog** [comment]
@bobbyware check the original video file inside the nzb.

**Comment by bobbyware** [comment]
@fernandog The original NZB contains a RAR file, with name
"sparrow.304.720p-dimension.rar" 
HOWEVER, that RAR file is not in my incomplete folder, as the entire download failed. 

And I think it's looking at a different file? When I look at the logs, I see this:

Error: unable to parse release name scnzbefnet529699-Arrow.S03E04.720p.HDTV.X264-DIMENSION-126-sparrow.304.720p-dimension.sfv into a valid show

**Comment by TagForce** [comment]
SabNZBd is telling SR to process that folder. The 'filename' you're seeing is actually a foldername.
And indeed SR cannot parse that name into a valid show name (show would have to be scnzbefnet529699-Arrow). So that's why SR is failing to handle the failed download, because it has no idea what download it is. The reason why SR is trying to PP the folder (when there's no video file in it) is because the Failed Download detection is handled by the ValidateDir function, which is called before it lists what files are inside it.

This is not something that we can do anything about, I think. If SabNZBd wants to provide us with a failed download, then it should be done using a proper scene name. If it fails, and decides to use the Simple File Verification filename for it with an addition of where the file originated, then we cannot handle it.

**Comment by bobbyware** [comment]
@TagForce Thanks for the clarification, makes sense. However, I don't know how to fix it... SabNZBD obviously doesn't know anything about what's being downloaded.
The NZB was downloaded in the first place, so at that time SR could detect the show name... 98% sure this was the original NZB: http://nzbclub.com/nzb_get/39384851/scnzb_efnet_529699_Arrow_S03E04_720p_HDTV_X264_DIMENSION_sparrow_304_720p_dimension.nzb

Perhaps it could do something with the NZB name? Not sure where to change (SR or SB), but just a suggestion?

Thanks again, appreciate the quick responses. I love SR! Except this "bug"/feature.

**Comment by TagForce** [comment]
@bobbyware Actually, the NZB name is "sparrow 304 720p dimension.nzb". At least that's how it gets downloaded. It could possibly find it by that name (if a search returns the title, and not the actual filename). That way SR could snatch this episode, pass the file that downloads it to SabNZBd, and then completely lose the relation to arrow because the filename is not what was in the title. 
Anyhow, the scnzb_efnet_529699_ part is not part of the filename, but is part of the message subject on Usenet:
[#scnzb@efnet][529699] Arrow.S03E04.720p.HDTV.X264-DIMENSION [1/26] - "sparrow.304.720p-dimension.sfv" yEnc
The actual filename is sparrow.304.720p-dimension.sfv.
If that gets messed up by SabNZBd to include the entire message subject, then SR won't be able to handle it...

I'll have a look to see if I can get SabNZBd to tell me why it does that, but there's really nothing we can do about this in SR.

**Comment by TagForce** [comment]
@bobbyware In SabNZBd Options, go to Special, and check rss_odd_titles... If nzbclub.com is not on the list, add it. If it is, remove it.
Alternatively (if you're on 0.7.3 or lower) try setting the rss_filenames option to on.
Both of those options change the behaviour for the naming of jobs... It normally uses the Title for the job name (which includes the [#scnzb blah blah] part), and the options above force it to use the NZB filename... Or it could be the other way around, I'm not sure. Either way, changing the behaviour might help your situation.

**Comment by bobbyware** [comment]
Thanks @TagForce I have tried it, but it still does not work.
The NZB name is actually: scnzbefnet530304-Arrow.S03E05.720p.HDTV.X264-DIMENSION-127-capn.jack.305.720p-dimension.sfv.nzb
I was wrong, it was not downloaded from NZBClub, but OpenNZB. Sorry for that.

The NZB is now passed as a web request from SR to SB. Ideally SR passed the job name as well? Not sure if that's possible? That would eliminate it always?

For now, I've disabled OpenNZB. 

Thanks again!

**Comment by fernandog** [comment]
@TagForce close this then?

**Comment by bobbyware** [comment]
@fernandog Sorry but it is still a defect, right? At least for me, as I use both pieces of software without customisation, and it is not 100% fail safe. 

Relying on the NZB name only is not enough.

The SabNZBD API provides an option to pass in NZBName: http://wiki.sabnzbd.org/api#toc28
If SR would provide the name of the show there, all issues would be solved?

**Comment by TagForce** [comment]
@bobbyware @fernandog Still open. This needs to be fixed in sab.py and probably nzbget.py as well. SR isn't using the nzbname=PrettyName option when sending urls, and that should be implemented using the releasename (because we know SR can parse that, otherwise it would not download it).
