### ISSUE TITLE
Marking all season episodes as wanted finds nothing

### ISSUE THREAD

**Issue by AdeHub** [SiCKRAGETV/sickrage-issues#1350]
Master
    975c0dd208c59cac8fd8a77a91da5d1dfc7235df
    OS X Yosemite 2.7.6

Did - Marked all episodes in a season as wanted
Results - Nothing Found
Expected - Provider episodes to be snatched

```
2015-04-21 19:08:29 INFO     SEARCHQUEUE-BACKLOG-260871 :: No needed episodes found during backlog search for: [Moone Boy]
2015-04-21 19:08:27 DEBUG    SEARCHQUEUE-BACKLOG-260871 :: Search string: https://kickass.to/usearch/Moone+Boy+%22Season+1%22+-Ep%2A+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-04-21 19:08:25 DEBUG    SEARCHQUEUE-BACKLOG-260871 :: Search string: https://kickass.to/usearch/Moone+Boy+S01+-S01E+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-04-21 19:08:25 INFO     SEARCHQUEUE-BACKLOG-260871 :: Performing season pack search for Moone Boy
2015-04-21 19:08:25 INFO     SEARCHQUEUE-BACKLOG-260871 :: FALLBACK SEASON PACK SEARCH INITIATED ...
2015-04-21 19:08:23 DEBUG    SEARCHQUEUE-BACKLOG-260871 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/Moone+Boy+%22Season+1%22+-Ep%2A+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-04-21 19:08:21 DEBUG    SEARCHQUEUE-BACKLOG-260871 :: [KickAssTorrents] :: Search string: https://kickass.to/usearch/Moone+Boy+S01+-S01E+category%3Atv/?field=seeders&sorder=desc&rss=1
2015-04-21 19:08:21 INFO     SEARCHQUEUE-BACKLOG-260871 :: [KickAssTorrents] :: Performing episode search for Moone Boy

```
Searching for individual episodes works, also if I open the following url (without the '-' from above) in a RSS reader I get results:

```
https://kickass.to/usearch/Moone+Boy+S01+S01E+category%3Atv/?field=seeders&sorder=desc&rss=1
```
Apologies if already a known issue

**Comment by fernandog** [comment]
@AdeHub change the season mode to eponly in providers. You are trying to download season packs and they are not available.

**Comment by AdeHub** [comment]
It is set as eponly:
```
[KICKASSTORRENTS]
kickasstorrents = 1
kickasstorrents_confirmed = 0
kickasstorrents_ratio = 1
kickasstorrents_minseed = 0
kickasstorrents_minleech = 0
kickasstorrents_proxy = 0
kickasstorrents_proxy_url = http://proxite.eu/
kickasstorrents_search_mode = eponly
kickasstorrents_search_fallback = 1
kickasstorrents_enable_daily = 1
kickasstorrents_enable_backlog = 1
```

**Comment by TagForce** [comment]
@AdeHub Do you have any other torrent providers enabled?
Are they exhibiting the same behaviour?

**Comment by AdeHub** [comment]
Same issue with piratebay

**Comment by TagForce** [comment]
@AdeHub I think I fixed it... If you know how, you can see if the PR works for you.

**Comment by fernandog** [comment]
@TagForce thanks!

**Comment by TagForce** [comment]
@fernandog It is, but the problem is not so much in that it tries a season search, but rather that the search strings for episode searches were still generated using season search logic.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1360#issuecomment-95091377

**Comment by abeloin** [comment]
@fernadog @TagForce  there is another issue open for this, don't remember the number. The issue is some providers doesn't support season search(search for show.s01 and return a bunch of episode) in ep mode(iptorrent is example) and need to be fixed. This was implemented to prevent too many requests on a provider.

I think we should fix the providers instead(findSearchResults, _get_episode_search_strings, _get_season_search_strings). Also split findSearchResults in 2 part so that the season search and sponly can be disabled properly

**Comment by TagForce** [comment]
@abeloin I'm not sure I'm following you... So, you prevent the fallback to eponly because some providers return single ep results in season searches?
That effectively breaks episode searches on providers that negating search strings do work on.

What happens now is that if a season result was not found, it will set search_mode to eponly, and then in findSearchResults it would completely disregard that setting and still search using season strings, which, for most providers, causes episodes to never be found, unless you manually search for them, one by one.

If sponly fails, it should always use eponly, and not pretend to use eponly and still use sponly (because it's useless that way, as you search the same thing twice, expecting different results).

I think we should make the generic provider work as intended, and if a certain provider doesn't work well with it, override it there (by preventing eponly searches completely, not by running sponly twice).

**Comment by TagForce** [comment]
@abeloin I went a ways back, and findSearchResults has had this problem for a long time:
https://github.com/SiCKRAGETV/SickRage/blob/5ac389560025e06fa37acef4aa60823404e1c746/sickbeard/providers/generic.py#L284
That's the version for september 20th, 2014... The if check always uses season search strings even in eponly mode when there's more than 1 episode in the search list. It shouldn't do that.

**Comment by abeloin** [comment]
@TagForce Sorry, I'll try to better explain it. I think what they intended to do was to search per season(string) instead of per episode when searching for multiple episodes in eponly to save calls but this doesn't work for some provider.

So for example, search s01e01-e02-e03:
* Per episode search in eponly:
  * Search s01e01
  * Search s01e02
  * Search s01e03
  * Parse results and find episodes

* Per season search in eponly:
  * Search s01 (Try to catch all episodes possible)
  * Parse results and find episodes

**Comment by TagForce** [comment]
@abeloin Ah, I understand it now...
I think you may be right, but the logic is off in the code.

I'll see if I can modify it so that eponly will also try a season search, and if it cannot find a result that way try episode searches. Logic for that is tricky.

Another solution would be to simply remove the eponly/sponly config settings, and simply have it search whatever seems best at the time and fallback to the other one if the first fails. So, if we're looking for 1 episode, do an episode search, if that fails try a sponly search if the provider supports it. If we're looking for more than one, try an sponly search and if that fails, try an episode search.

**Comment by fernandog** [comment]
@tagforce like the second option.

**Comment by coop73** [comment]
I don't understand why this issue keeps getting closed it is still a huge problem.

**Comment by TagForce** [comment]
@coop73 it's fixed in develop at the cost of increased provider calls.. Will be merged in master on sunday.

Only issue now remaining is the logic behind when to search with which method to minimize the provider calls.

**Comment by coop73** [comment]
Ok Thanks and we will see.
