### ISSUE TITLE
[APP SUBMITTED]: Thread-52 :: Failed to detect KODI version for 'localhost:4567', check configuration and try again.

### ISSUE THREAD

**Issue by MasterAslan** [SiCKRAGETV/sickrage-issues#1467]
### INFO
Python Version: **2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/698a16ad7cf6a46f2306
### ERROR
```
Thread-52 :: Failed to detect KODI version for 'localhost:4567', check configuration and try again.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
`2015-04-29 20:00:41 WARNING  Thread-52 :: Error while trying to retrieve KODI API version for localhost:4567: error [Errno 10061] No connection could be made because the target machine actively refused it`

Either your url:port is wrong, kodi was not running, or your settings in kodi are wrong.

For configuration inside kodi, see http://kodi.wiki/view/JSON-RPC_API#Enabling_JSON-RPC
