### ISSUE TITLE
Post processing wrong show detected

### ISSUE THREAD

**Issue by elixdreamer** [SiCKRAGETV/sickrage-issues#1487]
Hello,

I have some problems post processing a show.
Al the time it processes it detects an other show.

Any thoughts on this?
```
Processing folder /share/Download/transmission/completed
TV_DOWNLOAD_DIR: /share/Download/transmission/completed
PostProcessing Path: /share/CACHEDEV1_DATA/Download/transmission/completed
PostProcessing Dirs: ['.@__thumb']
PostProcessing Files: ["Marvel's.Daredevil.S01E01.mp4"]
PostProcessing VideoFiles: ["Marvel's.Daredevil.S01E01.mp4"]
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /share/CACHEDEV1_DATA/Download/transmission/completed/Marvel's.Daredevil.S01E01.mp4 (None)
Retrieving episode object for 1x1
Looking up quality for name completed, got Unknown
Looking up quality for name Marvel's.Daredevil.S01E01.mp4, got Unknown
Guessing quality for name Marvel's.Daredevil.S01E01.mp4, got SD TV
Is ep a priority download: False
File /share/Series/Marvel's Agent Carter/Marvel's Agent Carter S01/Marvels.Agent.Carter.S01E01.Now.is.Not.the.End.2HD.mp4 doesn't exist so there's no worries about replacing it
No associated files were during this pass
Destination folder for this episode: /share/Series/Marvel's Agent Carter/Marvel's Agent Carter S01
No associated files were during this pass
Moving file from /share/CACHEDEV1_DATA/Download/transmission/completed/Marvel's.Daredevil.S01E01.mp4 to /share/Series/Marvel's Agent Carter/Marvel's Agent Carter S01/Marvels.Agent.Carter.S01E01.Now.is.Not.the.End.SiCKRAGE.mp4
Processing succeeded for /share/CACHEDEV1_DATA/Download/transmission/completed/Marvel's.Daredevil.S01E01.mp4
Processing folder .@__thumb
Ignoring hidden folder: .@__thumb
Successfully processed
I did encounter some unprocessable items: 
[.@__thumb : Hidden folder]
```

My Sickrage version on QNAP
```
SR Version:	BRANCH: (master) / COMMIT: (5ef5a0b27e27cf937011408cb55329d1bd21ce9d)
Python Version:	2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]
```

**Comment by MrEnigmamgine** [comment]
I have this issue as well with Marvel's Agents of SHIELD.
Here is a copy/paste of the post I made on the forums:

I'm having trouble with Marvel's Agents of SHIELD getting postprocessed as Marve'ls Agent Carter. I can understand how the application gets confused but I'd like to know where to make changes so that it gets post-processed directly.

I should mention that Agents of SHIELD isn't being snatched by Sickrage. A couple of weeks ago it was snatching fine, but recently it's failed on the last two episodes and I had to manually add the torrent to Deluge and use manual post-processing. That's when I started running into this issue.

Here is the output from manual post-processing.
[CODE] Postprocessing results

Processing folder /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS
TV_DOWNLOAD_DIR: /mnt/data/downloads/tv
PostProcessing Path: /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS
PostProcessing Dirs: []
Packed Releases detected: ['marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.rar']
Unpacking archive: marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.rar
UnRar content: ['Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv']
PostProcessing Files: ['marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r05', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r13', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r06', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r01', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r17', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r18', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r00', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r11', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r08', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r14', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r10', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r04', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.nfo', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.rar', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r15', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r16', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r09', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r12', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r03', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r07', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.r02', 'marvels.agents.of.s.h.i.e.l.d.s02e19.proper.720p.hdtv.x264-killers.sfv', 'Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv']
PostProcessing VideoFiles: ['Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv']
PostProcessing RarContent: ['Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv']
PostProcessing VideoInRar: ['Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv']
Processing /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv (None)
Retrieving episode object for 2x19
Snatch history had a quality in it, using that: HD TV
This was manually downloaded but it appears to be a proper so I'm marking it as priority
Is ep a priority download: True
File /mnt/data/media/tv/Marvel's Agent Carter/Marvels.Agent.Carter.S02E19..mkv is the same size as /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv
This download is marked a priority download so I'm going to replace an existing file if I find one
Found the following associated files: [u"/mnt/data/media/tv/Marvel's Agent Carter/Marvels.Agent.Carter.S02E19..en.srt"]
Deleting file /mnt/data/media/tv/Marvel's Agent Carter/Marvels.Agent.Carter.S02E19..mkv
Deleting file /mnt/data/media/tv/Marvel's Agent Carter/Marvels.Agent.Carter.S02E19..en.srt
Found release name Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS
Destination folder for this episode: /mnt/data/media/tv/Marvel's Agent Carter
No associated files were during this pass
Moving file from /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv to /mnt/data/media/tv/Marvel's Agent Carter/Marvels.Agent.Carter.S02E19..mkv
Processing succeeded for /mnt/data/downloads/tv/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS/Marvels.Agents.of.S.H.I.E.L.D.S02E19.PROPER.720p.HDTV.x264-KILLERS.mkv
Successfully processed[/CODE]

I thought it might have something to do with the name exceptions I have defined for each of my shows. But I can't honestly figure out how it's getting the names confused.

Here's the exception list for SHIELD:
[CODE]
Marvel Agents Of SHIELD
Agents of S H I E L D
Agents of SHIELD
Marvels Agents of S H I E L D
Agents of S.H.I.E.L.D
Marvels Agents of S.H.I.E.L.D
Marvel Agents of S.H.I.E.L.D
[/CODE]

The exception list for Agent Carter is empty.

For Agent Carter I tried adding "SHIELD" and "S.H.I.E.L.D" to the ignored words and added "Carter" to the required words. From what I understand this should stop Sickrage from accepting releases with the ignored words in the name and only accept releases with required words in the name. Manually post processing the file still result in the SHIELD episode being processed as a Carter episode.

I'm out of ideas. You guys have any advice on how to stop this from happening.

**Comment by MrEnigmamgine** [comment]
Removed Agent Carter from my show list and now it post-processes to the correct show.  Not a very good fix but at least it's a work-around for now.

**Comment by Vodka2014** [comment]
Here is my 5 cents of what I have done hope it helps if not was worth a try :)

My folders are set-up like this and the Scene Name list are as follows and never had an issue (so far). (Folder is the name on my drive)

Folder: Marvel's Agents of S.H.I.E.L.D
Scene Name: Marvel Agents Of SHIELD | Agents of S H I E L D | Marvels Agents of S H I E L D

Folder: Marvel's Agent Carter
Scene Name: Marvel's Agent Carter

Folder: Marvel's Daredevil
Scene Name: Marvel's Daredevil

**Comment by OmgImAlexis** [comment]
Can you guys confirm if adding the correct scene exceptions fixed this? If it hasn't I'll reopen it.

**Comment by fernandog** [comment]
@elixdreamer
