### ISSUE TITLE
Ignore required word for anime

### ISSUE THREAD

**Issue by artentica** [SiCKRAGETV/sickrage-issues#1654]
Hi my problem is than I can not download anime beacause SR refused.
I explain myself, he find the correct anime show but like I want french subtitle in the global required word I put "VOSTFR" (Original version french subtitle), but I search the anime on a french provider who did not mark his show has being french subtitled (but they are). And SR refused to Download because it's not write.

So can we disabled the global required/ignoring word for anime?

Someone see how I can do?

**Comment by neoatomic** [comment]
@artentica If you go to that show and select the edit button you can add Ignored/Required Words.
That is specific for that show and you dont have to use Global Required Words.
Another solution could be to change the order of search providers. So that SR first searches on the French provider for those episodes.
