### ISSUE TITLE
Post-processing script error: 'module' has no attribute 'Session'

### ISSUE THREAD

**Issue by andyj682** [SiCKRAGETV/sickrage-issues#1730]
This cropped up for me sometime in the last few days--been using SR happily for months with no such problems with post-processing. Postt-processing script called from SAB errors out with the message below.

BRANCH: (master) / COMMIT: (e39fae0502b0993fd0163ea2f6888871426465be) 
Python version: 2.7.9 (default, Mar 22 2015, 23:26:38) [GCC 4.6.3]
Running on a Synology DS214play, DSM 5.2-5565 Update 1
SABnzbd version is 0.7.20

Postprocess script error on all episodes:

Opening URL: https://localhost:8083/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 29, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 128, in processEpisode
AttributeError: 'module' object has no attribute 'Session'

**Comment by andyj682** [comment]
Manual post-processing still seems to work fine, for what that's worth. Issue is only in the autoProcess script called from SAB.

**Comment by neoatomic** [comment]
@andyj682 @ulrick65 I run DSM 5.2-5565 Update 1 with SAB and sabToSickBeard without any problems.
The only difference from my setup is that i have the scripts in the /volume1/@appstore/sabnzbd/var/scripts folder. So give that a try, and move them there. Might be a permission issue.?

Also last week we have released a official package on Synocommunity for SickRage so you dont have to use the sickbeard-custom method to install. (Note different port as sickbeard-custom installation)

**Comment by ulrick65** [comment]
I tried opening up the permissions, but that did not help.  If I closed the permissions, I got a different error...so I kind of ruled that out.  I had HTTPS disabled and still a no go.

I ended up backing up, then removing the app and reinstalling the SickRage app from Synocommunity...works like a charm now.

**Comment by ulrick65** [comment]
By the way, since I installed from Synocomunity does that now mean that I will not be able to update from within SickRage from GIT?

**Comment by ulrick65** [comment]
Here's my comment from my other post about this...#1731.  I am not sure how else to do this, so let me know if there is a better way to reference it from here to keep all relevant info in one thread.



Branch - Master
Commit hash - (e39fae0502b0993fd0163ea2f6888871426465be) 
Operating system - Synology DSM
Python Version - 2.7.9-13

Updated SR about 3 days ago was the only change. Ever since this update autoProcess in SABNZBD has failed with "AttributeError: 'module' object has no attribute 'Session'".  It worked fine on a download that finished an hour or so before I upgraded to the latest commits 3 days ago...but fails everytime since.

I updated again today the latest commits to see if that would help, but still fails.

Everything works fine with the download, SR snatches, passes to SAB, SAB downloads, but then when the post processing happens on the TV episode (I use the standard "sabToSickBeard.py" script, no modifications) I get this error in the post processing script window:

Loading config from /volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.cfg
Opening URL: http://localhost:8083/home/postprocess/processEpisode Traceback (most recent call last):
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 29, in <module> autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 128, in processEpisode sess = requests.Session() 
AttributeError: 'module' object has no attribute 'Session'

The file is intact and looks find in the download folder....however, the file remains in the download folder and is not copied to its proper location. Any ideas what might be causing this? Was there something done in the last update that would have effected this? Everything was working perfectly until SR was updated about 3 days ago.

The SR log does not show anything about the post processing, it shows the file being passed to SAB, but then nothing after that and the episode never changes from "snatched" of course.

Here's my log

https://gist.github.com/14bdcb65fe1697bd2057.git

Any help would be much appreciated.

Thanks.

**Comment by neoatomic** [comment]
@ulrick65 Thanks for the feedback.
The new SickRage package works the same as the old one, and also uses GiT for updating. 

@andyj682 Backup and install the new SickRage package from SynoComunity and it should work again.

**Comment by andyj682** [comment]
@neoatomic So I backed up, installed the new synocommunity package, tried to restore. It creates the "restore" dir and has the right files in it, but after I restart it doesn't seem to actually be restoring. Restore dir is gone, but database/config hasn't actually been changed from the defaults. Any suggestions? Can I just manually copy the files in the restore dir to the right places, or would that mess things up?

**Comment by neoatomic** [comment]
@andyj682 Yes, Stop SickRage and manually overwrite the files. (dont delete, but overwrite.)
Than start SickRage again.

**Comment by ulrick65** [comment]
Sorry...I forgot about that, I could have mentioned it.  For some reason, when you restore from within SickRage is restores the files to:

/usr/local/sickrage/var

but it should restore to:

/volume1/@appstore/sickrage/var

Which is where the install is located.  I simply copied the files over the ones in there and it rebuilt fine.

Not sure why it copies the file to the wrong location, is this a bug or something?

**Comment by andyj682** [comment]
@ulrick65  @neoatomic Think those locations are one and the same, right? /usr/local/sickrage just seems to be a link to /volume1/@appstore/sickrage. 

At any rate, I restored manually and auto post-processing works fine again. Thanks guys.

**Comment by neoatomic** [comment]
Yes, they are linked and therefore the same. Synology does it for security reasons.

**Comment by ulrick65** [comment]
Damn...I never noticed that!  I wonder why they had to be copied over then?  When I did the restore from SickRage I got the message that then had been copied there...but in fact, the ones in there where not the correct ones.  Maybe permissions were the problem and SickRage just said it copied there but really didn't.

**Comment by ulrick65** [comment]
This problem came back again for me today...exactly the same error messages as before.  Any idea what could be causing this?  I hate to have to backup, uninstall, reinstall and restore again...  I noticed that my Python is updated to 2.7.10-14 could that be causing this problem?  Whenever Python updates something messes up in SickRage?

**Comment by neoatomic** [comment]
Hard to say. You can do a git reset and see if that works or remove the cache folder.

Yesterday i witched myself to nzbtomeda's nzbtosickbeard script and that works awesome. It also automates failed download handling and setting up is pretty much the same as for sabtosickbeard.
So you could also try that.

**Comment by ulrick65** [comment]
Thanks...I may have to check that out.  I tried uninstalling and reinstalling again..that worked, but a big pain due to the shows having downloaded but no updating of info, so I had to manually update those.  Then I come home tonight and updated SickRage to the latest build...and it now bombs with the exact same issue.  Really frustrating.

What is so frustrating is that it works perfectly fine more a long time and then updates and boom, the error comes back.  In this case it worked two days, updated and back to the same error.

**Comment by funboy92** [comment]
Hello
I still have the same problem, After reinstalling Sickrage it's works fine, but today I have Attribute Error after update 
how to fix this without another reinstall. Thanks

**Comment by flightlevel** [comment]
@funboy92 
Create a new issue and the post the exact error following guidelines https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket
"I have Attribute Error after update " is not helpful

**Comment by funboy92** [comment]
Hello I think this is a good topic

My configuration is

BRANCH: (master) / COMMIT: (7694b70047796dc0c9c812300a090f78a4240f46)
Running on a Synology DS11j
SABnzbd version is 0.7.20

After last sickrage update when I use sabTosickbeard.py I have an error message

Loading config from /usr/local/sickrage/var/SickRage/autoProcessTV/autoProcessTV.cfg
Opening URL: http://x.x.x.x:8899/home/postprocess/processEpisode
Traceback (most recent call last):
  File "/usr/local/sickrage/var/SickRage/autoProcessTV/sabToSickBeard.py", line 34, in <module>
    autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
  File "/volume1/@appstore/sickrage/var/SickRage/autoProcessTV/autoProcessTV.py", line 133, in processEpisode
    sess = requests.Session()
AttributeError: 'module' object has no attribute 'Session'

**Comment by ulrick65** [comment]
I have been able to fix this everytime now...simply by adjusting the permissions on the files in the autoProcessTV folder to 755.  For some reason, after an update they get reset such that sabnzbd can not read them.  This is a pain in the a@@ but easy enough to do (assuming you understand telnet, command line, etc.)

There is a really long post about it here...complete with a long post from me explaining the issue, what the folder and file permissions are an what I had to do to fix it.

Let me know how it goes.

https://github.com/SynoCommunity/spksrc/pull/1802

**Comment by funboy92** [comment]
thanks for your answer, but it didn't work
I adjust permissions to 755 and change group user to root like on fresh install

drwxrwxrwx    3 sickrage root          4096 Sep 19 23:08 .
drwxr-xr-x   12 sickrage root          4096 Sep 14 15:32 ..
-rw-r--r--    1 sickrage root            76 Sep 14 16:04 autoProcessTV.cfg
-rw-------    1 sickrage users           72 Sep 19 22:15 autoProcessTV.cfg.sample
-rwxr-xr-x    1 sickrage root          4596 Sep 19 22:15 autoProcessTV.py
-rw-------    1 sabnzbd  users         3258 Sep 19 23:08 autoProcessTV.pyc
-rwxr-xr-x    1 sickrage root          1166 Sep 19 22:15 hellaToSickBeard.py
drwxr-xr-x    3 sickrage root          4096 Sep  8 23:19 lib
-rwxr-xr-x    1 sickrage root          8076 Sep 19 22:15 mediaToSickbeard.py
-rwxr-xr-x    1 sickrage root          1332 Sep 19 22:15 sabToSickBeard.py
-rwxr-xr-x    1 sickrage root           374 Sep 19 22:15 setup.py
