### ISSUE TITLE
Traceback error on Pirate Bay searches

### ISSUE THREAD

**Issue by sts41** [SiCKRAGETV/sickrage-issues#1751]
Branch: Master
Commit Hash: 42b8d5a9c71c87fcde301967b6254ef08c3093ac
OS Version: Centos 6.6 (2.6.32-504.16.2.el6.x86_64)
Python Version:2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
What you did: Search for a show episode.
What Happened: SickRage searches all the providers I have configured, but when it reaches the Pirates Bay I get a traceback error. When I copy and paste the search string from the error log into a web browser, the url returns the show.
What I expect: I would like that The Pirates Bay works like other providers. By far the Pirates Bay returns a show when all the others providers do not. Fixing this would really help clear up backlog.

Log:  https://gist.github.com/anonymous/1d895197879e4594d0c2

**Comment by neoatomic** [comment]
@sts41 The connection times out because of a SSL problem.
When i enter the url is redirects to a .gd domain instead of the old .se domain. So i suspect that is the problem. (https://thepiratebay.vg/ https://thepiratebay.gd/ )
Looks like they are already redirecting the traffic to there new domains. : 
http://torrentfreak.com/pirate-bay-founder-appeals-domain-seizure-decision-150525

You can try to use a proxy for a temporary fix.

@fernandog @miigotu Do you want to change the url for the piratebay.?

**Comment by sts41** [comment]
I noticed that, and I tried updating the url in the conf file for pirates bay...did not make a difference. Thanks Steve


Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by miigotu** [comment]
@sts41 Try changing the url in `SickRage/sickbeard/providers/thepiratebay.py` at line 62 where is says `        self.urls = {'base_url': 'https://thepiratebay.se/'}` to `self.urls = {'base_url': 'https://thepiratebay.gd/'}
Restart SR and try again. If this change works, I will change it in the source, but I think some other change must be made.

**Comment by sts41** [comment]
I had tried that a few days ago… But just to be sure, I tried it again. Still getting same error except the url changed in the error. 

 

Thanks, Steve

**Comment by miigotu** [comment]
Eh, just read the log, '_socketobject' object has no attribute 'set_tlsext_host_name' is an ssl error. We have been searching for these problems forever and you should have searched the issues about it first.
