### ISSUE TITLE
underlines are not being ignored when searching for new shows.

### ISSUE THREAD

**Issue by vbab** [SiCKRAGETV/sickrage-issues#1755]
how can I get it to ignore or remove before search?? the underlines.

I have all the spaces replaced with underlines and it keeps trying to find  The_Show  instead of The Show.
-----------
also if the show ends in a comma like The Blue, eye   and you try to search for The Blue,    it fails  the comma needs removed from the end of a search

**Comment by neoatomic** [comment]
follow the rules for opening an issue. https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

Add a scene exception if the release name is different from the index name. If you use ignore/require words than you separate them with a "," so you cant use them in the file name.

**Comment by vbab** [comment]
problem was i replaces all spaces in show names with underlines

**Comment by miigotu** [comment]
Folder name has nothing to do with searching. Only if you modified the sickrage database and changed the show name would it affect searching. You performed some unsupported action and broke your setup.

**Comment by vbab** [comment]
I used a media renamer called media center master      it has options to replace all spaces with  periods like scene does  or to replace with underlines.    I have since used ant renamer and removed all the underlines since no one seems to support them.

**Comment by miigotu** [comment]
Do you mean searching when adding existing shows to SR from the page at /home/addShows/existingShows/ ? If so I can fix that, if you mean another problem let me know.

**Comment by miigotu** [comment]
@vbab also, you don't need to keep using external media managers or renamers if you are using sickrage. Sickrage does all of that for you.

**Comment by vbab** [comment]
there are lots of shows sickrage and sickbeard renames incorrectly and never offers you a choice.   mediacentermaster is pretty awful except for renaming things it has one of the best renamers I have seen.   i just wish it was built into sickbeard/rage   the best most common rename option you don't even have on your list and that is   show_name s01e01 episode  yours has  2 dashes and spaces extra with increases the filename length by 4  that can cause problems on some machines.  I don't care for the 1x00 format that is popular in some circles, i know it saves 1 space but it is much harder to search for mistakes in naming.  
 Im trying to merge old data i saved into my library need a renamer that stops and prompts me.   I have shows from all over and many use same name so i have to precreate the xml files .sadly sickbeard does not seem to be smart enough to use these files and trys to look up the shows and guesses them wrong.  so I tend to disable sickbeards renamer. 
You need to look at incorporating a interactive naming like I think you used to have.  its a real problem to have to stop and manually rename things because I cannot trust your renamer at this time.

**Comment by miigotu** [comment]
Our renamer works fine, and you can set how you want them named under http://ip:port/config/postProcessing/ on the episode naming tab. You can even set custom ones.

Mine is `Season %0S/S%0SE%0E - %EN` which gives `Season 02/S02E03 - Ep Name.ext`, 
Example: `season_%0s/%s_n_s%0se%0e_%e_n_%q_n-%rg` is `season_02/show_name_s02e03_ep_name_hdtv-rlsgroup.ext` or what you exaclt said you wanted: `%s_n_s%0se%0e_%e_n` which is `show_name_s02e03_ep_name.ext`

The most common is not `show_name s01e01 episode`. Most common is Camel Case with either spaces or dots.  `Show Name - S01E01 - Episode Name.ext` or `Season 01/S01E01 - Episode Name.ext` depending on if you use flat folders or not.

Claiming something is unreliable or doesn't work or doesn't have a feature just because you don't know how to use it is silly. SickRage does not rename shows incorrectly, and there is no reason for it to offer you a choice, as you told it what show it was to begin with. I have thousands of files, as do many other users, and the ONLY tool we use is SickRage.

As for the mass adding of shows, sickrage DOES use tvshow.nfo files, and/or series.xml files, although they are not necessary if shows are already named properly and in a proper folder layout.

It may need to ignore spaces under `http://ip@port/home/addShows/existingShows/`, which I can fix if you would clarify exactly where you are having a problem with it rather than bashing sickrage and never answering my question.

**Comment by vbab** [comment]
To simply my answer if all nfos get wiped from a library and we have many hundreds of shows to add back.   Yours is not the best renamer for the job.      for example   if we have   3 shows  Showone, Showone(2015), and Showone eu.
tvrage will most likely assign two of them to the same thetvdb id some shows only appear on imdb or tvrage also.  

"I do not recommend" anyone run out and try mediacentermaster on the library as they will most likely create a mess the default settings are not very friendly for tvrage if you try it, make a copy of you media to test it on.

thetvdb tvrage etc need to look at adding some kind of year/origion to media names.
Showone (2015) (yy2015) , showone (yy2014), showone eu (yy2012)

If shows were names like this it would stop a lot of the naming mistakes.  I have tried this and it caused lots of problems as if you try to look up a show named showone(2015)  and its not named that way on a database they do not attempt to just list showone.  So I'm forced to name the same way as the database minus the special symbols that cause problems on Windows Mac and Linux.

I have tried all kinds of naming appending video format sd hd  and underlined periods.   The problem is I get so many duplicates then. 
 show s01e01 episode hd
 show s01e01 episode sd ...

The best for dence home library is just show.s01e01.episode or show 1x01 episode. 
I also prefer folders with a 0 prefix thus 
 season 01   these sort much nicer.  

There is a way to download most of thetvdb names and you can test your renamer.

**Comment by miigotu** [comment]
1. Put your episodes inside a folder for each show. Shows/Showone (2015), Shows/Showone(EU), and Shows/Showone
2. Add them to SickRage, and have SR create nfo's for kodi, if there is more than 1 possibility for a show name, IT WILL ASK YOU. It also will let you check other indexers like tvrage or tvdb.
3. All 3 shows will have a different ID in Shows/Showone (2015)/tvshow.nfo, Shows/Showone(EU)/tvshow.nfo, and Shows/Showone/tvshow.nfo

http://thetvdb.com/?string=the+office&searchseriesid=&tab=listseries&function=Search

You are over-complicating things because you do not understand how it works, and you insist on making ridiculous statements like "the best". These are your oppinions, based on incorrect information.

SR will NOT incorrectly name anything without you incorrectly operating it. pebkac

**Comment by vbab** [comment]
here is a test zip with  just foldernames for shows   no metadata.     try aiming sickrage at the engtv folder and watch it crash.

<a href=http://www.filedropper.com/testfolderstvshows><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file storage</a></div>

**Comment by miigotu** [comment]
So, my question is, what are you actually here for? SR not replacing _, our renamer is shit, or your fux0rd up library wont add to SR and causes a crash? Make up your mind.

That set of folders is so ridiculously fubar'd, because of the renamer you used which you apparently don't know how to use either.

**Comment by miigotu** [comment]
And besides that, noone has 1414 different shows. You seem like a troll.

**Comment by vbab** [comment]
Sorry your wrong again.  im thinking your the troll.

**Comment by miigotu** [comment]
Lol.

**Comment by vbab** [comment]
I guess you have nothing to offer for a solution.   my box is just home made form leftover computer bits, I added 2 esata multiplexers  to run 2 external drive units.  3 boxes of drives 8 or so drives in each.

**Comment by miigotu** [comment]
You would need 50TB, just for the english shows. Anyways, if you want a specific fix, like what the issue was started as, explain it more. If you want to be able to add 1414 shows at one time, I can fix that.

The issue here is that you are bashing our renamer and our way of doing things. Saying our work is crap is not a good way to get our help.

The logic in SR is 1000x more complex (and almost always more accurate) than an ordinary scraper/renamer.

If you have that library added to a media center like plex, mediabrowser/emby, kodi or something, and they get it right, the easiest thing to do is export the library to separate files, which creates the nfo files for you.

**Comment by miigotu** [comment]
On another note, you can add AT LEAST 256 shows at one time, maybe we should limit it in gui.

Max folder name length is 255, tornado max parameter length 65535, so 65535/255.

**Comment by vbab** [comment]
i can add up to 600   at 610 it fails   i did not test each number in between   i looked at tornado code and it talked about 2 ways to sent it things.  one was more controlled and the other not. I could not understand how you coded it but i'm thinking you used the uncontrolled and it flooding it with to much data and there needs to be some hand shaking happening.

**Comment by vbab** [comment]
I added a few show folders   with metadata off
then i turned it on but left it set not to add any images and set metadata for xmbc 12+  and then im mass update ticked  update and rescan.   while it ran I watched the terminal window and it was loging it doing all  sort of things that seemed unneeded as there was no video in the folder.    
it seems to work correct and may just be logging strange things.

**Comment by miigotu** [comment]
It does work correct. Also tornado debugging I think is turned on in http://ip:port/config/general/ on interface tab under web interface->http logs

The error happens when the length of your folder names to be added at one time, combined, are more than 65535 characters. This is an edge case, as 99.999% of users have 50-60 shows, and the most extreme users have maybe 120 shows. You are just trying to add every show that exists and that is not what SR is intended for. One would almost need to be a tweaker to not see how ridiculous adding 1414 shows is.

**Comment by vbab** [comment]
with 5 tb usb drives for 99. on sale this week and 8 tb drives for under 200.   10tb will be here soon according to news on segates site. Their will be people creating 4 drive raids with 20 to 40 tb of shows will be happening.  manufactures have made a bunch of Ultra High Def Android tv boxes with 2gig ram  that are coming onto the market this year for near 100.00 retail.  They support kodi and plex and external usb drives.  I suspect you will run into more and more people with this problem.   Also asic tv will be come Asic-2  interactive tv.   some cable company's are going to drop traditional cable and go all digital with Roku boxes and have subscriptions for content.  
   Media as you have known it will evolve very fast in the next few years strap on some rockets to keep up or get lost in the dust.

**Comment by vbab** [comment]
Was fun im gonna test loading these 6k+ shows in and see what happens.

**Comment by miigotu** [comment]
Noone else attempts to download 6000 series', that they and everyone they know put together could never watch 1/10 of if they all watched separate episodes.  Seriously, stop tweaking this is nonsense.

**Comment by vbab** [comment]
dude you need to do some googling on your app and problems people are running into check out the mpc forums  and raids etc.      
i had all your shows loaded but moved them to different box and had to reload them They all already had the xml and nfos.  it has taken near 10 hours to load in 600 shows.  

And if you paid attention I do not have 6000 series.   Those files i sent you were just for testing your code. I gathered them form various databases online for you.   TWeak on my little tweaker
