### ISSUE TITLE
python: can't open file '/usr/local/sickrage/var/SickRage/autoProcessTV/sabToSickBeard.py': [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ejc1967** [SiCKRAGETV/sickrage-issues#1783]
BRANCH: (master) / COMMIT: (d185980c89055f7179deec708141710ce386a572) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
Synology DS3612xs DSM 5.2-5565 Update 1

After downloading with SABnzb when autoProcessTV is executed, it fails with this error:
python: can't open file '/usr/local/sickrage/var/SickRage/autoProcessTV/sabToSickBeard.py': [Errno 13] Permission denied

After some searching I found out that after the update the permissions of the following files in the folder autoProcessTV changed as follows:

autoProcessTV.cfg changed to Permissions 600 - Group users
Needs to be Permissions 644 - Group root

autoProcessTV.cfg.sample changed to Permissions 600 - Group users
Needs to be Permissions 644 - Group root

autoProcessTV.py changed to Permissions 700 - Group users
Needs to be Permissions 744 - Group root

autoProcessTV.pyc did not Change

hellaToSickBeard.py changed to Permissions 700 - Group users
Needs to be Permissions 755 - Group root

mediaToSickbeard.py changed to Permissions 700 - Group users
Needs to be Permissions 744 - Group root

sabToSickBeard.py changed to Permissions 700 - Group users
Needs to be Permissions 755 - Group root

setup.py changed to Permissions 700 - Group users
Needs to be Permissions 755 - Group root

All the other files in the subdirectories after that:

Changed to Permissions 600 - Group users but need to be Permissions 644 - Group root

This is the same issue previously indicated in issue #1730; Post-processing script error: 'module' has no attribute 'Session' and also in issue #1731 and #1739
If you change back the permissions and group settings it will work again.

I did the reinstall of the new package suggested in issue #1730 six days ago, but after the first update I got for that fresh install (last night), the same thing happens, see error mentioned in the first part of this message.

I also did an update for a friend, where I had previously corrected the settings manually, which fixed the problem without the need for a new package and everything kept on working, the settings were not changed again.

**Comment by miigotu** [comment]
How are you starting SR? How are you updating it? This is likely a configuration problem on your system. Check your startup script. *.py should be 775, as it is in the source. Is your SR running or updating from a share or something?

```
miigotu@srv:/opt/SickRage/autoProcessTV $ ls -l
total 36
-rw-rw-r-- 1 miigotu miigotu   72 Dec  5  2014 autoProcessTV.cfg.sample
-rwxrwxr-x 1 miigotu miigotu 4410 Apr 30 05:32 autoProcessTV.py
-rwxrwxr-x 1 miigotu miigotu  972 Dec  5  2014 hellaToSickBeard.py
drwx------ 3 miigotu miigotu 4096 May 19 11:05 lib
-rwxrwxr-x 1 miigotu miigotu 7294 Apr 30 05:32 mediaToSickbeard.py
-rwxrwxr-x 1 miigotu miigotu 1138 Dec  5  2014 sabToSickBeard.py
-rwx------ 1 miigotu miigotu  374 Dec 15 23:19 setup.py
```

**Comment by ejc1967** [comment]
Why did you close this issue without waiting for my comments ??
I'm running a package from SynoCommunity that has been running and updating fine for a year now and only after the update e39fae0502b0993fd0163ea2f6888871426465be it started to fail and not only for me, as evident by the other issues I mentioned.
So I don't understand why you assume it something related to just my system.
SR is updating true GIT, as it has been for that year, not from any share or something.

Also the new package from SynoCommunity worked for the first 6 day's until it was updated again true GIT and that the permission were changed again as I mentioned.

So it clearly looks like the update change the permissions, that why I'm addressing this so it can be fixed.

**Comment by miigotu** [comment]
Just because I closed it doesn't mean I don't see your comments, it just removes it form the list of new issues.

I only made changes to the lib folder in autoProcessTV, and no permissions were changed. Previously, a month ago, I made sure autoProcessTV.py and mediaToSickbeard.py used the correct requests library, nothing more.

Yes, the official package may have the right permissions originally, but on your system SR is ran with the group 'users' and creates files with that same group when it is updated. You can verify this by checking the running SR process with `ps aux | grep -i 'sick'` or whatever process viewer you have.

You fix this problem in the init/startup file.

SickRage probably shouldn't be ran as root anyways. By default, and in a proper install, it is ran with user sickrage and group sickrage, and then sickrage user is added to the group of the user's files it needs to access, and whatever user that needs to call autoProcessTV files is added to the sickrage group.

This is closed because it IS a system configuration fail, whether it be yours or Syno's official package, but that doesn't mean I won't help you fix it.

**Comment by ejc1967** [comment]
Okay, first of all thanks for response and clarification, I'm a first time user of this forum :-).

I don't really have a problem anymore since I corrected the permissions, but I was just wondering if this would ever happen again.
In the earlier mentioned issues it was just suggested to use the new package and remove the old one, but it turned out the problem reappeared with the new package as well.
That's is why I brought it up.

Maybe it has to do with the way the packages are created for Synology but it remains strange to me that this never happened before but only after these last changes.
Like I mentioned I have had that earlier Synology package running for a year and it was updated numerous times, including I recall with updates to autoProcessTV.

Then again I'm no Linux or GIT expert so I wouldn't presume to know where the problem really lies.
I just hoped if it had anything to do with the way the update changed files, my input could help to correct it.

It seems that for now, on systems where I corrected the permissions manually, new updates don't change the permissions again, so let see what happens in the future.

**Comment by miigotu** [comment]
The problem would only happen when autoProcessTV files are updated, which has not been updated for a year before a month ago. Let me explain why:

Your init script (provided with the syno package) is running SR with user root and group users.
Your sabnzbd is not running as root, and not with the group users, by default it is run as user sabnzbd and group media.

Initial files for SR have the correct permissions, user, and group. When you update using git, it uses the user and group that git is run as to create files and folders. Updating from inside SR, it gives the user root and group users which is different than the initial install.

SabNZBd is then no longer a member of the group the files belong to, because the group for the files has changed, so it no longer has permissions to read and execute the file.

The init script in syno needs fixed.

It ideally should be changed to run SR as user sickrage, group sickrage, and the source of SickRage should be `chown -R sickrage:sickrage /usr/local/sickrage/var/SickRage` . Also the data files and folder should be chowned this way if in a different location (Logs, databases, cache, config.ini).

SickRage's user should be added to the group that owns the media library and download locations
Then the user SabNZBd is run as  (technically should be user sabnzbd and either group sabnzbd or group media) should be added to the sickrage group, and the group who owns the downloads folders and their contents.

This way, user sabnzbd can rw files in the download locations without owning them, and can read and execute scripts in SickRage/autoProcessTV.
Also SickRage can rw files in the download folder and media library without owning them, and a git update from inside sickrage will create/edit files to the correct user.

**Comment by miigotu** [comment]
And to answer the question, yes, unless you fix the problems outline above, the next time anything in the autoProcessTV folder is updated you will have the problem again.

**Comment by ejc1967** [comment]
Thanks for your great explanation and insights.

It seems that that this is something clearly related to the way packages are created and installed on Synology.
If I look at other packages, it seems they all work the same way, with a user in the root group and one in the users group but almost never a new program groups.

To change all that, doesn't seem like something I would like to do right now because I don't know if I break something else.
Now everything works so why fix something that isn't really broken for this system, as long as you correct some permissions for files that need to accessed by other programs.

I would be helpful if the files in autoProcessTV and lower would have the standard permission 644, because these are the only files that need to be accessible by other programs.
Now it seems they get 600, even though other files in for example the image cache folder get 644.
This would get rid of the update problem for the autoProcessTV files.

For now I will just leave it as is and just fix it whenever autoProcessTV is changed, I now know what the problem is and can easily fix it by restoring the permissions.

**Comment by miigotu** [comment]
As I show above, the autoProcessTV folder and its children are 664 for folders, and 775 for scripts. Anyways, just fix it when autoprocesstv gets updated then.

**Comment by ulrick65** [comment]
I am glad I found this post...this has been driving me nuts and now I see what the issue is, thanks miigotu...I really appreciate the answer.  I don't have time right now to try and fix it, but will jump back on tonight and give it a go.

In your post above where you explain what permissions are needed where, groups, etc. I will have to decipher a bit more to truly understand (not a wizard at Linux, but I understand most of it).  However, I am using Synology and the Synology install.  I am curious, can you point me in the right direction on how do I change the Synology "init script" so it no longer runs as root and runs as the proper user and group as you mentioned?  

Thanks...

**Comment by miigotu** [comment]
I have no clue about how synology package/service system works, sorry.

**Comment by ulrick65** [comment]
The synology package/service is actually running as user sickrage and group users.  Both sabnzbd and sickrage are members of group users.  The issue I see is that when I update SickRage to the newest commits (from within SickRage) is sets the permissions on the autoProcessTV.py file to 600...rw for owner, but nothing for any others.  I can't seem to find what script is doing that, so I assume it must be something from git ?

**Comment by miigotu** [comment]
Is this the package you are using? http://apps.qnap.community/11-community/17-qsickrage

**Comment by ulrick65** [comment]
No, it is this one that installs directly from the Synology Package Manager

https://synocommunity.com/package/sickrage

Thanks.

**Comment by ulrick65** [comment]
Actually, I found the package area on github.  Here it is:

https://github.com/SynoCommunity/spksrc/tree/d97a1063e6de7b08dfb70e92535828afbd97befe/spk/sickrage

I am going to poke around and look at it but I am no expert...I am not even a amateur in fact with this kind of thing!  :)

**Comment by miigotu** [comment]
Oops, was thinking qnap for some reason. Should kick myself for responding when tired.

**Comment by miigotu** [comment]
Your package should be running as user sickrage and that user is in the `user` group
see:
https://github.com/SynoCommunity/spksrc/blob/d97a1063e6de7b08dfb70e92535828afbd97befe/spk/sickrage/src/dsm-control.sh
and
https://github.com/SynoCommunity/spksrc/blob/d97a1063e6de7b08dfb70e92535828afbd97befe/spk/sickrage/src/installer.sh

**Comment by ulrick65** [comment]
And it is running as that user.  The issue of it changing the permissions on the autoProcessTV stuff after an update is not clear to me though.  

I wondered if the issue is in the install.sh script for a pre or post update (starting at line 87), but I don't see anything there (other than it copies the entire var folder before and restores it after, which I don't understand...seems to me that would overwrite any new version of files in that folder (like autoProcessTV) with the old one?)  Maybe during the restore the permissions are getting rewritten?  

I did see in the post install section that line 71 does a chmod to autoProcessTV.cfg and sets it to 600...which doesn't seem right, because sabnzbd needs to read that file when it runs autoProcessTV for the first time ("includes" that file during the first run...which is likely causing a problem, but I am not positive).

Thanks.

**Comment by miigotu** [comment]
`I think its this line:
https://github.com/SynoCommunity/spksrc/blob/d97a1063e6de7b08dfb70e92535828afbd97befe/spk/sickrage/src/installer.sh#L79

I think it should be `chown -R ${USER}:${GROUP} ${SYNOPKG_PKGDEST}`

**Comment by ulrick65** [comment]
I think you are right, that is an issue...I just did a reinstall and am going through this one step at a time.  I noticed that everything is set to group "root" as you just discovered.  However, all the permissions are correct on the files so far (except for autoProcessTV.cfg...which is set to 600...which I think is going to cause sabnzbd to fail...but I will know shortly).

So, although this is wrong (sets the wrong group) it doesn't explain why autoProcessTV gets set to 600 permissions after an update.  Even if the group were correct, 600 would not allow the group access right?

Thanks for the help with this, I feel like we are onto something and maybe I get it fixed once and for all!

**Comment by miigotu** [comment]
But since autoProcessTV.py is in group root, sabnzbd also cannot access it either, since sabenzbd is running as group `users`

All three of those changes need made, and it will fix the issue.

**Comment by ulrick65** [comment]
I agree...to make it right and better.  But the initial permissions (before an update) on the files are 755, so that gives everyone read access...so sabnzbd is able to read the autoProcessTV.py file.  The problem comes in after an update, where the file permissions are changed to 600...that is the part I can't figure out why it is happening.  Even if I fix the group issue, it still wont work because after an update nobody but the owner (sickrage) has access.

I have also discovered a couple other issues that I am documenting along the way...like it does not restore itself properly.  It unzips the backup to the restore folder, but on restart it does not restore the files...it just deletes the restore folder.  Fun fun...  :)

**Comment by ulrick65** [comment]
I didn't see your previous edit...that makes sense to me, all 3 of those lines need updating.  

Not sure that helps with the update issue yet, but once I get this restored I will see what happens to the file permissions after an update

Thanks.

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/pull/1802

I've limited my PR to only changing the permissions set, not ownership, as it seems they have quite a few packages chmod'd to the `root` group (doesnt make sense)

**Comment by ulrick65** [comment]
I agree...it doesn't make sense.  The group is specified in the installer.sh at the top as it should be, but then chmod to "root"?  Also, kind of defeats the purpose of setting up a media group too (although I don't use it).  

If the group does not get changed to "users" then the permissions have to opened up to 755 or in some cases 777 I would guess?  Otherwise, sabnzbd can't read it regardless.  I guess that is the way it is working now, with the one exception being that line 71 sets autoProcessTV.cfg to 600 which causes sabnzbd to bomb out with a "permission denied" error.  If you set it to 640 then we need to add sabnzbd to the group "root" too I guess? (which seems odd to me).

In order to get a fresh install to work, here's what I had to to:

set autoProcessTV.cfg permissions to 664
edit autoProcessTV.cfg and change the port to 8899 (that is what SR is installed to by default on Synology and the port that they want it to use based on a matrix on the site).

I then had to manually copy over my backup files, because when I did the restore it extracted the files to the restore folder as it should, but on restart it does not put them in the var folder (overwriting the ones there).  It simply removes the restore folder.

After that, the fresh install works as it should.  Now I am waiting for the next update to see what happens when I update (not sure if there is a way to force an update at this point).

Thanks.

**Comment by Dr-Bean** [comment]
>I agree...it doesn't make sense. The group is specified in the installer.sh at the top as it should be, but then chmod to "root"? Also, kind of defeats the purpose of setting up a media group too (although I don't use it). 

Fwiw, several things are getting mixed up here. A package dir is limited to group `root`, seeing as in nearly all cases other (package)users have no business in entering those dirs (the only exception is, apparently, autoProcessTV scripts ;))
The `media` group can be used to allow people to set permissions on (Media-related)dirs for other people, via the DSM GUI.
The `users` groups exists for mostly legacy reasons, but we can't get rid of it without careful planning to avoid breaking existing installations. We're waiting on improvements from Synology to be able to take the next step.

**Comment by ulrick65** [comment]
Just to capture a follow up here (will also post in SynoCommunity pull thread):

I updated SickRage today and as expected, the permissions changed and caused sabnzbd to bomb out.

Here's some details along with the file permissions both after a fresh install and after the update.



On fresh install:

Group is set to "root".

Permissions on the autoProcessTV.cfg file are incorrectily set to 600 on line 71...so sabnzbd is unable to read the file to find the port

SR is installed on port 8899, but the autoProcessTV.cfg and autoProcessTV.cfg.sample file both have the port at 8081 so post processing from sabnzbd fails as it is unable to talk to SickRage (wrong port).

In order to get a fresh install to work, here's what I had to to:

set autoProcessTV.cfg permissions to 664
edit autoProcessTV.cfg and change the port to 8899 (that is what SR is installed to by default on Synology and the port that they want it to use based on a matrix on the site).

I then had to manually copy over my backup files, because when I did the restore it extracted the files to the restore folder as it should, but on restart it does not put them in the var folder (overwriting the ones there). It simply removes the restore folder.

After that, the fresh install works as it should.

After an update, it broke again.  See file permissions listed below:

Notice that autoProcessTV.py is set to 700 now (after update), whereas at fresh install it was 755.  I had to modify this to 755 after the update so sabnzbd could read it.

Question:  After an update, what happens to autoProcessTV.pyc?  Does sabnzbd recognize that autoProcessTV.py is different and recreate autoProcessTV.pyc or does it just use the old file and not pickup any changes that might have happened in autoProcessTV.py?  I could not test this as I removed the .pyc file and simply let sabnzbd recreate it before I thought about it.

Following are the various folders and files with their permissions both after a fresh install and after an update.


After fresh install (nothing touched):

DiskStation> pwd
/volume1/@appstore/sickrage
DiskStation> ls -al
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 .
drwxrwxrwx   15 root     root          4096 Aug  2 12:33 ..
drwxr-xr-x    3 sickrage root          4096 May 26 06:24 app
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 env
drwxr-sr-x    6 sickrage root          4096 Aug  2 12:44 var

DiskStation> cd var
DiskStation> ls -al
drwxr-sr-x    6 sickrage root          4096 Aug  2 12:44 .
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 ..
drwxr-sr-x    2 sickrage root          4096 Aug  2 12:34 Logs
drwxr-xr-x   10 sickrage root          4096 Aug  2 12:33 SickRage
drwx--S---    6 sickrage root          4096 Aug  2 12:44 cache
drwxr-sr-x    4 sickrage root          4096 Aug  2 12:34 cache-20150802_124401
-rw-r--r--    1 sickrage root        194560 Aug  2 12:44 cache.db
-rw-------    1 sickrage root         18522 Aug  2 12:43 config.ini
-rw-r--r--    1 sickrage root          4096 Aug  2 12:34 failed.db
-rw-r--r--    1 sickrage root         24576 Aug  2 12:44 sickbeard.db
-rw-------    1 sickrage root             6 Aug  2 12:44 sickrage.pid

DiskStation> cd SickRage
DiskStation> ls -al
drwxr-xr-x   10 sickrage root          4096 Aug  2 12:33 .
drwxr-sr-x    6 sickrage root          4096 Aug  2 12:44 ..
drwxr-xr-x    8 sickrage root          4096 Aug  2 12:44 .git
-rw-r--r--    1 sickrage root          1224 Aug  2 12:33 .gitattributes
-rw-r--r--    1 sickrage root           762 Aug  2 12:33 .gitignore
-rw-r--r--    1 sickrage root           334 Aug  2 12:33 .travis.yml
-rw-r--r--    1 sickrage root            98 Aug  2 12:33 CHANGES.md
-rw-r--r--    1 sickrage root         35130 Aug  2 12:33 COPYING.txt
-rwxr-xr-x    1 sickrage root         22738 Aug  2 12:33 SickBeard.py
-rw-r--r--    1 sickrage root           748 Aug  2 12:33 TODO.txt
drwxrwxrwx    3 sickrage root          4096 Aug  2 12:33 autoProcessTV
-rw-r--r--    1 sickrage root          6012 Aug  2 12:33 contributing.md
-rw-r--r--    1 sickrage root          8950 Aug  2 12:33 googlecode_upload.py
drwxr-xr-x    3 sickrage root          4096 Aug  2 12:33 gui
drwxr-xr-x   52 sickrage root          4096 Aug  2 12:34 lib
-rw-r--r--    1 sickrage root            95 Aug  2 12:33 news.md
-rw-r--r--    1 sickrage root          2478 Aug  2 12:33 readme.md
-rw-r--r--    1 sickrage root            26 Aug  2 12:33 requirements.txt
drwxr-xr-x    2 sickrage root          4096 Aug  2 12:33 runscripts
-rw-r--r--    1 sickrage root          8638 Aug  2 12:33 setup.py
drwxr-xr-x    9 sickrage root          4096 Aug  2 12:34 sickbeard
drwxr-xr-x    2 sickrage root          4096 Aug  2 12:33 tests
drwxr-xr-x    4 sickrage root          4096 Aug  2 12:34 tornado
-rw-r--r--    1 sickrage root          2741 Aug  2 12:33 updater.py

DiskStation> cd autoProcessTV
DiskStation> ls -al
drwxrwxrwx    3 sickrage root          4096 Aug  2 12:33 .
drwxr-xr-x   10 sickrage root          4096 Aug  2 12:33 ..
-rw-------    1 sickrage root            72 Aug  2 12:39 autoProcessTV.cfg
-rw-r--r--    1 sickrage root            72 Aug  2 12:39 autoProcessTV.cfg.sample
-rwxr-xr-x    1 sickrage root          4401 Aug  2 12:33 autoProcessTV.py
-rwxr-xr-x    1 sickrage root           972 Aug  2 12:33 hellaToSickBeard.py
drwxr-xr-x    3 sickrage root          4096 Aug  2 12:33 lib
-rwxr-xr-x    1 sickrage root          7285 Aug  2 12:33 mediaToSickbeard.py
-rwxr-xr-x    1 sickrage root          1138 Aug  2 12:33 sabToSickBeard.py
-rwxr-xr-x    1 sickrage root           374 Aug  2 12:33 setup.py
DiskStation>

DiskStation> cat autoProcessTV.cfg
[SickBeard]
host=localhost
port=8081
username=
password=
web_root=
ssl=0DiskStation>

DiskStation> cat autoProcessTV.cfg.sample
[SickBeard]
host=localhost
port=8081
username=
password=
web_root=
ssl=0DiskStation>

DiskStation> cd restore
DiskStation> ls -al
drwx--S---    3 sickrage root          4096 Aug  2 12:58 .
drwxr-sr-x    7 sickrage root          4096 Aug  2 12:58 ..
drwx--S---    5 sickrage root          4096 Aug  2 12:58 cache
-rw-------    1 sickrage root        248832 Aug  2 12:58 cache.db
-rw-------    1 sickrage root         20383 Aug  2 12:58 config.ini
-rw-------    1 sickrage root         11264 Aug  2 12:58 failed.db
-rw-------    1 sickrage root       7331840 Aug  2 12:58 sickbeard.db


AFTER UPDATE (nothing touched), keep in mind that I had set autoProcessTV.cfg permissions to 664 after the Fresh Install Above:

DiskStation> pwd
/volume1/@appstore/sickrage
DiskStation> ls -al
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 .
drwxrwxrwx   17 root     root          4096 Aug  2 16:52 ..
drwxr-xr-x    3 sickrage root          4096 May 26 06:24 app
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 env
drwxr-sr-x    9 sickrage root          4096 Aug  6 12:50 var

DiskStation> cd var
DiskStation> ls -al
drwxr-sr-x    9 sickrage root          4096 Aug  6 12:50 .
drwxr-xr-x    5 sickrage root          4096 Aug  2 12:33 ..
drwxr-sr-x    2 sickrage root          4096 Aug  6 07:44 Logs
drwxr-xr-x   10 sickrage root          4096 Aug  6 12:47 SickRage
drwx--S---    2 sickrage root          4096 Aug  6 12:46 backup
drwx--S---    7 sickrage root          4096 Aug  2 13:43 cache
drwxr-sr-x    4 sickrage root          4096 Aug  2 12:34 cache-20150802_124401
drwx--S---    6 sickrage root          4096 Aug  2 12:44 cache-20150802_130412
drwx--S---    6 sickrage root          4096 Aug  2 13:31 cache-20150802_134334
-rw-------    1 sickrage root        260096 Aug  6 12:50 cache.db
-rw-------    1 sickrage root         20388 Aug  6 12:47 config.ini
-rw-------    1 sickrage root         11264 Aug  6 01:57 failed.db
-rw-------    1 sickrage root       7331840 Aug  6 12:48 sickbeard.db
-rw-------    1 sickrage root             6 Aug  6 12:48 sickrage.pid

DiskStation> cd SickRage
DiskStation> ls -al
drwxr-xr-x   10 sickrage root          4096 Aug  6 12:47 .
drwxr-sr-x    9 sickrage root          4096 Aug  6 12:51 ..
drwxr-xr-x    8 sickrage root          4096 Aug  6 12:48 .git
-rw-------    1 sickrage users         1224 Aug  6 12:47 .gitattributes
-rw-------    1 sickrage users          762 Aug  6 12:47 .gitignore
-rw-------    1 sickrage users          334 Aug  6 12:47 .travis.yml
-rw-------    1 sickrage users           98 Aug  6 12:47 CHANGES.md
-rw-------    1 sickrage users        35130 Aug  6 12:47 COPYING.txt
-rwx------    1 sickrage users        22738 Aug  6 12:47 SickBeard.py
-rw-------    1 sickrage users          748 Aug  6 12:47 TODO.txt
drwxrwxrwx    3 sickrage root          4096 Aug  6 12:47 autoProcessTV
-rw-------    1 sickrage users         6012 Aug  6 12:47 contributing.md
-rw-------    1 sickrage users         8950 Aug  6 12:47 googlecode_upload.py
drwxr-xr-x    3 sickrage root          4096 Aug  2 12:33 gui
drwxr-xr-x   52 sickrage root          4096 Aug  6 12:48 lib
-rw-------    1 sickrage users           95 Aug  6 12:47 news.md
-rw-------    1 sickrage users         2478 Aug  6 12:47 readme.md
-rw-------    1 sickrage users           26 Aug  6 12:47 requirements.txt
drwxr-xr-x    2 sickrage root          4096 Aug  6 12:47 runscripts
-rw-------    1 sickrage users         8638 Aug  6 12:47 setup.py
drwxr-xr-x    9 sickrage root          4096 Aug  6 12:48 sickbeard
drwxr-xr-x    2 sickrage root          4096 Aug  6 12:47 tests
drwxr-xr-x    4 sickrage root          4096 Aug  6 12:48 tornado
-rw-------    1 sickrage users         2741 Aug  6 12:47 updater.py

DiskStation> cd autoProcessTV
DiskStation> ls -al
drwxrwxrwx    3 sickrage root          4096 Aug  6 12:47 .
drwxr-xr-x   10 sickrage root          4096 Aug  6 12:47 ..
-rw-rw-r--    1 sickrage root            72 Aug  2 14:12 autoProcessTV.cfg
-rw-------    1 sickrage users           72 Aug  6 12:47 autoProcessTV.cfg.sample
-rwx------    1 sickrage users         4401 Aug  6 12:47 autoProcessTV.py
-rw-------    1 sabnzbd  users         3258 Aug  2 14:05 autoProcessTV.pyc
-rwx------    1 sickrage users          972 Aug  6 12:47 hellaToSickBeard.py
drwxr-xr-x    3 sickrage root          4096 Aug  6 12:47 lib
-rwx------    1 sickrage users         7285 Aug  6 12:47 mediaToSickbeard.py
-rwx------    1 sickrage users         1138 Aug  6 12:47 sabToSickBeard.py
-rwx------    1 sickrage users          374 Aug  6 12:47 setup.py

DiskStation> cat autoProcessTV.cfg
[SickBeard]
host=localhost
port=8899
username=
password=
web_root=

DiskStation> cat autoProcessTV.cfg.sample
[SickBeard]
host=localhost
port=8081
username=
password=
web_root=
ssl=0DiskStation>


Let me know your thoughts or if there is other testing I should do.
