### ISSUE TITLE
Subtitle Language Flag - Afrikaans

### ISSUE THREAD

**Issue by Veldkornet** [SiCKRAGETV/sickrage-issues#1859]
In Subtitle Search -> Subtitle language, if you select "Afrikaans", the flag is wrong....

Afrikaans (af, afr, af-za) is a form of Dutch, originating and used mostly in South Africa. See -> [url]http://en.wikipedia.org/wiki/Afrikaans[/url]

Now, I'm not sure what flag this is being used in SickRage for Afrikaans (Afganistan maybe??), but it's definitely not that of South Africa, and definitely not any other country which speaks Afrikaans.

Could you please update this to South Africa's flag?

**Comment by Veldkornet** [comment]
See also on the forums -> https://www.sickrage.tv/forums/showthread.php?t=23927

**Comment by neoatomic** [comment]
Sadly this cant be fixed at this time. Its a limitation of the 2 letter country codes.
This happens when 2 country's/languages use the same 2 letter shortcut.
If we change the flag for you than it will show wrongly for other users. 

We have planned to completely overhaul the subtitle part and than use 3 letter country codes. That would solve this issue. 
And as this is already on the ToDo list i will close this.

**Comment by Veldkornet** [comment]
@neoatomic this has now been fixed which is awesome, thanks! However I noticed that it wasn't also copied to the country flags (as it didn't exist before in the country flags). Therefore, the country of origin (country code ZA) is not reflected for the show. 

Hence, can you please copy:
https://github.com/SiCKRAGETV/SickRage/tree/master/gui/slick/images/subtitles/flags/afr.png

To:
https://github.com/SiCKRAGETV/SickRage/tree/master/gui/slick/images/flags/za.png

**Comment by neoatomic** [comment]
@Veldkornet You are right, completely forgot about your previous request. 
Should be fixed with the next update. :)
