### ISSUE TITLE
[APP SUBMITTED]: global name 'time' is not defined

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#1901]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: global name 'time' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ovizii** [comment]
In which version has this been fixed? I am still getting the error:

`AANameError: global name 'time' is not defined
AA    time.sleep(cpu_presets[sickbeard.CPU_PRESET])
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/properFinder.py", line 246, in _downloadPropers
AA    self._downloadPropers(propers)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/properFinder.py", line 51, in run
AA    self.action.run(self.force)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-07-02 10:23:20 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: global name 'time' is not defined
AA
AA
AA
AA`

`Configuration
SR Version:	BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
SR User:	media
SR Locale:	(None, None)
SR Config file:	/var/db/sickrage/config.ini
SR Database file:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage/Logs
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]`

**Comment by miigotu** [comment]
That mutation of that error has not been fixed yet. I will hotfix it now and you can update.

**Comment by miigotu** [comment]
@ovizii Done, update please.

**Comment by ovizii** [comment]
successfully updated, hope that's that. Thanks for the quick reaction!

**Comment by miigotu** [comment]
@ovizii Sorry about that, we are in the middle of some major changes so some things can/are/will be broken sometimes in the near future. Best to not update from here until it settles down unless you want to test half written stuff on your precious library =P

All jokes aside, I made a mistake of prematurely merging the subtitle stuff into develop because I had no other way of getting it tested.
After subtitles changes are made I will be doing features in a separate branch on the main repo from now on, to make it easier on me and our testers without having to dirty the develop branch. Also, other collaborators will be able to PR against the same feature branch and actually collaborate for once.
