### ISSUE TITLE
SickRage snatching episodes outside usenet retention

### ISSUE THREAD

**Issue by CentristOuevre** [SiCKRAGETV/sickrage-issues#1910]
Branch: master
Commit hash: ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
OS and python version: Raspbian wheezy/Python 2.7.3
What I did: Set 2 seasons as WANTED
What happened: SickRage started searching usenet outside my retention limit of 30 days, sending both long-expired seasons to nzbget and marking them as SNATCHED, meaning they won't be looked for again (?)
What I expected: Retention limit to be obeyed, and the seasons to remain WANTED in case SickRage finds new releases of both seasons at some future point.
Link to a copy/paste of my logfile with clear debug info of the error on GIST: https://gist.github.com/CentristOuevre/c10e9b3aba3630f69e41

**Comment by miigotu** [comment]
Sorry, I made a change that set the maximum age allowed for an episode to be the number of days since it aired + 1 to limit spam requests and fake releases, but did not take into account the users defined limit. I will change it to be like `max(user_maxage, limit_maxage)`.

Let me finish up this dependancy junk I'm working on first.

**Comment by CentristOuevre** [comment]
Thank you for picking up on this. I was sure it respected the retention limit before and I didn't do anything wrong.

**Comment by miigotu** [comment]
Will be merged into develop shortly.

**Comment by CentristOuevre** [comment]
If the issue of episodes getting snatched which are outside retention setting is fixed, is it going to become part of master at any point?

**Comment by fernandog** [comment]
soon. need to fix some critical errors yet
