### ISSUE TITLE
Backlog Issue

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#1938]
Hi

BRANCH: (master)
COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
OpenElec RPI 2
Python Version: 2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]

I am getting the below error in the logs. Also Backlog is running all the time and it has found tons of items i did not want it to find.

2015-06-30 12:26:49 SEARCHQUEUE-BACKLOG-6659 :: Exception generated in thread SEARCHQUEUE-BACKLOG-6659: list modified during sort

Is this a setting or an bug.

Thanks

**Comment by fernandog** [comment]
@Vodka2014  did you deleted any shows recently?

**Comment by Vodka2014** [comment]
@fernandog No I did not. i even rebooted my system and backlog is still running. It should only run for a bit then stop correct ?

**Comment by miigotu** [comment]
`I am getting the below error in the logs. Also Backlog is running all the time and it has found tons of items i did not want it to find.`

When any search happens, and the rss cache for that indexer is out of date, it searches ALL new releases on that indexer and sees if they are in your show list, to see if it needs to be cached. Just because it says 'trying to cache' and 'unable to cache' does not mean it is finding stuff you dont want.

**Comment by miigotu** [comment]
Also, openning a second issue after I already explained this does not help anyone.

**Comment by Vodka2014** [comment]
The issue is that it is also getting stuff that was posted over 2 to 3 years ago. I am going to have to check the status of all the the shows to skipped. 

Thanks

**Comment by miigotu** [comment]
It is supposed to get old episodes that have status wanted, regardless if it is even 30 years old. That is what "Backlog" is for.

If you dont want something downloaded, that is what skipped and ignored status' are for.

**Comment by Vodka2014** [comment]
I agree with you 100% sure it is running all the time and does not stop. This is the issue. It is causing issues with new shows and daily search. I had to pause it to get it to run the Daily Search,

I do not know what is going on but more and more issues are coming up every day.

**Comment by Vodka2014** [comment]
Just a note that the update just fixed this issue and now it is stopped as it should be. thanks :)

**Comment by miigotu** [comment]
I think if you are using nzb and the backlog was snatching nab's from the indexers that were posted too long ago to still be valid because USENET_RETENTION was not honored then I need you to explain your problems better next time -.-.

I could have told you that was fixed already.

When something doesn't/can't get fixed it is usually either ebkac or the user is not explaining the problem with enough details/facts to properly diagnose the problem (also ebkac).
