### ISSUE TITLE
Doesn't overwrite SD quality with HD quality when the name is the same, and only folder contains quality tag

### ISSUE THREAD

**Issue by Merwenus** [SiCKRAGETV/sickrage-issues#1978]
EDIT.: Found out: same name = "already processed" doesn't matter if the folder name was different. Manual post processing with "Force already Post Processed Dir/Files" fix this issue, the problem is that automatic post process does not have this force post process option.
Any suggestions how to resolve this? How can I use Force post processing every 20 minutes? Even with command line and cronjob.

SR Version: 	BRANCH: (master) / COMMIT: (4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8) 
Python Version:	2.7.10 (default, Jun 3 2015, 18:49:44) [GCC 4.6.4]
Synology DSM latest + Custom GIT SickBeard / SickRage

Flexget downloads/renames SD torrent to download folder:
/!/!Delete/Anger.Management.S02E61.WEB-DL.x264.HUN-SLN/Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv

PostProcess complete, everything is fine.
2015-07-06 14:39:32 INFO     POSTPROCESSER :: Processing succeeded for /volume1/Downloads/!/!Delete/Anger.Management.S02E61.WEB-DL.x264.HUN-SLN/Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv
2015-07-06 14:39:17 INFO     POSTPROCESSER :: Release name (Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber) found from file (Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.nfo)
2015-07-06 14:39:16 INFO     POSTPROCESSER :: Processing /volume1/Downloads/!/!Delete/Anger.Management.S02E61.WEB-DL.x264.HUN-SLN/Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv (None)

Flexget downloads/rename HD (720p is only in foldername, file name is the same as the SD was) torrent to download folder 1 hour later:
/!/!Delete/Anger.Management.S02E61.720p.WEB-DL.H.264.Hun.Eng-HHD/Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv"

PostProcess complete, doesn't recognize as 720p version.
2015-07-06 15:38:26 DEBUG    POSTPROCESSER :: Processing folder /volume1/Downloads/!/!Delete/Anger.Management.S02E61.720p.WEB-DL.H.264.Hun.Eng-HHD
2015-07-06 15:38:26 DEBUG    POSTPROCESSER :: Parsed Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv into Anger Management - S2E61 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-07-06 15:38:26 DEBUG    POSTPROCESSER :: Found unwanted files: ['Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.nfo']
2015-07-06 15:38:26 DEBUG    POSTPROCESSER :: Using cached parse result for: /volume1/Downloads/!/!Delete/Anger.Management.S02E61.720p.WEB-DL.H.264.Hun.Eng-HHD
2015-07-06 15:38:26 DEBUG    POSTPROCESSER :: Already Processed /volume1/Downloads/!/!Delete/Anger.Management.S02E61.720p.WEB-DL.H.264.Hun.Eng-HHD/Anger Management - s02e61 - Charlie, Lacey and the Dangerous Plumber.mkv : Skipping

Tried with the same settings in SickBeard, it automatically removed the SD version, and copied the 720p version, I just can't do the same in SickRage, quality and file stays SD, and didn't get any help on any forums.

Quality Settings:
Initial: SDTV, SD DVD, Unknown
Replace with: HDTV, RawHD, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay 

But tried with HD and 720p and 1080p too. Nothing helped.

Config file:
http://pastebin.com/Fynwxdda

Log file:
http://pastebin.com/TKRSHfw7
Full Log file

**Comment by miigotu** [comment]
Must be something broken in release name detection, as it is supposed to use the folder name first. You don't want to force already PP files automatically, because what would happen if you had set to copy instead of move? It would constantly keep reprocessing already processed files and copying them, and would kill your HDD within weeks.

**Comment by Merwenus** [comment]
Force Postprocessing skip the same name + same size files. So the proper thing would be always force post process. Still this is a bug, and need to be fixed.

Until then I will just ask flexget to put quality in the end of the file. And I hope they will fix it soon, because this looks bad.
Anger Management - s02e65 - Charlie and the Lap Dance of Doom (720P WEBDL H264).mkv

**Comment by miigotu** [comment]
@Merwenus flexget shouldnt be renaming files/folders. thats why you are having these problems.

**Comment by Merwenus** [comment]
Easy as a pie. Can I ask Sickrage to auto rename 19 specific shows only, and leave the rest the way they are? :)

In flexget I can easily manage 100+ series, and ask it to rename only Hungarian dub shows (and only files, not folders). I can't do this in sickrage/sickbeard.

I know I have problems with SickRage, but don't blame me or Flexget, because I've tested this things in SickBeard yesterday, and It processed everything the way it is expected. I'm using Sickbeard for over 2 years without a problem, but the lack of updates and functionality forced me to switch to SickRage, which is better, but buggy. I just hope the devs support it, and fix it asap, so I can finally say goodbye to SickBeard.

**Comment by miigotu** [comment]
@Merwenus just because sickrage and sickbeard operate differently, domt blame sickrage for intended behavior. If you are having flexget rename an episode, have it rename the folder too.

Regardless if you expect it to work a different way, even if maybe it should, is not that big of an issue when it is an isolated issue based on your use case and there is a way to make it work. IMHO, bugs are things you cant just fix by tweaking your configuration properly.

Someday this might matter, but now, not so much.

**Comment by Merwenus** [comment]
Closed...Thanks, why?

**Comment by miigotu** [comment]
Stop renaming the file, and SR works perfect. YOU are causing the bug because you refuse to use it how it was intended.

If all of the information SR needs to process a file is in the filename, there is no reason for it to check the folder name.  If the filename is the same as an existing one, we refuse to overwrite it (because it SHOULD be the SAME file, as scene releases are always different.) Stop renaming it or put the quality in the filename. SR thinks it is the same file.

Anything can be broken if you bend it the wrong way. Does that mean a bone is buggy if you break it? No, it just means YOU broke it.

**Comment by Merwenus** [comment]
Yes, this is the easiest way for you :) you will implement mediainfo someday, and thats why I'm not arguing with you anymore, but your thinking is just like the ones who said the "Sun is going around the Earth, and everyone who says otherwise is stupid".

SickBeard can figure out quality easily, but sickrage works perfectly the way it is, and never need any improvement. :) I get it, okay.

I wouldn't broke it with renaming by Flexget if it would has the ability to rename only specific shows. But sickrage is like "ALL OR NOTHING".

**Comment by miigotu** [comment]
PEBKAC
