### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xe9 in position 18: invalid continuation byte

### ISSUE THREAD

**Issue by Twanislas** [SiCKRAGETV/sickrage-issues#1992]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
No Log available with ERRORS: 
### ERROR
```
Thread-90 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickBeard\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickBeard\sickbeard\webserve.py", line 1296, in displayShow
    return t.respond()
  File "C:\SickBeard\cache\cheetah\_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1315, in respond
    if _v is not None: write(_filter(_v))
  File "C:\SickBeard\sickbeard\webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "C:\SickBeard\sickbeard\exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 18: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Twanislas** [comment]
Hi !

This may be related to issue #1830.

I launched Sickrage after doing a chcp 65001.

Hope this helps ! :)

**Comment by miigotu** [comment]
utf-8 handles all languages, but if you encode to something that is not compatible with utf-8 first (like latin1) you will have problems.

Your problem happens because one of your shows has a latin1 character, which we do not handle decoding of right before trying to force to utf-8.

@fernandog The bad formatted log line you fixed earlier, should have just been switched to use ex(e.message) and it would have formatted it for you.

Also see this: http://stackoverflow.com/questions/6539881/python-converting-from-iso-8859-1-latin1-to-utf-8

@fernandog We should be trying to `.decode('iso-8859-1').encode('utf8')` if exception occurs when converting to utf-8

**Comment by miigotu** [comment]
@fernandog 
```
>>> a = '\xe9'
>>> print unicode(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
>>> print a.decode('latin-1')
é
>>> print a.decode('latin-1').encode('utf-8')
é
>>> print unicode(a.decode('latin-1'))
é
>>>
```

**Comment by miigotu** [comment]
```
>>> print unicode(a, 'latin-1')
é
>>> print unicode(a, 'utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 0: unexpected end of data
>>> 
```

**Comment by miigotu** [comment]
@fernandog I have a good solution, working on a PR now.
to create a unicode string:
`x = x.decode(chardet.detect(x).get('encoding'))`
