### ISSUE TITLE
[APP SUBMITTED]: column network_name is not unique

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#2012]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/d797bae2fba9c5b13fce
### ERROR
```
DAILYSEARCHER :: Fatal error executing query: column network_name is not unique
```
---
```
IntegrityError: column network_name is not unique
return self.connection.cursor().execute(query, args)
File "C:\Users\rusty\SickRage\sickbeard\db.py", line 77, in _execute
return self._execute(query, args)
File "C:\Users\rusty\SickRage\sickbeard\db.py", line 88, in execute
sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
File "C:\Users\rusty\SickRage\sickbeard\db.py", line 125, in mass_action
Traceback (most recent call last):
2015-07-09 07:10:39 ERROR DAILYSEARCHER :: Fatal error executing query: column network_name is not unique
```
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ripper1967** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/ffef8f672b63951db477
### ERROR
```
DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by stenavage** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/76977db0d757a05dc104
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Try deleting cache.db, nothing has changed there, and the code does not try to violate the unique contraint on primary key network_name.

**Comment by Rouzax** [comment]
I have the same after the update just now.

**Comment by mbxplex** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
No Log available with ERRORS: 
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/82af21c57085dd347fbf
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
I'm not sure how this is hapening yet, looking into it.

**Comment by miigotu** [comment]
@Rouzax can you try changing the line at https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/network_timezones.py#L157

from 
`with open(loc, 'r') as file:`
to
`with open(loc, 'rb') as file:`


delete cache.db and try again?

**Comment by miigotu** [comment]
I don't have windoze to test this one! It is only happenning on winbloze.

**Comment by miigotu** [comment]
@stenavage  @ripper1967  @mbxplex  Could one of you try that: https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120154559

**Comment by Knuta86** [comment]
I did the change and it still gives an error, but only 1 error instead of 2.

From log before change:

2015-07-10 00:31:52 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: column network_name is not unique
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage-master\sickbeard\db.py", line 125, in mass_action
AATraceback (most recent call last):
2015-07-10 00:31:52 ERROR    SHOWUPDATER :: Fatal error executing query: column network_name is not unique
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage-master\sickbeard\db.py", line 125, in mass_action
AA    my_db.mass_action(cl)
AA  File "C:\SickRage-master\sickbeard\network_timezones.py", line 200, in update_network_dict
AA    network_timezones.update_network_dict()
AA  File "C:\SickRage-master\sickbeard\dailysearcher.py", line 49, in run
AA    self.action.run(self.force)
AA  File "C:\SickRage-master\sickbeard\scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-07-10 00:31:51 ERROR    DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: column network_name is not unique
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage-master\sickbeard\db.py", line 125, in mass_action
AATraceback (most recent call last):
2015-07-10 00:31:51 ERROR    DAILYSEARCHER :: Fatal error executing query: column network_name is not unique




From log after change:

2015-07-10 00:39:13 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: column network_name is not unique
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage-master\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage-master\sickbeard\db.py", line 125, in mass_action
AATraceback (most recent call last):
2015-07-10 00:39:13 ERROR    SHOWUPDATER :: Fatal error executing query: column network_name is not unique

**Comment by Knuta86** [comment]
After a reboot of the computer I'm back to both errors again.

**Comment by krash1220** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1153ba18112827eb0fa8c71f111e076aca186416
Link to Log: https://gist.github.com/179fb05b7c5ae5befc6d
### ERROR
```
DAILYSEARCHER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/e9682b2ca29d8bcef209
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
I restarted, was prompted to update, installed update and received the above error again.

**Comment by miigotu** [comment]
Calm your nerves, it was not fixed yet. I have no idea why it is doing it.

**Comment by mbxplex** [comment]
lol very calm. I was just asked ... by you actually after looking at the email to do this. 

Regardless, let me know if I can be of further assistance. I will be available for the rest of the night.

**Comment by miigotu** [comment]
Ok, I'll try and figure it out but the code this is coming seems proper.

This issue is coming from this commit:
https://github.com/SiCKRAGETV/SickRage/commit/059e4cc8a809090fba695cd60e9822fdcfedc612

But everything there seems proper. Must be something to do with binary mode on windows.

**Comment by fernandog** [comment]
What about that commit about unicode and utf8? Related?

**Comment by mbxplex** [comment]
All of that is another language to me, but if you need me to test anything on my end to see if the error duplicates, let me know. 

Only thing that sucks about this error is sickrage won't pull any shows now :(

**Comment by rist3r** [comment]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-post2008Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/70341c1fe682a10f4f63
### ERROR
```
DAILYSEARCHER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@mbxplex I might have to revert to using the exceptions and network timezones form github repository (i like it better that way) but we had problems with people being able to update them then also.

**Comment by mbxplex** [comment]
Mind explaining that in more simplistic terms? Also, do you believe this is what's causing the error?

**Comment by mbxplex** [comment]
I never tried deleting my cache.db ... decided to try that since I'm falling behind on my episodes a little bit and after I restarted I still generated the same error. 

After checking the logs (post-restart) to see if SR was searching for any new episodes, I noticed logs surrounding the error I hadn't noticed before. Maybe it was there before, maybe it wasn't, but I thought I would post it, it case it was useful to you.

2015-07-10 00:06:43 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage\sickbeard\db.py", line 125, in mass_action
AA    my_db.mass_action(cl)
AA  File "C:\SickRage\sickbeard\network_timezones.py", line 200, in update_network_dict
AA    network_timezones.update_network_dict()
AA  File "C:\SickRage\sickbeard\showUpdater.py", line 46, in run
AA    self.action.run(self.force)
AA  File "C:\SickRage\sickbeard\scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-07-10 00:06:41 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: column network_name is not unique
AAIntegrityError: column network_name is not unique
AA    return self.connection.cursor().execute(query, args)
AA  File "C:\SickRage\sickbeard\db.py", line 77, in _execute
AA    return self._execute(query, args)
AA  File "C:\SickRage\sickbeard\db.py", line 88, in execute
AA    sqlResult.append(self.execute(qu[0], qu[1], fetchall=fetchall))
AA  File "C:\SickRage\sickbeard\db.py", line 125, in mass_action
AATraceback (most recent call last):
2015-07-10 00:06:41 ERROR    SHOWUPDATER :: Fatal error executing query: column network_name is not unique

**Comment by cwerdam** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/24237512b24ce32a4f6d
### ERROR
```
DAILYSEARCHER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@abeloin can you look at what I messed up in sickbeard/network_timezones.py?

**Comment by LouisF410** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/9aab882a23e575f7ca67
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
Error log updated ... when I pasted earlier, it didn't pasted the entire log.

**Comment by Rouzax** [comment]
My timezone :smile:  is now awake so if you need anything let me know.

**Comment by stervis** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ba8406163ad4ed0b6578cd6e76fdde3e69c28cf8
Link to Log: https://gist.github.com/9baf1efcfe0886038832
### ERROR
```
SHOWUPDATER :: Fatal error executing query: column network_name is not unique
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@Rouzax in sickbeard/network_timezones.py, line 186, can you try changing it from:
['UPDATE network_timezones SET network_name=?, timezone=? WHERE network_name=?', [cur_d, cur_t, cur_d]])
to:
['UPDATE network_timezones SET timezone=? WHERE network_name=?', [cur_t, cur_d]])

**Comment by stervis** [comment]
No effect. Applied changes, saved and rebooted SR

On 10 July 2015 at 09:53, miigotu <notifications@github.com> wrote:

> @Rouzax <https://github.com/Rouzax> in sickbeard/network_timezones.py,
> line 186, can you try changing it from:
> ['UPDATE network_timezones SET network_name=?, timezone=? WHERE
> network_name=?', [cur_d, cur_t, cur_d]])
> to:
> ['UPDATE network_timezones SET timezone=? WHERE network_name=?', [cur_t,
> cur_d]])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120273716>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by miigotu** [comment]
line 188:
to:
`            cl.append(['INSERT INTO network_timezones VALUES (?,?)', [cur_d, cur_t]])`

**Comment by stervis** [comment]
It's actually line 189 btw. Changed it, reboot and errors still there

On 10 July 2015 at 10:03, miigotu <notifications@github.com> wrote:

> line 188:
> to:
> cl.append(['INSERT INTO network_timezones VALUES (?,?)', [cur_d, cur_t]])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120278555>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by miigotu** [comment]
I think there is something else I changed with this, 

SickBeard.py, line 378, add `network_timezones.update_network_dict()` just under `sickbeard.start()`
(make sure its the same number of spaces indented as `sickbeard.start()` - spaces not tabs)

**Comment by Rouzax** [comment]
When it rains it pours, my internet connection just stopped and according to my ISP it can take up to 8 hours before it is reconnected, so I can't be of any help :disappointed:

**Comment by miigotu** [comment]
SR doesnt need internet to check this error =P

**Comment by miigotu** [comment]
I'm thinking the timezones are not updated yet, but more than one thread is trying to update them (and operating on the same primary keys)

**Comment by stervis** [comment]
Also getting errors now with one of my providers. While everything is
correct

2015-07-10 10:08:22 SEARCHQUEUE-BACKLOG-283468 :: [BTN] :: JSON-RPC
protocol error while accessing BTN: error (-32002, u'Call Limit
Exceeded')
2015-07-10 10:08:22 SEARCHQUEUE-BACKLOG-283468 :: [BTN] ::
Authentication error: Your authentication credentials for BTN are
incorrect, check your config.


On 10 July 2015 at 10:17, miigotu <notifications@github.com> wrote:

> I'm thinking the timezones are not updated yet, but more than one thread
> is trying to update them (and operating on the same primary keys)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120287903>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by stervis** [comment]
Didn't see your original mail, applying changes now.

On 10 July 2015 at 10:27, Stephan Vorstenberg <svorstenberg@gmail.com>
wrote:

> Also getting errors now with one of my providers. While everything is
> correct
>
> 2015-07-10 10:08:22 SEARCHQUEUE-BACKLOG-283468 :: [BTN] :: JSON-RPC protocol error while accessing BTN: error (-32002, u'Call Limit Exceeded')
> 2015-07-10 10:08:22 SEARCHQUEUE-BACKLOG-283468 :: [BTN] :: Authentication error: Your authentication credentials for BTN are incorrect, check your config.
>
>
> On 10 July 2015 at 10:17, miigotu <notifications@github.com> wrote:
>
>> I'm thinking the timezones are not updated yet, but more than one thread
>> is trying to update them (and operating on the same primary keys)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120287903>
>> .
>>
>
>
>
> --
> Met vriendelijke groeten,
>
> Stephan Vorstenberg
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by miigotu** [comment]
@stervis I pushed it as a hotfix, I think it will fix the network_name problem.

**Comment by Rouzax** [comment]
Updated to the latest master git SiCKRAGETV/SickRage@57760adc12e1559e8baa68564c064a6807769e9e and the error is gone.

**Comment by miigotu** [comment]
Sweet! Thanks for testing.

**Comment by stervis** [comment]
Somehow Sickbeard is now messed up, not running anymore. And 12 commints
behind it says...

On 10 July 2015 at 11:28, miigotu <notifications@github.com> wrote:

> Closed #2012 <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#event-352753596>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by miigotu** [comment]
cd into the sickrage dir and git pull

**Comment by stervis** [comment]
Yeh, did that :)

On 10 July 2015 at 23:38, miigotu <notifications@github.com> wrote:

> cd into the sickrage dir and git pull
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120535640>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg

**Comment by miigotu** [comment]
On master?

git fetch origin
git reset --hard origin/master

or if you are on develop:
git fetch origin
git reset --hard origin/develop

**Comment by stervis** [comment]
Yeh master.

On 10 July 2015 at 23:42, miigotu <notifications@github.com> wrote:

> On master?
>
> git fetch origin
> git reset --hard origin/master
>
> or if you are on develop:
> git fetch origin
> git reset --hard origin/develop
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2012#issuecomment-120536326>
> .
>



-- 
Met vriendelijke groeten,

Stephan Vorstenberg
