### ISSUE TITLE
Unable to find episode of Fairy tail

### ISSUE THREAD

**Issue by Olirakith** [SiCKRAGETV/sickrage-issues#2068]
Hello

My Sickrage is on a debian server
Branch: Master
Commit : 5926e2a25124c7d22f98895725464c67577c4ae7
Python Version:	2.7.9
My "bug" is : 
"SEARCHQUEUE-MANUAL-114801 :: [T411] :: The Data returned from T411 do not contains any torrent"

Sorry my english is bad..

**Comment by fernandog** [comment]
try disable proxy.

and followguide lines:
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by Olirakith** [comment]
I have not a proxy on this server But on another series everything works. just Anime.

**Comment by neoatomic** [comment]
@Olirakith Enable debug=1 in the SickRage settings and post the log with the "bug".

**Comment by Olirakith** [comment]
Sickrage.log here:
https://gist.github.com/Olirakith/afde70b43b015e01542e

**Comment by miigotu** [comment]
Every result that is not vostfr is ignored because you require vostfr.
The rest are not named properly, they are using non-anime scene release naming style.

Try searching for it with anime off.

**Comment by Olirakith** [comment]
I have the same result.

**Comment by miigotu** [comment]
@neoatomic @fernandog can you guys look into this a bit? I really need to figure out the PP problem and the failed DL history problem.

**Comment by neoatomic** [comment]
@Olirakith Can you open the Naruto Shippuden show in SickRage and click on "edit" ?
There should be a field named "Scene Exceptions. Can you check what is in that field? And if there are any special/Japanese characters.? 
If so remove them and try to do a scan again.

@miigotu Might be related to. :  https://github.com/SiCKRAGETV/sickrage-issues/issues/1734

**Comment by miigotu** [comment]
@neoatomic It seems that now the japanese string is being converted to his french local: `NARUTO.ç–¾é¢¨ä¼.418`

**Comment by Olirakith** [comment]
Same result. :/
Logs:
https://gist.github.com/Olirakith/b6abf02f8b0226c56f6a

**Comment by neoatomic** [comment]
@Olirakith Just o be sure do a reboot before the scan.
And where there any special/Japanese characters in the scene exceptions list.? And did you remove them.?

**Comment by Olirakith** [comment]
reboot and same result ^^,

How have this syntax in Sickrage ?
Naruto Shippuden 402 VOSTFR 720p HDTV... 
I think it's coming "season" that it does not work.

**Comment by neoatomic** [comment]
@Olirakith If "Naruto Shippuden" is the name used for the releases than you can add that name as a Scene Exception. And the releases should be found. Just make sure there aren't any Japanese entries in the scene exceptions list.

If the season/episode numbers aren't correct than noting we can do here. You have to correct those on the indexers page. (tvdb/tvrage etc.)

**Comment by Olirakith** [comment]
I remove the japanese name, " Naruto Shippuden" is correctly in Scene Exception.
How to Remove seasons in research of Sickrage ?
Naruto Shippuden 402 VOSTFR 720p HDTV... <<<< it's name of release on T411.

sorry for my english :/

**Comment by neoatomic** [comment]
@Olirakith Ok, understand now. The 402 might be the issue as it doesn't contain a season number. (like s01e06)

@miigotu Do you know if Animidb does some sort of scene numbering to get around this problem.?

**Comment by Olirakith** [comment]
New Log :
https://gist.github.com/Olirakith/a79855b8be9ca3d59204

In this log, i see :
Found result: Naruto Shippuden 406 VOSTFR 480p HDTV x264-Resistance (https://api.t411.io/torrents/download/5291081)
2015-07-12 13:15:16 DEBUG    SEARCHQUEUE-BACKLOG-79824 :: [T411] :: Found result: Naruto Shippuden 406 VOSTFR 720p HDTV x264-Resistance (https://api.t411.io/torrents/download/5291087)
2015-07-12 13:15:16 DEBUG    SEARCHQUEUE-BACKLOG-79824 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/Naruto.Shippuden.406?cid=455&limit=100 "

But not download, and in log on Sickrage i have :

SEARCHQUEUE-MANUAL-79824 :: [T411] :: The Data returned from T411 do not contains any torrent

**Comment by miigotu** [comment]
Anime uses 3 digit season/ep like that, but does not use -rlsgroup. release groups for anime are [abcdef] - Series Name 000 - quality

If you look in the log it skips the anime because the release goup is not found. On others they are skipped because of not having vostfr required word.

I think he doesn't understand that those results were ruled out.

`Found result:` does not mean it is a valid result, it just means it is a result to add to the list to be checked if it is wanted.

`The Data returned from T411 do not contains any torrent` from a search with a difference scene exception, simply means there were no results with that search string.

All is happening how it is supposed to here, OP just doesn't understand.

**Comment by Olirakith** [comment]
sorry, I'm completely lost :/

But Thank you for everything :)

**Comment by miigotu** [comment]
@Olirakith It's just that there is no error there. You limit results to `VOSTFR`, so all of the ones that are not `VOSTFR` are found, but disqualified.

The ones that are `VOSTFR` are disqualified because of incorrect filename format.

`The Data returned from T411 do not contains any torrent` means for that specific search string there were no results on T411, we search once for each scene exception, and it seems there are a lot of those for Naruto. Some of these searches don't return results.

All is working properly.

**Comment by Olirakith** [comment]
Why I find Naruto shippuden 402 VOSTFR on T411 but no Sickrage ?

**Comment by miigotu** [comment]
The release name is invalid. Not a proper anime name because of how the release group is set. There are rules for every kind of release name. anime/tvshows/movie/music all have different rules. These anime are mixing naming rules for both tvshows and anime, so the regex absolutely cannot match properly.

This is not because sickrage has bad regex, but because those torrents have incorrect names for anime.

**Comment by Olirakith** [comment]
Ok ok. 

This means that the drives can not be by Sickrage on T411 as they all have this format? (Naruto, Fairy tail, etc)

Thank you :)
