### ISSUE TITLE
Irritating "You're using the develop branch" notification, can't find where to remove it

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#2114]
How do I get rid of the "You're using the develop branch. Please use 'master' unless specifically asked" message? I know the choice I made and why I made it, don't need to be alerted about it every time I login. 

Thanks!

**Comment by MGaetan89** [comment]
There is no option to remove this message.

Maybe it could be possible to remove the alert when using "develop" and display an alert icon in the navigation bar? It would be less intrusive but still visible enough.

**Comment by miigotu** [comment]
Lies, lol.

Go in config.ini and change developer=0 to developer=1

**Comment by miigotu** [comment]
@MGaetan89 it is fully intended to be intrusive, to urge end users not to use develop as there is always a potential for breakage and/or total destruction (LOL).

We usually only want the people who reported a bug, or our testers using develop, in order to make sure things are tested before moving them to master. Everything gets merged to master every week anyway (as long as we are fairly stable) and that is not too much time to ask end user to wait.
