### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

### ISSUE THREAD

**Issue by mbxplex** [SiCKRAGETV/sickrage-issues#2115]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-74608 :: Unable to connect to AlphaRatio provider: error ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-74608 :: [AlphaRatio] :: Unable to connect to AlphaRatio provider: error ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbxplex** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2bfdb0a92083aa969fbfada92471850379a01045
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-255325 :: Unable to connect to AlphaRatio provider: error ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Error message says it all.

**Comment by mbxplex** [comment]
@miigotu & @fernandog  The only reason I'm using this closed issue as a source to discuss this is because it is in fact closed and I hope this makes it to you. I'm becoming frustrated because I can't get any help on the regular sickrage.tv website and this is the only place where I can actually get quick support. You've both been quick with responding and I'm hoping you can help!

I am willing to donate to either of you or both, via paypal or whatever, if you will just answer these 3 damn questions! lol 

1. Can you explain, in simplistic but extensive detail, what scene numbering is, how it works in SR and why certain shows I am adding show up with it pre-selected and some do not. I don't want to F with any shows pre-setup, but at the same time, if I can pull shows quicker by enabling this option or deactivating it, I will (as long as I understand it). 

2. I currently use NZBs (through SABnzb) and torrents (through uTorrent Pro unfortunately) and I have not been able to setup SR properly to handle failed downloads properly. I've read, whether through the setup guide or in peoples comments, that SR can manage failed downloads, which then triggers the re-download of a new file, but my current setup is not working that way. 

3. (Not as important but still like to know) Checking for PROPERS. When I look through the logs, I notice that when SR is checking for proper episodes, it finds them but will not download them and follows with a message like this:

2015-07-14 21:37:18 INFO     FINDPROPERS :: Unable to find an original history entry for proper Last.Week.Tonight.With.John.Oliver.S02E17.720p.HDTV.x264-BATV. so I'm not downloading it.

3Cont. This happens every time SR attempts to search for any proper episode and I don't know why considering I followed the setup guide to a T. 

Normally I would just say F it and let SR do what it's currently doing since it works 10,000x better than downloading manually but since I currently have 288 TV series in my collection, I'd like to take full advantage of this amazing program. I know that some people are shady and say they will download just to get the answers they are looking for, so if you are worried about that, I'd be glad to donate $5 to you each to start the answering process :) 

(Can you tell I just want to solve this? haha)

**Comment by miigotu** [comment]
1. Scene numbering: When TVDB has number of seasons and the number of episodes in a season wrong or set in a different way than the "scene" believes is right (or different than how torrent/nzb's are being released for it), users/sceners create a linked list on thexem.de to give SR the right season and episode number for episodes, so that episodes will be found when searching and are assigned the right names/season/episode. If it is automatically checked, thexem.de has a defined scene numbering.

2. I suggest not using failed downloads at this time, because there is an issue where if SR downloads say SD quality and succeeds, and then later downloads HD because it is a better quality in your list, which then fails, the original SD can be snatched again in a crappy release and overwrite your perfectly good SD copy. Once it is fixed and working properly in all providers, I will create some sort of guide on it.

3. Find propers: SR will only automatically snatch a proper and replace your copy if it is the same quality and release group as the copy you have already.

Last.Week.Tonight.With.John.Oliver.S02E17.720p.HDTV.x264-BATV will only be replaced with:
Last.Week.Tonight.With.John.Oliver.S02E17.PROPER.720p.HDTV.x264-BATV

This is because Last.Week.Tonight.With.John.Oliver.S02E17.720p.HDTV.x264-BATV may be perfectly fine. IE: A proper is released exactly for the video copy they released and for that specific quality only, as there was something not "proper" about it, ones from a different group or different quality likely do not have the improper video, or they would release a PROPER for that release as well.

4. It isn't required that you donate to get answers. But if you do donate, thanks in advance.

**Comment by mbxplex** [comment]
@miigotu donate to you directly or would you prefer a donation to SR community? I've read about a donations page.... you're choice ... you answered! lol 

Thanks again for the quick response and the detailed explanation. SR has been one of the greatest things I've learned about in a long time and I'm sure it can do even more if I was smart enough to understand.

**Comment by miigotu** [comment]
No reason to get an account on thexem.de, the lists are maintained by the people actually making the releases so they are always right.

https://github.com/SiCKRAGETV/SickRage/wiki/Donations
