### ISSUE TITLE
Non Aired shows keep being status "Skipped", not "unaired"

### ISSUE THREAD

**Issue by Paradoxx2015** [SiCKRAGETV/sickrage-issues#2153]
A problem with show status. I´ll keep getting shows that are unaired with status "Skipped", the date when show will be aired correct. 

SR Version:	BRANCH: (master) / COMMIT: (efdad7f24b806536abee630cd98211b6f64997b4) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

<img width="1181" alt="skjermbilde 2015-07-16 kl 08 28 42" src="https://cloud.githubusercontent.com/assets/13360967/8716790/c348e15c-2b94-11e5-8be8-3c80b4833202.png">

**Comment by mbxplex** [comment]
It's mostly likely because your "Default EP Status" is set to skipped and also SR is not going to set shows without Airdates as WANTED. If the show's Default EP Status is set as SKIPPED, Edit the show and change it to WANTED. Once the show has an Airdate entered, either on TheTVDB or TVRage, the status will change from Skipped.

**Comment by miigotu** [comment]
![image](https://cloud.githubusercontent.com/assets/390379/8721172/0e0ee222-2b6d-11e5-9d71-f068b25be2e6.png)

**Comment by miigotu** [comment]
Next time don't open a duplicate issue, thanks.
