### ISSUE TITLE
[FR] Add "Last episode" to Sort by list in show list

### ISSUE THREAD

**Issue by gabryk91** [SiCKRAGETV/sickrage-issues#218]
Useful to know instantly what's new to watch

**Comment by fernandog** [comment]
@abeloin @TagForce I did that change in the past. didn't know how to PR in that time. Do you think it's a good idea show "Previous Aired" in Home page?

**Comment by TagForce** [comment]
@fernandog Commit it, then we'll see if it adds anything to SR and merge it if it's fine...

**Comment by fernandog** [comment]
@TagForce but is it a good information to have in HOME? Would be useful for most users or won't?

**Comment by TagForce** [comment]
I know I would use it...
Right now I check the info by sorting on next aired episode, and then from the bottom up (since the newest downloaded episodes most often have the furthest next episode), but it would be nice to be able to just sort on the last episode aired, so I can see which ones are not downloading in a glance.
