### ISSUE TITLE
Bigger is not always better

### ISSUE THREAD

**Issue by NorNogaAdmin** [SiCKRAGETV/sickrage-issues#2289]
i have had some tv shows in the past that have had file sizes ~1gb that were ~320p. sr stated them as Unknown quality. however, i am now finding episodes with file sizes ~.3 gb for ~420p. however, when post-prossed, sr kept the bigger, worse files because the newer files were smaller. if there was some logic that checked the quality lookup for both files and took the better of the 2, that would be great!

**Comment by miigotu** [comment]
It already does use qualities.

It only falls back to size if the found quality of both are considered to be the same.

This will be improved with better use of hachoir.

**Comment by NorNogaAdmin** [comment]
that's not what it just did to me

**Comment by miigotu** [comment]
Was the old episode set in sickrage as "Unknown" quality? -.-

**Comment by NorNogaAdmin** [comment]
yes

**Comment by miigotu** [comment]
then it doesnt know what quality to compare with. You either set the quality or accept that it will not be accurate.

**Comment by NorNogaAdmin** [comment]
i guess i much rather it keep a known quality then an unknown one as an option at the least?

**Comment by miigotu** [comment]
Since we dont know what the unknown quality is, we can replace it. It may be a rare copy of something at a better quality.

If it was snatched and processed by SR it would know the quality.
Instead you had it renamed without quality information and the rescanned it in and it has no clue.

We can not make unsafe assumptions with peoples precious video library.

Like I said, it is planned to improve quality detection in the future by using hachoir to detect resultion and other factors, until then you need to set unknown qualities to the quality they actually are. SickRage does not snatch unknown qualities.

**Comment by NorNogaAdmin** [comment]
if I download an episode,  it would be better than the episode that I already have. ..
