### ISSUE TITLE
[FR] Add version/hash of current show episodes

### ISSUE THREAD

**Issue by HazCod** [SiCKRAGETV/sickrage-issues#2291]
Hello,

Would it be possible to implement an API function to see if shows/episodes have been downloaded recently? [I am building a web interface for SR  & CP](https://github.com/hazcod/gunther) and I would like to not query SickRage for every show & episode every x minutes.

Using a version id or a hash, I could see if the previous fetched result should be invalidated or not.

Any other suggestions are welcome.

EDIT: Is it possible to fetch the amount of downloaded shows and episodes? That could solve this.

**Comment by miigotu** [comment]
@MGaetan89 Isn't there an api call to get recent history?

**Comment by HazCod** [comment]
I believe there is, but this would require filtering out non-interesting stuff such as updates, ...

I could match "downloaded" and compare the date, but then I would need to grep the specific show too in various formats..

**Comment by miigotu** [comment]
There is only downloaded, snatched, and subtitled IIRC. The api returns things like indexer_id, season, episode...

I guess we could set/change an md5 every time something is post processed, and then add an api call to get the md5, and external applications will know if anything new has been PP since the last check.

I'm just spit-balling here.

**Comment by HazCod** [comment]
Oh alright, I tought recent history would just return the logs.
In that case, consider this solved. Thanks you.

**Comment by miigotu** [comment]
If it doesn't return more, re-open and ping me fernandog or MGaetan89 (MGaetan89 is using the api extensively right now)
