### ISSUE TITLE
SickRage not honouring the "Paused" flag on shows

### ISSUE THREAD

**Issue by Arathen** [SiCKRAGETV/sickrage-issues#2328]
The title says it all. I have a couple of shows which are set to "Paused" status. This is reflected by the green tick next to the Paused field in the GUI. Unfortunately, they still continue to be snatched anyway.

SR Version: 	BRANCH: (master) / COMMIT: (fc0af7c295bd37f11370ca8527e55d81a6822c36) 
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
Running on Windows Server 2012 R2.

The log file (which shows nothing other than a successful snatch) is linked here:

https://gist.github.com/anonymous/0667667bff6548f2ec44

Any help would be appreciated.

Thank you.

**Comment by miigotu** [comment]
@Arathen first, you need to enable debug in the settings and then reproduce. And then provide the FULL log.

I havent found anything that would cause a paused show to download except a possible one in backlog. Your log only shows some daily search.

Do you have trakt enabled?

**Comment by lendenrk** [comment]
more logs here #2267 
As it says, I have exactly the same situation.

**Comment by Arathen** [comment]
I'm definitely not using Trakt. I don't even have a login there, and the option is turned off. The only social notifier I use is Email.

Ive just turned on debug in the .ini file, but my next paused show doesn't air until Monday.

Just for fun, after I turned debug on I set the latest episode of a paused show to "wanted" and forced both Daily and Backlog searches. In the list of "DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from" shows, none of my paused shows appear. Same result for "DEBUG    BACKLOG :: Seeing if we need anything from". So it looks like this bug lies outside of that particular code.

**Comment by miigotu** [comment]
Depends if you just updated today, because I made some changes to help prevent this.

**Comment by Arathen** [comment]
I did update today. It has not fixed the problem.

The paused show episode that I marked as "wanted" earlier, snatched 20 mins ago. I captured the log with debug turned on. It is available at the following link:

https://gist.github.com/Arathen/7d3152897fe421838cdd

Given that other people are having the same problem (also here: https://github.com/SiCKRAGETV/sickrage-issues/issues/2267 ) then I would suggest that the "Unconfirmed" flag is a little unfair. I'm not sure why Issue#2267 was marked closed. Reading the thread, no resolution ever seemed to be reached.

**Comment by miigotu** [comment]
It is unconfirmed because no team member is able to experience this problem.
The other thread was closed because Hiltronix no longer is having the issue.

Regardless, "closed" does not mean a solution, nor does it mean we stop providing support in that case.

Being hypercritical of our task management methods when we spend countless hours to fix a problem that only a handful of user have reported is a little "Unfair".

Simply because you don't understand our process does not make it any less effective.

**Comment by Arathen** [comment]
It wasn't my intention to be critical. I just want the application to work properly, and I'm sure you feel the same way. So, to that end, is there anything else you need from me in addition to the log in order to debug this problem? I'm happy to help in any way I can.

**Comment by lendenrk** [comment]
@miigotu It seems like you guys managed to fix it. Last night I had one of aired episodes that wasn't snatched and the logs were clearly saying "Skipping ..... because the show is paused". (Following this format https://github.com/SiCKRAGETV/SickRage/commit/6496415183289a570759fb9a70b41b5edf62af50)

Thank you guys for your work.

**Comment by miigotu** [comment]
Yes, RSS returns all items matching a show in your list, and was disregarding the episodes we wanted. Glad that fixed it.

**Comment by Arathen** [comment]
Thanks heaps @miigotu :) I can confirm that the problem seems to be fixed. After todays update, I have a paused show which isn't snatched, and I can see the debug message saying a paused show is being skipped.

Thank you so much for the help, and for all the work you do to keep SickRage moving forward :)

**Comment by lendenrk** [comment]
@miigotu Just some clarification..
I also noticed that the paused episode (that wasn't snatched) was even so tagged "Wanted". My default EP status is "wanted", ok, but shouldn't it be tagged "skipped"?

It seems to have more sense to me, as I choose to "skip" this episode, and even the log says "Skipping ... because the show is paused". But maybe, you guys see it differently, don't know. It's not very important, just a detail.

**Comment by lendenrk** [comment]
@miigotu That clarification doesn't really need an issue to be open for it, so when you guys have like 1 minute, it would be great (not to hurry you or anything like that :), I was affraid this was consigned to oblivion)

Thanks

**Comment by miigotu** [comment]
Paused just means it will not update the show, and it will not download anything. As soon as you unpause, it will resume where it left off (just like unpausing a movie)

If it set those episodes to something other than your default episode status, you would have to go manually set them to your default episode status.

**Comment by lendenrk** [comment]
Ok, thank you for your answer.
