### ISSUE TITLE
[Feature request] Add a confirmation dialog for error submitting 

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2336]
I've noticed a lot of the time when I'm not paying enough attention I accidently click submit error instead of clear when I know what the issue is and a quick confirmation dialog would probably stop a lot of misclicks.

**Comment by neoatomic** [comment]
Agree that would be a good idea.

**Comment by Vodka2014** [comment]
+1

**Comment by miigotu** [comment]
I will see if I can do this. I also want to add a button to upload full logs (if debug is enabled) to make it easier for users when we ask for full debug log.

**Comment by fernandog** [comment]
Agree

**Comment by miigotu** [comment]
@fernandog why don't we force debug enabled in code if user is on anything other than master?

**Comment by miigotu** [comment]
We could get rid of the config setting then =P

**Comment by fernandog** [comment]
Can remember why this setting was created. Must have a reason.
I say force debug. Like git reset. 
Make saveConfig always set 1 instead of reading UI field

**Comment by miigotu** [comment]
OK we can leave the setting, so people can force debug in master, but we will force debug in develop.

I really want to go through every setting to try and find creative ways of eliminating the need for it.

Less settings when they aren't absolutely necessary will make the settings that are necessary easier to find and understand.

I know we do a lot more with SR than for example Netflix, but did you ever see how FEW settings there are in Netflix? Because they understand that if you don't avoid excessive configuration it gives you a headache on way or another =p. More settings more problems.

**Comment by fernandog** [comment]
I like settings =)
Kodi have a great solution for that.
expert settings and standard settings.

**Comment by miigotu** [comment]
I agree with a setting if it cant be handled any other way. When deciding if a setting should be there the question should not be "Could this be useful in some situation?". It should be "Can I make the code make this decision transparently and accurately so the user doesn't have to?"

**Comment by fernandog** [comment]
Agree with that.

**Comment by miigotu** [comment]
Committed to develop.
