### ISSUE TITLE
[Feature Request] Add Tixati support.

### ISSUE THREAD

**Issue by ChaosTherum** [SiCKRAGETV/sickrage-issues#2345]
Would love Tixati support it has a web interface so it shouldn't be too difficult to add support.
Wanted to tag it as feature request but couldn't figure out how to.

**Comment by neoatomic** [comment]
Needed to Google this program. http://www.tixati.com/ Its a classic/basic P2p client that also support torrents.

However to get Tixati working it needs to have a build in API, so that SickRage can sent the torrents to it etc. But it doesn't seem to have one... 

@ChaosTherum Can you ask around if it has an API or not.?

**Comment by OmgImAlexis** [comment]
@neoatomic looks like it was asked in 2014 and left at that. http://forum.tixati.com/support/1085/
I can't find any other mentions of an API or python interface anywhere.

**Comment by neoatomic** [comment]
@OmgImAlexis Thanks for checking. Sadly without API its not possible. :(

**Comment by ChaosTherum** [comment]
Well thanks for looking. I'll look into it a bit deeper.

**Comment by adaur** [comment]
Can't you use the black hole feature?

**Comment by WebSpider** [comment]
Black hole is already in SR, we wouldnt need to do anything to support that ! :+1:

**Comment by WebSpider** [comment]
Until tixati has an API available, we won't be able to specifically support it. Feel free to reopen this issue if the API becomes available.
