### ISSUE TITLE
Sickrage not downloading anime episode even though it has the correct episode and quality

### ISSUE THREAD

**Issue by Fumler** [SiCKRAGETV/sickrage-issues#2405]
The show "God Eater" is availible on 2 different providers. The episodes are named "God Eater - 01" etc. but Sickrage only found episode 3, and when I try manuelly searching I get these errors: http://pastie.org/private/bdta1j7pa9lqrek5eh6w

Settings for the show:
Animed checked
Scene Numbering currently unchecked, but tried checked as well
Everything else is unchecked

**Comment by Fumler** [comment]
Can't find any episodes for "Fate/Stay Night: Unlimited Blade Works" either. But it got "Overlord" just fine.

**Comment by Fumler** [comment]
Turned on debug. Relevant log is here: http://pastie.org/pastes/10324119/text?key=pzq7bbkaff6m7qhn6crg

Why does it not download it when it finds it in the correct quality? :confused:

**Comment by miigotu** [comment]
episode marked as wanted? there are some issue with nyaa.

**Comment by Fumler** [comment]
Episode is marked as wanted, yes. Weird thing is other shows are downloading just fine from nyaa.

**Comment by Fumler** [comment]
Anyone got any ideas?

**Comment by ProjektTHOR** [comment]
Were you able to get this file, eventually? I can't pull it from the search provider backlog unfortunately.

**Comment by Fumler** [comment]
@ProjektTHOR Nope, I had to download it manually.

**Comment by neoatomic** [comment]
Well if its only 1 episode than its probably a 1 time error. Also i cant find the issue here...

**Comment by bdcrypt** [comment]
I've actually run into almost the exact same issue, with the exact same anime (and another, so it's not just isolated to God Eater), so maybe I can shed some more light.

SickRage was unable to find any of the first 5 episodes of God Eater (everything that was available at the time of trying). However, if I searched for God Eater on the same website through my browser, I'd find every episode so far. I spent several hours trying to work out what was causing SickRage to fail to find anything, but ended up giving up. However, just last night (or today?), episode 6 was released, and SickRage found and grabbed episode 6 without any fuss at all.

After some investigation, the *only* difference I could identify between episode 6 & the other 5 is that episode 6 had no episode name at the time of search.

Now, I don't know exactly how SickRage searches, but I noticed in my logs that every time I did a manual search it'd log like this: `Unable to find a download for: [God Eater - 001 - Lenka Utsugi]` (seems to include the episode name?). Which lead me to believe it's the presence of the episode name that's causing the search to fail. (Because if I was to search for any variation of `God Eater 01 Lenka Utsugi`, I would also find nothing. Where `God Eater 01` would work)

The website I'm searching has consistent naming across *all* episode listings (including episode 6), so it's likely to be an inconsistency with how the search is performed. And the only difference in available information I could find is the lack of episode name for episode 6.
