### ISSUE TITLE
Error sending to DownloadStation on Synology

### ISSUE THREAD

**Issue by nstead** [SiCKRAGETV/sickrage-issues#2425]
When trying to snatch to Downloadstation, I get the following:

Unable to send Torrent: return code undefined

I'm using:	BRANCH: (master) / COMMIT: (47b2d5651f0c7ef1d8d20523dee85bc950d17e14) 
Operating System: Synology DSM 5.2-5592 Update 2
Python: 2.7.10 (default, Jun 3 2015, 23:30:53) [GCC 4.6.3]

I'm running DownloadStation on a separate Synology NAS on the same network.  

Here's what I've tried:
1) Ensure that the Admin password on the DownloadStation NAS has no special characters
2) Checked that "Test connection" works in SR
3) Using a different user login (for a user that also has Admin rights).
4) Ensured that DownloadStation has a default folder

I also checked that DownloadStation works OK on its own - it does.

I've searched on the forum for this problem, and although I've found the same symptoms, I think I've covered all the solutions given, above.

Any help would be appreciated!

Debug Log:
===========
```
2015-08-04 21:56:57 ERROR    SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: DownloadStation: Unable to send Torrent: Return code undefined
AA
2015-08-04 21:56:57 DEBUG    SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: DownloadStation: Response to POST request is {"error":{"code":100},"success":false}
2015-08-04 21:56:52 DEBUG    SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: DownloadStation: Requested a POST connection to url http://192.168.0.32:5000/webapi/DownloadStation/task.cgi with Params= {} Data={'version': '1', 'api': 'SYNO.DownloadStation.Task', '_sid': u'5AXSZRMkn5AHQCBKON13758', 'destinatio
2015-08-04 21:56:52 DEBUG    SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: DownloadStation: Requested a POST connection to url http://192.168.0.32:5000/webapi/DownloadStation/task.cgi with Params= {} Data={'version': '1', 'api': 'SYNO.DownloadStation.Task', '_sid': u'5AXSZRMkn5AHQCBKON13758', 'destinati
2015-08-04 21:56:46 DEBUG    SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: Calling DownloadStation Client
2015-08-04 21:56:46 INFO     SEARCHQUEUE-BACKLOG-71721 :: [ThePirateBay] :: Downloading Americas.Next.Top.Model.S10E02 from KickAssTorrents
AANone
```

**Comment by miigotu** [comment]
@nstead you need to put the whole log in gist. This one is cut off.

**Comment by nstead** [comment]
Sorry, new to this.  Since the log is, essentially just repetitions of the above with different files, I thought what I posted above would be sufficient.

How do I put it in gist ?

**Comment by miigotu** [comment]
go to http://sr_ip:sr_port/config/ and see where your logs are located, then open sickrage.log from that location and copy/paste the contents to gist, or upload the whole file somewhere.

**Comment by nstead** [comment]
You can find the full log at https://www.dropbox.com/s/g2s5lf6g3zpvvvd/sickrage.log?dl=0

**Comment by nstead** [comment]
Bump.

**Comment by miigotu** [comment]
@neoatomic

**Comment by neoatomic** [comment]
@nstead I just setup Download station with SickRage on my own Synology. No problems, the torrent is send to DS and Downloaded. So this must be something local to your installation/setup.

I see you already have tried the most common fixes. That leaves not much other things to try...
To make sure you are running Sickrage and DS on different machines.? If there on the same machine than use `http://localhost:5000/` instead of the ip.

In case you use encrypt passwords for the config.ini than try to remove the DS password. Sometimes that can solve the problem. In case that doesn't work do a backup of sickrage and remove the sickrage package in the package center and reinstall it. (Maybe the installation got bad.) Then do a basic setup with download station and try again.

**Comment by neoatomic** [comment]
And off course you can always try another download client than DS. On the Synocommunity Repo are many to chose from. Those might work for your setup.

**Comment by nstead** [comment]
@neoatomic - thanks.  Yes, I have Sickrage running on one Synology NAS, and DS running on a different one on the same subnet.  
I already tried reinstalling sickrage - no joy.  Haven't yet tried a reinstall of DS though.

I was previously running SickRage as a "Custom Sickbeard" package, and it worked fine.  When I decided to start using the SickRage page instead is when the problems started.

I'll take a look at the other Download clients - I kinda like DS, despite it's shortcomings, 'cause it has an iPad app, but I'll check out the others.

**Comment by neoatomic** [comment]
Only other things that you can check are the firewall and if the account has WebDAV access. But because you are using the admin account that should be fine...

Alternatively you can also use the Backhole method. 
Instead of sending the torrent/nzb directly to DS, SickRage will than place it in a folder/share that you prefer. So if you create a share/folder on the other Syno you can tell Sickrage to place the torrent/nzb there. Than you can tell DS to scan/monitor that folder for new nzb/torrents and they will be added to the download list.

**Comment by WebSpider** [comment]
Check out https://github.com/RuudBurger/CouchPotatoServer/issues/3183 ... does removing the / in your download path fix it?

**Comment by miigotu** [comment]
@WebSpider can you please PR and make it .rstrip('/\\') from the download location sent to DS?

**Comment by WebSpider** [comment]
@miigotu NP, just waiting for confirmation on solving the issue from @nstead when the trailing / is removed. The complete download destination isnt shown in the logfile :/

**Comment by nstead** [comment]
Yes!  Removing the trailing / fixed the problem!  Thanks!
