### ISSUE TITLE
Where is /torrents/downloads?     

### ISSUE THREAD

**Issue by javelin4effect** [SiCKRAGETV/sickrage-issues#2430]
In the past, I was able to locate the /torrents/downloads through sickrage to set backup / restore and movie downloads folder, but through the updates, i have lost track of its location.  Can you assist.

I have a problem with skipped movies...

**Comment by neoatomic** [comment]
Well SickRage doesn't use movies. Just Tv Shows. :P 
And concerning skipping newly aired episodes, you have probably not set Default Episode Status correctly. You can  look at the News page inside Sickrage for more info how to change that setting.

`
Default Episode Status: We recently fixed this feature so you need to:
Edit your shows via 'Mass update' and set the default status to WANTED instead of SKIPPED (if you want unaired episodes to be downloaded)   
Set all new episodes that were marked SKIPPED before that to WANTED. You can check all of them at "Episode Status Management" selecting "SKIPPED" in "Manage episodes with status". Be carefull with this! Make sure you have a backup of your database. Be advised!
Now when you will add a NEW show you will be asked for two status settings: already aired episodes and unaired episodes.
`

**Comment by javelin4effect** [comment]
thanks for the reply, i believe i have set it correctly.  Sorry for the
movie reference, my tv shows were not working.  Could you tell me where the
/torrents/download folder is located?

On Thu, Aug 6, 2015 at 7:32 PM, neoatomic <notifications@github.com> wrote:

> Well SickRage doesn't use movies. Just Tv Shows. :P
> And concerning skipping newly aired episodes, you have probably not set
> Default Episode Status correctly. You can look at the News page inside
> Sickrage for more info how to change that setting.
>
>
> Default Episode Status: We recently fixed this feature so you need to:
> Edit your shows via 'Mass update' and set the default status to WANTED
> instead of SKIPPED (if you want unaired episodes to be downloaded)
> Set all new episodes that were marked SKIPPED before that to WANTED. You
> can check all of them at "Episode Status Management" selecting "SKIPPED" in
> "Manage episodes with status". Be carefull with this! Make sure you have a
> backup of your database. Be advised!
> Now when you will add a NEW show you will be asked for two status
> settings: already aired episodes and unaired episodes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/2430#issuecomment-128319072>
> .
>



-- 
Warrant Officer Three

**Comment by neoatomic** [comment]
You have to update your shows also with the wanted  Default Episode Status. Otherwise only the newly added shows will work.
Your download folder i cant tell, that depends on where you have set it in your download client. The folder that SickRage monitors you can find under general -->Post-Processing and the setting is  TV Download Dir.
