### ISSUE TITLE
SDTV episodes without codec in name marked as HDTV

### ISSUE THREAD

**Issue by samdchuck** [SiCKRAGETV/sickrage-issues#2453]
When adding for example: "Tyrant.S02E09.HDTV-KILLERS" sickrage detects this as an HDTV file while this is an SDTV file. When the filename is "Tyrant.S02E09.HDTV.x264-KILLERS" it correctly identifies it as an SD file. It's annoying because my setup is SDTV+SDDVD then SDDVD, when an HDTV is 'downloaded' is thinks it's okay and doesn't download the SDDVD when it comes out.

This is an example of a manually downloaded and added file, but the same happens when snatched by SickRage.

I'm not quite sure how long this has been going on, but it didn't do it when I started using SickRage quite some time ago. I only noticed it recently as it skipped some DVDRips for this reason.

SR Version: BRANCH: (master) / COMMIT: (99ecfb5edcae4a8e5facff73f39ff1415a5e3e96) 
Python Version: 2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
OS: Synology DSM 5.2-5592 Update 2 (2015/07/23)

Log: https://gist.github.com/abbb3343f25277fb802f
File with .x264: https://gist.github.com/1d7e096b5f9d1b0800b2

**Comment by miigotu** [comment]
Those links dont work.

**Comment by duramato** [comment]
@miigotu there's an extra .git (prob mistake) at the end of it if you remove it they work

**Comment by samdchuck** [comment]
@miigotu & @duramato weird, they worked fine for me, the .git comes with the "copy to clipboard" button.

**Comment by thezoggy** [comment]
its probably defaulting to extension detection to figure out quality.. `.mkv` = hdtv.

**Comment by samdchuck** [comment]
@thezoggy the files are .mp4 as you can see in the log.

**Comment by miigotu** [comment]
In develop it will detect by resolution. For now just gonna have to live with this rate occurrence.

**Comment by samdchuck** [comment]
@miigotu what does that mean? The resolution is SD, not HD. Why would HDTV.x264-LOL be interpreted as SD but HDTV-LOL as HD?

**Comment by OmgImAlexis** [comment]
@samdchuck it was the regex we were using that defaulted to that weird behaviour. Have you checked this since? It should have been fixed by now.

**Comment by binhex** [comment]
im seeing the exact same error, this is running latest stable release of sickrage 4.0.61, snippet of log:-

2015-09-17 12:42:21 INFO     SEARCHQUEUE-BACKLOG-79285 :: [KickAssTorrents] :: Ignoring result Doc.Martin.S07E01.Rescue.Me.HDTV.x264-ORGANiC because we don't want an episode that is SDTV

2015-09-17 12:42:21 INFO     SEARCHQUEUE-BACKLOG-79285 :: [KickAssTorrents] :: Ignoring result Doc.Martin.S07E01.Rescue.Me.HDTV.x264-ORGANiC because we don't want an episode that is SDTV

2015-09-17 12:42:21 INFO     SEARCHQUEUE-BACKLOG-79285 :: [KickAssTorrents] :: Ignoring result Doc.Martin.S07E02.The.Shock.Of.The.New.HDTV.x264-ORGANiC.mp4 because we don't want an episode that is SDTV

looks like the bug is anything with HDTV is getting interpreted as SDTV and thus skipped (as i have chosen to download hd material only)

**Comment by miigotu** [comment]
@binhex you arent seeing the same bug, because that bug was fixed.

`Doc.Martin.S07E02.The.Shock.Of.The.New.HDTV.x264-ORGANiC.mp4` IS SDTV because is it missing resolution (720p or 1080p) in the filename.

The OP was reporting issues where something like `Doc.Martin.S07E02.The.Shock.Of.The.New.HDTV-ORGANiC.mp4` was being detected as HDTV when in fact it is SDTV.
