### ISSUE TITLE
Post Processing don't use scene exception. Error: "show isn't in your list. you need to add it" 

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#25]
<a href="https://github.com/Th3MadHatter"><img src="https://avatars.githubusercontent.com/u/7431902?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Th3MadHatter](https://github.com/Th3MadHatter)**
_Sunday Nov 30, 2014 at 12:39 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/987 (13 comment(s))_

----

Problems PPing specific episodes while PPing others in the past just fine and the show dir DOES exist:

```
Processing folder /media/HDD/downloads/process/tv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv
TV_DOWNLOAD_DIR:
PostProcessing Path: /media/HDD/downloads/process/tv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv
PostProcessing Dirs: []
PostProcessing Files: ['Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv']
PostProcessing VideoFiles: ['Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /media/HDD/downloads/process/tv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for /media/HDD/downloads/process/tv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv/Forever.S01E09.6.A.M.1080p.WEB-DL.DD5.1.H.264-ECI.mkv:
Problem(s) during processing
```

As you can see in my episode list previous eps PPed just fine:
 	N 	N 	10 	The Man in the Killer Suit 	Wednesday, 03-12-14 		Unaired 	search
	N 	N 	9 	6 A.M. 	Wednesday, 19-11-14 		Snatched 1080p WEB-DL 	search
	Y 	N 	8 	The Ecstasy of Agony 	Wednesday, 12-11-14 	English 	Downloaded HD TV 	search search subtitles

**Comment by fernandog** [comment]
@Tagforce can you confirm that PP don't use scene exception when snatching with it? I think a lot of issues is related to this.

**Comment by TagForce** [comment]
@fernandog I have no idea... I've never looked at the code that handles scene exceptions. If it's done during some reg-ex run in the name_parser, then yes, it uses scene exceptions. If it's not anywhere in the name_parser, then no, it doesn't use them.

Right now I'm inclined to say it doesn't use them, because I just ran through the code that Post Processes a file from start to finish real quick, and it doesn't seem to call any scene exception code anywhere. But then, it was real quick, so I might have missed it.

**Comment by fernandog** [comment]
@TagForce so it's a huge bug. There's a lot of issues related to this

@echel0n

**Comment by TagForce** [comment]
@fernandog I'm not sure if it's a huge bug... It misses some shows, but the majority of them will be found correctly. I'm not sure it should use the scene_exceptions for PP. Searching and PP work exactly the other way around. 
For daily or backlog searching, you only have a show-name, season and episode number, and you want to get a file out of that, so you need to search. Scene Exceptions help you find what you want by allowing SR to search for more than one string, especially when it gets posted under different names.
For Post-Processing, we have a filename, and we need to find a show-name, season and episode number from that. In most cases, querying the indexer (tvdb, tvrage) with the parsed showname will give you a list of shows that it could match. It should give you the same results for most (if not all) the scene exceptions you throw at it, anyway. SR then picks the best match to a show in your SR-list from the indexer list and uses that.

The problem with Forever is that there's actually 2 shows called that on thetvdb.com.
It SHOULD pick the one with (2014) on the end, since that is the one that is on your list (even if it's called Forever without the year on disk, its indexerid will still match the Forever (2014) on tvdb). For some reason SR is not doing that properly, even though I'm looking at the code that does it.

Again, I'm not sure if using scene_exceptions are the way to go, but I see no harm in adding that option to the PP code. As long as it's an extra check on the show, and it doesn't replace the indexerlookup. It's easy enough to implement, too, given some time. All that is needed is to implement an extra check on the get_show function in helpers.py that will perform a cache check, but on the scene_exceptions table instead of the scene_name table.
SELECT indexer_id from scene_exceptions WHERE show_name = 'self.showname'; should be enough to get what we need from the scene exceptions.
We could probably even throw the indexer_id at the actual indexer to see if we get a result that we expect (namely the actual show name in the show_list for that indexer_id).

However, first let @echel0n have a look at this, because it should simply work for most, if not all, shows, unless you have two very similarly named shows in your list (like forever, AND forever (2014)).

**Comment by fernandog** [comment]
@TagForce should we still wait?

**Comment by TagForce** [comment]
@fernandog Yeah, for now. I'll have a look if I have time, but I think @echel0n is really the person who should decide if my option is the way to go.

I don't think it's a big issue, as the type of search for a download is completely different from that for a Post Process. It should get a lot more hits on the post process search for the show, simply because of the way it handles the results (and which results it gets back).

**Comment by suprdave23** [comment]
I just ran into this issue (or a very similar one) as well. Downloading The Biggest Loser, it found the torrents fine, but the video files themselves are named strangely (tblhdtvx264s10e01.mp4 for example), so as a result post processing fails as it can't figure out what show that's for.

There should be some extra smarts where SR processes the torrent file itself to see what the resulting video names will be once they are done downloading, then handle it that way. It would prevent the need for looking at scene exceptions at all.

**Comment by fernandog** [comment]
@Th3MadHatter can you try this commit? 
https://github.com/SiCKRAGETV/SickRage/pull/1431
