### ISSUE TITLE
Sickrage encoding issue

### ISSUE THREAD

**Issue by JasperTack** [SiCKRAGETV/sickrage-issues#2500]
After adding a new show (The big bang theory), I got the following issue:

![Screenshot](http://i.imgur.com/1I9UW3L.png)

I just have updated to the latest version of the master branch. Does anybody know how to resolve this issue. After searching about this error message I understood this has to do with the encoding of the file/episode names?

**Comment by miigotu** [comment]
No, it has to do with you not changing code page to utf-8.

**Comment by BodoWitcha** [comment]
I have reported this same issue as #2485 
This error is caused by the use of characters in the filename outside the normal Ascii range.
In my case `Person.of.Interest.S02E11.2πR.mkv` or
`The.Simpsons.S12E09.HOMЯ.ts`
The characters __π__ and __Я__ are causing the issue.
__miigoto__ suggested to enter the chcp 65001 command, which effectively is telling to use utf-8 (https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx)

However when using this circumvention accessing these shows resulted in a new error:
![image](https://cloud.githubusercontent.com/assets/13832556/9330219/216d5b40-45b8-11e5-8062-a4a93d4d43ee.png)

Changing code page to utf-8.results in a new above shown issue, which I will report hereafter.
