### ISSUE TITLE
New subliminal version

### ISSUE THREAD

**Issue by MichalE7** [SiCKRAGETV/sickrage-issues#2558]
Hi,
I got information from subliminal developer that new version supports napiprojekt.pl which is polish subtitle provider. I can see it's only added to develop branch only for now.
Could you update the version of subliminal in SickRage or should we wait for master branch update?

Thanks in advance,
Michal

**Comment by DDamian** [comment]
I would like to ask for the same too! :)

**Comment by miigotu** [comment]
napiprojekt was added to subliminal 8 days ago, and is not part of a release yet.

I am waiting for subliminal to stabilize before updating it again, because I just had to do a major rewrite to update subliminal and immediately after I was done it was changed majorly again, and requires major rewrite AGAIN.

**Comment by neoatomic** [comment]
As we already have an FR open for the new Subliminal i'm going to close this. 
For updates please refer to https://github.com/SiCKRAGETV/sickrage-issues/issues/2147
