### ISSUE TITLE
[Feature Request] Manually point SR to files if they fail PP

### ISSUE THREAD

**Issue by ash212** [SiCKRAGETV/sickrage-issues#2701]
Would it be possible to have SR ask us to manually point a file to its respective series in case it fails in the post process since i just tried to manually post processes a file called lucifer-pilot.hdtv-lol.mp4 and Lucifer is on my show list but this was a leaked pilot.

**Comment by flightlevel** [comment]
I assume you are on the latest SR version so that you are definitely using the TVDB as an indexer.
If you go to TVDB http://thetvdb.com/?tab=series&id=295685 you can see this episode as a special.
Sickrage recognises this as episode S00E01. Just rename the file, including S00E01 in the filename and it will postprocess

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
