### ISSUE TITLE
after update sickrage not starting [Synology]

### ISSUE THREAD

**Issue by erickgrau** [SiCKRAGETV/sickrage-issues#2709]
I can't copy paste from the Synology Package Center "Logs" section.  Some guidance would be greatly appreciated.

**Comment by erickgrau** [comment]
![screenshot_301](https://cloud.githubusercontent.com/assets/12092672/9751061/ec120c2c-566d-11e5-9195-67ac2da98915.jpg)

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/2693#issuecomment-138744098

**Comment by erickgrau** [comment]
why did you close this?  the other ticket is mostly Windows.  Also I'm trying to comment on that ticket you mentioned and it won't allow me.  Please re-open or allow me to comment.

Thanks,

Erick

ALso, how to you use "git" within Synology ?  I use Terminal in OS X and it doesn't know the command GIT

**Comment by OmgImAlexis** [comment]
It should be the same issue and you should be able to comment on it.

**Comment by flightlevel** [comment]
@erickgrau Did you install git when installing Sickrage http://www.htpcguides.com/screenshot-guide-to-install-sickrage-on-synology-nas/
If so then just follow to get a terminal up http://forum.synology.com/wiki/index.php/Enabling_the_Command_Line_Interface

Your issue is the same as others, no need to comment on it, its being worked on. Try again a bit later
