### ISSUE TITLE
INFO / REQUEST / TBA

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2731]
Hi Admins / MOD's

Since TV Rage is gone i have "500GB worth of traffic Per Month / Web Traffic Allocation: Unlimited" on my site that i can use. Someone will just have to create a site, setup the info for the correct Shows as per the Air Date or Official site.

I do not mind assisting with this.

This is just a Suggestion. Let me know if interested and i can make some arrangements for access.

OR maybe we can use - http://epguides.com

Found this site as well: http://tvcountdown.com/

Thanks

**Comment by OmgImAlexis** [comment]
TvRage is being replaced with theTvDB, there's no reason to create yet another site.

**Comment by Vodka2014** [comment]
The issue with the TvDB is that some shows it does not have or will not allow I.E WWE, Formula 1 etc.... 

So with these people are stuck so why not create a site that has shows the TVDB does not have or is this going to change and they will allow everything ?

**Comment by OmgImAlexis** [comment]
@Vodka2014 wwe and formula 1 both seem to be one there. If I'm wrong feel free to let me know and we'll reopen this. Maybe check if tvmaze.com has them as well as were looking at possibly adding that.

**Comment by WebSpider** [comment]
All, fyi, I'm currently investigating if I can reopen a TVRage-like site, maybe on a separate domain, maybe under the sickrage.tv domain.

It would be great if someone could get a hold of the content/app running on TVRage.com as that would greatly speed up things :)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider if you need any help with anything including hosting, just give me a shout. I was actually in the middle of making my own version of it before I started helping with SickRage.

Since it went down the way it did I doubt anyone would have any backups of it, did they do zip backups of the db by any chance?

**Comment by flightlevel** [comment]
The other thing is, getting the data and hosting it is the EASY part!
It's maintaining, adding and correcting the data that's the hard part.
I would of thought you would need a regular user base in the hundreds of people (thats people that contribute to the database, not end users) to have a half decent database. TVDB has the MASSIVE advantage that Kodi uses it, so you've got lots of people depending on it. If the database is maintained half-arsed, it would create more problems than it fixes Honestly, how many hours a week would you contribute to adding TV shows?

**Comment by WebSpider** [comment]
I've been at the roots of setting up the communities around ftd and tvtorrents and have some ideas about this :)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
We could honestly automate a lot of this, most of the issues that come up are because the indexer isn't being run by anyone that makes software that interfaces with it, considering we know the scene rules, know what people want and know what SR, etc. needs to work that should help a lot. We could also import a copy of either tvdb or another opensource site as the base and work from there so we'd only need to work on the newer shows and episodes.

**Comment by WebSpider** [comment]
XO, whats your timezone? We should discuss some aspects on IRC :)

-----Original Message-----

**Comment by OmgImAlexis** [comment]
+9:30 South Australia, I'll probably be on for the next 12 hours.

**Comment by WebSpider** [comment]
Ah, i just drove off for work and will be busy for just about that same period XD

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider all's good, let me know when you're free and I can work around that.

**Comment by tvdavid** [comment]
@OmgImAlexis @WebSpider Hey guys, I noticed the mention :) We have a pretty complete API already at http://www.tvmaze.com/api but if you're missing anything just let us know, and we can likely accomodate it.

**Comment by OmgImAlexis** [comment]
@miigotu if we've got the devs helping out it may be a good idea to add tvmaze as a backup.

@tvdavid does tvmaze have sports and anime shows, also are you guys dev/sickrage friendly or do you rather your site and API stay the way you've designed it? I know theTVDB and tvrage both had issues where they'd rather do it their way and not listen to the people actually using their API.

**Comment by Vodka2014** [comment]
I am glad i started a good topic :) Let me know if anything is required and i will see where i can help.

**Comment by tvdavid** [comment]
@OmgImAlexis Yes, we allow everything including sports and anime. The only criteria is that it's an actual TV show: anything that has at least two different episodes.

We're very happy to improve our API for each possible use case! Of course we cant't promise to agree with every possible proposal, but if you check our forums you'll see that almost every suggestion has been integrated. If there is anything specific you'd like to discuss, please let me know. :)

**Comment by Vodka2014** [comment]
@tvdavid Can i add Formula 1 2015 to the site and list the shows per race that gets added I.E from Sky Sports F1 and Formula 1.com

There is another project on F1 - http://forum.kodi.tv/showthread.php?tid=96518

This is the site - http://www.thesportsdb.com

This is the request in the forms - https://github.com/SiCKRAGETV/sickrage-issues/issues/872

**Comment by miigotu** [comment]
TVDB is sufficient enough. Adding yet another indexing site that adds back the maintenance effort, the risk of another site going down, and the whole hassle of converting ID's back and forth and scene names/numbering nonsense.

Kodi and others live without using more than tvdb, there is no reason we cant.

**Comment by Vodka2014** [comment]
@miigotu Then if i read the comments on #872 http://www.thesportsdb.com will be getting added for Sports ?

**Comment by miigotu** [comment]
Not anytime soon, if ever.

**Comment by WebSpider** [comment]
Good thing everyone is free to send in PR's for additional indexers!

-----Original Message-----

**Comment by WebSpider** [comment]
@tvdavid do you know about any python libs exposing your API ?

**Comment by miigotu** [comment]
@WebSpider I am reluctant to add any new indexers. Not right away at least. I really want to fix whatever is going wrong with xem in SR atm at the very least, before adding another indexer option.

Removing tvrage because it went down was a good thing for us, not a bad thing. It removed so many points of potential (and actual) failure, as well as made the code much easier to debug and maintain. End users experiencing issues now have many fewer variables to influence the operation of their install that it makes it easier to help them. Also, the only major problem with theTVDB was scene numbering, which is/was addressed with thexem.de.

There is also the issue that TVrage made the decision to handle specials totally different and made them nearly impossible to work in SR, as well as the decision to give "named seasons" of shows a whole different show id number than it's real show. These issues cannot be reintroduced.

Any candidate before adding needs to be evaluated for these things, as well as any other possible issues, after fixing any existing issues with our current indexer process.

**Comment by Vodka2014** [comment]
@miigotu This is a valid point the difference between tvrage and the tvdb BUT since the TVDB has some changes names completely different the end user like my self has to rename everything. This is not a big deal as it takes a few mins to do this.

The issue is that some shows now do not get snatches via SickRage because of the naming standard / show numbering from the NZB / Torrent vs the TVDB. 

Also Sports can no longer get Snatched as the TVDB does not allow sports and what is listed is very old. IE. F1, WWE, UFC etc....

So of you do not want to add another index site for everything can we just have it for Sport Then ?

**Comment by WebSpider** [comment]
@miigotu nevertheless your point, and you have a few very good ones here, I remember how SR came to be of interest, which is it's base features: Combining failed downloads, torrent support and TVRage. As TVRage is no more, I take the liberty to think that TVRage support was actually about "being able to add stuff that isn't on tvdb".

In that mindset I think we should find an alternative to TVRage, that meets requirements best, so that when tvdb decides to, for instance, not do sports, we have an alternative and can keep on being the most automated and complete pvr out there.

This is not something we should do tomorrow, but imo we should be aiming that direction.


-----Original Message-----

**Comment by neoatomic** [comment]
On the short therm i'm with Miigotu on this. Lets use this as an opportunity to improve the overall code.

We will need to see how this all plays out. its just to soon to make such big decisions about he indexers.
For sure a site will fill the hole that TVRage left, but it needs to have the backing of the community. 
Just a fleshy site doesn't mean that will be the case. Maybe the community will support TvMaze.com or a brand new site that will popup. Lets wait where the trend go's...

For the long term i would be in favor of extending SickRage to also serve the sports community/users. 
Think there lay some opportunity's. And adding thesportsdb.com would be interesting to look at.

**Comment by githead001** [comment]
I find the data lacking for many shows on thetvdb, where tvmaze seems to have much more complete data.  TVmaze's API also easily allows show lookups by thetvdb (and tvrage for that matter) IDs, so that should help.

As an example (there are many more), "Watch What Happens Live!" on thetvdb hasn't been updated in months (here's a new show almost every night), but tvmaze is complete.   "Mythbusters" on thetvdb incorrectly uses the year for each season (Season 2014, 2015, etc.) and incorrectly groups the episodes by year, where tvmaze correctly lists the seasons by number (01, .., .., 15).

Point is, data on thetvdb seems to be way off in far too many cases.  We really do need other options.

**Comment by OmgImAlexis** [comment]
Since this isn't an issue it's being closed, we're still discussing within the development team on what we're going to do about this but the anime/sports issue will be addressed in the near future.
