### ISSUE TITLE
Unable to manually post-process shows after updating SickRage

### ISSUE THREAD

**Issue by rEes9P** [SiCKRAGETV/sickrage-issues#2761]
**Branch:** master
**Commit hash:** bb16d3a3e4d3462a73b944c6e7d9384798774ffd
**OS:** Mac OS X 10.10.5
**Python version:** 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
**What I did:** Tried to manually post-process some episodes
**What happened:** I get the error message "This show isn't in your list, you need to add it to SB before post-processing an episode"
**What I expected:** I expected the episodes to post-process successfully. The first two episodes of the Band of Brothers episodes, for example, post-processed fine before an update to SickRage (about 4-5 days ago) broke this behavior and led to all these errors. The remaining episodes, which are now not getting pos-processed, are from the same set.
**Debug log:** https://gist.github.com/rEes9P/07326a7ccd49d07c7263

**Comment by Al-25** [comment]
Problem is probably coming from the name of some of your file : 
/Volumes/Transfer/complete/BoB/Band.of.Brothers.E05.2001.720p.BluRay.x264-EbP/oAcnexsjqhKGvQXRMOjw/RcFyQm8NB2uFGmWOSjhu.mkv
The parser won't be able to parse such file, try to rename it using the name in the path.
For example : 
/Volumes/Transfer/complete/BoB/Band.of.Brothers.E05.2001.720p.BluRay.x264-EbP/oAcnexsjqhKGvQXRMOjw/RcFyQm8NB2uFGmWOSjhu.mkv
shoudl be renamed to 
/Volumes/Transfer/complete/BoB/Band.of.Brothers.E05.2001.720p.BluRay.x264-EbP/oAcnexsjqhKGvQXRMOjw/Band.of.Brothers.E05.2001.720p.BluRay.x264-EbP.mkv
And it should work better
Kr,

**Comment by rEes9P** [comment]
Thanks for looking into this, AI-25. What I don't understand is why I was able to post-process the first two episodes, which were named in the same manner and released by the same group on the same day successfully and why I suddenly started having an issue with the remaining episodes after the update that came out about 5 days ago. Also, doesn't SickRage grab the episode info, if it is included in the folder name, given that many releases use obfuscated file names?

**Comment by Al-25** [comment]
I won't be able to answer your question regarding the first two episodes, as i d'ont see the parsing process of these files in the log you gave.If you can post it, i would perhaps be able to give you more info.
Concerning the nfo, i would say yes but only a developper (or someone who knows sickrage better than me) will be able to confirm (i haven't touch python code since a long time, hard for me to check directly in the code)
BTW, If i look at the log i don't see any trace of nfo parsing, means that sickrage  seems not "seeing" it (what is strange is that i don't even see sickrage trying to look if a nfo file exist...)
Does the NFOs  are in the same folder and with the same name than MKVs ?

**Comment by flightlevel** [comment]
That is the most bizarre naming. Why would you name the file with the actual contents complete jibberish, yet name the folders properly?
Parsing proper file names is hard enough, obfuscating the file names is just asking for difficulties
