### ISSUE TITLE
SickRage can't see my Mapped Network Drives

### ISSUE THREAD

**Issue by ProffShadow** [SiCKRAGETV/sickrage-issues#2763]
After I have installed the SickRage Windows install I can't see any network share drives.
And yes I'm running Windows 7.
SR Version: 	BRANCH: (master) / COMMIT: (37914618686ee70479da0fa4b2cca851fa49c5e2)
SR User:	XPS8700-SAMANTH$
SR Locale:	('en_ZA', 'cp1252')
SR Config file:	C:\SickRage\Data\config.ini
SR Database file:	C:\SickRage\Data\sickbeard.db
SR Cache Dir:	C:\SickRage\Data\cache
SR Log Dir:	C:\SickRage\Data\Logs
SR Arguments:	['--nolaunch', '--port=9091', '--datadir=C:\\SickRage\\Data']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

There was an previous issue -  SickRage can't see my Mapped Network Drives #2501 - but this didn't help in my case.

**Comment by WebSpider** [comment]
Is this using the new windows installer from Vince?

**Comment by ProffShadow** [comment]
Yip seems like it is the one from Vince.
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SickRage-Windows-Installer

**Comment by neoatomic** [comment]
The installer creates an service to run SickRage in the background. This account is the build-in service account From Windows. Dont think the service account can detect mapped network shares from the logged in user.?

You can try to set a different user.
Go to the services console/menu and look for the service `SickRage`. Stop it and go to Properties --> Account tab. There you can select a user account that you would like to run SickRage with.
See if that allows you to see the mapped network share/drive.

**Comment by ProffShadow** [comment]
I have done as asked, but still network drive.
The account I use is set as the Administrator for the system.
There is no securities blocking this user account to access my network.

**Comment by ProffShadow** [comment]
As I'm running on a Windows ADDC domain, do you think the Domain User account is the issue?
Should I try and create a "local" user account for this?

**Comment by neoatomic** [comment]
Did you also create the network drives under the local admin account.?
What you also can try is to create a folder that redirects to that network share. (example \\SYNOLOGY\music)

**Comment by WebSpider** [comment]
Try running it as Network service?

-----Original Message-----

**Comment by WebSpider** [comment]
Or This: http://stackoverflow.com/questions/182750/map-a-network-drive-to-be-used-by-a-service

**Comment by ProffShadow** [comment]
GOT IT TO WORK !!!
It was a combination of "psexec -i -s cmd.exe and then "net use z: \\servername\sharedfolder /persistent:yes".
You also need to change to logon user for the service.
Then Sickrage can see the network drive "Z:"

Only after a restart, I must do it all over again, and network drive shows are gone.

So the soluton worked, but only if you done restart.

**Comment by ProffShadow** [comment]
Also tried the MKLink route, but no luck. Couldn't get the network drive linked.

**Comment by vkehayas** [comment]
Are there any plans to implement a permanent fix for this?
The change of the logon user for the service does not work and neither does creating a scheduled task on startup with 

>net use z: \servername\sharedfolder /persistent:yes

As stated in the link provided the psexec trick is a hack and it's not supported, and the need to install additional software to have this functionality is not evident.

**Comment by WebSpider** [comment]
Shared folders are always created in the context of a user that creates the mapping, and are always a pain to manage, since they are removed when the user is not logged on interactively.

 

A better way to go about this would be to support CIFS UNC paths as ROOT_DIR, so we can just access the share directly in the context the process is running in.

 

Van: vkehayas [mailto:notifications@github.com] 
Verzonden: zaterdag 26 september 2015 20:28
Aan: SiCKRAGETV/sickrage-issues <sickrage-issues@noreply.github.com>
CC: Nils <nils@familievogels.nl>
Onderwerp: Re: [sickrage-issues] SickRage can't see my Mapped Network Drives (#2763)

 

Are there any plans to implement a permanent fix for this?
The change of the logon user for the service does not work and neither does creating a scheduled task on startup with 

net use z: \servername\sharedfolder /persistent:yes

As stated in the link provided the psexec trick is a hack and it's not supported, and the need to install additional software to have this functionality is not evident.

**Comment by vkehayas** [comment]
Thanks for your thoughts @WebSpider. I decided to create a symlink from the network share to a local drive as a more practical and straightforward solution with no additional software required. It is detected just fine from SR and of course it will survive a reboot. In case someone would benefit in the future the command is:

>mklink /d "c:\target_folder_name" "\\NAS_NAME\share_name"

**Comment by trendless** [comment]
It appears you skipped a \ ?

Should be: mklink /d "c:\target_folder_name" "\\NAS_NAME\share_name"
