### ISSUE TITLE
Create directory during manual post processing

### ISSUE THREAD

**Issue by jorgb** [SiCKRAGETV/sickrage-issues#2789]
It has bugged me for quite some time, that I have a ton of empty folders in my TV series, which will contain (at one point) the series to be downloaded, or when I am done with the series, contain a new episode. I do not use a fancy series manager, Kobi player or something else, just the interface on my WD Live TV player. 

It would be really helpful if the directory where the series is moved to (during manual post processing) is actually created. It is during "adding" of a new show, so why not when it is missing? This will allow me to clean up a lot of empty directories that are lingering around

**Comment by flightlevel** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2496

**Comment by crazyasyou** [comment]
@jorgb This is not a direct answer to the issue you have rasied but it might be something of interest, for many years I used XBMC (now kobi) and it had a wonderful feature that allowed emtpy folders to auto hide from the main TV folder (good for shows I'm caught up on or are on a break) it also showed the number of unwatched shows as a number at the end of the show name. I moved away from XMBC and started using a mede8er device (very good for playing content but rubbish interface with limited features) I hated having to see a 100 strong list of TV shows when only about 30-40 are active at anyone time so I came up with a bit of a hack solution that works very well for me. I'm sharing all my content from  Windows server (but this would work with linux if I changed my script)

In summary I have Sickrage/utorrent work/store my tv shows, empty folders and metadata @ 'D:\TV Series'  but I have my mede8er pointed at 'D:\TV'

'D:\TV\' is the only folder that is real, under the 'D:\TV' folder I have NTFS directory junctions pointing back at the real show folder 'D:\TV Series' but only for the shows that have video content in them. To maintain an up-to-date set of directory junctions I wrote (hacked together) a little script that runs every 24 hours removing all the NTFS directory junctions from 'D:\TV' and creating new ones for shows that have valid content, its a little dirty and a real programmer would laugh at the mess of my code but it works well for me. 

As a side note my mede8er leaves a little file the same as the shows episode name when more than 90% is watched, I have another little script that looks for these files and moves/deletes the watched shows.

**Comment by crazyasyou** [comment]
here is the code if you want to have a play


:: This script washacked together by  crazyasyou (I'm not a programmer)
:: This is a windows batch script and works on windows 7, 8 and 10 (maybe more but not tested)
:: In summary it scans one folder for media with extension *.mkv *.avi *.mp4 and then creates NTFS directory junctions
:: to another folder, it will also do a show count and tag that on the end.

@echo off &setlocal enabledelayedexpansion
:: self call the batch but with all but error level 2 missing from echo output (so screen is not spammed with mklink output)
if "%1" == "1" goto else
echo Starting TV Link Maker
call %0 1 > nul
echo done
goto done
:else:
:: Put your paths below

:: Path to the real TV shows location (this is where the real data is held and my download client stores things)
:: This location has many TV show sub-folders some are empty as I've watch all the current shows which is one of the
:: points of this script, to parse the folder and output a new folder of sym links for mede8er to use that is not
:: endless scrolling of empty folders

set showsource=D:\TV Series\

:: Path where the new sym links will be created (there is nothing in this folder other than the sym links this script creates)
:: This is the path that my mede8er is using.
set showtarget=D:\TV\

:: Clear all the old links before we process and create new ones.
:: Takes you to the directory specified by path.
pushd %showtarget%
:: list all current links in the target folder and removes them.
echo Removing Old TV Links >&2
for /f "delims=" %%r in ('dir /b /a:d') do (
		rmdir "%%r"
		)
:: Takes you back to the directory you "pushd" from.
popd

:: Number of days to go back to be considered a new show
SET XDay=5
set firstshow=yes

:: set the current date in var JDNToday as Julian Day Number
CALL :DateToJDN "%DATE%" JDNToday

:: Takes you to the directory specified by path.
pushd %showsource%

:: search the path for all shows and action where needed
for /f "delims=" %%f in ('dir /b /s *.mkv *.avi *.mp4') do (
	rem Increment the total episode count counter
	rem  set /a episodecount=!episodecount!+1
	set /a episodecount+=1
	
	rem ### Show Date section ::-
		rem get the date/time of the current file/show - 06/06/2013 08:40
		set "showdate=%%~tf"
		 		
		rem strip the time off the end - 06/06/2013
		if not "!showdate!"=="" (
			set "showdate=!showdate:~,-6!"

			rem convert the date to JDN and store in showdate
			CALL :DateToJDN "!showdate!" showdate
			rem subtract the showdate JDN from the today JDN and store as diffdays
			SET /a diffdays=JDNToday-showdate
		)
		

	rem ### Show Path Section ::-
		rem get full path of show
		set ptemp=%%~dpf
		rem get the full path and filename and add .t to the end to look for watched shows.
		set pftemp=%%f.t
		rem change path to just the showname this only works on the style of path I've used
		rem and should really be something more fancy that counts the path length and sets a var at the start,
		rem	but I know all my shows are exactly like the below format
		rem D:\TV Series\  = 13 from start
		rem D:\TV Series\XXXXXXXX\Season 0X\  \Season 0X\ = 11 off the end
		set ptemp=!ptemp:~13,-11!
		
		
rem  Delay the first show found from writing out the links until the next show is picked up
rem  This allows the loop to process all episodes in the first show path so that recent episodes works correctly
rem  first show is set to yes before we start the loop meaning newshow is set from last run or blank
if !firstshow!==yes set newshow=!ptemp!

 rem - Compare the show name from the last for loop to the current one, 
 rem - if they differ enter this IF statement section and create the links
  if not [!ptemp!]==[!newshow!] (

		:: Call the function that looks to see if the show starts with the word The
		CALL :ShowStartsThe "!newshow!" linkshowname
		rem Create the symlinks with some crap at the end so I know there are recent shows in that path.
		rem also include the total number of episodes in the show.

		echo !newshow! has !showepisodecount! unwatched episodes link created >&2
		mklink /j "!showtarget!!linkshowname! !showepisodecount! !recentshow!" "!showsource!!newshow!"
		set recentshow=
		set newshow=!ptemp!
		rem Increment the total shows count counter
		set /a showcount=!showcount!+1
		rem Reset the total episodes for this show counter
		set showepisodecount=0
	)

	rem Increment the show episode count counter
	set /a showepisodecount=!showepisodecount!+1
	rem Compare the current date to the show episode date and see if less that Xdays to mark as recent or not
	IF !diffdays! LEQ !XDay! set recentshow=New
	rem Look for a a file with the same name but with extension .t after it. These episodes are
	rem watched and we don't want them counting towards the total show episode count or recent show
	if exist !pftemp! (
		set recentshow=
		set /a showepisodecount=!showepisodecount!-1
	)

	rem Clear first run / first show 
	set firstshow=no
)


:: due to how the above for loop functions this small duplication of code is required to 
:: output the last show in the list
	CALL :ShowStartsThe "!newshow!" linkshowname
	mklink /j "!showtarget!!linkshowname! !showepisodecount! !recentshow!" "!showsource!!newshow!"
	set /a showcount=!showcount!+1


echo !episodecount! Episodes Processed. >&2
echo !showcount! Total TV Shows Processed. >&2
endlocal
:: Takes you back to the directory you "pushd" from.
popd
pause
GOTO :EOF

:: function to convert date to Julian Day Number so we can perform basic maths for recent shows
:DateToJDN "DD mm/dd/yyyy" jdn=
setlocal
set date=%~1
set /A yy=%date:~-4%, mm=1%date:~-7,2% %% 100, dd=1%date:~-10,2% %% 100
set /A a=mm-14, jdn=(1461*(yy+4800+a/12))/4+(367*(mm-2-12*(a/12)))/12-(3*((yy+4900+a/12)/100))/4+dd-32075
endlocal & set %2=%jdn%
GOTO :EOF

:: function to find and move the word The to the end of the show name so it sorts better and also pad the end 
:: with spaces so new and count text is further to the right.
:ShowStartsThe
setlocal
set linkshowname=%~1
set startthe=%linkshowname:~0,3%
if "%startthe%"=="The" set linkshowname=%linkshowname:~4%, The
rem there are lots of spaces/blanks on the end of the next line/var to pad  the end sysm link name to make it look a bit better!!
rem this would be better with some sort of char counter with the width of each char added to then make them align well
set linkshowname=%linkshowname%                               
set linkshowname=%linkshowname:~0,35%
endlocal & set %2=%linkshowname%
:done:

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by jorgb** [comment]
Here is the feature request;

http://feathub.com/SiCKRAGETV/SickRage/+58

- Jorgen
