### ISSUE TITLE
[Feature Request] Add Custom Metadata Naming Pattern

### ISSUE THREAD

**Issue by mapleleafs89** [SiCKRAGETV/sickrage-issues#280]
I like the fact that sickrage will download artwork I select. I would like the option to use a custom naming convention rather than predefined names set by the supported metadata type.

Example I want it to download banners, but rather than banner.jpg I'd like .banner.jpg. Rather than Seaon XX Banner.jpg, I also want that just .banner.jpg located in the season folder.

**Comment by fernandog** [comment]
@mapleleafs89 we can't do this because it will break PP processes of deleting associated files

@TagForce confirm?

**Comment by TagForce** [comment]
@fernandog Indeed. Associated files are associated because they start with the name of the videofile. Season posters and metadata is put into the root folder only, so there is no provisioning for moving them around when renaming. If we allow moving those files to the season folders, we need to add something that will properly identify and move them when changing the renaming pattern.

**Comment by fernandog** [comment]
@TagForce close or keep as FR?

**Comment by TagForce** [comment]
@fernandog Keep it, because it should be possible. It's just a FR we won't be adding anytime soon. We're going to overhaul a lot of stuff, and this would definitely make SR more flexible, but we need to focus on the more requested FRs first.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
