### ISSUE TITLE
Is it possible to do Post Processing without Copying or Moving ? 

### ISSUE THREAD

**Issue by kailia** [SiCKRAGETV/sickrage-issues#2864]
Hello,
Because I like checking the downloaded files, extracting the embedded subs (if any) to SRT then applying corrections to them (e.g. using Subtitle Edit), and need to check that they are the right language, I'd rather not let SickRage move the files to their final location.
The best option for me would be to let it to the unpacking, renames etc., but NOT copying or moving the episodes to their final location after that.
Is this possible ?

**Comment by OmgImAlexis** [comment]
Why not have a seperate folder where it can move them to and then you can sort the processed files from there?

**Comment by kailia** [comment]
Hi, care to explain ? If "it" is SR post-processing, the only thing it can do is move the items straight into the proper TV shows.

**Comment by miigotu** [comment]
So make it move them to a different folder than your main TV shows folder.

**Comment by kailia** [comment]
I don't see how that's possible. From the folder where the downloaded files arrive, SR's Post-processing can only move them into each TV show's folder as configured separately for each TV show. As far as I can see there's nothing in the interface that allows you to set a single common folder where all postprocessed items would be moved to - please tell me if I'm wrong.

**Comment by miigotu** [comment]
Set your root dirs to a different place than your real library, set the shows in this root dir, PP to there. Mov e files out that you want into your real library.

Do you seriously think we should rewrite a whole mess of code so that you and only you can force SR to not work how it is supposed to? Why not just turn off auto post processing, verify the files after they are downloaded, and then manually click post processing and select the folder with the files you want to process? Just remove the files you dont want before manual PP and mark them wanted again in SR.

**Comment by fernandog** [comment]
@kailia will this FR help?

https://github.com/SiCKRAGETV/sickrage-issues/issues/996
