### ISSUE TITLE
Fresh Install... qualities seem to default to HDTV

### ISSUE THREAD

**Issue by daveyboy37** [SiCKRAGETV/sickrage-issues#2873]
Ok a long winded one and i'm still a bit of a newbie. 
I ran into issues a day ago with various error messages (mainly when trying to delete a show). Last night i decided I would reinstall & may as well try the windows installer. All was good and I decided not to use the backup. Rather just let SR scan the media
I let SickRage scan the shows (all named with qualities included).. The shows are mainly Blu-Ray.
However when Scanning the shows SR picks anything with BluRay quality as HDTV 
Anything named with 1080p BluRay  is scanned as 1080p HDTV
Anything named with 720P BluRay is scanned as 720p HDTV
Anything with SD or Web-DL is identified correctly. Anything BluRay quality seems to be identified as HDTV.
I did notice the same thing a couple of months ago with a totally fresh install on Windows 10.

No massive deal as I have hardly anything in HDTV certainly not a full season of any show. With the mass update I can correct the qualities reasonably quickly... Just thought it worth mentioning.( I did look but didn't see the issue already reported.) 

In effect I'm saying that although 80%+ of my shows are (named) Blu-Ray quality after Re-scanning I end up with apparently not a single episode in Blu-Ray... They're all detected as HDTV but always with the correct resolution.
It's been a long night shift.. So time for sleep. 
PS @miigotu .. Thanks for pushing TVChaos to master and thanks for all the hard work.

**Comment by miigotu** [comment]
@daveyboy37 TVChaos provider still needs some work =P

`all named with qualities included` <-- Not correctly.

To be correctly detected as a scene quality the filename must have screen size, source, and codec. `720p.BluRay.x264`

Your renamed files have only screen size and source.
`720p.BluRay`

When this happens SR scans the resolution info from the file container and makes a guess for the screen size and source. There is no way for us to infer bluray vs web-dl vs hdtv vs rawHD from the container info.

Now that I am thinking about it, we may be able to improve the logic in that second guess by searching for bluray, web-dl, etc in the filename after we have determined the screen size.

This method was intended for the majority of people who do not have quality information in their file names and also for ones with incomplete quality info in the file names because they were renamed by SR/SB or another application. Previously they would have been simply marked `Unknown` quality.

**Comment by daveyboy37** [comment]
@miigotu 
Ah cool yeah I had missed that part , I had indeed thought that simply having Blu-Ray in the file name would suffice.
I will re visit my file naming scheme. :-)

**Comment by daveyboy37** [comment]
@miigotu 
Just on a slight related note while working around this. 
In episode status management no downloaded options are available.
So in effect there isn't a option to mass edit shows.  
![status](https://cloud.githubusercontent.com/assets/9288228/9981138/f0dd5a3a-5fab-11e5-9087-60f8ba80bafe.PNG)
I'm fairly sure a few weeks ago it allowed me to select everything with 1080 HDTV for example and change them all to 1080p Blu-Ray.
 Was it removed or did I only dream it was previously an option? 
:-)

**Comment by miigotu** [comment]
@daveyboy37 apparently someone fucked with that drop down recently.

Could you try develop and rescanning some in from scratch? I added some more logic to the quality detection: https://github.com/SiCKRAGETV/SickRage/commit/2c67cca39ee9712f5198ef7d680e3210ea517aff

**Comment by daveyboy37** [comment]
@miigotu 
Okay will have a look when i get a chance.
Sadly I'm stuck at work on nights at the moment.

**Comment by daveyboy37** [comment]
@miigotu 
I still haven't had chance to test this but I will on my days off, so thanks.
Meanwhile seeing as the issue is closed can you confirm that the second issue regarding missing qualities in episode status management overview is gonna be looked at or do i need to open a separate Bug/Issue?

**Comment by miigotu** [comment]
@daveyboy37 thats separate, but we are aware.

**Comment by daveyboy37** [comment]
@miigotu 
Thanks :-)

**Comment by hugepants** [comment]
I can confirm that the fix is working correctly.

Files named 720p BluRay and 1080p BluRay are now being scanned in correctly without needing to include the codec in the name.

Thanks @miigotu !

**Comment by daveyboy37** [comment]
Awesome @miigotu @hugepants 
I had pretty much waded through mine to alter them manually.
I will probably set up a VM  with a "dummy" install on my days off to test it out.

**Comment by miigotu** [comment]
btw, my new method will work even if it just has a match for the regex "blue?-?ray" or "web.?dl". Screen size doesn't even need to be in the file name for it to work anymore since I use hachoir to guess that. Its pretty slick!
