### ISSUE TITLE
BUG : sorting of shows list page is not remembered / Sorting with articles does not work

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#3041]
BRANCH: (master) / COMMIT: (57bafd16faff76a5f2b6fb2cc4256956011b1e95) 
Python : 2.7.6
Win 8.1
Chrome, ios safari, OS X safari

Hello

1. The shows list page is sorted with show name. When I choose to sort by active, it works but the setting is not stored anymore. So if I clear my cache or if I access Sickrage with another browser, it goes back to show name sorting. I guarantee this was working until last week I think.

2. the "include articles ("The", "A", "An") when sorting show lists" is checked and the value is 1 in the config.ini but it does not work anymore : articles are not used anymore for the sorting.

I think the 2 issues may be related so I chose to write about them in the same post.

Many thanks for any help

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Make sure to submit all the [required information.](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) Other wise we wont be able to help you.! Provide as MUCH information as you can, and tell us how to replicate the problem. For basic questions use the [forum,](https://sickrage.tv/forums/) and for Feature Requests [Feathub](http://feathub.com/SiCKRAGETV/SickRage) Also make sure the title accurately describes your issue. (Not "SR not working" etc.!) 

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by. : 

- Making sure you update to the latest version. - Checkout the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki). [Config/Install Guides] [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained) [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained) - Use the search function to see it was already reported/solved.- Try to remove the `cachemako` & `cachesessions` folders. (shut-down SickRage first) - If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted` - If you use a QNAP try this [package.](http://apps.qnap.community/11-community/17-qsickrage)  ps. If you enjoy Sickrage and like the support provided, than please consider a small [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by tchirou** [comment]
I deleted the cache folders but no luck.

**Comment by OmgImAlexis** [comment]
For reference tonight, `return ($('meta[data-var="sickbeard.SORT_ARTICLE"]').data('content') == 'True' ? (s || '').replace(/^(The|A|An)\s/i,'')) : (s || '');`.

**Comment by tchirou** [comment]
Hello
I see that you just closed the issue. The sorting with articles is fixed but it still does not store the sorting I choose after clearing the browser cache. For the moment it sorts with ended shows first which is quite useless.
Could you please plan to look into it ?
Many thanks

**Comment by OmgImAlexis** [comment]
@tchirou can you open another issue for just that, we closed this for one part of the issue. Sorry about that.

**Comment by tchirou** [comment]
Done
Thanks
