### ISSUE TITLE
Kickass connection error hostname

### ISSUE THREAD

**Issue by tiitvaher** [SiCKRAGETV/sickrage-issues#3042]
>Connection error to getURL https://kat.cr/tv/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'

Noticed problem today morning, think it comes from yesterday's evening update

>SR Version: 	BRANCH: (master) / COMMIT: (57bafd16faff76a5f2b6fb2cc4256956011b1e95)
>Todays update didnt fix it
>No proxy

```
WARNING  SEARCHQUEUE-MANUAL-263365 :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/usearch/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
WARNING  SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/tv/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
```

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Make sure to submit all the [required information.](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) Other wise we wont be able to help you.! Provide as MUCH information as you can, and tell us how to replicate the problem. For basic questions use the [forum,](https://sickrage.tv/forums/) and for Feature Requests [Feathub](http://feathub.com/SiCKRAGETV/SickRage) Also make sure the title accurately describes your issue. (Not "SR not working" etc.!) 

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by. : 

- Making sure you update to the latest version. - Checkout the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki). [Config/Install Guides] [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained) [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained) - Use the search function to see it was already reported/solved.- Try to remove the `cachemako` & `cachesessions` folders. (shut-down SickRage first) - If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted` - If you use a QNAP try this [package.](http://apps.qnap.community/11-community/17-qsickrage)  ps. If you enjoy Sickrage and like the support provided, than please consider a small [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by tiitvaher** [comment]
### Fixed it

* enabled debug and TPB search provider, got another warning

```
WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/tv/latest Error: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

* searched issues about ssl
* found fix here https://github.com/SiCKRAGETV/sickrage-issues/issues/1231#issuecomment-97815695
* stoped SR
* installed pip
```wget https://bootstrap.pypa.io/get-pip.py -O - | sudo python2```

>```
sudo apt-get install python-dev libffi-dev libssl-dev
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python2
sudo pip install --upgrade ndg-httpsclient pyasn1
````

* got 200 from ```python -c "import lib.requests.packages.urllib3 as urllib3; ca_certs = 'lib/certifi/cacert.pem'; http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=ca_certs); r = http.request('GET', 'https://sceneaccess.eu/'); print r.status"```
* skipped: ```sudo pip install --upgrade pyopenssl```
* started SR, manual search worked and no warnings in log

**Comment by FoxBJK** [comment]
I'm having this issue, but the posted steps haven't changed anything. Running on Ubuntu Server 14.04

**Comment by evilpig** [comment]
Is there an easy way to fix this on windows? I'm not too experienced with all this.

**Comment by OmgImAlexis** [comment]
Reopening since it still seems to be an issue.

**Comment by miigotu** [comment]
Negative, they are on master, fix is in develop.

**Comment by ryangribble** [comment]
Hey all, just adding a note to this issue, as I ran into the same problem (on windows) and found my way here.  It seems the mentioned fix has already been merged into master but I was still having the same error message for kat searches "hostname not matching..." etc.

I updated my python install to the latest version (from 2.7.8 to 2.7.10) and am no longer getting the error.  Thought Id add that to this issue if anybody else is in the same boat

**Comment by robertchgo** [comment]
Hi all, just to confirm with what ryangribble said, also using windows updated python to 2.7.10 and solved both TPB and KAT problems. On a side note changed the pirate bay provider file to force a non secure connection by changing any https instance to http which also solved the issue.

**Comment by mbitson** [comment]
Some users (including myself) are still experiencing this issue, as is evident here: https://github.com/SiCKRAGETV/SickRage/commit/52e90e7ae8067a29b63ffeacceeef8ebbea1d90e#commitcomment-13748581

**Comment by miigotu** [comment]
PEBKAC.

**Comment by mbitson** [comment]
My issue, while producing the exact same error as the initial post, was with SSL verification. Sickbeard was unable to verify kat.cr's cert. Disabling SSL verification resolves the issue.

**Comment by mapleleafs89** [comment]
Thanks mbitson - I had the same issue and was causing lots of missed episodes. Though the error is still present for TPB, disabling SSL resolved this issue for KAT!
