### ISSUE TITLE
Mass update : /manage page not respecting sort articles setting

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3046]
even manage.js has the same code as home.js

`return ($('meta[data-var="sickbeard.SORT_ARTICLE"]').data('content') == 'True' ? (s || '') : (s || '').replace(/^(The|A|An)\s/i,''));`
https://github.com/SiCKRAGETV/SickRage/blob/develop/gui/slick/js/new/manage.js#L7

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Please sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), other wise we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.
For basic **questions* use the [forum](https://sickrage.tv/forums/), and for **Feature Requests** [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [Config/Install Guides](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cachemako` & `cachesessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by OmgImAlexis** [comment]
@fernandog they just need to be swapped.

````
return ($('meta[data-var="sickbeard.SORT_ARTICLE"]').data('content') == 'True' ? (s || '').replace(/^(The|A|An)\s/i,'')) : (s || '');
````

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/3041
