### ISSUE TITLE
can't select a subtitle language to download

### ISSUE THREAD

**Issue by NicoLeOca** [SiCKRAGETV/sickrage-issues#3047]
BRANCH: (master) / COMMIT: (4d37c1352e1a27023ffd520a4da8ab0f024333e6) 
https://gist.github.com/4d75670af73d5aef7406.git

updated SR to last master.
previous update was 24 hours old.

it deleted the language selected in the subtitles section
![image](https://cloud.githubusercontent.com/assets/9487685/10213790/e05c5896-6811-11e5-9a5b-49b81b30c5cf.png)
and I can't put it back
it says "searching" but nothing appears

@medariox

For some reasons, I am not facing the issue in develop
BRANCH: (develop) / COMMIT: (48ce3452985c82da5107ddbf2623dc9066a92f15) 
https://gist.github.com/b7353c4538112fb3c062.git

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Please sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), other wise we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.
For basic **questions* use the [forum](https://sickrage.tv/forums/), and for **Feature Requests** [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [Config/Install Guides](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cachemako` & `cachesessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by miigotu** [comment]
If it isnt an issue in develop than why open an issue? If it is fixed in develop you will get the fix in master in a few days.

**Comment by NicoLeOca** [comment]
because there was not commit with a change in subtitles in between the 2 of them

**Comment by miigotu** [comment]
Then you need to clear browser cache or ctrl+f5

**Comment by NicoLeOca** [comment]
it fixed it
thank you
