### ISSUE TITLE
Archive deleted episodes

### ISSUE THREAD

**Issue by neojoe666** [SiCKRAGETV/sickrage-issues#3050]
In the general configuration, it was possible to set this option :
"Default deleted episode status" to "Archive"
There is only Ignored and skipped now.

Is there a reason? Is ot possible to have "Archive" back?

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Please sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), other wise we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.
For basic **questions* use the [forum](https://sickrage.tv/forums/), and for **Feature Requests** [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [Config/Install Guides](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cachemako` & `cachesessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by fernandog** [comment]
Archived was removed. Now its archive + quality.
So SR should use archive  + previous downloaded quality

**Comment by neojoe666** [comment]
I agree it should but it doesn't do it automatically.

**Comment by fernandog** [comment]
@miigotu 
Issue is here:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tv.py#L1105

should be something like this:
```
if sickbeard.EP_DEFAULT_DELETED_STATUS == 'ARCHIVED':
     curEp.status = ??? (archived + current quality)
else:
    curEp.status = sickbeard.EP_DEFAULT_DELETED_STATUS
```

**Comment by miigotu** [comment]
This isn't a bug, it was removed intentionally until a better solution could be found, so that SR wouldnt error every time it found a deleted episode.

**Comment by fernandog** [comment]
not real bug but this does what we talked about that converting Downloaded > Archived keeping quality (at least when user remove file and don't have the setting SKIP_REMOVED_FILES enabled

**Comment by fernandog** [comment]
Should I do something else?
fernandog was assigned by miigotu 2 minutes ago

**Comment by miigotu** [comment]
No, you were assigned because you made the fix, in case problems come up later we know who did the fix.

**Comment by fernandog** [comment]
tested with some files and it's working.

**Comment by miigotu** [comment]
Archived composite status has been in master for like a week.
