### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-269613 :: [TorrentDay] :: Deluge: Unable to send Torrent: Return code undefined

### ISSUE THREAD

**Issue by FlyGuy94** [SiCKRAGETV/sickrage-issues#3051]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
Link to Log: https://gist.github.com/b437038636ac46f80992
### ERROR
```
SEARCHQUEUE-BACKLOG-269613 :: [TorrentDay] :: Deluge: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Im going to assume this was a one time thing? If it is happening on every torrent let me know, but I am going to close this for now.

PS: you could also try adding or removing a slash to the end of the "download location" you send to deluge in client torrent search settings.

**Comment by fernandog** [comment]
I think this happens when trying to add again the same torrent. An user did a test and said that.

**Comment by miigotu** [comment]
If we knew the return code, we could handle the code properly.

**Comment by fernandog** [comment]
Strange that all clients return 'undefined'

**Comment by miigotu** [comment]
It isnt the client that returns undefined, it is our code that says that when we dont recognize the code iirc.

**Comment by miigotu** [comment]
http://deluge-torrent.org/docs/1.2/core/rpc.html#deluge.__rpcapi.RpcApi.core.add_torrent_url
```
headers (dict) – any optional headers to send
Returns:	
a Deferred which returns the torrent_id as a str or None
```

Either the headers can be a problem (need auth?) or None is returned when the torrent is already in the client.

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/clients/generic.py#L191

**Comment by fernandog** [comment]
Nice. Im sure its the later. So all clients return None? What are the chances? Or it is bittorrent standards?

**Comment by fernandog** [comment]
@FlyGuy94 do you have torrent failed enabled? Did you recently did a manual search for a stalled torrent trying to get another?

**Comment by miigotu** [comment]
The client can return whatever it's api defines, our client adapters translate whatever it is into something SR understands.

As for deluge, according to their docs `None` can only be returned when sending it a link to a .torrent file, but a magnet will always return a string.

**Comment by fernandog** [comment]
Maybe torrent cache issue? That JS block?

**Comment by miigotu** [comment]
Your torrent client isnt likely to fail getting a link from the btcache sites afaik.

**Comment by vegeros** [comment]
### INFO
Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/7448d9529975b8480dcf
### ERROR
```
SEARCHQUEUE-BACKLOG-265766 :: [TNTVillage] :: Deluge: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by zparry** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/bd71c1298ad7d61638ab
### ERROR
```
SEARCHQUEUE-BACKLOG-85019 :: [ThePirateBay] :: Deluge: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by killinme1** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-295829 :: [Rarbg] :: Deluge: Unable to send Torrent: Return code undefined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
