### ISSUE TITLE
Torrent Search Test using old values

### ISSUE THREAD

**Issue by nemawashi** [SiCKRAGETV/sickrage-issues#3054]
Branch: master
Commit hash: 4d37c1352e1a27023ffd520a4da8ab0f024333e6
OS: Debian Jessie
Python: 2.7.9-1

Did: Changed transmission RPC url from "transmission" to "transmission/web" while debugging another issue. 

Happened: Clicked Test and reported successful. Saved changes, refreshed page and tested again. "Test Failed".

Expected: Test to pass after refreshing. Appears that when changing values and testing, it is still referencing the old values.

Reproduce: Set values to something valid, test [OK], change to something invalid, test [OK when should fail], save, refresh, test [Fail as expected].

Log not supplied - no relevant information. Nothing in web console either.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
@OmgImAlexis you broke that! xD know how to get it to use the right var?

**Comment by OmgImAlexis** [comment]
@miigotu I'll look into it, it's probably a simple fix.
