### ISSUE TITLE
Aquarius search and post processing

### ISSUE THREAD

**Issue by Dohnerd** [SiCKRAGETV/sickrage-issues#3057]
OKi heres the deal, I'm guessing its much like the Hawaii five-0 problem (year stamp etc.)
I've added the show Aquarius, setting the missing eps to wanted or doing a manual search dosn't find anything... so i DL'ed them myself but it wouldnt process from DL folder.... after som time messing around with it I came to the conclusion that if i strip the "us" from aquarius.us.s01e02.hdtv-lol.mp4 it would process it.....
Note the files in the folders have "us" as all the dl'ed eps has it, and it wont process the files:

Postprocessing results
Processing folder /share/Multimedia/Downloaded/done
TV_DOWNLOAD_DIR: /share/Multimedia/Downloaded/done
PostProcessing Path: /share/MD0_DATA/Multimedia/Downloaded/done
PostProcessing Dirs: ['Aquarius.US.S01E05.WEBRip.x264-WNN[ettv]', 'Aquarius.US.S01E02.HDTV.x264-LOL[ettv]', 'Aquarius.US.S01E09.WEBRip.x264-WNN[ettv]', 'Aquarius.US.S01E08.WEBRip.x264-WNN[ettv]', '.@__thumb', 'Aquarius.US.S01E07.WEBRip.x264-WNN[ettv]', 'Aquarius.US.S01E03.WEBRip.x264-WNN[ettv]', 'Aquarius.US.S01E04.WEBRip.x264-WNN[ettv]']
PostProcessing Files: ['aquarius.102.hdtv-lol.mp4']
PostProcessing VideoFiles: ['aquarius.102.hdtv-lol.mp4']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /share/MD0_DATA/Multimedia/Downloaded/done/aquarius.102.hdtv-lol.mp4 (None)
Retrieving episode object for 1x2
Looking up quality for name done, got Unknown
Looking up quality for name aquarius.102.hdtv-lol.mp4, got Unknown
Guessing quality for name aquarius.102.hdtv-lol.mp4, got SDTV
This was manually downloaded but it appears to be better quality than what we have so I'm marking it as priority
Is ep a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Found release name aquarius.102.hdtv-lol
Destination folder for this episode: /share/Multimedia/Serier/Aquarius
No associated files were during this pass
Moving file from /share/MD0_DATA/Multimedia/Downloaded/done/aquarius.102.hdtv-lol.mp4 to /share/Multimedia/Serier/Aquarius/Aquarius (2015) - S01E02 - The Hunter Gets Captured by the Game - aquarius.102.hdtv-lol.mp4
Processing succeeded for /share/MD0_DATA/Multimedia/Downloaded/done/aquarius.102.hdtv-lol.mp4
Processing folder Aquarius.US.S01E05.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E05.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E02.HDTV.x264-LOL[ettv]
Aquarius.US.S01E02.HDTV.x264-LOL[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E09.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E09.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E08.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E08.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E07.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E07.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E03.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E03.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing folder Aquarius.US.S01E04.WEBRip.x264-WNN[ettv]
Aquarius.US.S01E04.WEBRip.x264-WNN[ettv] : No processable items found in folder
Processing completed

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Add the scene exception to the scow "Aquarius US"
