### ISSUE TITLE
OSX El Capitan - No Unrar Executable Found

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#3058]
Branch: Master
commit 4d37c1352e1a27023ffd520a4da8ab0f024333e6
OS Mac Os EL Capitan
Python 2.7.10
Log: https://gist.github.com/XxUnkn0wnxX/96b7ab6abee24f90b5ec

now i used to be able to fix this by just doing ln -s /usr/local/bin/unrar /usr/bin/unrar but since El Capitan all write access has been removed from /usr/bin and a few other system folders
besides /usr/local

even as sudo or root i cannot create the SoftLink due to the new SIP protection in the OS.

is there a way to resolve this? as in tell sickrage to look for unrar in /usr/local not /usr/bin?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
@XxUnkn0wnxX we do not specify the folder where unrar goes. add `/usr/local/bin` to your system path.

**Comment by XxUnkn0wnxX** [comment]
resolved the issue:
#!/usr/local/bin/bash
source ~/.bash_profile
/usr/local/bin/python2.7 /Users/Admin/Apps/SickRage/SickBeard.py -d &

i use a script to run Sickrage in the background & at boot up the path variables where not imported so i used source ~/.bash_profile to resolve the issue.

**Comment by phirestalker** [comment]
ok I was using a automater application to start sickrage I added "export PATH=$PATH:/usr/local/bin before calling python and that fixed it. I was under the impression that /usr/local was in the path by default like on linux. Thanks for the help

**Comment by sudhanshugarg90** [comment]
hi . i cant find a solution from this. i am on os x el captain too. can u guide me on how to do this mod ?

**Comment by phirestalker** [comment]
I need to know how you are starting sickrage. If it is a script all you have to do is
1. download unrar from rarlabs.com
2. extract the zip file.
3. bring up terminal
4. cd to the directory it created.
5. execute this: sudo install -c -o $USER unrar /usr/local/bin
6. then: sudo install -c -o $USER rar /usr/local/bin
7. in the shell script that starts sicrage (has to have #!/bin/bash or #!/bin/sh) type in export PATH=$PATH:/usr/local/bin

then restart sickrage and it should work. If you are using another method to start sickrage let me know.

**Comment by sudhanshugarg90** [comment]
my sick rage runs on python on usr/bin . i have already downloaded the unbar and installed it . but its in usr/local/bin. i don’t know how to connect the two

**Comment by phirestalker** [comment]
I know it runs on python, but I mean, do you just click on the .py file to start it? does it start when you log in? or when the computer starts? because on my system /usr/local/bin was in /etc/paths the whole time but for some reason the automater created application I use ignores that PATH declaration, so I had to add it to the run shell script inside my automater application. Macs are very quirky

**Comment by sudhanshugarg90** [comment]
no. it starts automatically when the computer boots up

**Comment by phirestalker** [comment]
on terminal type: echo $PATH
if it does not include /usr/local/bin, then you will need to edit /etc/paths and just add a line with: /usr/local/bin

**Comment by sudhanshugarg90** [comment]
no. at login . sorry.

**Comment by sudhanshugarg90** [comment]
this is what i got



> /Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin

**Comment by phirestalker** [comment]
see quirky. stupid mac, it is right there in the path.

ok how do you have it starting at login? did you drag the python file to your login items?

**Comment by sudhanshugarg90** [comment]
install xcode>pip>cheetah>plist
from some guide in net


sudo nano /Library/LaunchDaemons/sickrage.plist
Here is a plist script that I tested and works on Mavericks, you may have to adjust the /usr/bin/python2.7 line to /usr/bin/python or use the path that the command which python returns in the Terminal

&lt;plist version='1.0'&gt;
&lt;dict&gt;
        &lt;key&gt;Label&lt;/key&gt;
        &lt;string&gt;sickrage&lt;/string&gt;
        &lt;key&gt;ProgramArguments&lt;/key&gt;
        &lt;array&gt;
                &lt;string&gt;/usr/bin/python2.7&lt;/string&gt;
                &lt;string&gt;/Applications/SickRage/SickBeard.py&lt;/string&gt;
                &lt;string&gt;-q&lt;/string&gt;
        &lt;/array&gt;
        &lt;key&gt;KeepAlive&lt;/key&gt;
        &lt;true/&gt;
&lt;/dict&gt;
&lt;/plist&gt;

**Comment by sudhanshugarg90** [comment]
as it said in this guide



http://www.htpcguides.com/install-sickrage-mac-osx-usenet-torrent-tv/ <http://www.htpcguides.com/install-sickrage-mac-osx-usenet-torrent-tv/>

made a plist to start at boot

**Comment by phirestalker** [comment]
ok only one last thing to check

see if /usr/local/bin shows up in the file /etc/paths or any of the files in /etc/paths.d

it is possible that it was added from your .bash_profile which isn't loaded yet when this executes. let me know if it is in those files

**Comment by sudhanshugarg90** [comment]
sudo nano /etc/paths gives



/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

**Comment by phirestalker** [comment]
sorry I have no idea why it isn't working then, it might not be the same problem I had

**Comment by sudhanshugarg90** [comment]
k thanks anyways!

**Comment by MaximusCub** [comment]
For anyone else trying to solve this. The issue is that when you are using a launch.plist file to leverage Mac OSX's launchd you need to tell OS X to update the PATH environment variable it uses for launching SickRage inside.

Since El Capitan restricts you from modifying /usr/bin and the like you will need to put the "unrar" command in /usr/local/bin and then do the following:

1. Run this command and make sure the output shows /usr/local/bin in the PATH variable. You may have multiple paths separated by the : character.

echo $PATH

2. Tell launchctl to update the PATH used for the "system" context for launchd to be equal to the current path you have, by running this command:

sudo launchctl config system path $PATH

It will tell you that you need to reboot your system for it to take effect, go ahead and do so.

SickRage should see the unrar command properly now.
