### ISSUE TITLE
[APP SUBMITTED]: Thread-36 :: "/usr/local/git/bin/git" fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/update-subliminal-1.0-dev: Permission denied
error: Cannot update the ref 'refs/remotes/origin/update-subliminal-1.0-dev'.
From https://github.com/SiCKRAGETV/SickRage
 ! ee5369e...514362a update-subliminal-1.0-dev -> origin/update-subliminal-1.0-dev  (unable to update local ref)

### ISSUE THREAD

**Issue by abetancort** [SiCKRAGETV/sickrage-issues#3059]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b
Link to Log: https://gist.github.com/23a07344fafce3868da1
### ERROR
```
Thread-36 :: "/usr/local/git/bin/git" fetch origin returned : error: Unable to append to .git/logs/refs/remotes/origin/update-subliminal-1.0-dev: Permission denied
error: Cannot update the ref 'refs/remotes/origin/update-subliminal-1.0-dev'.
From https://github.com/SiCKRAGETV/SickRage
 ! ee5369e...514362a update-subliminal-1.0-dev -> origin/update-subliminal-1.0-dev  (unable to update local ref)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by abetancort** [comment]
**APPARENTLY SOLVED** by performing a `git reset --hard followed by a git pull, chown -R sickbeard-custom:users * and chown -R sickbeard-custom:users .*`

##### Detailed instructions for *SickBeard Custom Package* from SynoCommunity for *Synology*:

       $ cd /volume1/@appstore/sickbeard-custom/var/SickBeard/
       $ /volume1/@appstore/git/bin/git reset --hard
       $ /volume1/@appstore/git/bin/git pull
    (1)$ chown -R sickbeard-custom:users *   
    (2)$ chown -R sickbeard-custom:users .*   
###### (1) *Not sure It is necessary nor wise but I did it anyways*. 
###### (2) *Even less sure it's wise or right thing to do, but I did it anyways* like living on the edge*.
