### ISSUE TITLE
One show's link goes to "ValueError: (22, 'Invalid argument')"

### ISSUE THREAD

**Issue by jessepiccolo** [SiCKRAGETV/sickrage-issues#3061]
Version: 4.0.68 (2015-09-28)
Commit: 4d37c
Win 7Pro

I have one show that when I click on it from the Shows (/home) page I get:

Error !

ValueError: (22, 'Invalid argument')

% else: Never % endif <span class="sort_data">${date.isoformat('T')}</span> </td> <td> % if sickbeard.DOWNLOAD_URL and epResult['location']: <%
C:\Users\jpiccolo\Documents\GitHub\SickRage\lib\dateutil\tz.py, line 152:
return time.localtime(timestamp+time.timezone).tm_isdst
C:\Users\jpiccolo\Documents\GitHub\SickRage\lib\dateutil\tz.py, line 108:
if self._isdst(dt):
C:\Users\jpiccolo\Documents\GitHub\SickRage\gui/slick/views/displayShow.mako, line 493:
<span class="sort_data">${date.isoformat('T')}</span>
C:\Users\jpiccolo\Documents\GitHub\SickRage\gui/slick/views/layouts/main.mako, line 220:
C:\Users\jpiccolo\Documents\GitHub\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

I haven't had this issue with any other show.
Thanks!

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
