### ISSUE TITLE
ISSUE: Failed Unrar Archive.

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#3064]
So im having this issue. Ive read online but I cant find an answer to my proble,

**2015-10-02 01:11:32 POSTPROCESSER :: Failed Unrar archive justified.s06e10.1080p.bluray.x264-rovers.rar: Unrar: No file extracted, check the parent folder and destination file permissions.**

More here, including my analysis:
https://gist.github.com/kossboss/49d6bb8612ab67b0c831

I know the typical steps for solving this are checking permissions: well sickrage is run as root (yes I know unexpected behavior and im hopeing this isnt one of them) and it has complete access into my complete download folders & to my final tv folders, which are permission kossboss:users .

Its able to copy other tv show episodes, just these certain ones that spit out errors. So its only some of them.

I was able to catch the same error for other episodes & I fixed it, as it was trying to dump to an old directory that doesnt exist (I renamed a tvshow dir). I fixed that by editing the show details to point at correct dir for the tvshow. On the other hand, with these episodes in the logs are all of folders that do exist and point to correct directory and also have good permissions.

Also the tv shows are already extracted in the folder, there is like 1 rar laying around, but the complete extracted thing is there.

Currently, I have a few of these folders its giving me those errors to (more than enough to do manually). Im usually able to troubleshoot from the messages in manual post process. 

**I was wondering if you could help me in solving this issue by showing me how to kick off an Automatic Post Process (either thru the shell or thru the GUI) & ill see If I can spot something and fix this myself.**

And if that doesnt work then I guess we have to look at why its doing it.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by kossboss** [comment]
Other info:


SR Version:	BRANCH: (master) / COMMIT: (4d37c1352e1a27023ffd520a4da8ab0f024333e6) 
SR User:	root
SR Locale:	('en_US', 'UTF-8')
SR Config:	/apps/sickrage/config.ini
SR Database:	/apps/sickrage/sickbeard.db
SR Cache Dir:	/apps/sickrage/cache
SR Log Dir:	/apps/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch']
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

**Comment by miigotu** [comment]
@kossboss please post the output of this command:
`unrar | head -3`

**Comment by fernandog** [comment]
@miigotu 
Unrar cant be added to lib as we need unfree?

**Comment by miigotu** [comment]
nope

**Comment by kossboss** [comment]
# unrar | head -3
UNRAR 4.10 freeware      Copyright (c) 1993-2012 Alexander Roshal

**Comment by miigotu** [comment]
@kossboss and this?

```bash
ls -l yoursourcefolderwhererarsare
ls -l thefoldertheraristryingtoextractto
```

**Comment by kossboss** [comment]
Added the answers to this:
https://gist.github.com/kossboss/49d6bb8612ab67b0c831

**Comment by miigotu** [comment]
and with SR running how you normally run it:
```bash
ps aux | grep Sick
```

**Comment by kossboss** [comment]
root@starlord:~# ps aux | grep [S]ick
root      7701  8.2 41.0 1929396 416908 ?      SNl  Oct02 188:05 /usr/bin/python2.7 /apps/sickrage/SickBeard.py -q --daemon --nolaunch

**Comment by miigotu** [comment]
I have no idea.

**Comment by kossboss** [comment]
Lol i know its wierd. i edited the comment above with more info

**Comment by mbitson** [comment]
Hey Everyone!

I am also receiving this same error. Strangely, for me, it extracts the first time (despite the error) and on the second attempt it post-processes the media correctly, but still continues to create the error and attempt to extract. My details are in a forum thread here: https://sickrage.tv/forums/forum/help-support/general-support/28498-unrar-permissions-issue-aanofiletoextract

Specifically, my portion of the log that is the same error:
```
2015-10-01 16:21:51 ERROR    POSTPROCESSER :: Failed Unrar archive placeholder.s02e21.720p.bluray.x264-demand.rar: Unrar: No file extracted, check the parent folder and destination file permissions.
AANoFileToExtract
AA    raise NoFileToExtract
AA  File "/home/transmission/.sickrage/lib/unrar2/unix.py", line 257, in _check_returncode
AA    self._check_returncode(proc.returncode)
AA  File "/home/transmission/.sickrage/lib/unrar2/unix.py", line 222, in extract
AA    return RarFileImplementation.extract(self, checker, path, withSubpath, overwrite)
AA  File "/home/transmission/.sickrage/lib/unrar2/__init__.py", line 158, in extract
AA    rar_handle.extract(path=path, withSubpath=False, overwrite=False)
AA  File "/home/transmission/.sickrage/sickbeard/processTV.py", line 433, in unRAR
AATraceback (most recent call last):
```

Here is my unrar | head -3 output:
```
UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal
```

**Comment by miigotu** [comment]
I think you need to increase your time between post processing. The second instance of post processing is running while the file is still being extracted and moved/removed.

Ive also just updated the unrar library the other day, to work with the new versions of unrar.

Closing this as there is no issue with unrar on unix atm.

**Comment by kossboss** [comment]
this looks resolved. thanks.

**Comment by miigotu** [comment]
10 mins is pretty low, especially for having to unarchive large releases. 15 mins min is probably much better, maybe 20m

**Comment by kossboss** [comment]
changing it now. thanks miigotu

**Comment by mbitson** [comment]
Just so everyone else knows, mine was set to something ridiculous... 5 minutes. I've just adjusted to 15 and I'll post results if I run into the error again, but I'm sure this'll fix it!
