### ISSUE TITLE
Episodes not snatched because minimum number of seeders/leechers not met

### ISSUE THREAD

**Issue by elrock** [SiCKRAGETV/sickrage-issues#3067]
BRANCH: (master) / COMMIT: (4d37c1352e1a27023ffd520a4da8ab0f024333e6)
Python version: 2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]
Xbian 20150919-1

SickRage is not snatching episodes from kat.cr because they don't meet the minimum number of seeders /leechers (0). In my SR settings, both values = 0. The episodes do have seeders and I am able to download them using a different device.

````2015-10-02 10:10:26 DEBUG    SEARCHQUEUE-MANUAL-74285 :: [KickAssTorrents] ::  Discarding torrent because it doesn't meet the minimum seeders or leechers: Project Runway S14E09 Make it Sell HDTV x264-DaViEW (S:0 L:0)````

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
It requires a minimum of 1 seeder no matter what, to prevent snatching unseeded, undownloadable, or fake torrents.

**Comment by fernandog** [comment]
https://kat.cr/usearch/Runway%20S14E09%20Make%20it%20Sell%20HDTV%20x264-DaViEW/

Are we sure seed parse is correct?
Kat seed count is  correct?

I know because HDT is not. Lots appears with 0 seeds but I still can download.

**Comment by fernandog** [comment]
Maybe we can allow 0 seed if uploader is verified/trusted

**Comment by miigotu** [comment]
Kat and TPB return the last 50 torrents added. On public trackers, especially those two, the majority of torrents added never get seeded and are pruned.

For private trackers there is still a chance of non-seeded torrents, but the chance is MUCH lower.

**Comment by fernandog** [comment]
Now torrent has seed. SR will get it in backlog search or dailysearch?

Check that torrent link. Lots of seeders

**Comment by miigotu** [comment]
Yes, it will be picked up in either backlog or daily. Since it was skipped instead of added to the list with 0 seeds, it has not been ignore for future searches.

However, if you let it add with 0 seeds, it still wont be picked as a cache result, because it has 0 seeds in the cache and has less seeds than minseed. This 0 seed number will never be updated again, because it is already added, and that torrent can never be snatched.

You actually get MORE snatches this way. This isnt a difficult thing to understand. Please stop contesting everything I say.

**Comment by fernandog** [comment]
Just trying to understand so we can explain better to users.

**Comment by miigotu** [comment]
All a user needs to know is that there is no reason to snatch a torrent that 0 seeds because more often than not it will stall. They understand that more than trying to get all technical about it.

**Comment by elrock** [comment]
FYI - the default setting for minimum seeders = 0 in my setup. I changed that value to 1 for each provider. I just added a few more public trackers so perhaps that will solve my problem. (I don't belong to any private trackers and I don't know how to get invites for them.)

**Comment by miigotu** [comment]
@elrock 1 is ok too, but you will still see that they are skipped in the log. It is not an error. (the torrents have 0 seeds, SR is requiring results to have at least 1 at minimum.)

@fernandog this is also why I didnt want you to add that log line spamming the log every time a result was skipped. Its causing confusion, and causing logs to rotate WAY too fast.
