### ISSUE TITLE
SickRage doesn't listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by timrettop** [SiCKRAGETV/sickrage-issues#3068]
My new ISP has enabled DS-Lite, so I do not have a public IPv4 address anymore.  Since this, I've been transitioning my services to support IPv6 so they can be reachable.   

The option to enable listening to IPv6 in the web browser unfortunately stops SR from listening on IPv4 as well. 

This forum post indicates that this has been an issue for some time: 
https://sickrage.tv/forums/forum/help-support/bug-issue-reports/4197-sickrage-only-binding-to-ipv6-addresses

Until IPv6 becomes the primary communication method for all browsers and OS's, it would be helpful to listen on both, rather than only IPv6. 

CouchPotato implemented this dual mode instead of exclusive mode, as has Plex, NZBGet and SABnzbd.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
This is not a bug, it is s feature request. We dont allow feature requests in the issue tracker anymore.

Feature requests go here => [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
