### ISSUE TITLE
Unable to find show The Asterisk War on thetvdb

### ISSUE THREAD

**Issue by cgdecker** [SiCKRAGETV/sickrage-issues#3072]
The show is clearly on thetvdb, as seen here: http://thetvdb.com/?tab=series&id=293996&lid=7

I've tried searching for it with a variety of words from both its English title (The Asterisk War) and Japanese title (Gakusen Toshi Asterisk), but all result in "No results found". Searching for the same on thetvdb website brings up the correct result(s) just fine.

- branch: master
- commit: 4d37c1352e1a27023ffd520a4da8ab0f024333e6
- OS: Ubuntu Server 14.04.2
- Python version: 2.7.6

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
@SiCKRAGETV/moderators not sure what's going on here, this should come up on search but doesn't at all.

**Comment by OmgImAlexis** [comment]
@cgdecker you may need to get in contact with tvdb as it seems it is probably an issue on their end.

**Comment by fernandog** [comment]
Is this a new show?
I cant find it but other shows I can.
Maybe api didnt get updated

**Comment by OmgImAlexis** [comment]
Ah, that may be the problem. First aired: October 3, 2015.

**Comment by miigotu** [comment]
Yes, either the show was JUST added and the api index has not been refreshed yet, or the show was removed and re-added with correct info and the api index was not refreshed yet.

@cgdecker we have no control over what thetvdb will return. Our code just shows what they give us.

**Comment by cgdecker** [comment]
Ok, so their API doesn't necessarily return results for things that show up in search on their site. Got it, thanks.

**Comment by miigotu** [comment]
Yes, exactly. Np.
