### ISSUE TITLE
WARNING  SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Failed to download any results

### ISSUE THREAD

**Issue by rross128** [SiCKRAGETV/sickrage-issues#3074]
SR fails to download any new nzb files from dognzb for past couple weeks. Started looking at the logs and I see the following for a search I forced. If I copy the link and post it to a browser, browser automatically retrieves nzb file.

OS: Ubuntu 15.04
SR Version: Updated to current version of master branch.
Python Version:	2.7.9

Relevant Info from Log
````
2015-10-02 19:57:34 DEBUG    SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Picked  Series.SXXEXX.BDRip.x264-DEMAND as the best
2015-10-02 19:57:34 DEBUG    SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Checking if we should keep searching after we've found Series.SXXEXX.BDRip.x264-DEMAND
2015-10-02 19:57:34 INFO     SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Downloading Series.SXXEXX.BDRip.x264-DEMAND from DOGnzb
2015-10-02 19:57:34 INFO     SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Downloading a result from DOGnzb at https://dognzb.cr/fetch/04e1eca5c4797ef18bdadaa4cdbe6a8f/my_api_key
2015-10-02 19:57:35 DEBUG    SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Requested download url https://dognzb.cr/fetch/04e1eca5c4797ef18bdadaa4cdbe6a8f/my_api_key returned status code is 500: Internal Server Error
2015-10-02 19:57:35 WARNING  SEARCHQUEUE-MANUAL-262980 :: [DOGnzb] :: Failed to download any results
````

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Internal server error.

**Comment by rross128** [comment]
I'm not sure if they use cloudflare or not. I'm not totally convinced it's a server error. As I stated, I can copy the noted URL into any other browser and it works fine.

I attempted to rebuild sickrage on a new machine and it's doing the exact same thing. I've also reset my api key on dognzb.

**Comment by miigotu** [comment]
It specifically says internal server error in your log. If it is cloudflare we need to change 1 line.

**Comment by fernandog** [comment]
@miigotu 
Should I do in my PR?

**Comment by miigotu** [comment]
yes need to update the user-agent header just like tpb

**Comment by fernandog** [comment]
Ok

**Comment by rross128** [comment]
Just as an update for this. I was afraid that maybe there was some permissions issues copying the files over to the network share, so I spun up one of my old Windows VM that had sickrage on it. Still getting the same error.

Please let me know if there's anything I can do to help you guys out with this. I have DogNZB installed as a custom newsnab provider on my box. Pretty sure it's configured right as I'm getting api calls. Just failing on DLs.

**Comment by rross128** [comment]
I switched over to the dev brach today, first search produced a succeful snatch.
