### ISSUE TITLE
Do we still use pnotify?

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3075]
@MGaetan89 since we use the web notifications API do we still use pnotify at all?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
I think we do.

**Comment by OmgImAlexis** [comment]
@miigotu the only stuff I can find that's related to it all uses web notifications. @MGaetan89 unless you know of somewhere that still needs it then I want to remove it, no need for things that aren't being used.

**Comment by MGaetan89** [comment]
I have no idea what pnotify is, how it works or if it is used, sorry.

**Comment by OmgImAlexis** [comment]
Well in that case I'm going to move everything over to native web notifications.

**Comment by miigotu** [comment]
@OmgImAlexis its for desktop notifications on linux gnome right? libnotify?

**Comment by OmgImAlexis** [comment]
@miigotu pnotify is mainly for the old style notifications. Desktop and web notification in all browsers can be done natively now so there's no reason to use a library that we need to keep to date just for that.

**Comment by fernandog** [comment]
Is this related to ui.notifications in webserve?

**Comment by OmgImAlexis** [comment]
@fernandog yes and no.. the ui.notifications just makes a notification, this displays them. I want to move to native html5 notifications though.
