### ISSUE TITLE
[Meta] Updating to Bootstrap 4

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3084]
Should we start updating to Bootstrap 4 now? It's almost at the stage of being fully released and there's a **LOT** to change.
http://v4-alpha.getbootstrap.com/migration/

@SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by flightlevel** [comment]
Personally I'd hold off a bit, its still at alpha stage. There is plenty to do on SR without fixing 3rd party bugs and it can make your own bugs even harder to work out.

**Comment by OmgImAlexis** [comment]
@flightlevel if we agree to do it I'll make a branch for it and start the conversion. I know it's in Alpha but I doubt there's any major bugs that'll break anything, at most there's probably just stuff not fully added.

**Comment by miigotu** [comment]
If we do that there is no moving away from bootstrap in the near future. not sure now is the time to decide just yet and we could wait until beta to give us more time to decide?

**Comment by OmgImAlexis** [comment]
@miigotu actually moving to v4 would help a LOT with that, it's moved towards being usable now. Honestly if it gets better than it is now I wouldn't mind keeping Bootstrap.

**Comment by miigotu** [comment]
Just sucks because we JUST got the gui working pretty cleanly =P. If you want to give it a go I don't see why not then I guess. We all know my first answer is always Naaaaaah... lol

**Comment by WebSpider** [comment]
I feel you miigotu :)

Im really charmed by the CP layout on mobile, tablet and desktop. Would upgrading to B4 make that less likely? I havent checked how CP new layout is built, tbh.

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider their new layout is all custom from the looks of it. We could do something like that but @MGaetan89 and I would have to work on it together and stop working on fixes, that's why for now I think we should just update to v4 and later on we can think about moving away from it.

CP's new layout is also using a frontend framework in a single page application similar to how Facebook, etc. works. We could move to that way but I personally don't like doing single page applications.

**Comment by WebSpider** [comment]
Im not too keen on single page either, I'm more in favor of modular setups.

I'm not in favor of custom designs either, since you're reinventing the wheel, and we have better things to spend energy on.

Just trying to make sure we're not coding ourselves in a corner, and keeping a view on what similar apps are doing. If B4 is the next logical step, ok!

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@WebSpider moving to a completely custom CSS design would actually mean it'll be easier to handle as we can just add and remove stuff instead of having to override Bootstrap to change anything. Really all we have at the moment is a themed version of a hacked Bootstrap install.

So for now I think moving to v4 would be the best for everyone.

**Comment by miigotu** [comment]
Also B4 is designed for mobile FIRST, and officially supports Lollipop. It does drop support for IE8 and Ios < 7 though.

**Comment by aarondunlap** [comment]
Just throwing out my two cents because I'm interested in contributing to the GUI.  I'm involved in enterprise development in my day job and the tenants that we're focusing on there make a lot of sense in this type of project (really any these days).  You have to focus on mobile first.  No matter what your application is (unless it is completely disconnected from the internet), people will want to use it on mobile... plus if you design it well, it will double as its own app (I'm iOS-centric, and being able to have a CP icon that launches straight into a responsive design has been *killer* since the update).

Regardless of whether a move is made toward B4, I am of the opinion that responsive design should be at the forefront.  If the move to B4 aids in faster delivery of the responsive design, then lets go for it.

**Comment by OmgImAlexis** [comment]
@WebSpider @fernandog @miigotu can an admin please make a b4 branch for us?

**Comment by OmgImAlexis** [comment]
All commits for b4 should goto https://github.com/SiCKRAGETV/SickRage/tree/bootstrap

**Comment by OmgImAlexis** [comment]
So it's easier I've made a fork of SickRage on my company account and anyone wanting to help with this can have write access, once it's done we'll go over everything and merge back into SiCKRAGETV/SickRage. https://github.com/Alete/SickRage
