### ISSUE TITLE
More errors with TPB and KAT after latest update.

### ISSUE THREAD

**Issue by evilpig** [SiCKRAGETV/sickrage-issues#3085]
I was already having issues with these providers, and I just updated to the latest master branch a few minutes ago (and deleted my cache.db) and now even more errors are popping up when searching. Any help? Thanks! 

edit: I am running on Windows. 

2015-10-04 00:36:30 INFO     SEARCHQUEUE-MANUAL-75897 :: [ThePirateBay] :: Unable to find a download for: [South Park - 19x03 - The City Part of Town]
2015-10-04 00:36:30 INFO     SEARCHQUEUE-MANUAL-75897 :: [ThePirateBay] :: Performing season pack search for South Park
AASSLError: [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
AA    raise SSLError(e, request=request)
AA  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "C:\SickRage\sickbeard\helpers.py", line 1622, in getURL
AATraceback (most recent call last):
2015-10-04 00:36:30 ERROR    SEARCHQUEUE-MANUAL-75897 :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-10-04 00:36:30 INFO     SEARCHQUEUE-MANUAL-75897 :: [ThePirateBay] :: Performing episode search for South Park
AASSLError: hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
AA    raise SSLError(e, request=request)
AA  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "C:\SickRage\sickbeard\helpers.py", line 1622, in getURL
AATraceback (most recent call last):
2015-10-04 00:36:30 ERROR    SEARCHQUEUE-MANUAL-75897 :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/usearch/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
2015-10-04 00:36:29 INFO     SEARCHQUEUE-MANUAL-75897 :: [KickAssTorrents] :: Performing episode search for South Park
2015-10-04 00:36:29 INFO     SEARCHQUEUE-MANUAL-75897 :: Beginning manual search for: [South Park - 19x03 - The City Part of Town]
2015-10-04 00:36:27 INFO     SEARCHQUEUE-MANUAL-295743 :: [ThePirateBay] :: Unable to find a download for: [Limitless - 1x01 - Pilot]
2015-10-04 00:36:27 INFO     SEARCHQUEUE-MANUAL-295743 :: [ThePirateBay] :: Performing season pack search for Limitless
AASSLError: [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
AA    raise SSLError(e, request=request)
AA  File "C:\SickRage\lib\requests\adapters.py", line 431, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "C:\SickRage\sickbeard\helpers.py", line 1622, in getURL
AATraceback (most recent call last):
2015-10-04 00:36:27 ERROR    SEARCHQUEUE-MANUAL-295743 :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-10-04 00:36:27 INFO     SEARCHQUEUE-MANUAL-295743 :: [ThePirateBay] :: Performing episode search for Limitless

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Try stopping SR and deleting cache/sessions, cache/rss also.
These providers work as long as you have python 2.7.9 or 2.7.10 or (2.7.3+pyOpenSSL).

**Comment by evilpig** [comment]
I have just updated from 2.7.3 to 2.7.10 and deleted both cache folders. Still no luck.

**Comment by evilpig** [comment]
Fixed, 2.7.10 was installed in the wrong directory. Woo no more errors!

**Comment by miigotu** [comment]
lol grats.
