### ISSUE TITLE
SearchPrivider KickAssTorrents gives connection error to getURL

### ISSUE THREAD

**Issue by MrHappy** [SiCKRAGETV/sickrage-issues#3087]
[KickAssTorrents] :: Connection error to getURL https://kat.cr/usearch/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
Updated to the latest version this morning.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by rd1** [comment]
i'm getting a lot of "Unknown exception in getURL" warnings in the logs for Kat

Qnap, Arm cpu
SR Version:	BRANCH: (master) / COMMIT: (0b2254c884f833bbb54b8c7e6f6231f4d61557d0) 
Python Version:	2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]


2015-10-04 06:34:18 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Unknown exception in getURL https://kat.cr/tv/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
2015-10-04 06:34:18 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1622, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'




repeat that 70 times since last night.

**Comment by MrHappy** [comment]
these are errors from my log:
AASSLError: hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
AA    raise SSLError(e, request=request)
AA  File "C:\Program Files (x86)\SickRage\lib\requests\adapters.py", line 431, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "C:\Program Files (x86)\SickRage\lib\cachecontrol\adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\Program Files (x86)\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\Program Files (x86)\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\Program Files (x86)\SickRage\lib\requests\sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "C:\Program Files (x86)\SickRage\sickbeard\helpers.py", line 1622, in getURL
AATraceback (most recent call last):
2015-10-04 13:13:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/tv/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
2015-10-04 13:13:12 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-10-04 13:13:10 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-10-04 13:13:10 INFO     DAILYSEARCHER :: Searching for new released episodes ...

**Comment by marshreddy** [comment]
Also getting this error. Tried deleting cache, as recommended in SickRage News, but I still get the error.

**Comment by fernandog** [comment]
Bot message: If you use a QNAP try this package.

**Comment by neoatomic** [comment]
@rd1 You are using an outdated package for your qnap.
@MrHappy You probbebly didn't install the correct modules for Python. (Use the Sickrage windows installer if you dont know how to do that.)
 
You can disable settings --> general --> advanced settings ---> Verify SSL Certs 
But that is a workaround not a fix.

**Comment by rd1** [comment]
there is no newer pkg released but it is uptodate with the latest commits.

the pkg linked here by SiCKRAGEB0T is for the x86 intel cpu only. i use the arm pkg.

**Comment by MrHappy** [comment]
Followed this description (http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/) and only thing missing was the pyOpenSSL. Installed it, but message keeps appearing. What other module(s) am I supposed to install (besides pyOpenSSL & Cheetah)?

**Comment by miigotu** [comment]
You dont need cheetah. And if you use python 2.7.10 you dont need pyOpenSSL.

If you use python 2.7.3 you need pyOpenSSL, pyasn1, ndg-httpsclient

**Comment by xalten** [comment]
Still getting the same errors as MrHappy, have deleted the cache.db.

Running Fedora 21 
Python 2.7.8
pyOpenSSL 0.13.1
pyasn1 0.1.7
ndg-httpsclient 0.4.0

Seeing these 2 errors in the log for KAT and TBP
>AASSLError: [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>AA    raise SSLError(e, request=request)
>AA  File "/usr/share/sickrage/lib/requests/adapters.py", line 431, in send
>AA    resp = super(CacheControlAdapter, self).send(request, **kw)
>AA  File "/usr/share/sickrage/lib/cachecontrol/adapter.py", line 46, in send
>AA    r = adapter.send(request, **kwargs)
>AA  File "/usr/share/sickrage/lib/requests/sessions.py", line 576, in send
>AA    resp = self.send(prep, **send_kwargs)
>AA  File "/usr/share/sickrage/lib/requests/sessions.py", line 464, in request
>AA    return self.request('GET', url, **kwargs)
>AA  File "/usr/share/sickrage/lib/requests/sessions.py", line 476, in get
>AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
>AA  File "/usr/share/sickrage/sickbeard/helpers.py", line 1622, in getURL
>AATraceback (most recent call last):
>2015-10-04 21:23:17 ERROR    SEARCHQUEUE-MANUAL-248835 :: [ThePirateBay] :: Connection >error to getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>2015-10-04 21:23:16 ERROR    SEARCHQUEUE-MANUAL-248835 :: [ThePirateBay] :: Connection >error to getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

2015-10-04 21:23:16 ERROR    SEARCHQUEUE-MANUAL-248835 :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/tv/ Error: error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'

**Comment by xalten** [comment]
Turned off Verify SSL certs and still get the same errors.

**Comment by miigotu** [comment]
You have to turn off ssl verify, stop SR, and then delete those cache folders and cache.db.

**Comment by xalten** [comment]
Ok, I turned off SSL verify, stopped SR, deleted cache.db, cache/mako and cache/sessions. Restarted my fedora box, KAT works now however still the same error with TPB 

>2015-10-05 10:08:44 SEARCHQUEUE-MANUAL-279201 :: [ThePirateBay] :: Connection error to >getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>2015-10-05 10:08:07 SEARCHQUEUE-BACKLOG-279201 :: [ThePirateBay] :: Connection error to >getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>2015-10-05 10:08:07 SEARCHQUEUE-BACKLOG-279201 :: [ThePirateBay] :: Connection error to >getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>2015-10-05 10:08:07 SEARCHQUEUE-BACKLOG-279201 :: [ThePirateBay] :: Connection error to >getURL https://thepiratebay.gd/s/ Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
>2015-10-05 10:08:05 SEARCHQUEUE-BACKLOG-279201 :: [ThePirateBay] :: Connection error to >getURL https://thepiratebay.gd/tv/latest Error: error [Errno 1] _ssl.c:510: error:14077438:SSL >routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by miigotu** [comment]
Up to date?

**Comment by xalten** [comment]
As far as I know. Check for updates doesn't bring up any. 

SR Version:	BRANCH: (master) / COMMIT: (0beda92f71145d448f8f784042a8d631448a0394)

**Comment by miigotu** [comment]
@xalten Possible your dns or isp has blocked thepiratebay.gd?

**Comment by xalten** [comment]
it pulls up fine from my windows box, is there any test I could do from the fedora box? It's terminal only so can't exactly bring up a browser and try.

**Comment by miigotu** [comment]
@xalten `openssl s_client -connect thepiratebay.gd:443 -servername thepiratebay.gd`

**Comment by xalten** [comment]
looks good, shows the certificate information then at the end 

    Start Time: 1444058230
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Comment by xalten** [comment]
I am completely ok with it on my machine only working with KAT but if you need anything from me to help drill this down just let me know

**Comment by miigotu** [comment]
`curl -v -1 https://thepiratebay.gd/s/?q=Game+of+Thrones -L -H 'SickRage/(Linux; 3.19.0-30-generic; 5d7d51d6-e5-a684-446d67bd4634)'`

Does that return any torrent in the ouput?

**Comment by xalten** [comment]
* Hostname was NOT found in DNS cache
*   Trying 104.24.100.99...
* Connected to thepiratebay.gd (104.24.100.99) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12286 (SSL_ERROR_NO_CYPHER_OVERLAP)
* Cannot communicate securely with peer: no common encryption algorithm(s).
* Closing connection 0
curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).

**Comment by antiinsight** [comment]
I have followed the above suggestions and I am still getting errors from KAT when searching. This is brand new as of a few days ago. Last week the search was working great.

Ive disables SSL, deleted all the cache folders and cache.db

OS: Lubuntu 12.04
SR Version: BRANCH: (master) / COMMIT: (638270689679f3958d1b593c329e7c6e5cb7448e) 
SR User: mediaserver
SR Locale: ('en_US', 'UTF-8')
SR Config: /home/mediaserver/.sickrage/config.ini
SR Database: /home/mediaserver/.sickrage/sickbeard.db
SR Cache Dir: /home/mediaserver/.sickrage/cache
SR Log Dir: /home/mediaserver/.sickrage/Logs
SR Arguments: []
Python Version: 2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]

Link to errors generated

http://pastebin.com/8XhbJ07S

**Comment by SanctiMortem** [comment]
Also turned off verify ssl certs, shutdown SR, deleted cache.db, deleted folders cache/mako and cache/sessions. but problem persists.

**Comment by wodeno** [comment]
I had this problem, I fixed it by updating python to 2.7.10 and deleting cache.db, cache/mako & cache/sessions.

-w0den

**Comment by brandner** [comment]
@wodeno - your solution worked for me as well. Windows 10, Python 2.7.8, SickRage a81fb5.
Stopped Sickrage, updated to Python 2.7.10, deleted (moved) the files and folders (cache.db, cache/mako, cache/sessions) and restarted Sickrage.

Before:
```
2015-10-13 20:24:54 ERROR    SEARCHQUEUE-BACKLOG-258171 :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/s/?q=ContXXXXX+S04EXX&orderby=7&category=200&type=search&page=0 Error: u'See: http://git.io/vJrkM'
2015-10-13 20:24:54 INFO     SEARCHQUEUE-BACKLOG-258171 :: [ThePirateBay] :: Performing episode search for ContXXXXX
2015-10-13 20:24:54 ERROR    SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Connection error to getURL https://kat.cr/usearch/?q=ContXXXXX+S04E06&field=seeders&category=tv&sorder=desc&rss=1 Error: u"error hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'"
2015-10-13 20:24:54 INFO     SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Performing episode search for ContXXXXX
2015-10-13 20:24:54 INFO     SEARCHQUEUE-BACKLOG-258171 :: Beginning backlog search for: [ContXXXXX]
```

After:
```
2015-10-13 22:27:44 INFO     SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Downloading ContXXXXX.S04EXX.HDTV.x264-KILLERS[ettv] from KickAssTorrents
...
2015-10-13 22:27:43 INFO     SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Performing episode search for ContXXXXX
2015-10-13 22:27:40 INFO     SEARCHQUEUE-BACKLOG-258171 :: Beginning backlog search for: [ContXXXXX]
```

**Comment by SanctiMortem** [comment]
I looked for an update as well, but I've had the latest version and the probkem is the same. It only with tpb now though. Hope they fix ut soon
