### ISSUE TITLE
[Feature Request] Add IMDB watchlist support

### ISSUE THREAD

**Issue by bitzorro** [SiCKRAGETV/sickrage-issues#309]
Add tv-shows from imdb watchlist.
Adding a show to your watchlist on the imdb and Sickrage picks it up and does its Magic.

**Comment by bitzorro** [comment]
Not to discredit the other providers, but the imdb is more wife/noob friendly...
Wile we are at it, what about adding the ability to add several accounts..
One for the you one for the wife and one for the kids.
What im trying to say is everybody have an imdb account..

**Comment by markheloking** [comment]
But then you'd want to be able to see from what account the specific show/episode was requested. Although this is a nice feature, that would mean adding multiple user support to a big part of sickrage (which is a BIG change in code and interface). Looking forward to it, but the chance of seeing that happen in the near future are quite slim if you ask me.

**Comment by bitzorro** [comment]
Multiple users newer crossed my mind, just the ability to add more than one account for the watchlists...
Your wife dont have to ask you, did you remember to add Wampire diaries to the collection honey?
With this she can just tick the watchlist herself, that simple.

**Comment by markheloking** [comment]
But that's also possible by using a specific account for stuff you want in sickrage (one imdb account specifically for this purpose to which both you and your wife have the login credentials).

**Comment by cerberusuk** [comment]
Hey there
Would be great to either get IMDB or Trakt watchlists up and running :-)
Thanks
PS congratulations on becoming a father :-)

**Comment by KontiSR** [comment]
Aah okay, finally find this repo. Nice to have issue tracker now!
Well i've build this functionality already like somewhere in september 2014. So this shouldn't be a FR but rather a bug.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/882

**Comment by KontiSR** [comment]
If I would start on this, we need to agree on the requirements for this feature.
JackDandy reverted the code because of the following reasons:

- It was based on trakt code for mapping imdb id's to tvdb id's. But as the trakt code was subject to change/not stable, this implementation was also subject to change/not stable. In the mean time the tvdb api now has the option to search using imdb id. 

Which I think would be a better solution.

- In the old implementation show status was set to "False". He fixed that, so that it was set to the default status.

I think using the default configured values for shows is fine.

- Users have no control over the shows added. Or they where not having the options offered they would normally have, when adding manually.

I don't really get this. If a user chooses to auto-magically  add shows using his imdb watchlist, he is choosing not to be prompted for all kinds of options. I can imagine you could discuss to create a feature where we create a new page that shows candidates for being added, and prompt for the option there. But imo that's not worth the effort. I believe in this case the user chooses for a lack of control.

Please let me know from a users perspective how you would like this to be implemented. And please be as specific as possible?!

**Comment by sepuku** [comment]
I requested this a few years ago on the SickBeard forums, and I'm pretty sure there were other requests for this too. The way I see this working, is much the same way as it is done on Couchpotato.
1. You would able to add as many public watchlist URL's as you like, but there would be no differentiation (at least at the beginning) between who's added it and who hasn't. Its annoying when stuff appears when you dont want it to, but you HAVE given other people "permission" to add stuff to your downloader, so you should expect that :) Not everyone has the same tastes.
2. It would add the TV series using your default quality/location settings. In my case, thats HD720p, and a particular TV series folder on a particular drive. If you need to use a different drive, then you just change the default folder setting in SickRage.

Thats all I have for now... :)

**Comment by MickHussey** [comment]
I agree with sepuku.....doing it as he suggests with default quality/location settings would be a great start.

**Comment by cerberusuk** [comment]
I agree also - Keep it simple - Couchpotato is great the way it just pulls in from an IMBD watchlist. Default settings all the way. Would be great to see this added - Thanks @p0psicles

**Comment by sepuku** [comment]
Can I also request another feature to go alongside this... This one might help the people who want to keep track of who's adding what to the list...
Maybe you could add an expander on each public watchlist URL along with the IMDB username of the owner of that watchlist.
This will show you what TV Series have been added via that particular users watchlist.
This can come after the implementation of the watchlist feature itself, but just putting it out there as a nice to have to be able to see where something has been added.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!

**Comment by nikagl** [comment]
Sounds not to difficult to do by adding SickAdd to SickRage?
https://github.com/Modjor/SickAdd
