### ISSUE TITLE
Status-stopped but functioning

### ISSUE THREAD

**Issue by BKSteve** [SiCKRAGETV/sickrage-issues#3092]
BRANCH: (master) / COMMIT: (0b2254c884f833bbb54b8c7e6f6231f4d61557d0) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
Synology DSM 412+ with DSM 5.2-5592 Update 4
Package Center lists Sickbeard Custom with a status of Stopped, however it is operational and seems fully functional.
Action > Run> it goes to starting then switched to stopped.
![sr-151004](https://cloud.githubusercontent.com/assets/10173496/10267956/04e6ad7e-6ad3-11e5-9e0d-65383a9c2614.png)
This happened after updating just today via ipad and the error message created can no longer be found.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@BKSteve Try a reboot on the Synology.
If that doesn't help than backup and remove the sickbeard-custom package and install the new/official sickrage package. (You can also find that on the synocommunity repo.)
Then restore your backup.

**Comment by BKSteve** [comment]
Reboot of DS worked. Thanks.

**Comment by BKSteve** [comment]
Although the reboot worked I moved to the new/official sickrage package.
Remember when you restore the port will be the old sickbeard custom port 8083 not the 8899, it can then be changed in the general settings tab.
