### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SHOWS_RECENT'

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3094]
While updating

```
Error !
AttributeError: 'module' object has no attribute 'SHOWS_RECENT'
<li><a href="${srRoot}/home/"><i class="menu-icon-home"></i>&nbsp;Show List</a></li> <li><a href="${srRoot}/home/addShows/"><i class="menu-icon-addshow"></i>&nbsp;Add Shows</a></li> <li><a href="${srRoot}/home/postprocess/"><i class="menu-icon-postprocess"></i>&nbsp;Manual Post-Processing</a></li> % if sickbeard.SHOWS_RECENT: <li role="separator" class="divider"></li> % for recentShow in sickbeard.SHOWS_RECENT: <li><a href="${srRoot}/home/displayShow/?show=${recentShow['indexerid']}"><i class="menu-icon-addshow"></i>&nbsp;${recentShow['name']|trim,h}</a></li> % endfor % endif
/home/osmc/SickRage/gui/slick/views/layouts/main.mako, line 120:
% if sickbeard.SHOWS_RECENT:
/home/osmc/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)
```

SR Version:	BRANCH: (develop) / COMMIT: (0ad151792871c8d106d58648ae5feb0be3739408) 
SR User:	osmc
SR Locale:	('pt_BR', 'UTF-8')
SR Config:	/home/osmc/SickRage/config.ini
SR Database:	/home/osmc/SickRage/sickbeard.db
SR Cache Dir:	/home/osmc/SickRage/cache
SR Log Dir:	/home/osmc/SickRage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch']
Python Version:	2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
@fernandog a restart of SR should fix that.

**Comment by fernandog** [comment]
Every update I get mako errors.

**Comment by OmgImAlexis** [comment]
@fernandog now that we delete the mako cache on update that should be solved.

**Comment by fernandog** [comment]
but we do that since a long time...I think it's not working. will do some more tests

**Comment by OmgImAlexis** [comment]
Nah, if you have a look it wasn't properly added till one of the last commits.
