### ISSUE TITLE
Daily Search on startup

### ISSUE THREAD

**Issue by gielie** [SiCKRAGETV/sickrage-issues#3105]
BRANCH: (master) / 
COMMIT: (0beda92f71145d448f8f784042a8d631448a0394) 
Os: Synology

What happend to the daily search and show refresh on start up?
I don't want my sick rage running all day so I start SR every morning at 8 and shut it down at 10. Time enough to get all the shows of that day. But the shows of that day stay on unaired and older shows aren't fetched, only after manual search or if I set the daily search interval on a shorter time then 1440 minutes (1day). 

How can I make SR search and fefresh on startup?

**Comment by miigotu** [comment]
You can't. And this feature will not be added back.

It causes unnecessary strain on indexers and providers and they were blocking ALL SR users because of the spam since every restart of SR did a new search/refresh/update.

SickRage is not designed to be a fire-once application. It is, was and always will be designed to be run as a service/daemon.
