### ISSUE TITLE
ERROR    SEARCHQUEUE-BACKLOG :: KickAssTorrents

### ISSUE THREAD

**Issue by rogc** [SiCKRAGETV/sickrage-issues#3112]
Hello,
I did everything: I turned off the program and deleted files and cache.db failed.db, nothing. I reinstalled the program updated to the latest version of master github few minutes ago, and nothing,  the problem persists:

    AAExpatError: syntax error: line 1, column 62
    AA    parser.Parse(xml_input, True)
    AA  File "/opt/sickrage/lib/xmltodict.py", line 248, in parse
    AA    data = xmltodict.parse(data)
    AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 137, in _doSearch
    AATraceback (most recent call last):
    AAExpatError: syntax error: line 1, column 62
    AA    parser.Parse(xml_input, True)
    AA  File "/opt/sickrage/lib/xmltodict.py", line 248, in parse
    AA    data = xmltodict.parse(data)
    AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 137, in _doSearch
    2015-10-05 13:48:01 ERROR    SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
    2015-10-05 13:47:55 INFO     SEARCHQUEUE-BACKLOG-258171 :: [KickAssTorrents] :: Performing episode search for *******
    2015-10-05 13:46:46 INFO     SEARCHQUEUE-BACKLOG-258171 :: Beginning backlog search for: [********]

In this way all the episodes are queued and visible in BACKLOG OVERVIEW. If I manually insert 
the torrents, they are detected and processed as planned.
Sickrage, master and downloaded few minutes ago, runs on a raspberry pi with Debian OS:
Linux raspberrypi 4.1.7+ # 817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU / Linux
Python 2.7.3 (default, 18 March 2014, 05:13:23)
[GCC 4.6.3] on linux2

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/3111
