### ISSUE TITLE
Error while searching T411, skipping: ValueError('No JSON object could be decoded',)

### ISSUE THREAD

**Issue by giaat** [SiCKRAGETV/sickrage-issues#3124]
### INFO

Python Version: 2.7.10
Operating System: Synology DSM 5.2-5592 Update 4
Branch: master
COMMIT: 6f972deef18a2e93bbcc3ba25eb05e02c0201f22)

### ERROR

> 2015-10-05 22:28:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-05 22:28:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: Transaction with 4 queries executed
2015-10-05 22:28:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: Transaction with 4 queries executed
2015-10-05 22:28:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: Error while searching T411, skipping: ValueError('No JSON object could be decoded',)
2015-10-05 22:28:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: T411 search page URL: https://api.t411.in/torrents/search/?cid=433&limit=100
2015-10-05 22:28:58 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: Using T411 Authorization token : 100528426:277:f4c704ffb05924741f23182fac304e95
2015-10-05 22:28:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Cpasbien] :: Last update was too soon, using old cache: 2015-10-05 22:27:57. Updated less then 10 minutes ago
2015-10-05 22:28:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: Performing authentication to T411
2015-10-05 22:28:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: _doSearch started with ...{'RSS': ['']}

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
disable proxy for this provider

**Comment by giaat** [comment]
@fernandog 
it's already disable

**Comment by miigotu** [comment]
This happens where there is no result, this provider returns an empty response instead of an empty json.

**Comment by Abbo44** [comment]
'''
2015-10-06 21:03:45 ERROR    SEARCHQUEUE-MANUAL-274431 :: [T411] :: Torrent file content is empty
AAReadTimeout: HTTPSConnectionPool(host='api.t411.in', port=443): Read timed out. (read timeout=30)
AA    raise ReadTimeout(e, request=request)
AA  File "/opt/sickrage/lib/requests/adapters.py", line 433, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/opt/sickrage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/opt/sickrage/sickbeard/helpers.py", line 1623, in getURL
AATraceback (most recent call last):
2015-10-06 21:03:45 ERROR    SEARCHQUEUE-MANUAL-274431 :: [T411] :: Connection timed out accessing getURL https://api.t411.in/torrents/download/5388053 Error: error HTTPSConnectionPool(host='api.t411.in', port=443): Read timed out. (read timeout=30)
2015-10-06 21:03:15 INFO     SEARCHQUEUE-MANUAL-274431 :: [T411] :: Downloading Gotham.S02E03.FASTSUB.VOSTFR.720p.HDTV.X264-RUDY from T411
'''
Connection timed out when he found a file, its normal ?

**Comment by duramato** [comment]
@Abbo44 thats a problem with their servers or your internet not SR

**Comment by miigotu** [comment]
Actually its a problem using proxy I think.

**Comment by Abbo44** [comment]
Oh yes the tracker is off. Ty @duramato and @miigotu
