### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute 'render_body'

### ISSUE THREAD

**Issue by MilhouseVH** [SiCKRAGETV/sickrage-issues#3127]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.0.6-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2380148b926e0e731d7fbac805d3a88c42cf1e31
Link to Log: https://gist.github.com/4ccfc04d6cebfd9d6853
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Stop sickrage and delete cache/mako

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by count00zero** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.7-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/pi/SickRage/lib/mako/template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brouzz** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/baf9b0226ce5c44b0f56
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage-master\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage-master\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage-master\lib\mako\template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brouzz** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/c6171d4c5d7337cbc802
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage-master\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage-master\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage-master\lib\mako\template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brouzz** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/ded30d5f1ec7bdf23c30
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage-master\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage-master\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage-master\lib\mako\template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Stop sickrage and delete cache/mako
