### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/nicolas/Downloads/S\xc3\xa9ries'

### ISSUE THREAD

**Issue by atout001** [SiCKRAGETV/sickrage-issues#3156]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cd3a07214e294bb90c79ff097a7f92ebb04cfcdb
Link to Log: https://gist.github.com/1e3ca0f6c52282febef8
### ERROR
```
Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/nicolas/sickrage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/nicolas/sickrage/sickbeard/webserve.py", line 1045, in status
    rootDir[subject] = helpers.getDiskSpaceUsage(subject)
  File "/home/nicolas/sickrage/sickbeard/helpers.py", line 1929, in getDiskSpaceUsage
    st = os.statvfs(diskPath)
OSError: [Errno 2] No such file or directory: '/home/nicolas/Downloads/S\xc3\xa9ries'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by atout001** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cd3a07214e294bb90c79ff097a7f92ebb04cfcdb
Link to Log: https://gist.github.com/6deb54e4c0d9b19e246a
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/nicolas/sickrage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/nicolas/sickrage/sickbeard/webserve.py", line 1045, in status
    rootDir[subject] = helpers.getDiskSpaceUsage(subject)
  File "/home/nicolas/sickrage/sickbeard/helpers.py", line 1929, in getDiskSpaceUsage
    st = os.statvfs(diskPath)
OSError: [Errno 2] No such file or directory: '/home/nicolas/Downloads/S\xc3\xa9ries'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
