### ISSUE TITLE
email notification via gmail?

### ISSUE THREAD

**Issue by nic0dk** [SiCKRAGETV/sickrage-issues#3158]
tried to setup notification via gmail without any luck, getting follow error:
ERROR: SMTP AUTH extension not supported by server.

ubuntu 14.04
COMMIT: (638270689679f3958d1b593c329e7c6e5cb7448e)
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

im using following settings:
SMTP host: smtp.gmail.com
SMTP port: 587
use TLS: checked
SMTP user: xxxx@gmail.com
SMTP password: xxxxx
Global email list: xxxx@gmail.com

anyone that have other settings that will work for gmail?

log http://pastebin.com/GnyqdLr5

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Support/questions belong in the forum, not on an issue tracker.

**Comment by nic0dk** [comment]
ok, ill try to hear in the forum

**Comment by fernandog** [comment]
Also read wiki/faqs as bot said

**Comment by nic0dk** [comment]
tried to look it up on the wiki but wasn't able to find much about it. many i overlooked it :)

**Comment by fernandog** [comment]
i think some one already replied here in issues. try to use the issues search

https://github.com/SiCKRAGETV/sickrage-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+gmail

**Comment by kkorolz** [comment]
Please, keep in mind that some users have Google 2-Step Verification, then "lesssecureapps" url enable/disable doesn't work therefore we must create and set specific app passwords to be used by Sickrage notification. Actually, same settings with same app password in OpenMediaVault notification is working properly. Any ideas?

**Comment by miigotu** [comment]
If you have 2 step working then you need a different single use login generated per app. If you used it for OMV it is tied to OMV. Create another just for SR.

**Comment by kkorolz** [comment]
My firs try with the app password was in SR before OMV. As it didn't work in SR, I copy/pasted same password in OMV and worked at first try. I've just generated a new one, completely unused by any device yet, used same settings I'm using with OMV and it doesn't work in SR.
