### ISSUE TITLE
[APP SUBMITTED]: TypeError: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by didyouexpectthat** [SiCKRAGETV/sickrage-issues#3167]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: --Not accurate auto-generated link
### ERROR
```
2015-10-06 18:13:02 SEARCHQUEUE-BACKLOG-78956 :: [omgwtfnzbs] :: Unknown exception in getURL https://api.omgwtfnzbs.org/json/?search=So.You.Think.You.Can.Dance.7x23&catid=19%2C20&eng=1&api=XXXXXXXX&user=XXXXXXXX&retention=1000 Error: __str__ returned non-string (type Error)
2015-10-06 18:13:02 SEARCHQUEUE-BACKLOG-78956 :: [omgwtfnzbs] :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/helpers.py", line 1622, in getURL
    else:
  File "/usr/share/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/sickrage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/sickrage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/sickrage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/share/sickrage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/share/sickrage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/share/sickrage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by didyouexpectthat** [comment]
This is not the bug I thought it was going to file.

**Comment by didyouexpectthat** [comment]
When I try to access the API manually, i am greeted with a certificate error. Maybe this is the root cause.

**Comment by fernandog** [comment]
@miigotu can we add a sockets timeout here? isn't what his error is ?
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1654

**Comment by fernandog** [comment]
```
import socket
except socket.timeout: 
        logger.log(u"Connection timed out accessing getURL %s" %  url, logger.WARNING)
```
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1638

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/3169
