### ISSUE TITLE
Log After Clean start of QSickrage on QNAP and Update to latest Commit

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#3187]
"2015-10-07 13:21:22 ERROR    Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
```
AAAttributeError: 'module' object has no attribute 'render_body'
AA    self.callable_ = self.module.render_body
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 328, in __init__
AA    super(PageTemplate, self).__init__(*args, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 116, in __init__
AA    t = PageTemplate(rh=self, file="home.mako")
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 660, in index
AA    result = function(**kwargs)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 265, in async_call
AATraceback (most recent call last):
AAAttributeError: 'module' object has no attribute 'render_body'
AA    self.callable_ = self.module.render_body
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 328, in __init__
AA    super(PageTemplate, self).__init__(*args, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 116, in __init__
AA    t = PageTemplate(rh=self, file="home.mako")
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 660, in index
AA    result = function(**kwargs)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 265, in async_call
2015-10-07 13:21:22 ERROR    Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-bg_glass_75_dadada_1x400_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-bg_highlight-soft_75_cccccc_1x100_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-bg_glass_65_ffffff_1x400_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-bg_glass_75_e6e6e6_1x400_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-bg_flat_75_ffffff_40x100_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ConfigGeneral' object has no attribute 'images/ui-icons_222222_256x240_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ErrorLogs' object has no attribute 'viewlog/images/ui-bg_flat_75_ffffff_40x100_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
AAAttributeError: 'ErrorLogs' object has no attribute 'viewlog/images/ui-bg_highlight-soft_75_cccccc_1x100_png'
AA    method = getattr(self, route)
AA  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 248, in get
AA
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by Peke** [comment]
QPython3 is installed.

**Comment by miigotu** [comment]
QPython3 ?

**Comment by OmgImAlexis** [comment]
@Peke clear your browser cache and this error should go away.

**Comment by Peke** [comment]
@miigotu
Qpython3 http://forum.qnap.com/viewtopic.php?t=114113
I also found that only this version pass first Update http://www.forum-nas.fr/viewtopic.php?f=21&t=1359&hilit=Qsickrage and it looks that it have 2.7 embed in Package :( with all those errors due the Python 2.7 in compat.py Line 66

@OmgImAlexis 
It worked for now.

I cant beleive that there is no goo/stable Fork of Sickrage for QNAP Those I found Force installing Python 2.7 and you are moving to Python 3.x which is great and forward thinking.

**Comment by miigotu** [comment]
Python 3 absolutely will not run SR atm.

**Comment by Peke** [comment]
Good to Know. Closing

**Comment by OmgImAlexis** [comment]
@Peke crashing after an update doesn't mean it's not stable, apart from a very few crashes after update SR hardly ever crashes. This is stable.
