### ISSUE TITLE
Too much warning messages

### ISSUE THREAD

**Issue by c4uran** [SiCKRAGETV/sickrage-issues#3189]
in Sickrage watch folder(for postprocess) i have not just TV series, i have music for headphones and movies for couchpotato so here lots of files and they different reasons not moved automated

so after last update of sickrage for every file in watch folder i got one warning message every 10 minutes(i have hundreds of they already), could you please make switch or just turn off warning for shows isn't in my list

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Which warning message? Full message please

**Comment by c4uran** [comment]
![sickrage-warning](https://cloud.githubusercontent.com/assets/12890369/10338645/d528dfaa-6d0f-11e5-9c1c-7a33d3efc60f.png)

**Comment by c4uran** [comment]
its looks like push

**Comment by fernandog** [comment]
Not that. What is THE message that in your opinion shouldnt be a WARNING?

**Comment by c4uran** [comment]
ah... sorry, looks like:

2015-10-07 15:53:23 POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  
2015-10-07 15:53:23 POSTPROCESSER :: [/volume1/waiting/sickbear/Trainwreck.mkv : Processing failed: ]
2015-10-07 15:53:23 POSTPROCESSER :: [/volume1/waiting/sickbear/[DeadFish] Mou Hitotsu no Mirai wo. - 03 - ONA [720p][AAC].mp4 : Processing failed: ]
2015-10-07 15:53:23 POSTPROCESSER :: [/volume1/waiting/sickbear/Gekijouban Steins;Gate.avi : Processing failed: ]
2015-10-07 15:53:23 POSTPROCESSER :: [/volume1/waiting/sickbear/The Brink - Temporada 1 .mkv : Processing failed: ]
2015-10-07 15:53:23 POSTPROCESSER :: [/volume1/waiting/sickbear/Derren.Brown.The.Great.Art.Robbery.480p.HDTV.x264-mSD.mkv : Processing failed: ]
2015-10-07 15:53:15 POSTPROCESSER :: This show isn't in your list, you need to add it to SB before post-processing an episode

**Comment by fernandog** [comment]
You need to fix that. Without it How user would know and fix it?

**Comment by OmgImAlexis** [comment]
@c4uran if you don't want the warnings do what everyone else does and make a seperate download directory for sickrage.

**Comment by c4uran** [comment]
i cant get why u didnt recognize it like a bug, because all time before that wasnt work like that and do you really think if people automate TV they dont automate movies or something else?

may be just add switch in Advanced settings - log as only warnings or something else

**Comment by c4uran** [comment]
fernandog its pretty easy because you can see it in filesystem

**Comment by miigotu** [comment]
@c4uran its not a bug, they always had these warnings. We simply did not have a notification of warnings before.

**Comment by c4uran** [comment]
anyway thank you for support i hope youll change youre mind about that

**Comment by fernandog** [comment]
YOU that should deal with that warning. not us.
