### ISSUE TITLE
When shows fail loading tvdb we need to show more info

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3198]
From seeing just this in my warnings it doesn't tell me anything that'd help me fix the issue when I've got well over 100 shows. We should at least show the tvdb `ID` or show name.

````
2015-10-08 03:39:53 SHOWQUEUE-FORCE-UPDATE :: Error when trying to load the episode from theTVDB: Could not find season 2
````

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
log error message: "Could not find season 2" ?

what you need more? maybe the season 2 info are missing in the indexer

https://github.com/SiCKRAGETV/SickRage/blob/8b23076c2737af47b603e8cd0d4c8529e56b2b1b/sickbeard/tv.py#L513

**Comment by miigotu** [comment]
@OmgImAlexis considering like 2 lines before that in your log it says what show it is working on....

**Comment by OmgImAlexis** [comment]
@miigotu actually that's ALL it says on the viewlog page. I got nothing more, that's why I added this issue.

**Comment by miigotu** [comment]
Even in debug? Probably just needs some lines adjusted from degug=>info or vice versa.

**Comment by OmgImAlexis** [comment]
@miigotu in debug it gives the full message, we should just add the show name/id to the info tag.

**Comment by fernandog** [comment]
@miigotu what about change to:

`logger.log(u"%s: Error when trying to load the episode from %. Message: %s " (curResult['showid'], sickbeard.indexerApi(self.indexer).name, e.message), logger.WARNING)`

**Comment by miigotu** [comment]
sure

**Comment by fernandog** [comment]
Also some log messages there are wrong

 curResult is empty in the log (log message before that one)

**Comment by fernandog** [comment]
@OmgImAlexis did you get that warning again?

**Comment by OmgImAlexis** [comment]
@fernandog nope!
