### ISSUE TITLE
What happens when the show name is not what it should be looking for?

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#3199]
So, this is probably a little strange. But this is an issue i came across mainly with using SickRage with Anime.

Here is an example: `http://thetvdb.com/?tab=series&id=293996`
The actual name of this anime is different, it actually is: `http://myanimelist.net/anime/30544/Gakusen_Toshi_Asterisk`

I mean, its not my place to say what is correct and what is wrong. But for the sake of finding downloads, you cannot do so with the name on the first link, but you can if you use the name of the second link. Whats the solution here? I cant really use sickrage for shows such as this, as sickrage searches for the name it thinks it should be and then fails to find it.

im not really going to bother stating os/version details, as this would be the same across what ever the scenario is.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by syrys** [comment]
hmm maybe i should also ask, is this an issue with sickrage? i guess so? I guess you can provide us with some sort of an alternative field to state show name manually (for searching and post processing)? 

Or is this an issue with theTVDB or torrent provider? Even if it is, theres nothing really we can do about it.

So what im saying is, is there a way for us to define an override name?

**Comment by syrys** [comment]
now that i look at it further, to be fair, quite a lot of my anime are a little messed up.

Eg1: TVDB thinks the anime has 2 seasons, but season 2 actually has a different name (so if you search for ShowName S02E01 or something, you wont get any hits).
Eg2: anime might have an english name and a Japanese name. TVDB uses English but torrents use Japanese name. 
Eg3: Anime torrents use a different episode numbering to what TVDB uses and thus what torrents sickrage searches for. 

Is there any better solution for anime than TVDB?

Sorry, this problem so far is only for anime.

**Comment by OmgImAlexis** [comment]
Not sure if you know but there's scene exceptions which should fix this in your case, we're also looking into adding another indexer just for anime as there's quite a few issues that affect them.

**Comment by syrys** [comment]
@OmgImAlexis thanks, ill give that a go. Thats not really the biggest issues i have at the moment, the not downloading anime part is the biggest annoyance. But in the meantime, if there is a guide or any docs about this scene numbering/exception thing, flick me a link. otherwise i should be able to figure it out.

Cheers.

**Comment by miigotu** [comment]
Edit show => add the other name as a scene exception. Enable scene numbering. Its that simple.
