### ISSUE TITLE
Plex Media Server notification broken when using web_root

### ISSUE THREAD

**Issue by Alives** [SiCKRAGETV/sickrage-issues#3200]
* Branch: `master`
* Commit hash: `1c57cce2d73d9775acb01f256e07d22a93f4c1f4`
* Your operating system and python version: `Ubuntu 15.04`, `Python 2.7.9`
* What you did: `Entered my Plex Tag and Plex server IP:Port in the Plex Media Server notification fields`
* What happened: `Nothing, spinning wheel, no communication with plex.`
* What you expected: `A GET request to my Plex service.`
* How can we reproduce your issue:

1. In the Notifications settings in SickRage, under "Plex Media **Server**", click "Enable".
2. Change the "Plex Media Server IP:Port" to your local IP and a high port (above 1024, like 10.0.0.2:9998).
3. Run netcat on that port in your terminal: `nc -vl 9998`
4. Click "Test Plex Server" in the SickRage notification settings area for Plex Media Server.
5. You won't see anything show up on your netcat session.  You also won't see any new log lines, error or otherwise.

You can prove that this test works using the other portion of the Plex nofication script, "Plex Media Client":

1. In the Notifications settings in SickRage, under "Plex Media **Client**", click "Enable".
2. Change the "Plex Client IP:Port" to your local IP and a high port (above 1024, like 10.0.0.2:9998).
3. Run netcat again on that port in your terminal: `nc -vl 9998`
4. Click Test Plex Media Client in the SickRage notification settings area for Plex Media Client.
5. You will now see the HTTP GET request:
```
# nc -l 9998
GET /xbmcCmds/xbmcHttp/?parameter=Notification%28Test+Notification%2CThis+is+a+test+notification+from+SickRage%29&command=ExecBuiltIn HTTP/1.1
Accept-Encoding: identity
Host: 10.0.0.2:9998
Connection: close
User-Agent: Python-urllib/2.7
```

You will also see this in the log.  If you don't run netcat, you'll also see the error in the log that it couldn't connect.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
This must be an issue with your firewall, etc. I have plex running on the default 32400 port and it works fine. Just to test I run netcat on the server and changed the port in the Plex server config section to 9998 like you said and netcat gets the request fine.

````
media@media:~$ nc -vl 9998
Listening on [0.0.0.0] (family 0, port 9998)
Connection from [127.0.0.1] port 9998 [tcp/*] accepted (family 2, sport 51711)
GET /library/sections?X-Plex-Token=4PXy6SaeqVs3D1BSpyvL HTTP/1.0
Host: 127.0.0.1:9998
User-Agent: SickRage/(Linux; 3.13.0-57-generic; 64ba49ee-6d40-11e5-b406-08002711baf6)
````

**Comment by Alives** [comment]
You should edit that comment and remove your tag.

I don't think it's a firewall issue as I don't run one that I'm aware of...

`# echo 'test' | nc 10.0.0.2 9998`

Then in another terminal I get:
```
# nc -vl 9998
Listening on [0.0.0.0] (family 0, port 9998)
Connection from [10.0.0.2] port 9998 [tcp/*] accepted (family 2, sport 46783)
test
```
If I try hitting my plex instance itself:
```
# echo -e 'GET /library/sections?X-Plex-Token=blah HTTP/1.0\r\n\r\n' | nc localhost 32400
HTTP/1.1 200 OK
Content-Type: text/xml;charset=utf-8
Content-Length: 2473
Connection: close
X-Plex-Protocol: 1.0
Cache-Control: no-cache

<?xml version="1.0" encoding="UTF-8"?>
...
```

Actually that's interesting... localhost works, but for some reason 10.0.0.2 doesn't...
```
# echo -e 'GET /library/sections?X-Plex-Token=blah HTTP/1.0\r\n\r\n' | nc 10.0.0.2 32400
```
Nothing, exit status 0.
```
# netstat -plnt | grep 32400
tcp        0      0 0.0.0.0:32400           0.0.0.0:*               LISTEN      28156/Plex Media Se
```

Putting `127.0.0.1` into the plex notification settings still doesn't work.  I tried going into my plex server settings and disabling secure connections as well, but still nothing.

I setup a new sickrage instance in a docker and it works fine, so I'll close this.  Sorry for the confusion.

**Comment by Alives** [comment]
Apparently this is due to having web_root set.  When I remove the setting, everything works fine.  Also, side issue, the plex images in the notifications page are broken when web_root is set.

**Comment by Alives** [comment]
It was a problem with my reverse proxy :(
