### ISSUE TITLE
Search icon missing for Specials 

### ISSUE THREAD

**Issue by yoleks** [SiCKRAGETV/sickrage-issues#3202]
Kind of self explanatory , it doesn't search for the episode during backlog and the daily search. 

![capture](https://cloud.githubusercontent.com/assets/15025384/10356656/a56b864a-6d79-11e5-912d-54fbc5efdf57.JPG)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Please make sure to submit all of the required information, or we won't be able to help you!

**Comment by OmgImAlexis** [comment]
@fernandog I asked him to open it, sorry.

https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/views/displayShow.mako#L515

For some reason we don't show search buttons on specials, @miigotu ?

**Comment by fernandog** [comment]
Before mako used to have Afaik.

@duramato confirm?

**Comment by yoleks** [comment]
Branch is master 

OS is  Xubuntu 14.04 Desktop (Trusty Tahr) based on a 64-bit system.

I only recently decided to download some specials and I found that the search icon is missing and it didn't include them in the daily search or the backlog overview.

**Comment by yoleks** [comment]
:update Even after a restart the icon does not apear.

**Comment by OmgImAlexis** [comment]
@yoleks they're missing in the code. You'll just have to wait till we fix it.

**Comment by miigotu** [comment]
AFAIK they are not there on purpose? I dont think we support downloading specials atm.

**Comment by OmgImAlexis** [comment]
@miigotu maybe it was taken out when we stripped tvrage?

**Comment by miigotu** [comment]
Nope, tvrage stripping was all backend

**Comment by duramato** [comment]
@fernandog nope,afaik since I've be been using SR it never had special search
It is the only thing SR has missing ,its the lack of support for specials 
BUT having it would be a good addition..

**Comment by miigotu** [comment]
Having providers work would be a better addition.

**Comment by miigotu** [comment]
Feature requests go on feathub. Check the reply from @SiCKRAGEB0T for the link
