### ISSUE TITLE
Pause/unpaused a show change its `paused` attribute type

### ISSUE THREAD

**Issue by MGaetan89** [SiCKRAGETV/sickrage-issues#3204]
The API used to return the `paused` attribute of a show as an int (0 or 1).
If you pause/unpaused a show, the returned value is now a boolean, which breaks the parsing of the response in my application (didn't try other applications).
This affects, at least, the `shows` and `show` command.

See https://github.com/MGaetan89/ShowsRage/issues/24

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by MGaetan89** [comment]
`subtitles` are also mixed (`true` and `false` instead of `0` and `1`).
I guess all possible boolean values are affected.

**Comment by miigotu** [comment]
From when you combined the api/webserve methods =P

**Comment by MGaetan89** [comment]
Nah, can't be me, I never make mistakes :P

In the `CMD_Show` class, I think the follow values should be fixed to return `0` or `1`:
- `paused`
- `subtitles`
- `air_by_date`
- `flatten_folders`
- `sports`
- `anime`
- `dvdorder`
- `scene`
- `archive_firstmatch`

For the `CMD_Shows`, there is:
- `paused`
- `air_by_date`
- `sports`
- `anime`
- `subtitles`

I guess a simple `(0, 1)[show.property_name]` should be enough. What do you think?
I can fix this next Monday I think.

**Comment by miigotu** [comment]
Can be done when creating the json right? It should stay as a bool value internally

**Comment by MGaetan89** [comment]
Yes, I meant changing it on the API part. I don't mind having boolean values internally, as long as the API remains stable. I will have to be more careful with that with my next refactor :P
When we start working on the new API, we will be able to switch to boolean values.

**Comment by fernandog** [comment]
i would keep as it was before. so we don't broke the other apps

**Comment by miigotu** [comment]
Api v2 will run alongside the original api (or have the orignail api calls as a subset). This is about returning original api to previous behavior.

**Comment by fernandog** [comment]
ok. it's better run both

**Comment by MGaetan89** [comment]
Fixed in `develop`.
