### ISSUE TITLE
Episode Not Processing Possibly Due to Long Filename

### ISSUE THREAD

**Issue by Digital-Jedi** [SiCKRAGETV/sickrage-issues#3211]
BRANCH: (master)
COMMIT: (82012b1b6063b59ef441ec1dd0a671ad51b62172) 
Windows 10 / Python 2.7
Log: http://pastebin.com/s6J39NNj

This is more of an FYI than anything, as I've only ran into this problem with this particular file. Neither automatic, nor manual post-processing work on this one file. I suspect, because of the parameters I have set, to use the name of the episode in the filename, is making just this one episode's filename larger than what Windows normally allows.

>2015-10-08 09:31:27 ERROR    Thread-24 :: Unable to copy file C:\Users\markd_000\Downloads\Torrent Downloads\Completed\Stephen.Colbert.2015.09.24.Andrew.Sullivan.720p.CBS.WEBRip.AAC2.0.x264-SynHD[rarbg]\The.Late.Show.with.Stephen.Colbert.2015.09.24.Andrew.Sullivan.720p.CBS.WEBRip.AAC2.0.x264-SynHD.mkv to C:\Users\markd_000\Videos\TV Shows\Late Show with Stephen Colbert\Season 01\The Late Show with Stephen Colbert - s01e13 - ''Andrew Sullivan, Maria Shriver, Jim Gaffigan, Archbishop Thomas Wenski, YMCA Jerusalem Youth Chorus, the Choir of St. Jean Baptiste''.mkv: error 2 : No such file or directory

So my usual formatting is **_Season 00/Show Name - s00e00 - ''Episode Title''.ext_** (Those are doubled single quotes, by the way.)

Which would make this particular filename be **_The Late Show with Stephen Colbert - s01e13 - ''Andrew Sullivan, Maria Shriver, Jim Gaffigan, Archbishop Thomas Wenski, YMCA Jerusalem Youth Chorus, the Choir of St. Jean Baptiste''.mkv_**

So, yeah, I'm just gonna move it manually, since that's waaaaay larger than what Windows allows. But figured you'd want to know, should this come up again with some of the larger "Episode Names" on some of these newer talk shows. (Unless, of course, it's a completely different issue that I didn't know I had.) Note that I was no longer seeding the episode and had removed it from the torrent client.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Cant we epname[:20] for example? Using windows/linux limit 

In db, what is max lenght for ep name field?

**Comment by miigotu** [comment]
His file name is literally 2 characters to long.

The way we would work around this is by prepending all rootdir/showdir with \\?\
```To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".```

**Comment by fernandog** [comment]
ok!

**Comment by Digital-Jedi** [comment]
For what it's worth, when I manually rename it, Windows truncates 8 characters. Not 2. 

St. Jean Ba*`ptiste''`*
