### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't encode character u'\u014d' in position 32: character maps to <undefined>

### ISSUE THREAD

**Issue by apoapostolov** [SiCKRAGETV/sickrage-issues#3213]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@e74d495173df72eb458328bd9fd7616dd742e1f3
Link to Log: https://gist.github.com/ecaf82707a881ffa0b94
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "D:\!Media\!Tools\SickRage\sickbeard\tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "D:\!Media\!Tools\SickRage\sickbeard\tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "D:\!Media\!Tools\SickRage\sickbeard\subtitles.py", line 102, in subtitlesLanguages
    with open(video_path.encode(sickbeard.SYS_ENCODING), 'rb') as f:
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 32: character maps to <undefined>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
chcp 65001 && python SickBeard.py

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8d2f7834841409f57aedbcc24e4b739c0d088e8a
Link to Log: https://gist.github.com/ed3f8e90dec06e697797
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/sickbeard/tv.py", line 1505, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_path.encode(sickbeard.SYS_ENCODING), single=not sickbeard.SUBTITLES_MULTI)
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 110: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8d2f7834841409f57aedbcc24e4b739c0d088e8a
Link to Log: https://gist.github.com/3223eb49856417d9c564
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/sickbeard/tv.py", line 1505, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_path.encode(sickbeard.SYS_ENCODING), single=not sickbeard.SUBTITLES_MULTI)
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 82: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8d2f7834841409f57aedbcc24e4b739c0d088e8a
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/sickbeard/tv.py", line 1505, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_path.encode(sickbeard.SYS_ENCODING), single=not sickbeard.SUBTITLES_MULTI)
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 110: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by brse** [comment]
### INFO
Python Version: **2.7.3 (default, Sep  4 2013, 13:54:56) [GCC 4.6.4 20120731 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8d2f7834841409f57aedbcc24e4b739c0d088e8a
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/sickbeard/tv.py", line 1505, in downloadSubtitles
    subliminal.save_subtitles(foundSubs, directory=subs_path.encode(sickbeard.SYS_ENCODING), single=not sickbeard.SUBTITLES_MULTI)
  File "/mnt/HD/HD_a2/Nas_Prog/sb/sickbeard/lib/subliminal/api.py", line 133, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 82: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
chcp 65001 && python SickBeard.py

**Comment by miigotu** [comment]
Last poster was linux user, needs to set locale to utf-8 by exporting LANG as the SR user before running SR.
