### ISSUE TITLE
Invalid username or password for IPTorrents

### ISSUE THREAD

**Issue by sbaak** [SiCKRAGETV/sickrage-issues#3215]
IPT is giving me the error in the title but I 100% know it is the correct information I mean I am on it right now log out and back in no issue. I even changed my password and tried that. 
I edited the iptorrent config file from iptorrents.eu to .com, .us, also enabled and disabled the SSL verification in sickrage to no avail. In my Config.ini it shows the correct username/password

Restarted Sickrage each time*

Log- http://pasted.co/193741f0

Google has brought me to various sickrage support q/a's that led me doing the above.

You guys are smarter than me.. 
I'm lost mom :(

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
probably you exceeded login attempts as now you have to wait

```
        if re.search('tries left', response) \
                or re.search('<title>IPT</title>', response):
            logger.log(u'Invalid username or password for ' + self.name + ', Check your settings!', logger.ERROR)
            return False
```

@duramato do you have IPT? any issues ?

**Comment by miigotu** [comment]
I have ipt I'll try when I get home

**Comment by WebSpider** [comment]
I have ipt, it's working fine for me

**Comment by sbaak** [comment]
I believe it to be the "exceeded login attempts you have to wait" I will see what it says tomorrow
<3

**Comment by fernandog** [comment]
we will check when 'exceeded login' and when 'incorrect password' in html
need to check the html so we can check and post the correct message

**Comment by fernandog** [comment]
Any of you can tell me the html for that situations?

**Comment by sbaak** [comment]
I still have the issue today but idk the time limit after failing to login so many times.

the html um Idk exactly what you need but 

<div style="color: black; background-color: yellow;padding:2px 10px; position:absolute;width:260px;margin-left:-140px;left:50%;top:200px;text-align:center">Password not correct<br>11 tries left<br /></div>

<div style="color: black; background-color: yellow;padding:2px 10px; position:absolute;width:260px;margin-left:-140px;left:50%;top:200px;text-align:center">You tried too often, please try again after 1 hour!<br>0 tries left<br /></div>

**Comment by maxcore** [comment]
the same with FNT to ...libertalia all work good now

**Comment by fernandog** [comment]
@sbaak please send the html for password invalid

**Comment by fernandog** [comment]
@sbaak please disable IPT for at least one hour

**Comment by fernandog** [comment]
@maxcore can you open an new issue with html data ?

**Comment by maxcore** [comment]
@fernandog  i put me debug log

**Comment by fernandog** [comment]
@maxcore debug log don't help
