### ISSUE TITLE
Sickrage as a service - does not start

### ISSUE THREAD

**Issue by sjay1** [SiCKRAGETV/sickrage-issues#3222]
Hi,

I currently have Sickrage installed as a service, and all of a sudden it just doesn't start anymore and stopped randomly at some point. 

http://puu.sh/kDSSZ/014f9cab84.png

Any ideas on how to fix?

Thanks

Required Info:

Branch/Commit: unknown.. perhaps this happened after an update? I can't start it
OS: Windows 10
What I did: nothing
What happened: it doesn't start

The log looks interesting? http://pastebin.com/qznyVsRK

Installed using the service installer from this website.

Thanks

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
@fernandog or @VinceVal can someone explain how to do a manual git pull when installed using the installer?

**Comment by VinceVal** [comment]
@miigotu not sure about making the service do a git pull, but we could probably make a shortcut for the user that does that easily enough...

Since the Windows installer doesn't add git to the system path, you'd want to do something like:

    cd \SickRage\SickRage
    ..\Git\cmd\git.exe <blahblahblah>

**Comment by miigotu** [comment]
@sjay1 open a cmd prompt and do:
```
cd C:\SickRage\SickRage
..\Git\cmd\git.exe fetch origin
..\Git\cmd\git.exe git reset --hard origin/master
```
reboot your pc.

**Comment by sjay1** [comment]
@miigotu 

http://puu.sh/kELNf/d13d5da772.png

Worked after I removed the git from the command.

While you're here - do you know how to make this accessible on the local network? I was linked some other article when I asked before and it didn't help.

I already changed the login user to Network Service but it still does not work.

Thanks

**Comment by miigotu** [comment]
No clue without trying to configure it myself. I dont use windows.
