### ISSUE TITLE
Some search providers are completely broken

### ISSUE THREAD

**Issue by HenrikPoulsen** [SiCKRAGETV/sickrage-issues#3242]
I have noticed that at least NyaaTorrents and TokyoToshokan provider has broken this week (Using latest master (d1118cb1c9114778535b85b7e59758fde57ad9a5)).

Here are some of the log outputs I get from the logs when searching for some episodes:

Utawarerumono
```
AA
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/feedparser/feedparser.py", line 353, in __getitem__
AA    title = curItem[0]
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/nyaatorrents.py", line 80, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/generic.py", line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/nyaatorrents.py", line 53, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/search.py", line 488, in searchProviders
2015-10-10 15:57:43 ERROR    SEARCHQUEUE-MANUAL-79880 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0
2015-10-10 15:57:43 INFO     SEARCHQUEUE-MANUAL-79880 :: [NyaaTorrents] :: Performing episode search for Utawarerumono
```

Is It Wrong to Try to Pick Up Girls in a Dungeon?
```
AA
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/feedparser/feedparser.py", line 353, in __getitem__
AA    title = curItem[0]
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/nyaatorrents.py", line 80, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/generic.py", line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/nyaatorrents.py", line 53, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/search.py", line 488, in searchProviders
2015-10-10 16:01:11 ERROR    SEARCHQUEUE-MANUAL-289882 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0
2015-10-10 16:01:10 INFO     SEARCHQUEUE-MANUAL-289882 :: [NyaaTorrents] :: Performing episode search for Is It Wrong to Try to Pick Up Girls in a Dungeon?
```

It seems to be from commit ff9d636104a86efd91cce3fce315549bac40fa49 where the FeedparserDict seems to be treated like a list instead of a Dict without the feedparser itself having been updated.
Doesn't seem like that code was ready to go into master.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by HenrikPoulsen** [comment]
Which issue is it duplicating? I can't really find any recent issues with a similar issue.
