### ISSUE TITLE
Nyaa Provider broken

### ISSUE THREAD

**Issue by seed1234** [SiCKRAGETV/sickrage-issues#3246]
AA
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py", line 353, in __getitem__
AA    title = curItem[0]
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py", line 85, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py", line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py", line 58, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py", line 488, in searchProviders
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py", line 353, in __getitem__
AA    title = curItem[0]
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py", line 85, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py", line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py", line 58, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py", line 488, in searchProviders
AATraceback (most recent call last):
2015-10-11 06:38:20 ERROR    SEARCHQUEUE-MANUAL-252384 :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error 0

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
please update

**Comment by seed1234** [comment]
already did

**Comment by fernandog** [comment]
@miigotu know whats wrong?

**Comment by seed1234** [comment]
AA
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py",
line 353, in __getitem__
AA    title = curItem[0]
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py",
line 85, in _doSearch
AA    itemList += self._doSearch(curString, search_mode,
len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py",
line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show,
episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py",
line 58, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes,
search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py",
line 488, in searchProviders
AAKeyError: 0
AA    return dict.__getitem__(self, key)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/feedparser/feedparser.py",
line 353, in __getitem__
AA    title = curItem[0]
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py",
line 85, in _doSearch
AA    itemList += self._doSearch(curString, search_mode,
len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py",
line 352, in findSearchResults
AA    return generic.TorrentProvider.findSearchResults(self, show,
episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nyaatorrents.py",
line 58, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes,
search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py",
line 488, in searchProviders
AATraceback (most recent call last):
2015-10-11 06:52:38 ERROR    SEARCHQUEUE-MANUAL-114801 ::
[NyaaTorrents] :: Error while searching NyaaTorrents, skipping: error
0

**Comment by seed1234** [comment]
on another provider

AA
AAKeyError: u'\u30d5'
AA    return ''.join(map(quoter, s))
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 1294, in quote
AA    searchURL = self.urls['api'] + "?s=%s&out=json" % quote(search_string)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/torrentproject.py",
line 62, in _doSearch
AA    itemList += self._doSearch(curString, search_mode,
len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py",
line 352, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes,
search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py",
line 488, in searchProviders
AAKeyError: u'\u30d5'
AA    return ''.join(map(quoter, s))
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 1294, in quote
AA    searchURL = self.urls['api'] + "?s=%s&out=json" % quote(search_string)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/torrentproject.py",
line 62, in _doSearch
AA    itemList += self._doSearch(curString, search_mode,
len(episodes), epObj=epObj)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/generic.py",
line 352, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes,
search_mode, manualSearch, downCurQuality)
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/search.py",
line 488, in searchProviders
AATraceback (most recent call last):
2015-10-11 06:52:50 ERROR    SEARCHQUEUE-MANUAL-114801 ::
[TorrentProject] :: Error while searching TorrentProject, skipping: フ

**Comment by miigotu** [comment]
dont mix providers in issues, or the logs get lost in closed issues.

**Comment by fernandog** [comment]
@seed1234 are you sure you are using latest master? Maybe this error happened before you update. Open new issue if happens again
