### ISSUE TITLE
[APP SUBMITTED]: 'indexerid'

### ISSUE THREAD

**Issue by ThomasDK81** [SiCKRAGETV/sickrage-issues#3251]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1146, in downloadSubtitles
    episode.downloadSubtitles(force=force)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 1456, in downloadSubtitles
    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/subtitles.py", line 126, in downloadSubtitles
    (subtitles_info['indexerid'], subtitles_info['season'], subtitles_info['episode']), logger.DEBUG)
KeyError: 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@medariox

**Comment by medariox** [comment]
Fixed https://github.com/SiCKRAGETV/SickRage/pull/2829

**Comment by didyouexpectthat** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c
Link to Log: https://gist.github.com/6d4a28ab20f3129f98d6
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 2151, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 268, in processDir
    process_media(processPath, videoInRar, nzbName, process_method, force, is_priority, result)
  File "/usr/share/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/usr/share/sickrage/sickbeard/postProcessor.py", line 1079, in process
    cur_ep.downloadSubtitles(force=True)
  File "/usr/share/sickrage/sickbeard/tv.py", line 1456, in downloadSubtitles
    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
  File "/usr/share/sickrage/sickbeard/subtitles.py", line 126, in downloadSubtitles
    (subtitles_info['indexerid'], subtitles_info['season'], subtitles_info['episode']), logger.DEBUG)
KeyError: 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
