### ISSUE TITLE
Failed doing webui callback- Trakt.tv- This interrupts post processing 

### ISSUE THREAD

**Issue by frriction** [SiCKRAGETV/sickrage-issues#3254]
###  NFO

Python Version: 2.7.10 (default, Sep 17 2015, 18:40:31) [GCC 5.2.0]
Operating System: Linux-4.1.10-2-ARCH-armv7l-with-glibc2.4
Locale: UTF-8
Branch: master
Commit: SiCKRAGETV/SickRage@4e9e531
Link to Log: https://gist.github.com/aebec71c0036065ce73b

### ERROR

````
2015-10-11 19:57:06 Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "/srv/http/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/srv/http/SickRage/sickbeard/webserve.py", line 2151, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/srv/http/SickRage/sickbeard/processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/srv/http/SickRage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/srv/http/SickRage/sickbeard/postProcessor.py", line 1131, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "/srv/http/SickRage/sickbeard/notifiers/trakt.py", line 74, in update_library
    trakt_api.traktRequest("sync/watchlist/remove", data, method='POST')
  File "/srv/http/SickRage/lib/libtrakt/trakt.py", line 85, in traktRequest
    data=json.dumps(data) if data else [], verify=self.verify)
  File "/srv/http/SickRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/http/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/srv/http/SickRage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/srv/http/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/srv/http/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/srv/http/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type SysCallError)
````
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@miigotu need to sockets timeout here too. Isnt?

**Comment by miigotu** [comment]
no.
