### ISSUE TITLE
No suitable RAR unpacker installed

### ISSUE THREAD

**Issue by Trever123** [SiCKRAGETV/sickrage-issues#3256]
I know this has come up a few times before but i seem to have followed all the other fixes and it still doesn't seem to work. This issue has only started since installing El Capitan and may be something to do with the new Rootless system where you can't write to certain folders.

Branch: master
Commit Hash: 4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c
OS: OSX El Capitan
Python Version: 2.7.10
What you did: The error occurs whenever a show has finished downloading, file isnt unrared
What happened: Files not unrared
What you expected: Files to be unrared
How can we reproduce your issue: El Capitan, with unrar installed using homebrew

Log extract:
```
UnpackerNotInstalled: No suitable RAR unpacker installed
    raise UnpackerNotInstalled("No suitable RAR unpacker installed")
  File "/Applications/SickRage/lib/unrar2/unix.py", line 50, in call_unrar
    return call_unrar([cmd]+soptions+['--',self.archiveName]+files)
  File "/Applications/SickRage/lib/unrar2/unix.py", line 121, in call
    stdoutdata, stderrdata = self.call('v', []).communicate()
  File "/Applications/SickRage/lib/unrar2/unix.py", line 67, in init
    RarFileImplementation.init(self, password)
  File "/Applications/SickRage/lib/unrar2/__init__.py", line 100, in __init__
    rar_handle = RarFile(os.path.join(path, archive))
  File "/Applications/SickRage/sickbeard/processTV.py", line 422, in unRAR
```

Fulls logs: http://www.pastebin.com/Dq9GErYP

Unrar can be run from the command line perfectly fine. It is located in /usr/local/bin

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
unrar needs to be in your path.

**Comment by Trever123** [comment]
@miigotu unrar is located in /usr/bin/local and /usr/bin/local is in my $PATH and this still doesn't work.

Also when i try to disable and reenable unrar files in the post processing menu, it also says there that no suitable unrar unpacker found

**Comment by miigotu** [comment]
From that `ls -l` it is NOT located in `/usr/bin/local/unrar`, a link is. It is linked to a relative path `../Cellar/unrar/5.2.7/bin/unrar`

Fix the link to point to an absolute path and it should be fine.

**Comment by eliasdc** [comment]
I'm having problems as well. I do have a bit of a weird setup. I used py2app to generate an OS X app in alias mode. But the python bundled within this app does not find unrar. When running from source I do not have any problems.
