### ISSUE TITLE
Shazbat - No download found while it is in the RSS feed

### ISSUE THREAD

**Issue by dirkr07** [SiCKRAGETV/sickrage-issues#3257]
Since a couple of days I've noticed that the provider Shazbat.tv no longer finds any episodes to download.
The logs don't really give me anything to go on of what might be the cause. (see below)
When I activate another provider the episode is found on that one so I'm assuming it's related to something with the Shazbat provider settings?

Any help to troubleshoot would be appreciated!

This is what I can see in the logs:

https://gist.github.com/dirkr07/11cbacb8edd3f12e8032

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by dirkr07** [comment]
Forgot to add this:

SR Version:	BRANCH: (master) / COMMIT: (e1bf8412922d898878e98e5f4466492eb39c4456) 
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')
SR Config:	/usr/local/sickbeard-custom/var/config.ini
SR Database:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/usr/local/sickbeard-custom/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 4 2015, 00:30:19) [GCC 4.3.2]

**Comment by fernandog** [comment]
@duramato do you have this issue?

**Comment by duramato** [comment]
@fernandog I don't have an shazbat  account

**Comment by fernandog** [comment]
@dirkr07 need full log. Missing logs "Cache update URL"

**Comment by dirkr07** [comment]
Here's what I could find in the Debug Log regarding Cache Update URL:
```
2015-10-12 12:20:54 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-12 12:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Shazbat.tv] :: Transaction with 230 queries executed
2015-10-12 12:20:54 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Shazbat.tv] :: Error while searching Shazbat.tv, skipping: KeyError(0,)
2015-10-12 12:20:04 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Shazbat.tv] :: Cache update URL: http://www.shazbat.tv/rss/recent?passkey=****************************************&fname=true
```

Seems to be all the detail I can get from the log (unless you can tell me how to get more)

**Comment by fernandog** [comment]
Open that URL and paste contents in GIST

**Comment by dirkr07** [comment]
There you go. I've omitted my passkey from the logfile.
Best to use a line wrap to make it more readable

https://gist.github.com/dirkr07/5139bb2c1ca048e4ac4b

**Comment by fernandog** [comment]
@miigotu the result its not a xml anymore.

**Comment by dirkr07** [comment]
@fernandog @miigotu 
My apologies, my Feedly plugin reformatted it in Chrome, here's the xml:

https://gist.github.com/dirkr07/8adfa48d53dc28dfab64

**Comment by fernandog** [comment]
I got:

SEARCHQUEUE-DAILY-SEARCH :: [Shazbat.tv] :: Error while searching Shazbat.tv, skipping: KeyError(0,)

**Comment by dirkr07** [comment]
@fernandog 
Strange, when I copy/paste the XML from the gist in to the xmlviewer and hit "Beautify" I don't get an error
