### ISSUE TITLE
SickRage Complains About *.part Files

### ISSUE THREAD

**Issue by benyjr** [SiCKRAGETV/sickrage-issues#3271]
Is there a reason that SickRage has to inundate me with these complaints?  .part files are commonly created temporary files.  Could we get SickRage to completely ignore files with the .part extension?

I'm seeing the following errors as "Warning" in cases where the torrent is particularly slow:

2015-10-12 23:19:25 ERROR    POSTPROCESSER :: Sync Files: ['The.Sarah.Jane.Adventures.S02E08.WS.PDTV.XviD-CaRaT.avi.part', 'The.Sarah.Jane.Adventures.S02E12.WS.PDTV.XviD-BiA.avi.part', 'The.Sarah.Jane.Adventures.S02E10.WS.PDTV.XviD-BiA.avi.part', 'The.Sarah.Jane.Adventures.S02E02.WS.PDTV.XviD-BiA.avi.part'] in path: /home/******/Downloads
AANone
2015-10-12 23:19:25 ERROR    POSTPROCESSER :: Found temporary sync files, skipping post processing for folder /home/******/Downloads

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Warnings are not errors. We might move those "warnings" to debug or info.

**Comment by benyjr** [comment]
They are being highlighted to me as "View Warnings" so call them what you will.

All I know is I got 84 "Warnings" when I shouldn't be seeing them at all since the file hadn't finished downloading yet.

**Comment by miigotu** [comment]
without them in the log we will have users complaining "but the files are there why wont they PP???!?!?"

Never assume a user knows wtf they are doing.
