### ISSUE TITLE
Episode being marked as "missed" before it's even aired

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3273]
The block doesn't air till 7:00PM tonight and it's only 3:40PM, shouldn't this be marked as green/today?
I'm assuming this may be part of the reason some shows disappear early from that page?

@SiCKRAGETV/moderators 

![screen shot 2015-10-13 at 3 39 56 pm](https://cloud.githubusercontent.com/assets/6525926/10445944/b7d70fa2-71c0-11e5-923f-acba1e493947.png)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
What about list layout?

**Comment by neoatomic** [comment]
I also noted that the date format is not showing correctly inside a shows page.
The format is mm/dd/yyyy but i'm using system default and that should be dd/mm/yyyy

![naamloos](https://cloud.githubusercontent.com/assets/7928052/10453083/e98a5ab6-71a9-11e5-9bbc-f7ca0a319f99.png)

**Comment by OmgImAlexis** [comment]
@neoatomic that's because of the stupid way we handle showing dates. We need to move to another setup for that that uses the system format instead of the predefined one.

@fernandog it's most likely the SQL that's the issue. The show's already been on now so I can't check I'll have to wait till it's on next.

**Comment by fernandog** [comment]
Afaik convert_to_settings does the convertion to the user setting

@neoatomic only displayShow? What about backlogOverview and Schedule?

**Comment by neoatomic** [comment]
@fernandog Indeed same for Schedule. Backlog i cant check as i dont have any missed episodes.

**Comment by fernandog** [comment]
@neoatomic strange as mine is respecting my setting. Just tested with a few diff settings.

**Comment by fernandog** [comment]
@neoatomic are you going to open a new issue about 'system' date style not working?

**Comment by neoatomic** [comment]
@fernandog https://github.com/SiCKRAGETV/sickrage-issues/issues/3288

**Comment by fernandog** [comment]
@MGaetan89 can you check this? looks wrong SQL? Have impact in API too. Don't know if the comingEpisods common class caused this

**Comment by fernandog** [comment]
@neoatomic that PR fixed this? can you confirm?

**Comment by neoatomic** [comment]
@fernandog Just updated. Its still mm/dd/yyyy when i set it to 'system default'

**Comment by fernandog** [comment]
no, the "Episode being marked as "missed" before it's even aired" issue lol

**Comment by ROpdebee** [comment]
@fernandog It's currently 6pm here, see screens.
Before fix
![screen shot 2015-10-21 at 18 02 14](https://cloud.githubusercontent.com/assets/15186467/10642458/0e585c6a-781e-11e5-9a85-e31318d7fd96.png)

After fix
![screen shot 2015-10-21 at 18 02 36](https://cloud.githubusercontent.com/assets/15186467/10642465/14f49836-781e-11e5-85d2-a5868ed56373.png)

**Comment by fernandog** [comment]
@ROpdebee thanks!
