### ISSUE TITLE
[BTN] :: Torrent file content is empty

### ISSUE THREAD

**Issue by bobsoppe** [SiCKRAGETV/sickrage-issues#3274]
## INFO

Python Version: **2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]**
Operating System: **Mac OS X 10.11.1 Beta (15B30a)**
Locale: **UTF-8**
Branch: **master**
Commit: **SiCKRAGETV/SickRage@0ecc6bb4ec2e9f707b45828e0b97f78b49d42dfe**

## ERROR
```
2015-10-13 09:02:02 SEARCHQUEUE-MANUAL-80379 :: [BTN] :: Unknown exception in getURL https://broadcasthe.net/torrents.php?action=download&id=560433&authkey=bf8d88b16cf8710fe4c13886c595a56f&torrent_pass=ij003yjcbmdhgdjs4hujl1ckemf9105u Error: '__str__ returned non-string (type Error)'
2015-10-13 09:02:02 SEARCHQUEUE-MANUAL-80379 :: [BTN] :: Traceback (most recent call last):
  File "/Applications/Sickrage/sickbeard/helpers.py", line 1611, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/Applications/Sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/Applications/Sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/Sickrage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/Sickrage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Applications/Sickrage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Applications/Sickrage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Applications/Sickrage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Applications/Sickrage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)

2015-10-13 09:02:02 SEARCHQUEUE-MANUAL-80379 :: [BTN] :: Torrent file content is empty
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by bobsoppe** [comment]
Why is this one closed?

**Comment by miigotu** [comment]
Because its not an error, its a timeout.

**Comment by fernandog** [comment]
@miigotu The sockets timeout PR is not working then?

https://github.com/SiCKRAGETV/SickRage/commit/7789ff733c7d2756e1beee7523aa2789a34987d1

**Comment by miigotu** [comment]
From this line:
`TypeError: __str__ returned non-string (type Error)`
You see that the error you need to catch in getURL is `TypeError` not socket.timeout.
