### ISSUE TITLE
Daily search isn't silent

### ISSUE THREAD

**Issue by Inervo** [SiCKRAGETV/sickrage-issues#3278]
Hi,

The daily search scheduler is supposed to be silent when nothing is found, but the log generated doesn't allow such behavior.

Each time the daily searcher runs, and no needed episode is found, the following logs are generated:
> 2015-10-13 18:16:27 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
> 2015-10-13 18:14:36 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
> 2015-10-13 18:14:34 INFO     DAILYSEARCHER :: No new released episodes found ...
> 2015-10-13 18:14:34 INFO     DAILYSEARCHER :: Searching for new released episodes ...

Unfortunately, these logs aren't silent, and for devices which may hibernate (like Synology), this prevents the hibernation.

Is it possible to set these logs as debug logs?
Thanks.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
`The daily search scheduler is supposed to be silent when nothing is found`

Are you telling the people who design this how it is supposed to be or asking for a change?
Asking is ok but telling us like you are the authority on it is not.

**Comment by Inervo** [comment]
Far from me to tell the developpers how Sickrage is supposed to work.

It is what is written in the Server Status:
On the line corresponding to "Daily Search", the Silent column is set to "True". So I guessed that this scheduler is supposed to be silent.

But perhaps I didn't understand this correctly, and I that case, you have my apologies.

**Comment by miigotu** [comment]
Server status "Silent" has nothing to do with log lines.
