### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/config/cache/mako/layouts/tmpKkE3C2'

### ISSUE THREAD

**Issue by nordika** [SiCKRAGETV/sickrage-issues#3279]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-4.1.7-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
Link to Log: https://gist.github.com/6dffd973ae4d6432c8dc
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 4080, in index
    return t.render(submenu=self.ConfigMenu(), title='Config - Providers', header='Search Providers', topmenu='config')
  File "/opt/sickrage/sickbeard/webserve.py", line 141, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/opt/sickrage/lib/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/opt/sickrage/lib/mako/runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/opt/sickrage/lib/mako/runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "/config/cache/mako/opt/sickrage/gui/slick/views/config_providers.mako.py", line 33, in _mako_inherit
  File "/opt/sickrage/lib/mako/runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/opt/sickrage/lib/mako/runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/opt/sickrage/lib/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/opt/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/opt/sickrage/lib/mako/template.py", line 691, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/layouts/tmpKkE3C2'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
