### ISSUE TITLE
GUI menubar showing errors & warning as a sum design mistake - Low Priority 

### ISSUE THREAD

**Issue by kossboss** [SiCKRAGETV/sickrage-issues#3281]
# BUG INFO

GUI design causes slight confusion and brain disorientation: error + warning combined for total in the menu bar. When you expand you see that error and warning have different numbers.

Menu bar makes it seem like I have 27 errors. When I only have 2 errors and 25 warnings.

That should be redesigned to show either:

1. a red oval for 2 errors and an orange oval for 27 errors (show both counts)
2. Or just show the most critical ones first red 2 errors. Then if those errors cleared it will show the 25 warnings orange oval.
3. Or maybe change the color of the oval to be part red and orange, so people know its a sum of both

Personally # 3 or # 1 sounds best.

![image](https://cloud.githubusercontent.com/assets/2777198/10466162/953217a8-71a7-11e5-8f61-31a4dc423bd6.png)

# SYSTEM INFO

SR Version:	BRANCH: (master) / COMMIT: (30435190ef8880901df555bcda0d46902ea81fb5) 
SR User:	root
SR Locale:	('en_US', 'UTF-8')
SR Config:	/apps/sickrage/config.ini
SR Database:	/apps/sickrage/sickbeard.db
SR Cache Dir:	/apps/sickrage/cache
SR Log Dir:	/apps/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch']
Python Version:	2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Its correct.

**Comment by miigotu** [comment]
Yes, it should be read as "27 notifications" or "27 things you should attend to", not "27 errors"
