### ISSUE TITLE
Error while trying to download subtitles for some episodes

### ISSUE THREAD

**Issue by fbdu53** [SiCKRAGETV/sickrage-issues#3282]
Hi,

First the formalities :
BRANCH: (master) / COMMIT: (30435190ef8880901df555bcda0d46902ea81fb5)
Python Version: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
OS : Windows 7 64 bits

What I did : Download How to get away with murder S02E03 or Narcos S01E02 with the "Download subtitiles" option checked.

What happened : Post-processing crashed with this error : 
```
AATypeError: 'NoneType' object is not iterable
AA    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
AA  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1458, in downloadSubtitles
AA    episode.downloadSubtitles(force=force)
AA  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1146, in downloadSubtitles
AATraceback (most recent call last):
AATypeError: 'NoneType' object is not iterable
AA    self.subtitles, newSubtitles = subtitles.downloadSubtitles(subtitles_info)
AA  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1458, in downloadSubtitles
AA    episode.downloadSubtitles(force=force)
AA  File "C:\SickRage\SickRage\sickbeard\tv.py", line 1146, in downloadSubtitles
2015-10-13 21:26:33 ERROR    SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
```
The rest is here : https://gist.github.com/fbdu53/7836a66e0adb024fb2bc

What I expected : Post-processing working like a charm and subtitles downloaded.

To reproduce : Try to download How to get away with murder S02E03 720p or Narcos S01E02 720p  with the "Download subtitiles" option checked.

More informations :
I 've encountered this error twice on two differents files : How to get away with murder S02E03 and Narcos S01E02. Each time, post-processing works fine until it tries to download subtitles for one of these episodes. 
I can reproduce it if I force downloading subtitles manually.
If I uncheck the "Subtitles" option in the show, post-processing works like a charm.
I 've tried with differents subtitles providers, result is always the same. 
I 've already restart many times SickRage without any change.
Tried to delete cached.db but didn't work as well.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by medariox** [comment]
@fbdu53 
Just tried with Narcos S01E02 and couldn't reproduce the error.
Can you please let me know you subtitles settings? It would be best if you could just take a screenshot of the whole settings.

**Comment by fernandog** [comment]
@fbdu53 are you renaming files? what's the pattern?

@medariox subtitles_info can be None?

**Comment by medariox** [comment]
@fernandog 
No, self.subtitles should never be None, but maybe I missed something. That's why I'd like to know the subtitles settings.

**Comment by fbdu53** [comment]
@fernandog Yes, I rename files. I don't have the particular pattern in mind right now.I will post a screen from my renaming settings as soon as I get home. 

@medariox You should try with the S02E03 episode of How to get away with murder. For the Narcos episode, the problem seems similar but I didn't activate debug for this one, so I don't have as much information as the How to get away with murder one. i will post a screen from my subtitles setting as soon as I get home.

**Comment by medariox** [comment]
Fixed locally. Will PR later today, thanks for the bug report.
