### ISSUE TITLE
File is locked for reading/writing issue

### ISSUE THREAD

**Issue by deniz946** [SiCKRAGETV/sickrage-issues#3291]
Hello, I have raspberry 2pi installed with transimission and sickrage and I can't PP the episodes, im getting this error, is there any help please?

2015-10-14 13:24:17 POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  

2015-10-14 13:24:17 POSTPROCESSER :: [/media/2TB/SERIES/Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET[rarbg]/Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET.mp4 : Processing failed: File is locked for reading/writing]

2015-10-14 13:24:17 POSTPROCESSER :: [/media/2TB/SERIES/Grimm.S04E22.HDTV.x264-LOL[ettv]/grimm.422.hdtv-lol.mp4 : Processing failed: File is locked for reading/writing]

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
other process is using that file

**Comment by miigotu** [comment]
set up transmission to move the file to a different folder when completed. Then point the sickrage "TV Download Dir" to this completed torrents dir, not the dir where torrents that are still downloading are.

**Comment by deniz946** [comment]
How i can check the groups of that items?

**Comment by miigotu** [comment]
ls -l

We are not here to teach you how to use linux, or a computer for that matter.

**Comment by deniz946** [comment]
Changed the dirs like you told me, put the same groups for both, still having the problem ;/

**Comment by deniz946** [comment]
Problem fixed changing the user and group to root  in /etc/init.d/sickrage
