### ISSUE TITLE
downloading wrong episode

### ISSUE THREAD

**Issue by arckosfr** [SiCKRAGETV/sickrage-issues#3294]
Branch: master
COMMIT: (30435190ef8880901df555bcda0d46902ea81fb5) 
OS :Debian 8
Python Version:	2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]

Example : i want to download the Flash Season 2, i set season 2 on wanted (season 1 is ignored)
but sickrage is gonna downloading entire season 1 and before postprocess he think he have correctly snatched season 2

Show who cause problem actually , The Flash, Doctor Who

log : http://pastebin.com/9BGi3m79

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@arckosfr Theres lots of stuff going on in your log.

First dont let your download client put movies ( mad-max, Jurassic park etc.) into the monitored folder. Only courses errors.
For Doctor who you probbebly need to add a scene exception, as `Doctor.Who.2005` is not recognized as a valid show name by Sickrage. (see below)
For `the flash` its probbebly downloading season packs that also include the season 01 episodes.
See if you can set that provider to download episodes only and not season only .


```
2015-10-14 18:54:56 DEBUG    Thread-83 :: Unable to parse, skipping: Unable to parse torrents Doctor.Who.2005.S08E01.RERiP.FRENCH.DVDRip.x264-LiBERTY
2015-10-14 18:54:56 ERROR    Thread-83 :: This show isn't in your list, you need to add it to SB before post-processing an episode
None
2015-10-14 18:54:56 ERROR    Thread-83 :: Processing failed for /home/******/torrents/Doctor.Who.2005.S08E01.RERiP.FRENCH.DVDRip.x264-LiBERTY.mkv: 
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 876, in process
    raise EpisodePostProcessingFailedException()
EpisodePostProcessingFailedException
```

**Comment by OmgImAlexis** [comment]
@neoatomic DO NOT add a scene exception for Doctor Who, he's probably got the old one added not the new one and that's why it's got issues. He needs to add `Doctor Who (2005)` as `Doctor Who 2005` is already a scene exception and `Doctor Who (2005)` is the show name.
