### ISSUE TITLE
Anime - Scanner Assumes Season Appended in Front if Episode Number is Triple Digit

### ISSUE THREAD

**Issue by shottothedome** [SiCKRAGETV/sickrage-issues#3300]
Branch:	Master
Commit:	9eb3d66a66f9633fefacf53484920b5fd1d1df09
OS	Debian - Linux kernel 3.2.63-45 amd 64
Python ver:	2.7.3
Issue:	When adding any large scene numbered anime as an existing show, the scanner assumes any episode greater than 99 has a season number appended in front of it. So for example episode 215 is assumed to be Season 2, episode 15 instead. Does the same with downloads if it downloads them.
Expectation:	Anime checked with scene numbered should not be read assuming a season number is appended with triple digit or greater episode numbers
Reproducing:	Any anime or even just naming files so that they are above 100 should reproduce this when adding an anime using THETVDB. Best example is One Piece and it's 700+ shows. I'm using Bleach. Example episode name: Bleach - 225 - All Vice-Captains Annihilated! The Terrifying Demonic Beast.avi - This get's put in by sickrage as S02E25
Log file: Ran with bleach anime as the test bed. - https://gist.github.com/anonymous/65c9bc9b525bdba3a717

Screenshots of issue with Bleach anime:
http://s6.postimg.org/h9j7vcntd/sickrage_triple_digit_1.jpg
http://s6.postimg.org/x91vewjv5/sickrage_triple_digit_2.jpg

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Nobody really cares about anime here, so this probably wont be fixed anytime soon (if it can even be verified)

**Comment by RabidWolf** [comment]
Why have an Anime section at all then if no one cares. What a great attitude to have.

**Comment by miigotu** [comment]
To be honest, many of us would rather NOT have anime in SR at all. It is hella headache.  Anyways it doesnt think there is a season if you set the show to anime.

**Comment by kcoyo** [comment]
I have three ongoing Anime (One Piece, Fairy Tail, Naruto) working just fine. In fact, Naruto recently got released today 10/15 and it downloaded just fine. http://imgur.com/8wP5BfD http://imgur.com/R5s5dio

I use NyaaTorrents as my torrent provider and use HorribleSubs as my release group. 

Other Info on my setup:
BRANCH: (master) / COMMIT: (a3a3b92f0fb813beffa5473576396b0e49aa04ba) 
Python Version:	2.7.9
OS: Win 8.1 x64

**Comment by shottothedome** [comment]
kcoyo did it pull them in correctly when you add existing show or does that only work that way if sickrage downloads all of it from scratch? For me it doesn't add like that when i pull in shows if they are labeled scene numbered instead of S17E73. For anime, it should be able to add them correctly based on thetvdb season breakdown just using the scene numbered episode

**Comment by miigotu** [comment]
@shottothedome its not `scene numbered` its `absolute numbering`

Make sure you have selected the anime checkbox when adding the show.

**Comment by shottothedome** [comment]
miigotu i have selected anime every time and have the animes separated into it's own section using the setting in anime config menu
From what i can tell scene numbering and absolute numbering appear to be the same 

Also as a positive note, I just wanted to comment that SickRage works great for anime. I have 189 being handled. It's very handy. Making sure they are complete and tracking specials is where sickrage combined with thetvdb really shines. Every now and then i just open all the animes one at a time to see if anything new has come out or is incoming. Usually it is OVAs/Movies or even sometimes the series starts up again much later. It's an excellent tool. This is the only real problem i've had. I can work around it but was just hoping it was an easy fix for the scanner. For smaller sized anime I just use filebot to rename. It's just these much larger, longer running animes that get tricky.

**Comment by miigotu** [comment]
I think you need to change your naming pattern is all.
%AB is absolute number

**Comment by kcoyo** [comment]
@shottothedome I have added 20 Anime from scratch (not in the past month). I actually used SickRage to re-name my archive to the naming pattern Plex accepts without messing with scanners.

**Comment by fernandog** [comment]
any of you that uses anidb can test this change ?

https://github.com/SiCKRAGETV/SickRage/pull/2895/files

just stop SR, edit  SickRage/sickbeard/blackandwhitelist.py, delete contents and past this one:
https://raw.githubusercontent.com/fernandog/SickRage/fix_anidb_traceback/sickbeard/blackandwhitelist.py

save, start SR
