### ISSUE TITLE
[APP SUBMITTED]: not well-formed (invalid token): line 40, column 24

### ISSUE THREAD

**Issue by rrd911** [SiCKRAGETV/sickrage-issues#3311]
### INFO
Python Version: **2.7.10 (default, Jun 30 2015, 15:30:23) [GCC 4.8.4]**
Operating System: **Linux-3.19.0-30-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@a3a3b92f0fb813beffa5473576396b0e49aa04ba
Link to Log: https://gist.github.com/4cbea923468dd2bee4eb
### ERROR
```
SEARCHQUEUE-BACKLOG-102591 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/raydias/sickrage/sickbeard/providers/kat.py", line 100, in _doSearch\n    data = xmltodict.parse(HTMLParser.HTMLParser().unescape(data))\n  File "/home/raydias/sickrage/lib/xmltodict.py", line 248, in parse\n    parser.Parse(xml_input, True)\nExpatError: not well-formed (invalid token): line 40, column 24\n'
'<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:torrent="http://xmlns.ezrss.it/0.1/">\n<channel>\n    <title>tv torrents RSS feed - KickassTorrents</title>\n    <link>http://kat.cr/</link>\n    <description>tv torrents RSS feed</description>\n    <item>\n        <title>[GoGoAnime] Canaan - 05 Raw [720].Avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/gogoanime-canaan-05-raw-720-avi-t2876628.html</link>\n        <guid>http://kat.cr/gogoanime-canaan-05-raw-720-avi-t2876628.html</guid>\n        <pubDate>Sat, 01 Aug 2009 18:53:39 +0000</pubDate>\n        <torrent:contentLength>189926370</torrent:contentLength>\n        <torrent:infoHash>53dcc8acdc3698359bf42b30251dc78c27de1bf4</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:53dcc8acdc3698359bf42b30251dc78c27de1bf4&dn=gogoanime+canaan+05+raw+720+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>gogoanime.canaan.05.raw.720.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/53DCC8ACDC3698359BF42B30251DC78C27DE1BF4.torrent?title=[kat.cr]gogoanime.canaan.05.raw.720.avi" length="189926370" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>[GoGoAnime] Canaan - 05 Raw [720].Avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/gogoanime-canaan-05-raw-720-avi-t2876690.html</link>\n        <guid>http://kat.cr/gogoanime-canaan-05-raw-720-avi-t2876690.html</guid>\n        <pubDate>Sat, 01 Aug 2009 19:13:12 +0000</pubDate>\n        <torrent:contentLength>189926370</torrent:contentLength>\n        <torrent:infoHash>9d14278f867dcc5687f86274e41c579e052d8c0d</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:9d14278f867dcc5687f86274e41c579e052d8c0d&dn=gogoanime+canaan+05+raw+720+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>gogoanime.canaan.05.raw.720.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/9D14278F867DCC5687F86274E41C579E052D8C0D.torrent?title=[kat.cr]gogoanime.canaan.05.raw.720.avi" length="189926370" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>[DMHY&amp;SGS][CANAAN][04&amp;05][rmvb]</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/dmhy-sgs-canaan-04-05-rmvb-t2896548.html</link>\n        <guid>http://kat.cr/dmhy-sgs-canaan-04-05-rmvb-t2896548.html</guid>\n        <pubDate>Sat, 08 Aug 2009 02:02:43 +0000</pubDate>\n        <torrent:contentLength>221130000</torrent:contentLength>\n        <torrent:infoHash>e7d1e2dae67267ff3066040ecdb4f534c098bb87</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:e7d1e2dae67267ff3066040ecdb4f534c098bb87&dn=dmhy+sgs+canaan+04+05+rmvb&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>dmhy.sgs.canaan.04.05.rmvb.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/E7D1E2DAE67267FF3066040ECDB4F534C098BB87.torrent?title=[kat.cr]dmhy.sgs.canaan.04.05.rmvb" length="221130000" type="application/x-bittorrent" />\n    </item>\n    </channel>\n</rss>'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
