### ISSUE TITLE
Post-processor dies when trying to process files sometimes. Never tries to process again, have to do it manually.

### ISSUE THREAD

**Issue by Fumler** [SiCKRAGETV/sickrage-issues#3319]
This usually happens with anime where I get
```
2015-10-15 14:49:13 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: %d format: a number is required, not NoneType
```

But it can also happen with normal tv-shows.

Error log:
```
2015-10-16 01:07:41 Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/fredrik/.sickrage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/home/fredrik/.sickrage/sickbeard/webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 234, in processDir
    for dir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/home/fredrik/.sickrage/sickbeard/processTV.py", line 374, in validateDir
    NameParser().parse(video, cache_result=False)
  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 420, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/home/fredrik/.sickrage/sickbeard/name_parser/parser.py", line 273, in _parse_string
    (s, e) = helpers.get_all_episodes_from_absolute_number(bestResult.show, [a])
  File "/home/fredrik/.sickrage/sickbeard/helpers.py", line 882, in get_all_episodes_from_absolute_number
    ep = show.getEpisode(None, None, absolute_number=absolute_number)
  File "/home/fredrik/.sickrage/sickbeard/tv.py", line 290, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "/home/fredrik/.sickrage/sickbeard/tv.py", line 1394, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "/home/fredrik/.sickrage/sickbeard/tv.py", line 1505, in specifyEpisode
    sqlResult = self.loadFromDB(season, episode)
  File "/home/fredrik/.sickrage/sickbeard/tv.py", line 1527, in loadFromDB
    logger.log(u"%s: Loading episode details from DB for episode %s S%02dE%02d" % (self.show.indexerid, self.show.name, season, episode), logger.DEBUG)
TypeError: %d format: a number is required, not NoneType

2015-10-15 14:49:13 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: %d format: a number is required, not NoneType
```

Warning log:
```
2015-10-16 01:07:36 Thread-18 :: Processing failed for /media/done/Kingdom.S02E01.New Money.720p.HDTV.x264_TTL.mkv: 
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
