### ISSUE TITLE
Mark snatched downloads as failed per torrent-HASH

### ISSUE THREAD

**Issue by petwri** [SiCKRAGETV/sickrage-issues#3327]
I use a custom postprocessing-script, which gets triggered when a torrent finishes to start SR postprocessing via an API-call. If a torrent however is stalled for x days, I consider it failed and tell SR that that very download has failed. But according to the current API, this is only possible with passing the parameters 'status', 'indexerid', 'season' and 'episode' as well as the option to keep previously downloaded episodes or to replace them.

But with that options, the following scenario is really hard to handle: consider a snatched torrent which then fails after x days, and at the same time, another download in the torrent client's queue for the same episode, which would work. If I then mark the download for that episode as failed, I believe that SR would mark both of these downloads as failed, and therefore mark a working torrent as not good.

Maybe anybody could confirm this behavior, but anyways, I think it would be a huge improvement to mark downloads as failed by unique identifiers for a torrent. This would make such a situation way easier to handle.

According to https://github.com/SiCKRAGETV/sickrage-issues/issues/2589, the torrents HASH is already stored in the db, so imho it would just be a change to the API.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
I think we need the hash in DB...

**Comment by petwri** [comment]
Isn't it in there already? I might be wrong, though.

**Comment by fernandog** [comment]
Not in DB

**Comment by petwri** [comment]
Are you planning on adding it?

**Comment by fernandog** [comment]
Yes. Dont know when. @miigotu can tell I think

**Comment by miigotu** [comment]
We are still in an information gathering stage about the next db upgrade, and fixing current bugs.

Soon we will sift through all of the ideas for the new fields and determine which we actually need (hash is already on the must haves list)
