### ISSUE TITLE
Open show with subtitles enabled takes very long time

### ISSUE THREAD

**Issue by gverdellen** [SiCKRAGETV/sickrage-issues#3328]
I love the subtitle feature but what i noticed is that when shows have more episodes and seasons it takes very long to open when subtitles are enabled. Opening a show with subtitles enabled takes about 20 secondes, when disable subtitles the show opens in a second.
For all the shows I have disabled subtitles but I would like to turn this on again, please help?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@medariox can you reproduce?

**Comment by gverdellen** [comment]
Yes, when I turn on the subtitles for a show the issue is back.
If you need more info on this please let me know how I can be hepfull on this.
 
Regards,
Gerard
 
Date: Fri, 16 Oct 2015 04:01:09 -0700

**Comment by medariox** [comment]
@fernandog 
@gverdellen 
There is nothing that can be done about this in the python code. The mako template has to be optimized (if possible). If you have subtitles enabled the mako template will try to generate every country flag, for each and every episode of the show - this takes time, especially on slow machines. One possible "solution" would be to let the user decide to not display the flag (aka don't let mako do the "heavy task"). Otherwise, as I already mentioned, maybe the mako code can be optimized, but we need to ask @OmgImAlexis for that.

**Comment by gverdellen** [comment]
I think that is not totally true, when subtitles are off the flags are still displayed for those episodes that have subtitles!?
 
Date: Fri, 16 Oct 2015 04:11:43 -0700

**Comment by medariox** [comment]
@gverdellen 
Well, if you think you know it better, you are free to make the changes to the python code to improve it and send a PR.

PS: Subtitles are not being refreshed when opening a show page, so it can ONLY be caused by mako. The flags you see are probably cached, do a refresh and they will be gone.

**Comment by OmgImAlexis** [comment]
@medariox maybe there's a way we can pass just the info about the flags to a data attribute and use jQuery to load them? I don't have subtitles enabled at all so I'm not too sure which part of the code you guys are talking about.

**Comment by gverdellen** [comment]
@medariox 
I do not know better, just willing to help to solve this issue...

What do you mean with: 'do a refresh and they will be gone'?
I did a 're-scan files' and the flags are still there...

**Comment by medariox** [comment]
@OmgImAlexis 
I think this for loop is killing it (especially with a lot of elements): https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/views/displayShow.mako#L503

@gverdellen 
So why do you say that what I'm saying is not "totally true"? I wrote that code and made sure that python code is only executed on refresh or download. That's why I know that it can't be a python issue.
Actually it doesn't make any difference code-wise with subtitles disabled or enabled.

**Comment by gverdellen** [comment]
@medariox 
Relax. Glad that you know your code!
