### ISSUE TITLE
Keep getting errors with autoprocessing

### ISSUE THREAD

**Issue by ArjandeV** [SiCKRAGETV/sickrage-issues#3330]
So I have troubles moving my downloaded files with the autoprocessing. Everything gets downloaded at my NAS and my NAS volumes are mounted as NFS mounts on my Rasp. Sickrage running on my Rasp, sending download to tranmission, works all great.

It all gets downloaded on my NAS which is mounted on my Rasp at /home/osmc/ix2/TV/Downloads

I've tried several things:
- Checked file permissions
- Checked autoProcessTV.cfg
- Ran sabToSickBeard.py by hand from command line

All results into same log files:
https://gist.github.com/8826f1aac37e511756b2

Running: commit 136f531f93093a5287b588ca37e19c11153f47a4 / master

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Missing gist. 404 error

**Comment by OmgImAlexis** [comment]
@fernandog remove the .git from the url https://gist.github.com/ArjandeV/8826f1aac37e511756b2

**Comment by neoatomic** [comment]
Also look-into NZBtoMedia. https://github.com/SiCKRAGETV/sickrage-issues/wiki/NZBtoMedia
sabToSickBeard.py is outdated and the files will be removed (in the coming weeks) from the sickrage folder.

**Comment by fernandog** [comment]
@miigotu hidden folders shouldnt cause PP to fail. Isnt?

**Comment by ArjandeV** [comment]
Also, non of the others seem to be moved... Before I switched to SickRage this setup always worked.. I switched because of using torrents instead of nzb's, as the nzb's were always removed and failed downloads..

**Comment by miigotu** [comment]
@ArjandeV could you try opening SickRage/sickbeard/postProcessor.py and changing line 58 from:
`IGNORED_FILESTRINGS = ["/.AppleDouble/", ".DS_Store"]`
to:
`IGNORED_FILESTRINGS = [".AppleDouble", ".DS_Store"]`

Let me know if that fixes it. I have no idea why someone added the slashes there.

**Comment by ArjandeV** [comment]
@miigotu changed it, saved it, restarted sickrage and ran the autoprocess again, still same errors. I guess the slashes are there because they are directories, but on the other hand it shouldnt care right?

According to the code it should say: Ignored file skipping right:
self._log(u"File %s is ignored type, skipping" % self.file_path)

But it keeps saying:
``[/home/osmc/ix2/TV/Downloads/The.Vampire.Diaries.S07E01.720p.HDTV.X264-DIMENSION[EtHD]/.AppleDouble : Hidden folder]`

**Comment by miigotu** [comment]
@ArjandeV it should be without the slashes.

Also, try adding a # before line 345:
`#        result.missedfiles.append(dirName + " : Hidden folder")`

**Comment by ArjandeV** [comment]
@miigotu well that's weird, I uncommented it, but it still gives the same message. I've restarted sickrage, but it seems it doesnt affect it.. Im trying to upgrade my system now and python with it, maybe that helps..

**Comment by fernandog** [comment]
@ArjandeV did you stop SR before doing the changes? please double check

@neoatomic can he update/edit sickrage files in NAS?
