### ISSUE TITLE
[APP SUBMITTED]: u'\u2019'

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#3335]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-284073 :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: ’
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu see why I batch change? Another provider, another PR,

**Comment by miigotu** [comment]
I rather another provider and another PR than to have 60 issues from 1 PR. Batch changes are not proper for exactly this reason, all of these issues are due to the original batch change. If the first one was only 1 provider, and see if issues pop up, we would have had an issue or two and then had it fixed.
