### ISSUE TITLE
[APP SUBMITTED]: global name 'search_string' is not defined

### ISSUE THREAD

**Issue by MaDTaZ** [SiCKRAGETV/sickrage-issues#3342]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
Link to Log: https://gist.github.com/1de150022f8964cef61a
### ERROR
```
SEARCHQUEUE-BACKLOG-282257 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
@fernandog quick fix here.

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/6a5031054d34c353bc59
### ERROR
```
SEARCHQUEUE-MANUAL-281622 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/115bfc0828417952df1a
### ERROR
```
SEARCHQUEUE-MANUAL-80273 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/39b2c1b3f71faec041d5
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/095d050639e0e3c8f267
### ERROR
```
SEARCHQUEUE-MANUAL-182061 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/305de0fb8e6ebb5ff333
### ERROR
```
SEARCHQUEUE-MANUAL-264108 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/651c20be3463041ae9ac
### ERROR
```
SEARCHQUEUE-MANUAL-247897 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/3677001df20d4ca0c7f3
### ERROR
```
SEARCHQUEUE-MANUAL-281623 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/39f658a71a446104d0e1
### ERROR
```
SEARCHQUEUE-MANUAL-71663 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/273ce9c596a2dce2b835
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/367714d0bc4f5f321d41
### ERROR
```
SEARCHQUEUE-MANUAL-82701 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MaDTaZ** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@65515c5cf7b3468e15b5f3a3d9a1fd603ba4dafb
Link to Log: https://gist.github.com/cf0ee2630009bf87a29e
### ERROR
```
SEARCHQUEUE-MANUAL-299304 :: [TitansOfTV] :: Error while searching TitansOfTV, skipping: global name 'search_string' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
