### ISSUE TITLE
Plex Notifier Socket Error : SSL

### ISSUE THREAD

**Issue by BKSteve** [SiCKRAGETV/sickrage-issues#3344]
With the latest update have Plex Media Server Notifications causing warning messages in regard to SSL. on my Synology NAS.

BRANCH: (master) / COMMIT: (d5a336dc0bf98249902ec3c455846624ac19387e) 
2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

With Notifications > Home Theater / NAS > Plex Media Server > Enabled and Update server library selected the previously ok connection now fails.
Warning Log:
AAIOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:590)
AA    self._sslobj.do_handshake()
AA  File "/usr/local/python/lib/python2.7/ssl.py", line 808, in do_handshake
AA    self.do_handshake()
AA  File "/usr/local/python/lib/python2.7/ssl.py", line 579, in __init__
AA    _context=self)
AA  File "/usr/local/python/lib/python2.7/ssl.py", line 352, in wrap_socket
AA    server_hostname=server_hostname)
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 1274, in connect
AA    self.connect()
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 855, in send
AA    self.send(msg)
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 893, in _send_output
AA    self._send_output(message_body)
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 1049, in endheaders
AA    h.endheaders(data)
AA  File "/usr/local/python/lib/python2.7/urllib.py", line 443, in open_https
AA    return getattr(self, name)(url)
AA  File "/usr/local/python/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/local/python/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):

With Notifications > Home Theater / NAS > Plex Media Server > Enabled only I get 
Thread-61 :: PLEX: Error while trying to contact Plex Media Server: socket error : error EOF occurred in violation of protocol (_ssl.c:590)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by nucshuco** [comment]
Freenas 9.3.1
the latest update to sickrage broke the plex notification. rolled back works fine.

AASSLError: ('The read operation timed out',)
AA    v = self._sslobj.read(len or 1024)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 608, in read
AA    return self.read(buflen)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/ssl.py", line 714, in recv
AA    data = self._sock.recv(left)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 380, in read
AA  File "", line 38, in parse
AA  File "", line 62, in parse
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-10-16 21:58:51 ERROR    Thread-23 :: PLEX: Error while trying to contact Plex Media Server: The read operation timed out

![plex](https://cloud.githubusercontent.com/assets/8262089/10557123/eeae956a-7452-11e5-9676-a8168ab3d23e.JPG)

**Comment by neoatomic** [comment]
@BKSteve Same as : https://github.com/SiCKRAGETV/sickrage-issues/issues/3344 
Please continue/add your comments there.

We added https authentication to the Plex notifier, as Plex wants to remove http support.
But clearly that is causing some problems that we need to lookinto.

**Comment by tproenca** [comment]
I'm having the same problem as wel... :/

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/SiCKRAGETV/SickRage/pull/2907
