### ISSUE TITLE
SickRage is not finding an episode of Fargo on HD-Torrents when it's clearly there

### ISSUE THREAD

**Issue by ncksol** [SiCKRAGETV/sickrage-issues#3347]
Just updated to the latest version: BRANCH: (master) / COMMIT: (d5a336dc0bf98249902ec3c455846624ac19387e) 

Trying to setup new season of Fargo to download. One episode has aired so far, I've clicked manual search. In log it says that it has found only one episode, but when I go to the URL that search has been using there are 4 available:
http://content.screencast.com/users/Mefiras/folders/Jing/media/49e52d90-39d7-4617-97b6-1aab8f50ae4d/2015-10-17_1243.png

Log: http://pastebin.com/ENxYpjBt

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Know issue

**Comment by ncksol** [comment]
So I got curious and even though I have no expertise in python I wanted to investigate this issue.
I've installed python and some IDE and six hours later I know the problem =)
Turns out HD-Torrents have some invalid html and it prevents soup from getting the full table that containts the download links.
I have come up with two fixes for it:
1. By default soup is using html parser. Unfortunately it cannot process invalid html from HD-Torrents. But when I've plugged in html5lib parser, it worked! So if you are ok with using html5 parser that's the simpliest fix, just few lines of code change
2. I have found a workaround on how to find the right links using the default parser. I am avoiding parsing the table that has invalid html. This fix requires a few more lines to change and it's also a bit more fragile because it depends on the structure of the page. But I've tested it with a couple different searches and it works.

Now there is one problem. Being a c# enterprise developer I have zero experience in how github works =) I've been using SVN my whole life.
So I have both fixes sitting here localy on my PC. If you want me to proceed with any of them, I would need some guidance on how to properly commit this stuff, as I know the process is more complicated with git.

**Comment by fernandog** [comment]
thanks!

**Comment by fernandog** [comment]
@ncksol 
If you know html/parsing well and want to help us, we have others providers that need adding seeders/leechers/size parsing.
Just find FIXME inside the providers files.

**Comment by ncksol** [comment]
Cheers. I will take a look.

**Comment by fernandog** [comment]
we recently changed the providers to make all code similar (log message, same search string, adding mode RSS/Episode/Season etc).

**Comment by fernandog** [comment]
do you use IRC? join us in #sickrage

do you have hdbits or btn? they need fix

**Comment by ncksol** [comment]
Sure I can find some irc client, it's been a while since I used it =)
Unfortunately I am not on hdbits or btn. Out of providers sickrage supports I have hd-torrents, freshontv and torrent bytes

**Comment by ncksol** [comment]
which network is the irc channel on btw?

**Comment by fernandog** [comment]
Freenode

**Comment by duramato** [comment]
@ncksol freenode ;)

**Comment by fernandog** [comment]
sickrage has builtin IRC at Tools menus. you can connect there or use another client
