### ISSUE TITLE
Failed doing webui callback

### ISSUE THREAD

**Issue by inmazer** [SiCKRAGETV/sickrage-issues#3354]
I'm on the master branch latest version (303d80)

Getting this in the log, it might be when it's initiating PP, but not sure. Don't know what it affects, but should be cleaned up I guess.

AA
AAImportError: Loaded module X__SickRage_gui_slick_views_home_mako not found in sys.modules
AA    return imp.load_source(module_id, path, fp)
AA  File "X:\SickRage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "X:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "X:\SickRage\lib\mako\template.py", line 321, in __init__
AA    super(PageTemplate, self).__init__(*args, **kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 101, in __init__
AA    t = PageTemplate(rh=self, file="home.mako")
AA  File "X:\SickRage\sickbeard\webserve.py", line 645, in index
AA    result = function(**kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 250, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "X:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "X:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "X:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "X:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
AA    value = future.result()
AA  File "X:\SickRage\tornado\gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "X:\SickRage\sickbeard\webserve.py", line 235, in get
AAImportError: Loaded module X__SickRage_gui_slick_views_home_mako not found in sys.modules
AA    return imp.load_source(module_id, path, fp)
AA  File "X:\SickRage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "X:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "X:\SickRage\lib\mako\template.py", line 321, in __init__
AA    super(PageTemplate, self).__init__(*args, **kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 101, in __init__
AA    t = PageTemplate(rh=self, file="home.mako")
AA  File "X:\SickRage\sickbeard\webserve.py", line 645, in index
AA    result = function(**kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 250, in async_call
AATraceback (most recent call last):
AAImportError: Loaded module X__SickRage_gui_slick_views_home_mako not found in sys.modules
AA    return imp.load_source(module_id, path, fp)
AA  File "X:\SickRage\lib\mako\compat.py", line 66, in load_module
AA    module = compat.load_module(self.module_id, path)
AA  File "X:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
AA    module = self._compile_from_file(path, filename)
AA  File "X:\SickRage\lib\mako\template.py", line 321, in __init__
AA    super(PageTemplate, self).__init__(*args, **kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 101, in __init__
AA    t = PageTemplate(rh=self, file="home.mako")
AA  File "X:\SickRage\sickbeard\webserve.py", line 645, in index
AA    result = function(**kwargs)
AA  File "X:\SickRage\sickbeard\webserve.py", line 250, in async_call
2015-10-18 00:32:12 ERROR    Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
2015-10-18 00:32:06 INFO     POSTPROCESSER :: PostProcessing Path: X:\uTorrent\sickrage

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
As the bot says:

Shutting down SickRage and removing the cache/mako & cache/sessions folders.
