### ISSUE TITLE
[APP SUBMITTED]: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/269586/all/en.zip

### ISSUE THREAD

**Issue by ragnew287** [SiCKRAGETV/sickrage-issues#3368]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-62-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
Link to Log: https://gist.github.com/491ccfb6620c605a9f17
### ERROR
```
SHOWQUEUE-ADD :: Show name with ID 269586 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by ragnew287** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-62-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
Link to Log: https://gist.github.com/b33d0a1444e6848e520a
### ERROR
```
SHOWQUEUE-ADD :: Show name with ID 269586 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ragnew287** [comment]
TV show not updating information.  Removed the show and tried adding it in again.  Unable to add it in again.  Getting the error that the show is no longer on theTVDB.  I have confirmed that the ID is working on the website.

I have removed the nfo files within the show but it has made no difference.

I have renamed the folder and tried adding the show in as new show but getting the same error.

Happening with the following TV Shows
-Brooklyn Nine-Nine
-Gotham
-The Flash

**Comment by fernandog** [comment]
@ragnew287 Show name with ID 269586 doesn't exist on theTVDB anymore.

**Comment by ragnew287** [comment]
It is there - http://thetvdb.com/?tab=series&id=269586

**Comment by miigotu** [comment]
Adds just fine for me.
```
15:27:21 DEBUG::SHOWQUEUE-ADD :: 269586: Loading show info from database
15:27:21 INFO::SHOWQUEUE-ADD :: 269586: Unable to find the show in the database
15:27:21 DEBUG::SHOWQUEUE-ADD :: 269586: Loading show info from theTVDB
15:27:22 DEBUG::SHOWQUEUE-ADD :: Setter sets location to /home/******/Videos/Brooklyn Nine-Nine
15:27:22 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
15:27:22 DEBUG::SHOWQUEUE-ADD :: Retrieving show info from IMDb
15:27:22 DEBUG::SHOWQUEUE-ADD :: 269586: Loading show info from IMDb
15:27:25 DEBUG::SHOWQUEUE-ADD :: 269586: Obtained info from IMDb ->{'rating': 8.3, 'votes': 49032, 'countries': u'USA', 'title': u'Brooklyn Nine-Nine', 'genres': u'Comedy|Crime', 'imdb_id': u'tt2467372', 'country_codes': u'us', 'year': 2013, 'certificates': u'TV-14', 'runtimes': u'22', 'akas': u'\u0411\u0440\u0443\u043a\u043b\u0438\u043d 9-9::Russia|Brooklyn 9-9::Brazil (imdb display title)|Brooklyn 9-9::Poland (imdb display title)|Brooklyn 99::Finland (imdb display title)|Brooklyn 99: Nem sz\xe1zas k\xf6rzet::Hungary (imdb display title)', 'last_update': 735889}
15:27:25 DEBUG::SHOWQUEUE-ADD :: 269586: Saving show info to database
15:27:25 DEBUG::SHOWQUEUE-ADD :: 269586: Loading all episodes from theTVDB..
```

**Comment by ragnew287** [comment]
Have you any ideas as to how to resolve on my end?  It's not just the one show.

2015-10-19 14:34:13 SHOWQUEUE-ADD :: Show name with ID 269586 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
2015-10-19 14:33:49 SHOWQUEUE-ADD :: Show name with ID 274431 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
2015-10-19 14:33:25 SHOWQUEUE-ADD :: Show name with ID 279121 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again

Are there any files I can remove which can let me start from scratch even?

**Comment by miigotu** [comment]
I would assume you should update SR as your first step of action.

**Comment by ragnew287** [comment]
Its up-to-date.  I run the update as soon as there is one.  I checked and there is not a newer version for the master branch.

**Comment by ragnew287** [comment]
Latest update is no longer throwing errors.  The shows are not being added though.

   SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/home/xbmc/.sickrage/cache/indexers/theTVDB', 'language': 'en'}
2015-10-19 21:18:44 INFO     SHOWQUEUE-ADD :: Starting to add show /media/nas/Videos/TV Shows/The Flash
2015-10-19 21:18:20 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/home/xbmc/.sickrage/cache/indexers/theTVDB', 'language': 'en'}
2015-10-19 21:18:20 INFO     SHOWQUEUE-ADD :: Starting to add show /media/nas/Videos/TV Shows/Brooklyn Nine-Nine
2015-10-19 21:17:56 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/home/xbmc/.sickrage/cache/indexers/theTVDB', 'language': 'en'}
2015-10-19 21:17:56 INFO     SHOWQUEUE-ADD :: Starting to add show /media/nas/Videos/TV Shows/Gotham

**Comment by miigotu** [comment]
Stop SR and try removing this folder:
`/home/xbmc/.sickrage/cache/indexers/theTVDB`

**Comment by ragnew287** [comment]
Fantastic.  That sorted it!

Thank you so so much.
