### ISSUE TITLE
Preview rename don't work

### ISSUE THREAD

**Issue by falkin** [SiCKRAGETV/sickrage-issues#3373]
Branch : master
Commit hash : 303d80c
Your operating system and python version : Linux 3.2.40 / python 2.7.9
What you did : Search anime show (Dragon ball super) and configure - Post Processing - Episode naming
What happened : Custom Anime wasn't taken into account when searching. And on the show Preview Rename - Rename selected button don't work and the pattern seen don't work
What you expected : don't always download the show available on [Cpasbien]. 

Include a link with your log file. 
![img1](https://cloud.githubusercontent.com/assets/1089835/10564773/d0dad372-75c0-11e5-8993-29ad4e004f2b.PNG)
![img2](https://cloud.githubusercontent.com/assets/1089835/10564774/d0db43d4-75c0-11e5-8487-bfe2c9e4e784.PNG)

https://gist.github.com/falkin/678ce56bc3c525fe5a5c

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@OmgImAlexis JS issue?

**Comment by falkin** [comment]
Tested with Firefox developper edition 43.0a2 (2015-10-03). There is no error inside the console. No JS error when i click on the button. But it don't work.

**Comment by fernandog** [comment]
maybe mako error/issue. we recently changed from cheetah to mako

**Comment by fernandog** [comment]
@SiCKRAGETV/moderators any of you can confirm this?

**Comment by miigotu** [comment]
Preview rename has nothing to do with searching on providers.
