### ISSUE TITLE
SEARCHQUEUE-DAILY-SEARCH :: [URL_NAME] :: Connection error to getURL https://URL Error: u"error ('Connection aborted.', error(111, 'Connection refused'))"

### ISSUE THREAD

**Issue by Weggy** [SiCKRAGETV/sickrage-issues#3375]
Hi,

This issue has been posted by others recently, but the issues have been closed without a proper fix (at-least it seems so to me). The issue still remains for me after following all outlined instructions and methods, so something must have changed recently for this to appear.

References (With no fixes) -
https://github.com/SiCKRAGETV/sickrage-issues/issues/3087
https://github.com/SiCKRAGETV/sickrage-issues/issues/3295

Issue -
I recieve the following error(s) when a "Daily Search" is run:
SEARCHQUEUE-DAILY-SEARCH :: [URL_NAME] :: Connection error to getURL https://URL Error: u"error ('Connection aborted.', error(111, 'Connection refused'))"

Notes -
NAS: Synology DS214Play
OpenSSL Version: OpenSSL 1.0.1p-fips 9 Jul 2015
Python Version: 2.7.10 (default, Jun 3 2015, 23:30:53) [GCC 4.6.3]
SR Version:	BRANCH: (master) / COMMIT: (d5a336dc0bf98249902ec3c455846624ac19387e) 

Attempts to fix include:
Shutting down SR
Verify SSL Certs: Disabled
Deleting cache.db
Deleting folders cache/mako and cache/sessions

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by Weggy** [comment]
Additional debug info:
2015-10-18 20:23:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-18 20:23:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [URL_A] :: No data returned from provider
AAConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
AA    raise ConnectionError(err, request=request)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/adapters.py", line 415, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/usr/local/sickrage/var/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1611, in getURL
AATraceback (most recent call last):
2015-10-18 20:23:46 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [URL_A] :: Connection error to getURL https://URL_A/tv/?q=&field=time_add&category=tv&sorder=desc&rss=1 Error: u"error ('Connection aborted.', error(111, 'Connection refused'))"
AAConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
AA    raise ConnectionError(err, request=request)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/adapters.py", line 415, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/usr/local/sickrage/var/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1611, in getURL
AATraceback (most recent call last):
2015-10-18 20:23:46 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [URL_B] :: Connection error to getURL https://URL_B.gd/tv/latest?q=&orderby=7&category=200&type=search&page=0 Error: u"error ('Connection aborted.', error(111, 'Connection refused'))"
2015-10-18 20:23:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [URL_A] :: Search URL: https://URL_A/tv/?q=&field=time_add&category=tv&sorder=desc&rss=1
2015-10-18 20:23:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [URL_A] :: Search Mode: RSS
2015-10-18 20:23:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [URL_B] :: Search URL: https://URL_B.gd/tv/latest?q=&orderby=7&category=200&type=search&page=0
2015-10-18 20:23:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [URL_B] :: Search Mode: RSS

**Comment by Weggy** [comment]
Why did you close this issue? This is exactly what happened with the other issues, there isn't any direction on a fix.

Very confusing.

**Comment by miigotu** [comment]
a.) Redacted logs cannot be troubleshot
b.) just because a previous issue is closed does not mean you need to open a new issue.
c.) there is no problem in SR preventing peoviders from connecting.
d.) PEBKAC

**Comment by Weggy** [comment]
If there is no problem with SR connecting, why have so many users all had the same issue at the same time?

**Comment by fernandog** [comment]
@Weggy are you using proxy? I seems your are using TPB

**Comment by Weggy** [comment]
Hi @fernandog My NAS is on a VPN and can connect to TPB and KAT without issues via other means. For example when I use it as my PCs gateway. Its only when SickRage tires to connect to either I get issues.

Is there any tests I can run to narrow down the issues?

Thanks

**Comment by fernandog** [comment]
@Weggy some proxies add html tags / junk in the code and SR gets confused. We can't handle all proxies

**Comment by Weggy** [comment]
@fernandog Can you give me an example? I don't see any junk in the URL being requested above.

Does this mean SR only supports certain VPNs?

**Comment by miigotu** [comment]
It means your VPN is refusing the connection.

**Comment by Weggy** [comment]
@miigotu If the VPN is refusing the connection, executing that same URL in a browser should equal the same result. However the URL executes fine within my browser.

**Comment by miigotu** [comment]
Negative, SR uses a custom user agent.

**Comment by Weggy** [comment]
@miigotu , humm okay. I'm not sure where to go from here then. I use a pretty common VPN in "Private InternetAcess". Do I need them to fix something?

**Comment by miigotu** [comment]
Nope, it is very likely your setup of the vpn. You are using tun instead of tap right? There are several google results about openvpn  and that error 111.

**Comment by Weggy** [comment]
Figured it out, it was a DNS issue on my NAS. Thanks very much for your help
