### ISSUE TITLE
Warring with ThePirateBay (Too many Redirects)

### ISSUE THREAD

**Issue by Nomelas** [SiCKRAGETV/sickrage-issues#3376]
I keep seeing this:

> 2015-10-18 17:25:26 SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/tv/latest?q=&orderby=7&category=200&type=search&page=0 Error: 'Exceeded 30 redirects.'
2015-10-18 17:25:26 SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\helpers.py", line 1611, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 602, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\SickRage\lib\requests\sessions.py", line 114, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
TooManyRedirects: Exceeded 30 redirects.

I've tried turning off and on SSL verification and deleting cache.db file. I'm not sure why this is showing up.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Seems blocked? Some dns/isp block it. And most proxy's don't work for it.

**Comment by OmgImAlexis** [comment]
@miigotu I think it may have been down today at some stage as I had the same issue with it and it's completely unblocked here. .se .mn and .gd were also down for a while last night and just showed the cloudflare page.

**Comment by miigotu** [comment]
closing this then, thats exactly what happens when cloudflare pops up

**Comment by OmgImAlexis** [comment]
Can't you check if the cloudflare page is showing and then show a message?

**Comment by miigotu** [comment]
We need to add a library for cloudflare, but need to finish the half done provider changes first. Working on providers now.

**Comment by rmilyard** [comment]
I am still getting this same error as of today.

**Comment by Nomelas** [comment]
I am also still receiving these, they flood my warnings

**Comment by miigotu** [comment]
Shouldnt the first thing you do when trying to figure out why a connection to a site isnt work be to try and load the site?


"Website is offline No cached version of this page is available."

"Error 522 Ray ID: 23a79a42bc8a11dd • 2015-10-24 18:04:25 UTC
Connection timed out"
