### ISSUE TITLE
Subtitles aren't downloaded

### ISSUE THREAD

**Issue by fana13** [SiCKRAGETV/sickrage-issues#3389]
Hi,

Subtitles are available on Addic7ed or Opensubtitles but they're not grab by sickrage.
In log i just have "FINDSUBTITLES :: Checking for subtitles" and nothing more
If i forced search by missed subtitles management, my episode appear in list, i put "go" et nothing more, no donwload and nothing in log. Same thing if i forced into the show.
My config : 
![image](https://cloud.githubusercontent.com/assets/14030280/10578327/bc8446cc-7671-11e5-9d06-4d45c110a88e.png)

![image](https://cloud.githubusercontent.com/assets/14030280/10578348/dda0419e-7671-11e5-924b-b14c59eeebd2.png)

Thanks for helpful

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by medariox** [comment]
@fana13 
Post your full log please.

**Comment by fana13** [comment]
Allright when i see the complete log i found this :
"Episode file does not exist, cannot download subtitles for episode 6x2 of show The Walking Dead"
But i don't have any file for my episode, it's in a single folder name "Downloads" where all my donwloads come. Must have put a subtitle directory like : /home/***/torrents/downloads ?

**Comment by medariox** [comment]
You need the episode file to download the subtitle. If the file is there try a refresh. You can also set an absolute path, but it shouldn't be needed.

**Comment by fana13** [comment]
Thanks for your help, i understand now.
