### ISSUE TITLE
Value Error: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by labrys** [SiCKRAGETV/sickrage-issues#3394]
@miigotu @fernandog 

Issue #3007 does not appear to be fixed.  I am still getting this error with a handful of shows. (Log at bottom of post)  I'm running Windows 10 Pro x64 and Python 2.7. I have SR running as Master Branch, it is not running as a service.  If you would like I can also attempt to recreate on a RPi B+ running Raspbian.

###### Minimum steps needed to reproduce.
1. Install fresh: `git clone https://github.com/SiCKRAGETV/sickrage.git sickrage`
2. Change directory: `cd sickrage`
3. Start **SickRage**: `C:\python27\python.exe SickBeard.py` assuming Python 2.7 is installed in `c:\python27`
4. Add _**Batman: The 1943 Serial**_ as a new show
5. Click on _**Batman: The 1943 Serial**_ from the Shows page once it has been added and observe error

###### Info
```
SR Version:	BRANCH: (master) / COMMIT: (7045417b59bb23cbc2426e2e1f7b0e59f21a87fb) 
SR User:	**_REDACTED_**
SR Locale:	('en_US', 'cp1252')
SR Config:	C:\sickrage\config.ini
SR Database:	C:\sickrage\sickbeard.db
SR Cache Dir:	C:\sickrage\cache
SR Log Dir:	C:\sickrage\Logs
SR Arguments:	[]
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
```
###### Error Log
```
Error !

ValueError: (22, 'Invalid argument')

% if int(epResult['airdate']) != 1: ## Lets do this exactly like ComingEpisodes and History <% airDate = sbdatetime.sbdatetime.convert_to_setting(network_timezones.parse_date_time(epResult['airdate'], show.airs, show.network)) %> <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time> % else: Never % endif </td> <td>

C:\sickrage\lib\dateutil\tz.py, line 152:
return time.localtime(timestamp+time.timezone).tm_isdst
C:\sickrage\lib\dateutil\tz.py, line 108:
if self._isdst(dt):
C:\sickrage\gui/slick/views/displayShow.mako, line 483:
<time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
C:\sickrage\gui/slick/views/layouts/main.mako, line 274:
C:\sickrage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by labrys** [comment]
Update: Tested on RPi B+ running Raspbian and does not fail.

**Comment by miigotu** [comment]
Use the other existing thread, thanks.
