### ISSUE TITLE
[APP SUBMITTED]: global name 'cur_actor_name' is not defined

### ISSUE THREAD

**Issue by TekGamer** [SiCKRAGETV/sickrage-issues#3398]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@7045417b59bb23cbc2426e2e1f7b0e59f21a87fb
Link to Log: https://gist.github.com/06effc3ef068b33ed80d
### ERROR
```
Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "Q:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "Q:\SickRage\sickbeard\webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "Q:\SickRage\sickbeard\processTV.py", line 226, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "Q:\SickRage\sickbeard\processTV.py", line 555, in process_media
    result.result = processor.process()
  File "Q:\SickRage\sickbeard\postProcessor.py", line 1104, in process
    ep_obj.createMetaFiles()
  File "Q:\SickRage\sickbeard\tv.py", line 1865, in createMetaFiles
    self.createNFO()
  File "Q:\SickRage\sickbeard\tv.py", line 1876, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "Q:\SickRage\sickbeard\metadata\generic.py", line 278, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "Q:\SickRage\sickbeard\metadata\mede8er.py", line 413, in write_ep_file
    data = self._ep_data(ep_obj)
  File "Q:\SickRage\sickbeard\metadata\mede8er.py", line 325, in _ep_data
    cur_actor_name.text = actor
NameError: global name 'cur_actor_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by mcmikev** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7045417b59bb23cbc2426e2e1f7b0e59f21a87fb
No Log available with ERRORS: 
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1104, in process
    ep_obj.createMetaFiles()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1865, in createMetaFiles
    self.createNFO()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1876, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/generic.py", line 278, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/mede8er.py", line 413, in write_ep_file
    data = self._ep_data(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/mede8er.py", line 325, in _ep_data
    cur_actor_name.text = actor
NameError: global name 'cur_actor_name' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mcmikev** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7045417b59bb23cbc2426e2e1f7b0e59f21a87fb
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: global name 'cur_actor_name' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
