### ISSUE TITLE
Make resultFilters in show_name_helpers.py configurable?

### ISSUE THREAD

**Issue by Jopand** [SiCKRAGETV/sickrage-issues#3401]
Would it be possible to make the resultFilters configurable?
When using a provider such as Nextgen, most of the torrents contain "dksubs" in them, but they are discarded unless I manually edit the 'resultFilters' in show_name_helpers.py file. 

Why hardcode it instead of making it configurable???

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Feature requests are not allowed on the issue tracker. http://feathub.com/SiCKRAGETV/SickRage

**Comment by fernandog** [comment]
@SiCKRAGETV/moderators  to me its a bug issue

```
resultFilters = [
    "sub(bed|ed|pack|s)",
    "(dk|fin|heb|kor|nor|nordic|pl|swe)sub(bed|ed|s)?",
    "(dir|sample|sub|nfo)fix",
    "sample",
    "(dvd)?extras",
    "dub(bed)?"
]

# if any of the bad strings are in the name then say no
ignore_words = list(resultFilters)
```

language in release name are NOT bad strings. 

we are skipping results with this words when they really should be at IGNORED words
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/show_name_helpers.py#L37

**Comment by fernandog** [comment]
can't we add a new setting in gui

"(" + IGNORE_LANGUAGES + ) + sub(bed|ed|s)?

remove the last regex and add a note in UI: `add |dub| to ignore dubbed releases`
with JS we can check values and don't allow to be saved without "|"

**Comment by fernandog** [comment]
@Jopand 

is it ok for you ?

Screen shot:
![image](https://cloud.githubusercontent.com/assets/2620870/10612267/d29d3708-772e-11e5-85df-a94b0038561d.png)

**Comment by Jopand** [comment]
Yes, it looks good :-)
No more manual editing when updating \o/
