### ISSUE TITLE
Not able to set SR to use the "network timezone" anymore

### ISSUE THREAD

**Issue by rmbleeker** [SiCKRAGETV/sickrage-issues#3402]
**BRANCH:** master
**COMMIT:** 7045417b59bb23cbc2426e2e1f7b0e59f21a87fb
**OS:** Ubuntu 14.04 LTS kernel 3.19.0-30-generic 64-bit
**Python:** 2.7.6

Since yesterday I can not set SR to use network time zones any more after it somehow had changed it's settings to use local time. Even when I go to Settings -> General -> Interface, change the radio button from **Local** to **Network** and click *Save Changes* it keeps showing local times as show air dates and the setting doesn't actually change, neither in the GUI nor in the config.ini file. This also affects the dates SR changes the downloaded files to once it re-scans the show.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by rmbleeker** [comment]
I did a little test where I stopped SR, edited the config.ini changing the value for *timezone_display* from **local** to **network** and started SR again. SR then showed the actual airdates and -times for shows again and after re-scanning some shows also reverted the file times back. However when I change the setting in the GUI to show local time zones I can't change it back to showing network time zones any more, I have to stop SR and edit the config file every time now.

**Comment by fernandog** [comment]
Just a simple question: why would you prefer network time instead of local? what's your locale?

**Comment by rmbleeker** [comment]
Fair question. My local time zone is UTC +2 which means show air times for most shows are at ridiculous times in the middle of the night in my local time zone, since all shows that I watch are from the USA or Canada. I would prefer SR and the downloaded files to show me the time the show actually airs, not what time that happens to be in my little country.

As for the locale of the user I run sickrage under (I gave it it's own system user account), it's a mix of US english and Dutch:

LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=

**Comment by fernandog** [comment]
@rmbleeker 
problem is, if you enable 'network' and show airs (network time) at 20:00, SR will mark this episode as wanted at 21:00 (yours, not network). And if ep is wanted at your 21:00 but it REALLY airs at yours 03:00, SR will keep searching all providers from 21:00 until 03:00 and won't get anything as the show hasn't aired yet and we will be hitting providers with unnecessary requests

**Comment by rmbleeker** [comment]
Good point and I see why you would want to avoid that. Honestly I don't really care about how SR handles the show times internally and I could live with showing local times in the GUI, but I would much prefer the actual files to have the network air time set on them by the post processor.

Ideally SR should convert network air times to local for the purpose of when to look for new shows (without users being able to mess with this, IMO), but users should be able to choose whether they want network or local times for the GUI and files. Should I propose that as a feature on the FeatHub?

**Comment by fernandog** [comment]
do you have this setting enabled? maybe we can fix that converting to network airtime

```
Change File Date
Set last modified filedate to the date that the episode aired?
 
NOTE: Some systems may ignore this feature.
```

please open a FeatHub for this

**Comment by rmbleeker** [comment]
Yes I have that enabled.

**Comment by rmbleeker** [comment]
http://feathub.com/SiCKRAGETV/SickRage/+223

**Comment by rmbleeker** [comment]
I'm re-opening this issue because it's still not fixed. Sometimes when I save new setting under **General** -> **Interface** SR reverts the setting for the **Timezone** to *local*, causing all air times to be displayed in my local time again. I then have to stop SR and edit the *config.ini* to set it back.

**Comment by fernandog** [comment]
@rmbleeker 
you must change network time in PP settings NOT in general

**Comment by rmbleeker** [comment]
@fernandog I see, hadn't noticed it there before so thanks for pointing it out. Looks like the wiki could do with some updates :-)

Alright so the GUI part of this issue is still a feature request, which I made in http://feathub.com/SiCKRAGETV/SickRage/+223

**Comment by fernandog** [comment]
fixed in develop. reverted the force

**Comment by rmbleeker** [comment]
@fernandog you mean that you also changed how the GUI displays times now? I just updated my feature request and when I clicked submit I saw your short message there.

**Comment by fernandog** [comment]
yes

**Comment by rmbleeker** [comment]
cool :+1:

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/adb3058cd64c4977fdf71c9d1b6dd67e81708560
