### ISSUE TITLE
New Episode info on TVDB not appearing in SR

### ISSUE THREAD

**Issue by BenBeyond** [SiCKRAGETV/sickrage-issues#3405]
SR Version:	BRANCH: (master) / COMMIT: (29c97fb37688d31bfa4b765d309647bbaddb335a) 
SR Arguments:	['-d']
Python Version:	2.7.9 (default, Apr 2 2015, 15:34:55) [GCC 4.9.2]
Running on Ubuntu 15.04

For the show Steven Universe, there is new season/episode information on TVDB that is not being pulled into SR.

![image](https://cloud.githubusercontent.com/assets/5505883/10611794/b3b9399e-771b-11e5-9cdb-fa890fac1389.png)

SR shows a Season 3, while TVDB does not, and SR shows "Super Watermelon Island" as the first episode of Season 3, but TVDB shows an episode called "Too Far" as the next sequential episode.

I have tried the "Stop SR, delete cache.db, delete folders in cache except images" fix from other issues, but it did not fix it.
Also tried "Force Full Refresh", but that also does not fix the inconsistency and No errors in log.

Might be caused by something to do with the XEM connection on this show, which I think has caused issues with this particular show before...

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Seems to be working fine here.
Try to remove the show and re-add it. (Otherwise it could be indeed a numbering issue with XEM. But you have to change it on there site.)

![naamloos](https://cloud.githubusercontent.com/assets/7928052/10612466/377264ba-7751-11e5-8ab5-e58de1f4a5d5.png)

**Comment by BenBeyond** [comment]
removing/re-adding the show worked, thanks!

**Comment by fernandog** [comment]
Maybe when he added the show season 3 exists.
Dont know if SR removes seasons or only single episodes
