### ISSUE TITLE
Error! AttributeError: class Show has no attribute 'overall_stats'

### ISSUE THREAD

**Issue by antakar** [SiCKRAGETV/sickrage-issues#3412]
Error !
AttributeError: class Show has no attribute 'overall_stats'
% if sbLogin: <footer> <div class="footer clearfix"> <% stats = Show.overall_stats() ep_downloaded = stats['episodes']['downloaded'] ep_snatched = stats['episodes']['snatched'] ep_total = stats['episodes']['total'] ep_percentage = '' if ep_total == 0 else '(<span class="footerhighlight">%s%%</span>)' % re.sub(r'(\d+)(\.\d)\d+', r'\1\2', str((float(ep_downloaded)/float(ep_total))*100))
/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/gui/slick/views/layouts/main.mako, line 283:
<%
/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

This is when upgraded to the latest version.

Unable to start sickRage.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@antakar 

Shutting down SickRage and removing the cache/mako & cache/sessions folders

**Comment by antakar** [comment]
Thank you. I am unable to find the cache dir under SickRage dir.
Please tell me where can i find it.

**Comment by fernandog** [comment]
open "Help & Info" in SR's menu

find "SR Cache Dir:"
remove the cache/mako & cache/sessions folders

**Comment by antakar** [comment]
I can not start SR at all.
Unable to connect

Firefox can't establish a connection to the server at 192.168.12.46:7073.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by fernandog** [comment]
check:

/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/cache/

**Comment by antakar** [comment]
[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage] # ls
CHANGES.md       TODO.txt         contributing.md  news.md          sickbeard/       tornado/
COPYING.txt      autoProcessTV/   gui/             readme.md        sickrage/
SickBeard.py*    contrib/         lib/             runscripts/      tests/

**Comment by fernandog** [comment]
@neoatomic help here please?

**Comment by antakar** [comment]
Also:

[/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage] # ls
Repository/          arm/                 sickbeard-tvrage.sh* x86/
SickBeard-TVRage/    config/              x31/

**Comment by neoatomic** [comment]
@antakar You are using an old/outdated package you need to use. : http://apps.qnap.community/11-community/17-qsickrage

Not sure what the exact path for the cache folder is, but should be the same as where your sickbeard.db and config.ini are.

**Comment by antakar** [comment]
this is the version i use:
BRANCH: (master) / COMMIT: (56fd7a9447fb0e72398568be737c1f00b5bb07f4) 
But, how can i check what actual version do i run atm?

Ie the latest is: 4.0.73 (2015-10-04)
But where is SR can i find out what version is it that i have installed?

**Comment by miigotu** [comment]
The PACKAGE is outdated. Please install the one from the link neoatomic gave you. You can copy your db and config from the old install into there.

**Comment by antakar** [comment]
Well, my SickRage version was updating from the GitHub all the time. Just yesterday i have updated to the latest.

Can you tell how can you tell my package is outdated?

**Comment by neoatomic** [comment]
It has noting to do with the sickrage version. Its the QPKG package that is outdated. (that you use to run Sickrage on your qnap)

**Comment by rascalli** [comment]
@neoatomic , that package is only for Intel based NAS
Note that ARM based NAS should still use the old package

**Comment by miigotu** [comment]
@rascalli for arm qnap you need this python package: https://github.com/SiCKRAGETV/sickrage-issues/issues/3117#issuecomment-151292252

**Comment by antakar** [comment]
I do have ts-453 Pro, which is x86. I will update as soon as I will find some time.
Thank you for your help.

**Comment by antakar** [comment]
In QSickRage the config file is sickrage.conf
In the package i have installed it is config.ini

So i assume i have to rename config.ini > sickrage.conf ?
Also, 
Is that the directory where i should put sickrage.db and renamed config.ini > sickrage.conf ?
/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/CONFIG

I ask because it seems as the config has been picked up, but i dont see any shows listed, so i assume the db hasnt been picked up?

**Comment by antakar** [comment]
Another problem, since my last post, Sickrage didnt pull the posters for the episode...
How can i make it to pull this data again?

**Comment by miigotu** [comment]
config.ini goes in DATAS also afaik.m sickrage.conf was the service configuration.
