### ISSUE TITLE
SR Randomly requiring cache purge to find new episodes 

### ISSUE THREAD

**Issue by Zipties** [SiCKRAGETV/sickrage-issues#3413]
Starting a few weeks back the episode searcher will fail to search any sources. You can see it start in the log, but it never polls anything. The only resolution I have found is to delete the cache folder and the corresponding database. This is now happening every 2 days.

Branch:  (master) / COMMIT: (56fd7a9447fb0e72398568be737c1f00b5bb07f4) 
Your operating system and python version: Server 2008 R2/Python 2.7.1
What you did: Expected shows to be searched and downloaded
What happened: They did not search or download
What you expected: Them to be found
How can we reproduce your issue: Uncertain
Include a link with your log file. https://drive.google.com/folderview?id=0B2ggqo902tNhZGI3aElWSU1hSFU&usp=sharing

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@miigotu something is corrupting cache.db ?

**Comment by fernandog** [comment]
maybe related to KAT/TPB as I don't have this issue and don't have this providers enabled

**Comment by Zipties** [comment]
I don't use KAT or TPB

**Comment by miigotu** [comment]
@Zipties it is because of the providers being refactored, it will settle down once they are all normalized and refactored completely.

**Comment by Zipties** [comment]
@miigotu Thank you. Could you explain a bit more what refactored means?

**Comment by miigotu** [comment]
It means that they are being changed heavily, moving methods around and changing their operation to make the code simpler and cleaner and more efficient. We are trying to get them all to follow a simple format and only have to have a few functions to add a new provider.

Im also going to be changing the entire provider layout soon to make it easier to add new provider types like a proper torznab implementation (right now we cant get seeders when using torznab), and possibly in the future there will be options like IRC providers and FTP providers.

Most importantly it is to stop having a few providers here and there that dont work and us not knowing about it before releases.
