### ISSUE TITLE
Sickrage not snatching wanted episodes

### ISSUE THREAD

**Issue by japdevil** [SiCKRAGETV/sickrage-issues#3414]
Hello,
I am running Sickrage on synology nas (installed from synocommunity and for some reason it has only recently stopped snatching wanted episodes.
Fork: https://github.com/SiCKRAGETV/SickRage.git / Master branch.
Python version: 2.7.10-14
SynologyDSM: 5.2-5592 Update 4
Sickrage is setting new episodes to wanted but not actually snatching them. If i manually search, it successfully snatches the episode.
Have updated to latest version and restarted NAS.
I have also tried the following suggestions: 
- Shutting down SickRage and removing the cache/mako & cache/sessions folders.
- Added a scene exception for a series that new episodes are not being snatched.
- All series episodes are set WANTED as default. 
- 

See extract of logs:

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Shutdown SickRage and remove the cache.db file.

**Comment by japdevil** [comment]
Not sure why this has been closed when i've already tried the suggestion????

**Comment by fernandog** [comment]
@japdevil  you don't have needed episodes

" SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found"

wait until next ep airs

**Comment by japdevil** [comment]
There are three series where episodes are set to wanted .. and the show has already been aired. This seems to be the issue where shows are not being snatched because the daily search keeps coming back with No needed episodes found". E.g. Good Wife S07E03 has been aired and is set to wanted but daily search comes back with no needed episodes. Not sure why this is happening,

**Comment by fernandog** [comment]
without FULL logs as mentioned, can't do nothing
force dailysearch wait it to finishe and send full logs

**Comment by japdevil** [comment]
Ok. i've forced a daily search and waited until finished but still did not snatch any wanted episodes. Is it possible for me to email you logs?

**Comment by fernandog** [comment]
No. Use GIST
