### ISSUE TITLE
Episode not showing in schedule

### ISSUE THREAD

**Issue by ROpdebee** [SiCKRAGETV/sickrage-issues#3416]
It's currently 2:30am here, here's some screens
![screen shot 2015-10-22 at 02 30 07](https://cloud.githubusercontent.com/assets/15186467/10653981/0c8e6fae-7865-11e5-9850-f38d27814db3.png)
![screen shot 2015-10-22 at 02 28 53](https://cloud.githubusercontent.com/assets/15186467/10653982/0f233222-7865-11e5-9f96-6298367791ce.png)
As you can see, South Park should be in this list as it's set to air in 2h, but it's not in the list. I haven't looked into it much but I think I'd be able to pinpoint the problem, I suspect the problem is that the episodes are listed in network time in the db but are selected based on local time. South Park would have an airdate in network time as Oct 21 2015 10:00pm but since it's local time Oct 22 2015 here already, the episode doesn't get selected from the db until it's actually marked as wanted.

I think I'd be able to fix this one and I'd gladly do so, but seeing as it's part of that new ComingEpisodes class @MGaetan89's working on, and I don't want to interfere with his work, I'm posting here first.

Reproducing this issue is going to be a tough one, probably need to fiddle with the system time and timezone settings to get this

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@ROpdebee it will only convert from UNAIRED > WANTED in the next dailysearcher after airtime+show run time

**Comment by miigotu** [comment]
@ROpdebee Seems @MGaetan89 would rather you fix the initial issues and he'll handle reworking his side for his PR's when he comes back... have at it.
