### ISSUE TITLE
Archive on first match has an incorrect description

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3417]
From the edit page, "archive episode after the first best match is found from your archive quality list". There's no such thing as an "archive quality list".

We should also add a cancel button next to the submit button that just takes the person back a page or even to the homepage.

@SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by duramato** [comment]
@OmgImAlexis it just needs a rename to "preferred quality list" afaik

**Comment by miigotu** [comment]
The whole archive on first match thing needs reworked and logic redone.

original "archive_on_first_match" feature was badly named. It was just meant to say "stop searching for a better episode"

This conflicted with the "archived quality" and confused people that they were connected, when in fact they are 2 separate features. Just a badly named added feature that caused the two to be blended into each other over time and they mean two totally different things, so now neither works correctly.

"Archived (Quality)" will become only when a file does not exist or is detected as deleted (depending on your removed file detection settings).
"Archive on first match" will be removed (I think), as it is unnecessary with the 2 quality lists we have now and makes for less confusion.

It will continue to get better qualities in the first list until it gets one from the second list, and then it will stop.

This way you can have Downloaded (1080p WEB-DL) as Overview.GOOD and Downloaded(720p WEB-DL) as Overview.QUAL (needs redownload better quality).

If you want it to stop on whatever it gets, add them all to the second list.

None of this is a priority right now.

**Comment by OmgImAlexis** [comment]
The problem with that is it still needs to be reworked in my mind for people that want it to download a better quality like 1080p WEB-DL and then replace it with a SDTV for archiving purposes. Really we need custom lists of qualities and a way to have it stop at any quality in the list like CP. I know people keep comparing SickRage to CouchPotato but the way they handle it just works so much better than this does currently.

**Comment by miigotu** [comment]
The problem is that it works fine for now and doesn't need to keep being discussed every other day. =)

**Comment by neoatomic** [comment]
Lets discuss this further in Issues STATs.
