### ISSUE TITLE
PP doesn't wait for subtitles ?

### ISSUE THREAD

**Issue by DDamian** [SiCKRAGETV/sickrage-issues#3419]
Not sure if this is a bug or it just works this way. Can someone please explain, what is the workflow of downloading subtitles on Sickrage ? 

What seems logic to me is following:
1. Search for episode
2. Found, downloading - mark as 'snatched'
3. Episode downloaded - mark as 'downloaded' - do NOT post process.
4. Search for subtitles
    4a) Found subtitles - begin post processing, move episode & subs to final folder
    4b) Subtitles not found - do NOT post process, wait until subtitles are found and then post process

But it seems that it does not work this way, and post processing happens directly after download of episode is finished - no matter whether there are subtitles or not.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by medariox** [comment]
SickRage downloads the file and moves it with or without subtitles. The subtitles are being searched after the PP, not sure why you got the impression that the PP waits for the subtitles, but it is not the case right now.

**Comment by DDamian** [comment]
Ok, thanks :) I didn't get that impression, it just seemed logic for me that it will work this way. If it doesn't well, my bad.

Let me show you my point of view: I'm from poland, so any video without polish subtitles is basically useles for me. Altough when postprocessing finishes, episode is moved to final folder and appear in my xbmc instance, which is pointess, because at this point I don't know if I can watch this video or not. So I have to then manually check if subtitles are already downloaded or not.

Maybe it would be a feature request for future, to have some flag in postprocessor settings, to hold postprocessing until there are subtitles downloaded?

**Comment by medariox** [comment]
Well, I think that many non-English mother tongues enjoy their series without subtitles (like myself) or with English subtitles. Saying that it's useless without subtitles seems a bit exaggerated to me. :) 
But of course anyone has his personal opinion and needs. Feel free to open a feature request if you like: feathub.com/SiCKRAGETV/SickRage

**Comment by DDamian** [comment]
Thats why I proposed a flag to enable/disable it. Thanks, will do.
