### ISSUE TITLE
Post-processing didn't create season poster for Kodi12+

### ISSUE THREAD

**Issue by jrozelle** [SiCKRAGETV/sickrage-issues#3420]
Hello,

I notice that post-processing failed to create season poster, whereas everthing is enebled in "metadata" under kodi12+., log is ok, but files are missing...

Thanx a lot !

# Info
**Python** : Python 2.7.9 (default, Jun 11 2015, 05:37:13) 
**Branch** : Master, Your branch is up-to-date with 'origin/master'.
commit 4d37c1352e1a27023ffd520a4da8ab0f024333e6
Merge: 57bafd1 db81cc9
**OS** : Synology DSM 5.2-5592 Update 4 

Here the log detail : 

https://gist.github.com/jrozelle/680106735015491dce46#file-gistfile1-txt

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Show me output of:
`ls /volume1/Video/Series/Continuum/*.jpg`

**Comment by jrozelle** [comment]
ls -l *.jpg
-rw-rw-rw-    1 Julien   users       492584 Nov 27  2014 backdrop.jpg
-rw-r--r--    1 Julien   users        32923 Mar 14  2015 banner.jpg
-rw-r--r--    1 Julien   users       550619 Mar 14  2015 fanart.jpg
-rw-rw-rw-    1 sickrage users       231451 Sep 14 19:08 poster.jpg
-rw-rw-rw-    1 sickrage users        32078 Sep 14 19:08 season-all-banner.jpg
-rw-rw-rw-    1 sickrage users       231451 Sep 14 19:08 season-all-poster.jpg
-rw-rw-rw-    1 sickrage users       131952 Sep 14 19:08 season03-poster.jpg

**Comment by miigotu** [comment]
The log says thats all that exists too, only problem could be a permissions issue or the images werent returned by theTVDB. It works here.

**Comment by miigotu** [comment]
Continuum:
```
dusted@PC:~/Videos/Continuum: ls
banner.jpg           season02-poster.jpg    season-all-poster.jpg
fanart.jpg           season03-poster.jpg    season-specials-poster.jpg
poster.jpg           season04-poster.jpg    tvshow.nfo
season01-poster.jpg  season-all-banner.jpg
```

Continuum (Web Series):
```
dusted@PC:~/Videos/Continuum (Web Series): ls
banner.jpg  poster.jpg           season-all-banner.jpg  tvshow.nfo
fanart.jpg  season01-poster.jpg  season-all-poster.jp
```

**Comment by jrozelle** [comment]
Yes, log says that all files exists, but the problem is that :

34:48 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season01-poster.jpg exists: False
2015-10-22 12:34:48 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum
2015-10-22 12:34:49 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season02-poster.jpg exists: False
2015-10-22 12:34:49 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum
2015-10-22 12:34:51 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season03-poster.jpg exists: True
2015-10-22 12:34:51 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season04-poster.jpg exists: False
2015-10-22 12:34:51 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum

And season01-poster.jpg season02-poster.jpg season04-poster.jpg are not created.

I check the permission : /volume1/Video/Series/Continuum/ is 777.

**Comment by miigotu** [comment]
It doesnt say that all exist.m It says that it doesnt exist. Your cache/images folder might not have the right permissions. Ive tested it here with this exact show and it works.

**Comment by jrozelle** [comment]
I try to delete all metadata files (*.jpg and nfo) and to do full upgrade : same problem.

**Comment by jrozelle** [comment]
I move cache/image into cache/image.bak.

Here the result after a fullupdate : 
Syno> ls cache/images/*
cache/images/258171.banner.jpg  cache/images/258171.fanart.jpg  cache/images/258171.poster.jpg

cache/images/thumbnails:
258171.banner.jpg  258171.poster.jpg

**Comment by jrozelle** [comment]
deleted cache folder + cache.db and restart SR.

here the log : 
2015-10-22 21:12:09 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season01-poster.jpg exists: False
2015-10-22 21:12:09 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum
2015-10-22 21:12:10 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season02-poster.jpg exists: False
2015-10-22 21:12:10 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum
2015-10-22 21:12:12 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season03-poster.jpg exists: False
2015-10-22 21:12:12 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum
2015-10-22 21:12:13 DEBUG    SHOWQUEUE-REFRESH :: Fetching image from http://thetvdb.com/banners/seasons/258171-3-10.jpg
2015-10-22 21:12:14 DEBUG    SHOWQUEUE-REFRESH :: Checking if /volume1/Video/Series/Continuum/season04-poster.jpg exists: False
2015-10-22 21:12:14 DEBUG    SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating season posters for Continuum


only fetching season03 poster... I don't understand...

**Comment by jrozelle** [comment]
Problem solved : 
My "Default Indexer Language" was French. It seems that tvdb didn't have season poster for this show.

Switched Default Indexer Language to English : everything ok...

Maybe adding a feature allowing to verify if poster exist in selected langage. If not => try with english langage ?
