### ISSUE TITLE
Incorrect encoding of polish subtitles - broken just yesterday

### ISSUE THREAD

**Issue by DDamian** [SiCKRAGETV/sickrage-issues#3421]
Polish subtitles downloaded by subliminal are in windows-1250, but after that sickrage mark them as utf-8 and it breaks the thing. Subtitles no longer look ok, no matter if I select utf-8 or windows-1250. Was working 2 days ago.

In subtitles.py:
```
 #Force subtitle encoding to utf-8 for some languages
+            if subtitle.language.alpha3 == 'pol':
+                setattr(subtitle, 'encoding', 'utf-8')
```
Broken subtitles here:
https://www.dropbox.com/s/m9xaq3zsxx95amu/Homeland%20-%205x03.srt?dl=0

EDIT//  From what I can see, subliminal will first try to decode downloaded subs in utf-8 and if fails, try with windows 1250.  By setting .encoding property, you force it to use only utf-8, so if it fails, it just returns broken subs.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@medariox

**Comment by medariox** [comment]
That change was made because of this PR: https://github.com/SiCKRAGETV/SickRage/pull/2894
The author ( @mbiernacik ) stated that polish subtitles must be encoded to UTF-8 to be properly viewed. I tested quite a lot and indeed with setting to UTF-8 some subtitles are broken, but others work fine and with setting it to "windows-1250" (sublimnal default). I really wouldn't like to spend much more time trying to understand which encoding works better for you, so I ask you please - polish SickRage users - do your tests, make up your mind and let me know what encoding you'd like to have for your subtitles, as you just can't have both of them. Thanks!

**Comment by DDamian** [comment]
Yes, but subliminal tries to encode them in utf-8 at the first place. and ONLY if it fails, it try with windows-1250. So I guess it's better than just forcing always utf-8.

**Comment by medariox** [comment]
Fixed in https://github.com/SiCKRAGETV/SickRage/pull/2964 
(Reverted the forced encoding.)
