### ISSUE TITLE
MKV seems to be malformed, ignoring embedded subtitles

### ISSUE THREAD

**Issue by Kwebbel** [SiCKRAGETV/sickrage-issues#3422]
<img width="788" alt="screen shot 2015-10-22 at 20 56 07" src="https://cloud.githubusercontent.com/assets/3310298/10675234/5b5ea014-78ff-11e5-9d5a-0ce42835eaeb.png">

Refreshing the show homeland results in error in log while files are perfectly readable by video player

```
2015-10-22 20:50:59 ERROR    SHOWQUEUE-REFRESH :: MKV seems to be malformed, ignoring embedded subtitles
2015-10-22 20:50:58 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Homeland
2015-10-22 20:49:47 ERROR    SHOWQUEUE-REFRESH :: MKV seems to be malformed, ignoring embedded subtitles
2015-10-22 20:49:46 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Homeland
```

Refreshing was initiated because the shows where on status snatched while files are available and playing perfectly. With a refresh I hoped that the new files where found and status would be set correctly

However this doesn't work.

I've set it to manual Downloaded now just to be sure sickrage won't overwrite or delete files that are good. Should I be concerned for all the other shows?

<img width="1239" alt="screen shot 2015-10-22 at 20 58 41" src="https://cloud.githubusercontent.com/assets/3310298/10675309/bd22e828-78ff-11e5-91e7-3bd98744c544.png">

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
the mkv are malformed.

@medariox this shouldnt be an error log.

**Comment by medariox** [comment]
It's actually Warning:
```
logger.log('MKV seems to be malformed, ignoring embedded subtitles', logger.WARNING)
```

**Comment by medariox** [comment]
@miigotu 
Should we change it to Debug?

**Comment by miigotu** [comment]
I think it can be INFO or DEBUG, depending on whether the user really needs to see it yes.

**Comment by medariox** [comment]
Fixed in https://github.com/SiCKRAGETV/SickRage/pull/2964

**Comment by Kumolo** [comment]
@medariox Thanks for fixing this, I also get this warning a lot and due to the new "Badge with error count on Logs & Errors" it draws my attention every day.

By the way, wouldn't it a be a good idea to print the movie name/path instead of just saying "mkv"? This way, at least I can have a look at the file or ignore it if it is an old warning...

**Comment by medariox** [comment]
@Kumolo 
You are right, the path will be shown in parenthesis now. I included the change in this PR: https://github.com/SiCKRAGETV/SickRage/pull/2967
