### ISSUE TITLE
Subtitles Languages descriptions are equal for different languages.

### ISSUE THREAD

**Issue by xaxim** [SiCKRAGETV/sickrage-issues#3425]
On ***Subtitles Settings*** page, ***Subtitles Search*** tab, ***Subtitles Languages*** field, when I type *Portuguese*, it brings two options with the same description, both of which are *Portuguese* (I know one is *brazilian portuguese* and the other is *european portuguese*, although it is hidden in the UI, so I dont know if I selected *Brazilian* or *European*)

I even tried to find it in the code, but couldn't figure out from where does it get the languages names and ids.

![captura de tela 2015-10-23 03 19 46](https://cloud.githubusercontent.com/assets/10148155/10685149/0786735a-7935-11e5-9872-cd4d83559e99.png)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by xaxim** [comment]
***Complimentary Information:***

SR Version:	BRANCH: (master) / COMMIT: (3572446c66615e7876bf996e3eaf4d6d26400a7d) 
SR Locale:	('pt_BR', 'cp1252')
SR Config:	D:\MEDIA\SickRage\Data\config.ini
SR Database:	D:\MEDIA\SickRage\Data\sickbeard.db
SR Cache Dir:	D:\MEDIA\SickRage\Data\cache
SR Log Dir:	D:\MEDIA\SickRage\Data\Logs
SR Arguments:	['--nolaunch', '--port=8081', '--datadir=D:\\MEDIA\\SickRage\\Data']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

Windows 10 Pro 64 bits

***What you did:***
I typed a language in the subtitles settings.

***What happened:***
Two languages with the same name appeared (both Portuguese)

***What you expected:***
I expected two languages: Portuguese and Brazilian Portuguese

***How can we reproduce your issue:***
Go to Subtitles Settings page and type 'Portugues' in the Subtitles language field.

There was nothing related to that issue in the log file.

**Comment by medariox** [comment]
This is already fixed with this PR in develop: https://github.com/SiCKRAGETV/SickRage/commit/a5a15a68ceaa676ac163bb1d64c2dea8a3ffb1fa
You can switch to develop or wait until it gets merged to master.
