### ISSUE TITLE
[APP SUBMITTED]: Thread-35 :: Errors: [u"New location <tt>/home/gormson/termines/tv/Marvel's Daredevil</tt> does not exist"]

### ISSUE THREAD

**Issue by gormson** [SiCKRAGETV/sickrage-issues#3441]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7b6040b3a706331bac4bf7ec5dc8b8d2845bf0b4
Link to Log: https://gist.github.com/e71bb668c622dbd611a0
### ERROR
```
Thread-35 :: Errors: [u"New location <tt>/home/gormson/termines/tv/Marvel's Daredevil</tt> does not exist"]
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@gormson are you trying to move show to a location where SR don't have permission?

**Comment by gormson** [comment]
Hello,

I think i understood the issue. when I created the show, i put a folder for the finished download, there, sickrage created correctly the show folder
but then i changed this folder.
but the show folder haven’t been created.

I just noticed that.

maybe, if the location of the show is updated, the folder could be created again to avoid this?

Thanks for the support.

**Comment by fernandog** [comment]
@gormson you should use folder navigation to change show folder. So the folder should exist. You can't type

@miigotu is there a way to avoid type show folder in that field?

**Comment by gormson** [comment]
I did not type it, I selected it but I think i mixed the the root directory principle with the edit fonction

I though that we only have to select a new root directory and the show folder was created again if not existing (with the correct name and the correct permissions)

**Comment by fernandog** [comment]
No. You must select show folder. Not root

**Comment by gormson** [comment]
Understood now, I’ll correct the associated show

Thanks
