### ISSUE TITLE
SR says Airdate "Never" while TVDB has valid data

### ISSUE THREAD

**Issue by Kumolo** [SiCKRAGETV/sickrage-issues#3450]
Hi guys,

I have recently added German TV show "ZDF History". During the Add, I told SR/Indexer to use German language. TVDB has valid data for Airdate, which can be seen here: http://thetvdb.com/?tab=season&seriesid=151731&seasonid=612283&lid=14

However, SR says for all episodes "Airdate Never". I can only explain this if SR/TVDB would ignore the language setting for this show? (i.e use WRONG URL: http://thetvdb.com/?tab=series&id=151731 )

SR Master #7b6040b3a706331bac4bf7ec5dc8b8d2845bf0b4

Thanks.

![sr](https://cloud.githubusercontent.com/assets/12941715/10714703/cbd40cec-7afa-11e5-8315-79aab0af9a0f.JPG)
![tvdb](https://cloud.githubusercontent.com/assets/12941715/10714705/d04cf810-7afa-11e5-87e8-02e6810b57f7.JPG)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by squareflapjack** [comment]
I have the same issue with Celebrity Name Game and I am using English.  The show page shows all episodes airdates as never but the Schedule page shows the correct date for the episodes.  TVDB has airdates for all episodes

SR Version: 	BRANCH: (master) / COMMIT: (4028db3d7a2cc582b0f591d981ed3af344b4e75a) 
SR Locale:	('en_US', 'UTF-8')
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

![schedule](https://cloud.githubusercontent.com/assets/5619740/10715109/9e96dc1e-7b09-11e5-9bd0-6015197a0a46.png)

![showpage](https://cloud.githubusercontent.com/assets/5619740/10715132/8d70162a-7b0a-11e5-8b3a-ef1b269c22ba.png)

**Comment by Kumolo** [comment]
@squareflapjack Yes, I noticed it is not Language related since the epsiode name is correct in my case (German). I just editet the title to avoid this obviously wrong assumption.

Must be something different that causes this behaviour.

**Comment by neoatomic** [comment]
@Kumolo I just tested and indeed no airdates are shown for this show.
However thats not the only issue. Even if we find the course the show isn't going to work.
All the releases dont contain a `s01e01` or `airdate` etc. in the tile so they cant be detected by sickrage wile searching.

**Comment by duramato** [comment]
@Kumolo you need to go on tvdb and change the original airdate and the air day afaik

**Comment by Kumolo** [comment]
Thanks for confiming @neoatomic.

Yeah, noticed that already and worked around by manually adding "S20abExy" (S2015E23 for example) to fit to TVDB naming convention for my manual downloads for this show. 

Anyway, since SR doesn't parse the title of an episode and since the Release Group doesn't add airdate or S20abExy to the releases I understand automatic downloads won't work.

So that leaves us to the question if we can at least fix the airdate display in SR or if we need to edit TVDB as @duramato suggests?!

**Comment by neoatomic** [comment]
@Kumolo I already checked that on TVDB and all is fine.
So i'm currently not sure why no air-date is shown, needles to say i'm curios why...

**Comment by fernandog** [comment]
@miigotu dateutil update related?

**Comment by neoatomic** [comment]
Ok, the next airdate is shown fine on the shown overview. Also on Schedule its shown correctly.: 

`25-10-2015, 00:00 	25-10-2015, 00:45 	ZDF History 	S2015E36 	Der letzte Tag - Romy Schneider 	ZDF 	45min `

![naamloos](https://cloud.githubusercontent.com/assets/7928052/10715395/cc236ae2-7b15-11e5-9183-2afda3f8fa0c.png)

So its seems isolated to the shows own page.

**Comment by duramato** [comment]
@Kumolo , @neoatomic & @fernandog 
Like i said it was missing info...
It was missing the time it aired
![image](https://cloud.githubusercontent.com/assets/10121067/10715508/b241c8e4-7b10-11e5-9bac-b844735d2d76.png)

**Comment by duramato** [comment]
same for @squareflapjack 
![image](https://cloud.githubusercontent.com/assets/10121067/10715533/9da8adfc-7b11-11e5-9c5f-45e0cbc13691.png)
after update
![image](https://cloud.githubusercontent.com/assets/10121067/10715671/74ae489e-7b16-11e5-80ea-b9ecab7a7f56.png)

**Comment by miigotu** [comment]
This is a temporary problem. I had to manually override this because it gives an error on windows (due to a bug in dateutil)

https://github.com/dateutil/dateutil/issues/133

**Comment by miigotu** [comment]
Nevertheless, still update theTVDB with the missing info.

**Comment by labrys** [comment]
@miigotu Fixing issue dateutil/dateutil#133 still doesn't resolve the error on Windows.  Further troubleshooting shows it's an issue with dateutil not being able to determine daylight savings time for dates prior to the epoch, even if the datetime object is otherwise valid.  
For example `dt = datetime.datetime.fromordinal(719162)` would yield 1969-12-31 00:00:00 but
`dt = dt.replace(tzinfo=tz.tzlocal())` would fail to print with the following ValueError:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib\dateutil\tz.py", line 115, in utcoffset
    if self._isdst(dt):
  File "lib\dateutil\tz.py", line 159, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')
```

**Comment by miigotu** [comment]
@labrys on windows you shouldnt call `tz.tzlocal()` you would call `tz.tzwinlocal()`

Maybe `sb_timezone` needs to be set selectively based on OS, which would be quite simple. Does `tz.tzwinlocal()` work in your example above or does `tz.tzwinlocal is None` ?

**Comment by labrys** [comment]
A quick test calling `tz.tzwinlocal()` directly with the dateutil/dateutil#133 fix does work properly on Win XP x86 SP3.   I'll try the fix out in SickRage tonight and I'll confirm on Win 10 x64 later this morning when I get a chance.

You would think that since it is auto-detecting the OS that `tz.tzlocal()` would fall back to `tz.tzwinlocal()` on Windows systems, especially since `gettz()` falls back to `tzwin()`.

In the mean time the following change to 'displayShow.mako' should get most dates working even with the current `dateutil`:
```python
<td class="col-airdate">
    % if int(epResult['airdate']) > 1:
        ## Lets do this exactly like ComingEpisodes and History
        <% airDate = datetime.datetime.fromordinal(epResult['airdate']) %>
        % if airDate.year >= 1970 or show.network:
            <% airDate = sbdatetime.sbdatetime.convert_to_setting(network_timezones.parse_date_time(epResult['airdate'], show.airs, show.network)) %>
        % endif
        <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
    % else:
        Never
    % endif
</td>
```

**Comment by labrys** [comment]
With the fixed `tz.tzwinlocal()` being called, SickRage fails with `ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439` so the `utcoffset()` has an issue as well.

**Comment by labrys** [comment]
Tested the `displayShow.mako' fix I posted with current master build and the shows listed above, __ZDF History__,  and __Celebrity Name Game__, along with __Batman: The 1943 Serial__  from #3007 all work correctly.

**Comment by miigotu** [comment]
so it's just >1 instead of !=1 ?

**Comment by labrys** [comment]
Either works.. >1 was what was in the current code so I left that unchanged.
