### ISSUE TITLE
Search using xthor provider failed

### ISSUE THREAD

**Issue by nabot93** [SiCKRAGETV/sickrage-issues#3459]
Hi everyone,

I have some issue with the provider xthor. When it try to download, it looks for the search url: https://xthor.bz/browse.php?search="The%20Player%20%282015%29%20S01E05"&searchin=title&incldead=0 and no result on the xthor website are found...

If I manually remove the quotes and enter in my web browser this url: https://xthor.bz/browse.php?search=The%20Player%20%282015%29%20S01E05&searchin=title&incldead=0, the search on the website succed.

Could it be possible to replicate this modification in SickRage provider? I do not know how to do it myself...

Thanks !

log file: http://pastebin.com/BhUKQvqu
commit: 5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@nabot93 Cant test this provider as i dont have an account...

Related to https://github.com/SiCKRAGETV/SickRage/pull/2565 ?

**Comment by nabot93** [comment]
Ok, what I am asking is the exact opposite of the PR #2565...

**Comment by neoatomic** [comment]
@raver2046 @adaur Could any of you do a quick check if this is indeed an issue.?

**Comment by raver2046** [comment]
you have to let the quotes.
The probleme is elsewhere this is a typical scene exception
http://www.htpcguides.com/fix-sickrage-not-finding-shows-with-torrents-or-usenet/

you try to find "The Player (2015) S01E05" but the result is The.Player.2015.S01E05.FASTSUB.VOSTFR.HDTV.x264-3ARLY   

put The.Player.2015 in scene exeption.

If that works with scene exeptions let the code as it is.

**Comment by nabot93** [comment]
Ok, I just find out about this scene exception feature.

**Comment by adaur** [comment]
I don't know why raver added these quotes in the first place so...

**Comment by raver2046** [comment]
i was annoyed. See below.
But it seem's xthor have fixed there without quotes search .
Also i am ok if you remove it.


https://github.com/raver2046/SickRage/commit/404aa3db9d863d4fc1f237f737fc4d8eb4041298

==> for exemple if your search extant.s02e03 you don't find the episode.
And if you do "extant.s02e03" it works.
