### ISSUE TITLE
Web Interface HTTP port changes after updates

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#3464]
Web Interface HTTP port changes to it's default value (8081) after runing updates (automatic or manual).

It's turning a real pain in the @ss.......

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by labrys** [comment]
What OS and Python version are you using and how are you updating?  I have SickRage running on 3 separate systems (Win XP x86 SP3, Win 10 x64, and Win 8.1 x64) running on 3 separate ports (8081, 8082, and 8083) and I regularly update using git pull and the update from the browser and haven't seen this yet.  Also are you running it as a service or running it directly? (I run mine directly)

**Comment by Trapizomba** [comment]
I'm using the latest version of FreeNAS...

Python Version: 2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]

I allways update using the SickRage's web GUI (browser)...

**Comment by neoatomic** [comment]
All working fine here. Its probably the installation package of bad permissions.

**Comment by Trapizomba** [comment]
What?! Installation package of bad permissions?! How can you tell this? Are you kiddin, don't you?!

The last update (COMMIT: 5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f do not changed the default port back to 8081 but the previous one done this. And some commits back changed tthe port to 8081 too... If I remember the port changed from 80 to 8081 occurred at least 5 times last month when some updates weas applied...

Are you kiddin, don't you?!

Well tell "Its probably the installation package of bad permissions" is an easy way to resolve an update bug or something... Great!

**Comment by fernandog** [comment]
@Trapizomba why port 80? no reason for that. please user other than 80

You are the only one complaining about this. So we are a little skeptical about the issue otherwise we would have A LOT of open issues about this

**Comment by neoatomic** [comment]
If you take the time to properly report an issue i dont have to guess.!
I tested and cant replicate it, meaning its a local issue on YOUR system. aka permissions or bad installation package.

**Comment by Trapizomba** [comment]
@fernandog,

Why port 80? Because I need it running on port 80. Simple as that.

How many users are using SickRage on port 80 or are running it on another port (not 8081)?

@neoatomic,
My SickRage installation is runing on a FreeBSD jail, nothing more is running there...

How can I update the software without errors and the port stills changing from 80 to 8081? 

I reboot the machine and/or the jail and the port stills 80 but when I update the app using the Web GUI some specific commits changes the port back to 8081?

Are you really convicted it is a permission issue?

Thank you!

**Comment by Trapizomba** [comment]
Looking at the SickRage's backup file directory (/var/db/sickrage/backup) I found a backup of an update (the update was made automatically):

-rw-rw-rw-  1 media  media  53496168 Oct 25 18:23 sickrage-20151025182222.zip

I unzipped the file an opened the config.ini file. Part of the content is:

cur_commit_hash = 4028db3d7a2cc582b0f591d981ed3af344b4e75a
cur_commit_branch = master
config_version = 7
web_port = 8081

How the web_port changed to 8081 If I did NOT changed it from 80 to 8081? Weird...

**Comment by Trapizomba** [comment]
Looked the SickRage's directory (/var/db/sickrage/) and found an file called config.ini.v6 (Apr 21  2015)

Content includes:

cur_commit_hash = 975c0dd208c59cac8fd8a77a91da5d1dfc7235df
cur_commit_branch = master
config_version = 6
web_port = 8081

Well... I think you are messing with the config.ini file during updates and don't know that or don't want to know...

**Comment by labrys** [comment]
While I haven't been able to reproduce this on Windows (XP x86 SP3, 8.1 x64, and 10 x64) I did have an issue where SickRage wasn't updating from the browser for any of my installs on any of my systems.  It went through the process but still showed that the same updates were still pending.  

This may be due to some testing I'm doing though, and since I usually pull updates manually, I can't say that its not something I've done locally or how long it's had this issue.  I'll try a clean install as time permits to see if I can successfully update from the browser, however ports have all remained constant throughout.
