### ISSUE TITLE
error when adding existing shows

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#3466]
SR Version:	BRANCH: (master) / COMMIT: (5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f) 
SR User:	Pedro
SR Locale:	('en_US', 'cp1252')
SR Config:	C:\Users\Pedro\Desktop\SickRage\config.ini
SR Database:	C:\Users\Pedro\Desktop\SickRage\sickbeard.db
SR Cache Dir:	C:\Users\Pedro\Desktop\SickRage\cache
SR Log Dir:	C:\Users\Pedro\Desktop\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

i decided to make a clean SR installation, when using the latest master version and trying to use the option to "add existing shows" the page displays the text below and no errors are logged

edit: log https://gist.github.com/pct00/28a12bc78780920d5694

Error !

UnicodeEncodeError: 'charmap' codec can't encode character u'\u03a7' in position 7: character maps to <undefined>
<thead><tr><th class="col-checkbox"><input type="checkbox" id="checkAll" checked=checked></th><th>Directory</th><th width="20%">Show Name (tvshow.nfo)<th width="20%">Indexer</td></tr></thead> <tbody> % for curDir in dirList: <% if curDir['added_already']: continue show_id = curDir['dir'] if curDir['existing_info'][0]:
C:\Program Files (x86)\Python\lib\encodings\cp1252.py, line 12:
return codecs.charmap_encode(input,errors,encoding_table)
C:\Users\Pedro\Desktop\SickRage\gui/slick/views/home_massAddTable.mako, line 10:
<%
C:\Users\Pedro\Desktop\SickRage\lib\mako\runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by labrys** [comment]
Looking at your log it looks like an issue with the `Z:\Fear the Walking Dead\tvshow.nfo`.  Would you mind posting the .nfo so I can attempt to duplicate it on my system?

**Comment by pct00** [comment]
hi, that log message seems to be from an earlier attepmpt, that file was causing another error so i deleted it

**Comment by neoatomic** [comment]
Make sure there aren't any special characters in the folder/file/nfo files.
And: Shutting down SickRage and removing the cache/mako & cache/sessions folders.

**Comment by pct00** [comment]
@neoatomic its a clean install so clearing cache didnt solve anything. did it anyway just to make sure.

as for the special characters the only that exist are from the folders / files created by SR itself on the previous install so there are some from non common show names but SR never had much trouble with them

**Comment by neoatomic** [comment]
@pct00 See if you can rename those folders/files to not include any special characters. Windows doesn't like those.

**Comment by pct00** [comment]
@neoatomic thanks for the tips. figured out that the problem wasnt on the folders themselves but on the conntents of the .nfo files previously generated by SR
think SR didnt like some of the contents.
after deleting the all it worked fine
cant pinpoint eh exact cause of the problem since it was 300+ .nfo files in the mix...

thanks again
