### ISSUE TITLE
Web Interface HTTP port changes back to 8081 after updates

### ISSUE THREAD

**Issue by Trapizomba** [SiCKRAGETV/sickrage-issues#3471]
Actual Version: BRANCH: (master) / COMMIT: (5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f) 
Python Version: 2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]
OS: FreeNAS-9.3-STABLE-201509282017

- Updates made using the Web GUI (browser);
- Intermittent bug: some updates changes SR port from 80 to 8081, some updates not.

Looking at the SickRage's backup directory (/var/db/sickrage/backup) I found a backup file called sickrage-20151025182222.zip

I unzipped the file and opened the config.ini file. Part of the content is:

cur_commit_hash = 4028db3d7a2cc582b0f591d981ed3af344b4e75a
cur_commit_branch = master
config_version = 7
**web_port = 8081**

The web_port is set to 8081 but I did NOT changed it from 80 to 8081.

There is another zip file in that directory (/var/db/sickrage/backup) called sickrage-20151026153553.zip

I unzipped the file and opened the config.ini file. Part of the content is:

cur_commit_hash = bd2b8c682277da2cbdaae05ba9d8163b399d6931
cur_commit_branch = master
config_version = 7
**web_port = 80**

Than looked the SickRage's directory (/var/db/sickrage/) and found an file called config.ini.v6 (Apr 21 2015)

Content includes:

cur_commit_hash = 975c0dd208c59cac8fd8a77a91da5d1dfc7235df
cur_commit_branch = master
config_version = 6
**web_port = 8081**

Well... I think you are messing with the config.ini file during updates......

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
