### ISSUE TITLE
Auto post process issue when the torrent contains both the file and the file sample

### ISSUE THREAD

**Issue by marco219** [SiCKRAGETV/sickrage-issues#3477]
This torrent contains a .mkv and .mp4. The .mkv is the tvshow and the .mp4 is the file sample.
The issue is that when post process is done the sample  file is moved instead of the actual file.
Here is the log:
```
2015-10-27 02:51:04 INFO     POSTPROCESSER :: Not deleting folder /mnt/hdd/downloads/Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG found the following files: [u'Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG.mkv']
2015-10-27 02:51:04 INFO     POSTPROCESSER :: Processing succeeded for /mnt/hdd/downloads/Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG/RARBG.com.mp4
2015-10-27 02:50:55 INFO     POSTPROCESSER :: Release name (Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG) found from file (Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG.nfo)
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@marco219 We need more info like described here. : https://github.com/SiCKRAGETV/sickrage-issues#before-you-open-an-issue

Also see if you can find the link of the torrent that caused this, so we can replicate the problem.

**Comment by marco219** [comment]
Here is the info about my setup :+1: 

SR Version: 	BRANCH: (master) / COMMIT: (5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f)
SR User:	root
SR Locale:	(None, None)
SR Config:	/home/*****/sickrage/config.ini
SR Database:	/home/*****/sickrage/sickbeard.db
SR Cache Dir:	/home/*****/sickrage/cache
SR Log Dir:	/home/*****/sickrage/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/*****/sickrage/']
Python Version:	2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]

Here is the torrent link https://rarbg.to/download.php?id=j3spwn1&f=Gotham.S02E03.1080p.WEB-DL.DD5.1.H264-RARBG-[rarbg.com].torrent
This torrent contains a .mkv and .mp4. The .mkv is the tvshow and the .mp4 is the file sample.
The issue is that when post process is done the sample file is moved instead of the actual file.
Hope you have all the info you need

**Comment by rarbg** [comment]
the mp4 is not the sample
the mp4 is the group video :)
for the devs - preg to exclude those files from our torrents - ^RARBG\.([A-Za-z]+)\.(mp4|avi|txt)$i

**Comment by fernandog** [comment]
@miigotu ^^

**Comment by miigotu** [comment]
Fixing now

```
    if re.search(r'^RARBG\.\W+\.(mp4|avi|txt)$', filename, re.I):
        return False
```

**Comment by miigotu** [comment]
zzz changed `\W` for `\w` in the next commit. numbnuts I are.
