### ISSUE TITLE
Unable to change layout in Schedule view

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#3481]
When I'm in the Schedule view I'm unable to change the layout. There is nothing in the debug log.
```
R Version:	BRANCH: (master) / COMMIT: (5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f) 
SR User:	Download
SR Locale:	('nl_NL', 'cp1252')
SR Config:	C:\GitHub\SickRage\config.ini
SR Database:	C:\GitHub\SickRage\sickbeard.db
SR Cache Dir:	C:\GitHub\SickRage\cache
SR Log Dir:	C:\GitHub\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
```

Tried with:
* Chrome Version 46.0.2490.71 m (64-bit)
* IE Version 11.0.9600.18053

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@Rouzax Its working fine here. (Probably the cache has gone bad.)  

Try : Shutting down SickRage and removing the cache/mako & cache/sessions folders.

**Comment by Rouzax** [comment]
@neoatomic No still has the same issue after clearing the mako and sessions

**Comment by fernandog** [comment]
What exact happen? No JS errors?

**Comment by Rouzax** [comment]
Nothing.
When I change the menu
![image](https://cloud.githubusercontent.com/assets/4103090/10756319/8aa48b16-7ca3-11e5-9a53-f28d3a72f612.png)

The screen belows refreshes but does not show the new layout also the previous option is back.

**Comment by neoatomic** [comment]
Just did a fresh install on Windows 10. 
Still all working fine here... : 

![1](https://cloud.githubusercontent.com/assets/7928052/10756383/0a512dce-7ca4-11e5-9ce2-c4f8f94920f5.png)
![2](https://cloud.githubusercontent.com/assets/7928052/10756384/0a6b6f86-7ca4-11e5-9619-d1ca20786d71.png)

**Comment by Rouzax** [comment]
Did it from 2 different machines with the same result.
I think I found the issue, I have a reverse proxy in front of SR. When accessing the site directly it works.

Previously this did work because I always had a reverse proxy.
