### ISSUE TITLE
nzbToMedia setup wiki page edit request

### ISSUE THREAD

**Issue by codemann8** [SiCKRAGETV/sickrage-issues#3485]
I'm new to this but there are three additions I'd recommend adding since this is what i had to do in addition to get everything to work.

1) The .cfg file also must have "fork = sickrage" in the [SickBeard] section.
2) You must create a "logs" directory inside the root nzbToMedia directory (or the repository should just include this)
3) Permissions must be set on the nzbToMedia directory to Full Access (I couldn't figure out which user is executing the script since having the Administrators group wasn't sufficient, I had to give "Everyone" Full Access)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
@neoatomic

**Comment by neoatomic** [comment]
@codemann8 Thank you for helping.

However i'm unsure what exactly to add.

1) By default the setting is `auto` and no need to change it to "fork = sickrage" as that is auto-detected.
(The only time that doesn't happen is when failed downloads is disabled in Sickrage)

2) If i recall right Logging is disabled by default. So setting this up is more a extended feature.
(And the download client also has the log of the running script.)

3) The permissions depend on the setup that the user uses. Sickrage & SABnzbd only need access to the nzbtomedia folder.
(Think i already have that in the wiki. Will double check that.)

The thing is that the wiki is meant as a basic setup for sickrage users. NZBtoMedia is a third-party package and official support is at there repository.

**Comment by codemann8** [comment]
Hmm, I've also had failed downloading enabled but I kept getting errors, it was only resolved by changing the fork.  And I didn't change any other setup in nzbToMedia, as I don't know what I'm doing, I'm just following guides and Googling error codes as i go along, but i got a error, could not find file or directory C:\Program F...\nzbToMedia\logs

**Comment by miigotu** [comment]
Nothing belongs in `Program Files`, thats why the windows installer for SickRage installs to C:\SickRage by default, and nzbtomedia is included in SickRage/contrib

**Comment by neoatomic** [comment]
@codemann8 I myself used `auto` and that works fine. sickrage fork is detected.
However just to be sure i added that part to the wiki anyway. 
Also made a note that both sickrage & sabnzbd need access to the folder.

Probably it just Windows that is coursing those strange issues, wont be the first time. :)

**Comment by codemann8** [comment]
Yeah, I install ALL my programs to Program Files or (x86), whichever is relevant.  I NEVER install anything to C:, it's just messy organization, I think many will agree.

Yes, I know nzbToMedia is included, that's where I'm pointing to it from SAB.

**Comment by miigotu** [comment]
@codemann8 it isn't messy organization, there is a reason ported linux applications do not belong in program files. You can argue if you want and do it your own way but then when shit doesnt work don't come ask for help.

**Comment by codemann8** [comment]
There's no need to be nasty about it, but since we're here, it IS messy organization.  I'm sure in Linux you just put shit wherever the eff you want willy-nilly, but I like to put my stuff in meaningful-named folders.  I have yet to have a program fail that tried to, by default, install to C.  The only exception to this was yagarto-tools for programming my RaspberryPi and the only reason was that the directories leading to it couldn't contain a space.  That's fine, I'm okay with that reason, I created a new folder called Programs and put it there, maintaining good organization, and it worked perfect.

**Comment by miigotu** [comment]
It isn't messy organization, it is the normal layout for a cross platform application. The directories with spaces and parenthesis are the problem, not because SR cant handle them but because users like yourself don't undertsand how to escape paths in config files and you end up getting errors like " could not find file or directory C:\Program F...\nzbToMedia\logs"

Thinking you know better than all of the open source world is kind of silly.

**Comment by codemann8** [comment]
I don't know better than all, but I know as much as I've never had a program fail on me despite putting all of them in Program Files since my first computer in '92.  It worked just fine once I added the logs directory.  You make it sound as if I got that error because it's where it is, I didn't.  I understand your typical user doesn't know how to escape properly, but I do, but that's beside the point, there is no config file that I have to modify for SickRage or nzbToMedia where I have to specify a directory.  All that config resides in the UI, which the code should handle escaping for.  So I'm confused why you're so upset I put a program where all the other programs are, if it bothers you that much, why have the destination in the installation be editable?

**Comment by miigotu** [comment]
1. I didnt write the installer
2. There are many installs I have had to connect to over team viewer and move to a sane linux type path before it would work correctly.
3. If you don't like the answers, just don't ask the questions. You can't ask for help and then say the advice is wrong in the same breath (because if you knew you wouldn't be asking).

**Comment by codemann8** [comment]
See the OP, I wasn't asking questions or asking for help, I was trying to provide it for other users.  I didn't have to post here, I solved my issues well before I posted, I just figured other users might want to know the extra steps they'll have to take but since that's not welcome here I'll just be on my way.

**Comment by miigotu** [comment]
You're missing the point. The `issues` you had getting nzbToMedia to work were because you had SR/NZBtoMedia in program files, which not only has spaces and special chars in the path, but are also protected by UAC and permissions in the file system. If you had followed the instructions none of those issues would have happened.

Moral of the story is it is fine that you got your install working by taking your own path, but our wiki does not need updated with specialized information from your custom setup.
