### ISSUE TITLE
SickRage is suddenly unable to setup GitHub

### ISSUE THREAD

**Issue by SiliconKid** [SiCKRAGETV/sickrage-issues#3486]
Everything was fine and then SickRage did an auto update yesterday, and now I see this happening in the log constantly:

AAGithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u"API rate limit exceeded for 169.0.165.87. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
AA    raise self.__createException(status, responseHeaders, output)
AA  File "/opt/sickrage/lib/github/Requester.py", line 179, in __check
AA    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA  File "/opt/sickrage/lib/github/Requester.py", line 171, in requestJsonAndCheck
AA    "/orgs/" + login
AA  File "/opt/sickrage/lib/github/MainClass.py", line 188, in get_organization
AA    gh = Github(user_agent="SiCKRAGE").get_organization(GIT_ORG).get_repo(GIT_REPO)
AA  File "/opt/sickrage/sickbeard/__init__.py", line 687, in initialize
AATraceback (most recent call last):
2015-10-28 07:36:52 ERROR    MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error: 

My concern is that no updates will come through now, so if this is a bug of some sort SickRage isn't going to get any fix you release.

SR Version:	BRANCH: (master) / COMMIT: (e61aaf37645e360e5527b4d0b44a532dea63976c) 
SR User:	nobody
SR Locale:	('en_US', 'UTF-8')
SR Config:	/config/config.ini
SR Database:	/config/sickbeard.db
SR Cache Dir:	/config/cache
SR Log Dir:	/config/Logs
SR Arguments:	['--datadir=/config']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
This is a limitation of GIT. If you read the error : `API rate limit exceeded`
Meaning your IP did to many requests. 

As this is not Sickrage, but Git related we cant do anything about that...

**Comment by SiliconKid** [comment]
I sorted it out by giving SickRage my own Git credentials and setting the Branch again etc.

The thing is:

a. I only have SickRage checking for updates every 24 hours, so I can't be responsible for any rate violation with a check interval that wide.

b. Why did all the Git information that WAS set and WAS working vanish from the SickRage config after SickRage updated itself yesterday ?

It was working fine without me giving it my own Git creds previously, and even IF it's making anonymous requests to Git, why does a 24 hour check interval cause a rate violation ?

**Comment by neoatomic** [comment]
The update never touches the config.ini where all this info is stored. And update has no influence on GIT whatsoever. its a third party app.
So that tells me you are probbebly using an (bad?) installation package.? That is the only way if those settings get changed.

Also what do you mean with `Git information that WAS set and WAS working vanish` 
We dont add/set a GIT account/details in Sickrage. This again sounds like some1 did make a bad installation package for your device. And if there are per-configured GIT credentials in that package i'm not  surprised that you get the `API rate limit exceeded` as all users are using the same account...

**Comment by SiliconKid** [comment]
In General settings -> Advanced tab, there is a section at the bottom for setting all the Git related info.

Branch, Username, Password etc.  All related to Git. In SickRage.
