### ISSUE TITLE
Please reconsider removing mediaToSickbeard.py

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#3489]
I've tried using https://github.com/clinton-hall/nzbToMedia but it is doing things I do not need or want.

It is making a copy of the episode and stopping the torrent, etc.
I only want to be able to run a script and let SickRage import that episode.
Right now I'm running
```
"C:\GitHub\SickRage\autoProcessTV\mediaToSickBeard.py" "\\hyperv\data\Private\uTorrent\_Proccessed\TVSeries\The.Knick.S02E02.720p.HDTV.x264-KILLERS" "The.Knick.S02E02.720p.HDTV.x264-KILLERS"
```
And that will run the import in SickRage for that specific episode.

Please reconsider removing mediaToSickbeard.py

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
We are not removing support for autoProcessTV. We just dont include them in the sickrage folder (by default) anymore.
Just copy them where ever you like on your disk, and they will work just fine.

**Comment by Rouzax** [comment]
Unfortunately it doesn't work
```
C:\GitHub\autoProcessTV>mediaToSickBeard.py" "\\hyperv\data\Private\uTorrent\_Proccessed\TVSeries\The.Knick.S02E02.720p.HDTV.x264-KILLERS" "The.Knick.S02E02.720
p.HDTV.x264-KILLERS"
The system cannot find the path specified.
```

**Comment by neoatomic** [comment]
You need to configure the settings/path in the config file with the new location etc..

**Comment by Rouzax** [comment]
No, mediaToSickbeard.py only works if it is in a subfolder of SickRage.
```
try:
    fp = open(configFilename, "r")
    config.readfp(fp)
    fp.close()
except IOError, e:
    print "Could not find/read Sickbeard config.ini: " + str(e)
    print 'Possibly wrong mediaToSickbeard.py location. Ensure the file is in the autoProcessTV subdir of your Sickbeard installation'
    time.sleep(3)
    sys.exit(1)
```

**Comment by neoatomic** [comment]
You can also copy back the whole autoProcessTV to the original location if you want. (after we removed the folder)

But i would recommend switching to nzbtomedia, and if there is a function you are missing, you can always do a feature request on there repository.
