### ISSUE TITLE
wrong quality downloads 

### ISSUE THREAD

**Issue by sacretagent** [SiCKRAGETV/sickrage-issues#3494]
Hi.. running this version 

R Version:	BRANCH: (master) / COMMIT: (5b5446030ea3c0a1e403cb3f1a02c804e20c2196) 
SR User:	nobody
SR Locale:	('en_US', 'UTF-8')
SR Config:	/config/config.ini
SR Database:	/config/sickbeard.db
SR Cache Dir:	/config/cache
SR Log Dir:	/config/Logs
SR Arguments:	['--datadir=/config']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

since a few days i get these downloads that SR thinks are dvd rips but are not 

this is an example but i have them for many shows 

Season 2
	NFO	TBN	Episode	Name	Airdate	Subtitles	Status	Search
	N	N	10	Bridges	03/24/2015, 09:00		Snatched SD DVD	search
	N	N	9	Orphans	03/17/2015, 09:00		Snatched SD DVD	search
	N	N	8	Babylon	03/10/2015, 09:00		Snatched SD DVD	search
	N	N	7	Property Line	03/03/2015, 10:00		Snatched SD DVD	search
	N	N	6	Tables	02/24/2015, 10:00	English	Snatched SD DVD	search
	N	N	5	Rock Garden	02/17/2015, 10:00	English	Snatched SD DVD	

and these are the nzb he send to sab / same for torrents

19-2.2014.S02E07.Property.Line.WS.XviD-err0001-NZBgeek.nzb
19-2.2014.S02E08.Babylon.WS.XviD-err0001-NZBgeek.nzb
19-2.2014.S02E09.Orphans.WS.XviD-err0001-NZBgeek.nzb
19-2.2014.S02E10.Bridges.WS.XviD-err0001-NZBgeek.nzb

19-2_2014_S02E06_Tables_WS.XviD-err0001.torrent
19-2_2014_S02E05_Rock_Garden_WS.XviD-err0001.torrent

have them from other scene releasers too

	N	N	19	10 Things They Hate About You	08/27/2015, 10:00	English	Snatched (Proper) SD DVD	search
	N	N	18	Knotting Phil	08/20/2015, 10:00	English	Snatched SD DVD	search
	N	N	17	Haskell Doesn't Live Here Anymore	08/13/2015, 10:00	English  Undetermined	Snatched SD DVD	

here are the  torrents 

The.Exes.S04E19.REPACK.XviD-AFG.torrent
The.Exes.S04E18.XviD-AFG.torrent
The.Exes.S04E17.XviD-AFG.torrent

seems he is thinking XVID stands for dvd rip ?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Will check this when I get home.
