### ISSUE TITLE
Update Kodi don't work since fews days...

### ISSUE THREAD

**Issue by akhlan** [SiCKRAGETV/sickrage-issues#3497]
Hi,

I have an issue with the menu "Update Kodi", it doesn't work since fews days and I haven't change anything....

the error log...

```
2015-10-29 10:46:31 ERROR    Thread-35 :: Failed to detect KODI version for '192.168.35.41:80', check configuration and try again.
AAURLError: 
AA    raise URLError(err)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 1197, in do_open
AA    return self.do_open(httplib.HTTPConnection, req)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 1227, in http_open
AA    result = func(*args)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 409, in _call_chain
AA    '_open', req)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 449, in _open
AA    response = self._open(req, data)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 431, in open
AA    return opener.open(url, data, timeout)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 154, in urlopen
AA    response = urllib2.urlopen(req)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/notifiers/kodi.py", line 386, in _send_to_kodi_json
AATraceback (most recent call last):
2015-10-29 10:46:31 ERROR    Thread-35 :: Error while trying to retrieve KODI API version for 192.168.35.41:80: error [Errno 111] Connection refused
AANone
```
the IP adress is good, the Kodi password too, I don't understand....

Please could you help me ?

Rgds
Akhlan

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Port is likely supposed to be 8080 instead of 80 right?

**Comment by akhlan** [comment]
I used port 80, not 8080 ;)

I have try just to see but same issue...

**Comment by miigotu** [comment]
Maybe you are using an old ass kodi? This works here on kodi 13 to kodi 16

Does the test notify button return a success?
