### ISSUE TITLE
Fail to download SD version from provider

### ISSUE THREAD

**Issue by renatofsp** [SiCKRAGETV/sickrage-issues#3499]
When I try to snatch a tv series I line like this in the logs

* 2015-10-29 11:21:33 INFO     SEARCHQUEUE-MANUAL-269641 :: [ThePirateBay] :: Ignoring result Chicago.Fire.S03E06.HDTV.x264-LOL because we don't want an episode that is SDTV"

but for this show (in fact for all my shows) i have quality defined as SD, I'm wrong to assume that this file should be snatch?!!!!

I have the latest version updated this morning UTC+0 timezone. But I guess this happens since yesterday at least (not sure since only today I check he reason why this episode was not snatch)

I have some programing experience so if you want me to help in anyway let me know.

    Branch: master
    Commit hash: 3c63ee88e6e6ef033d841986decf7a3086fad7fe
    Your operating system and python version: linux (ubuntu 14.04 LTS) python 2.7
    What you did: I try to manualy snatch Chicago PD episode after it fail on the daily search
    What happened: the episode for Chicago PD was not snatch
    What you expected: an SD version to be snatch
    How can we reproduce your issue: not sure
    Include a link with your log file: https://gist.github.com/renatofsp/9654c3c304636a285141#file-sickragelog-txt

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Follow the guidelines. https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

**Comment by miigotu** [comment]
Haha. The log lines are just illformed. The results are ignored because they are for "Chicago Fire" and you are searching for "Chicago P.D."

**Comment by renatofsp** [comment]
The message is a bit misleading sorry about that the names are similar and since I was reading with nano on my terminal my eyes just trick me

**Comment by miigotu** [comment]
Yep, np, logging is a bit cryptic at times. We are working to improve the logging output all the time.
