### ISSUE TITLE
sabtosickrage postprocessing script error 

### ISSUE THREAD

**Issue by wigwam12** [SiCKRAGETV/sickrage-issues#3500]
I'm new to the Usenet world and have been enjoying setting up Sickrage and Sabsnzbd onto my NAS
 I am having a problem getting the sabtosickbeard autoprocessing working.
 I have pointed sabnzbd to the relevant script folder, I have edited my autoProcessTV.cfg (as below) but when I untick the processing box in Sickrage and let Sabs manage it, it doesn't work and I get the error below.
 When I tick the box to let sickrage manage post-processing I still get the error below but the file is processed properly and moved.
 Could someone please tell me what I need to change to sort this.

 Error log I get is:
 Loading config from /usr/local/sickrage/var/SickRage/autoProcessTV/autoProcessTV.cfg

 Traceback (most recent call last):
 File "/usr/local/sickrage/var/SickRage/autoProcessTV/sabToSickBeard.py", line 34, in
 autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
 File "/volume1/@appstore/sickrage/var/SickRage/autoProcessTV/autoProcessTV.py", line 83, in processEpisode
 host = config.get("SickBeard", "host")
 File "/usr/local/python/lib/python2.7/ConfigParser.py", line 330, in get
 raise NoSectionError(section)
 ConfigParser.NoSectionError: No section: 'SickBeard' 

 I edited my sickrage autoprocessTV.cfg as this:
 [SickBeard]
 host=192.168.0.20:8899
 port=8899
 username=wigwam12
 password=****
 web_root=
 ssl=0

 Don't know what to do at all.

Thanks

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by wigwam12** [comment]
Sorry Additional info:
OS = Xpenology latest build on a new microserver build as of 2 weeks ago so Sickrave, python, Sabnzbd etc all the versions from the package manager from that date

**Comment by neoatomic** [comment]
According to the error the Problem lies within autoprocessTV.cfg
Missing the API key and sabnzbd settings.?

However better to switch to nzbtomedia, more info you can find here.:

https://github.com/SiCKRAGETV/sickrage-issues/wiki/NZBtoMedia

(Or use nzbget instead of sabnzbd, witch has all the scripts build-in.)

And here is a guide for the old sabtosickbeard.py. : http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/

**Comment by wigwam12** [comment]
Sorry could you please clarify for me
When you say the  autoprocessTV.cfg is missing the API key and sabnzbd settings do you mean I need to include extra entries into AutoprocessTV.cfg with the sabnzbd port, user/password and API?
I haven't seen this online so didn't know I have to do this.
So under my [sickbeard] do you mean I need to add the following:

[sabnzbd]
sabnzbd_host = 192.168.0.20:8899
sabnzbd_port = 8080
sabnzbd_apikey = SABnzbd api key
?

Thanks for clarifying further.
I would rather try to sort with the info I have that try to work out how to install nzbtomedia etc

**Comment by neoatomic** [comment]
Indeed those settings. If you need more info try to search the forum/Google.

However i would strongly advise to switch to nzbtomedia, as it also supports failed downloads.
Lastly we are removing the autoprocessTV folder from the Sickrage folder, So if you still want to use those outdated scripts you will have to copy them to another location on your disk.

**Comment by wigwam12** [comment]
Okay thanks again.
I'll try to work out how to install nzbtomedia as it isn't in the community package list.
