### ISSUE TITLE
Sickrage incorrectly identifying TV Show & Not naming correctly.

### ISSUE THREAD

**Issue by PaulW** [SiCKRAGETV/sickrage-issues#3502]
Python Version: **Python 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux**
Localt: **UTF-8**
Branch: **master**
Commit: **https://github.com/SiCKRAGETV/SickRage/commit/3c63ee88e6e6ef033d841986decf7a3086fad7fe**

Log: **http://pastebin.com/Pc5whkTj**

I'm wanting to use SickRage to search, download and index the UK TV Show '8 Out Of 10 Cats Does Countdown', of which most I had previously downloaded.  However, SickRage has incorrectly numbered episodes it has downloaded, and as a result, overwritten and messed up the collection.

As can be seen in the Log, it is trying to rename files like this:

```
File /share/MD0_DATA/Media/Videos/TV/8 Out of 10 Cats Does Countdown/Season 07/8 Out of 10 Cats Does Countdown - S07E01 - David Mitchell, Katherine Ryan, David O'Doherty (720p HDTV).mkv is larger than /share/MD0_DATA/Media/Downloads/TV/8 Out of 10 Cats Does Countdown/8 Out of 10 Cats Does Countdown Season 5/8 Out of 10 Cats Does Countdown - S05E01 - Episode 1 (720p HDTV).mkv
2015-10-29 15:03:15 INFO     Thread-52 :: File exists and new file is smaller, marking it unsafe to replace
```

Obviously this is an issue.

I've removes 8 out of 10 cats from SickRage for now, while I rebuild the collection manually, however, I would rather retain the ability to use SR for this.

Thanks

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Sickrage uses the episode numbering from theTVdb. So you probbebly downloaded those episodes with TVRage before it went down.? And TVRage is possibly using another numbering. 

You basically have two options. 
*  Add a numbering scheme on http://thexem.de/ for that show.
*  Rename your liberty to match the numbering of theTVDB.

But why are you Post-processing those files anyway.? Thats means you are asking sickrage to change/overwrite files...
