### ISSUE TITLE
Sickrage Windows: how to kill/stop it?

### ISSUE THREAD

**Issue by syrys** [SiCKRAGETV/sickrage-issues#3526]
Hey,

I have recently migrated from the old sickrage installation to the new windows installer (https://github.com/VinceVal/SickRageInstaller/releases) on a windows 10 pc.

In the past, i was able to simply ctrl+c on the windows command prompt that is running sickrage to kill the process (or to simply use the "shutdown" option on the menu). But with this new installation, there is no command prompt to force kill, no taskbar icon to exit out of, nor the shutdown option on the menu may as well be renamed to reboot (because it does not shut it down, i cant tell if it shuts down and starts up again or if it does absolutely nothing, but either way, sickrage is still running).

This is quite frustration. Maybe im missing something here? So, here is what im asking for.

1. if there is a manual way to kill the process (and not have it start up again), please tell me.
2. make the shutdown button actually do what it says (and not start it up again).
3. ideally, its nice to have a taskbar item like most other apps (plex, wamp, couchpotato etc), where you can rightclick and exit if you want to (and make sure it actually exits).

i dont think i really need to give a reason to request this functionality, as im sure its a bug or a feature overlooked.

````
SR Version:	BRANCH: (master) / COMMIT: (297ccc3043957ffa96fa142035a9393845cdb024) 
SR Locale:	('en_NZ', 'cp1252')
SR Arguments:	['--nolaunch', '--port=8081', '--datadir=C:\\SickRage\\Data']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
````

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
start/stop it just like any other windows service.

`sc stop SickRage` or `net stop SickRage`

**Comment by syrys** [comment]
@miigotu thanks for that. can we please have a permanent solution? either adding it to the taskbar and you can exit out of it like a normal app, or have sickrage honour the shutdown command (or both, preferably).

**Comment by miigotu** [comment]
its not a normal app, it is a service daemon. It is not designed to run part-time, but to run all the time.

As for the shutdown/restart options we are working on a way to make that reliable, but it is somewhat difficult to do that in a platform independent way.
