### ISSUE TITLE
This show isn't in your list, you need to add it to SB before post-processing an episode

### ISSUE THREAD

**Issue by lpallard1** [SiCKRAGETV/sickrage-issues#3529]
I have an issue with some episodes being snatched, downloaded but not postprocessed.  SR is refusing to postprocess these episodes on the basis that the associated shows are not in my list... ?!?

I know this issue was encountered before with the suggestion to use scene exceptions but unless I did not do it right, its not helping.

For example, the following file and folder is in my downloaded folder (place where SR is setup to posrtptocess from):

/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE/10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv

When I initiate manual postprocessing and pointing to the "/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE/" folder, I get:

Processing folder /mnt/data/sabnzbd/complete/tv/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE
TV_DOWNLOAD_DIR: /mnt/data/sabnzbd/complete/tv
PostProcessing Path: /mnt/data/sabnzbd/complete/tv/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE
PostProcessing Dirs: []
PostProcessing Files: ['10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv']
PostProcessing VideoFiles: ['10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /mnt/data/sabnzbd/complete/tv/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE/10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for /mnt/data/sabnzbd/complete/tv/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE/10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv:
Problem(s) during processing, failed the following files/folders:
[/mnt/data/sabnzbd/complete/tv/ddudes_real_no_passw_10_Game_of_Thrones_S03E10_720p_HDTV_x264_EVOLVE/10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv : Processing failed: ]

of course GoT is in my shows...  Sickbeard never had issues with this so I am wondering what's different in SR for this to happen?  I really dont want to have to manually rename files and folders each time... This should be automated.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
`10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv` <-- Remove the 10.
SickRage will see that as `10. Game.of.Thrones` and not `Game.of.Thrones` as you're expecting.

**Comment by lpallard1** [comment]
Thanks for replying!  
I just did and it worked.  I however wonder why this is not done automatically?  I have been using SB for 5 years+ without this issue... This is worrisome because it means that every time something will not be perfectly named, it will require manual intervention?

SR is running on a remote VPS with only CLI access....

**Comment by OmgImAlexis** [comment]
@miigotu is there any chance this could be solved with guessit?

**Comment by miigotu** [comment]
Nope, its just a bad release.

```
For: 10. Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv
GuessIt found: {
    [1.00] "mimetype": "video/x-matroska", 
    [1.00] "episodeNumber": 10, 
    [1.00] "videoCodec": "h264", 
    [1.00] "container": "mkv", 
    [1.00] "format": "HDTV", 
    [0.70] "series": "10 Game of Thrones", 
    [1.00] "releaseGroup": "EVOLVE", 
    [1.00] "screenSize": "720p", 
    [1.00] "season": 3, 
    [1.00] "type": "episode"
}
```
