### ISSUE TITLE
History: action snatched contains non-release groups making action "archived" instead of "downloaded"

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3530]
When we remove the non-release groups from the file like [rarbg], Shows in history appear as ARCHIVED because files are different.

We should remove the [rarbg] from SNATCHED release

**Showing in history as ARCHIVED - release have non-release groups**

![image](https://cloud.githubusercontent.com/assets/2620870/10869886/c270db04-80a3-11e5-8a12-a26c70971b7b.png)

Allowed: 720p HDTV
Preferred: 1080p HDTV
```
sqlite> select * from history where showid=95021 and season=7 and episode=6 limit 5;
1602|20151029080949|95021|7|6|16|The.Middle.S07E06.1080p.HDTV.X264-DIMENSION[rartv]|Rarbg|-1
1606|20151030190530|95021|7|6|16|/media/PostProcess/The.Middle.S07E06.1080p.HDTV.X264-DIMENSION.mkv|DIMENSION|-1
```

**Showing in history as DOWNLOADED - release don't have non-release groups**

![image](https://cloud.githubusercontent.com/assets/2620870/10869881/ae52ac1a-80a3-11e5-8557-43ac1d438f29.png)

Allowed: 1080p WEB-DL
Preferred: 1080p HDTV

```
sqlite> select * from history where showid=279201 and season=1 and episode=7 limit 5;
6402|20151031055718|279201|1|7|64|Heroes.Reborn.S01E07.1080p.WEB-DL.DD5.1.H264-RARBG|Rarbg|-1
6404|20151031190613|279201|1|7|64|/media/PostProcess/Heroes.Reborn.S01E07.1080p.WEB-DL.DD5.1.H264-RARBG.mkv|RARBG|-1
sqlite>
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
what is the any/best for those two shows?

**Comment by fernandog** [comment]
Another one:

![image](https://cloud.githubusercontent.com/assets/2620870/10871160/51a49ec4-80c6-11e5-891b-c3b4d30c98e1.png)

Allowed: 1080p WEB-DL
Preferred: 1080p HDTV

```
sqlite> select * from history where showid=257655 and season=4 and episode=4 limit 5;
1602|20151028232837|257655|4|4|16|Arrow.S04E04.1080p.HDTV.X264-DIMENSION[rartv]|Rarbg|-1
1606|20151029231422|257655|4|4|16|/media/PostProcess/Arrow.S04E04.1080p.HDTV.X264-DIMENSION.mkv|DIMENSION|-1
```

**Comment by miigotu** [comment]
Its archived because it is highest of preferred quality. Has nothing to do with the history.

**Comment by fernandog** [comment]
ok. 

so to fix the snatched release name in history with non-release groups should we fix it here?
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L161

keeping the non-release groups in history can break failed because it searchers without the non-release group, isn't?

**Comment by miigotu** [comment]
Dont know what that line is pointing to but history and failed history are two separate databases and tables.
