### ISSUE TITLE
Subtitles doesn't work properly anymore

### ISSUE THREAD

**Issue by abibouba** [SiCKRAGETV/sickrage-issues#3534]
Hi,

With one of the latest commit, subtitles download doesn't work anymore.
I use to download from Addicted only, but now this is not working at all.

Plus, two weird things happens:
- If I check Addic7ed only and look for subs, then all the providers become unchecked
- If I check Addicted only, subs are sometimes downloaded from OpenSubtitles

I ana provide you some logs or do some additional tests if needed.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Why closed?

**Comment by miigotu** [comment]
because the bot told them exactly what information must be provided, and after some time it was not provided, and this is verified as working by others.

**Comment by fernandog** [comment]
If is JS issue logs wont help. 
And user dont know how to check JS errors.

**Comment by abibouba** [comment]
Miigotu and his legendary diplomacy. :s
I told you I can provide some additional info if needed.
"It's verified as working by others" = "it's working for everyone". With that kind of logic, I understand why Sickrage is constantly having bugs since a few months.
FYI I run sickrage inside a docker container used by many users. It's up to date with the latest version (docker, image and sickrage).
And I can tell you subtitle download is all messed up. I didn't touch anything except for updates.
So I will try to reset everything and launch a fresh container.

**Comment by abibouba** [comment]
Making sure you update to the latest version. --> Done
Have you tried turning your device off and on again? --> Done
Using the search function to see if this issue has already been reported/solved. --> Done
Do a GIT reset. --> Done
Checking the [Wiki] for [Guides] , [FAQS] [Main settings] , [Show settings] [Remaining settings] --> Done
Shutting down SickRage and removing the cache/mako & cache/sessions folders. --> Done
If SickRage doesnt find any episodes you probably need to :
add a Scene Exception
Set the Default Episode Status to WANTED
Make sure you understand how quality detection works during searches.
Shutdown SickRage and remove the cache.db file. --> Done
If you use a QNAP and have SSL errors try this package.
If you have a 'ascii' codec can't encode character error, than set your Locale to UTF-8

**Comment by abibouba** [comment]
I used a fresh and different docker image.
Log 1 --> https://gist.github.com/abibouba/d7b08eb6f3a170e36bc8
Log 2 (Full) --> https://gist.github.com/abibouba/d8c7f76c148ed5d4a85c

I tried with:
- Only Addic7ed
- Addic7ed + Opensubtitles
- Only Opensubtitles

**Comment by miigotu** [comment]
Specifically:

`Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!`

and:

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

SickRage has hella LESS problems and bugs than before I came.


I suspect you need to add your opensubtitles and addic7ed logins to the subtitles provider settings.

**Comment by abibouba** [comment]
I think I SPECIFICALLY gave you all the information in my 3 last posts.

Now, I suspect you need to check if option to encrypt passwords doesn't break addic7ed subtitles download (and maybe OpenSubtitles but I don't have an account there)

I am not saying there are more bugs than before, I am saying that there are more regression. Things are working perfectly well, then all of a sudden a commit breaks everything. 1 day/week later, another commit fixes it.
Probably less frequent and better tested updates would be a good practice.
Anyway I think I will turn off automatic updates as long as my version is working fine.

And don't get me wrong, I think you are doing a great job on SickRage and thanks for taking time to answer.
