### ISSUE TITLE
Libertalia provider: cannot download not "new" torrents

### ISSUE THREAD

**Issue by nabot93** [SiCKRAGETV/sickrage-issues#3543]
In the Libertalia website, the torrents can be labeled "new". In the current provider script, only the torrents labeled as "new" are processed (cf. https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/libertalia.py#L105).

So, if I want to download a torrent which is no longer labeled as "new", SR won't find it. I think this is a limitation and I do not understand why only "new" torrents should be processed/downloaded.  For example, if I discovered a new serie at its third episode, I will have to download by hand the first two.

Is it possible to remove this restriction to "new" torrents?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@adaur Can you confirm this is indeed the case.?

**Comment by miigotu** [comment]
Easy fix. I'll commit the fix later.

**Comment by nabot93** [comment]
Great! Thank you guys!

**Comment by adaur** [comment]
Sorry guys, I didn't have time yesterday night.

**Comment by adaur** [comment]
You fix causes a new error:

2015-11-08 12:44:19 SEARCHQUEUE-BACKLOG-252322 :: [Libertalia] :: Error while searching Libertalia, skipping: nothing to repeat

**Comment by adaur** [comment]
Hi there, anyone?

**Comment by maxcore** [comment]
@adaur i can test

**Comment by adaur** [comment]
I have submitted a PR which fixes it. This is sad that an untested fixes crashes a whole provider

**Comment by maxcore** [comment]
its me or the search was boring on thix site ? i search for Boomerang and : 
````

2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E07 VOSTFR 720p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E07 VOSTFR WEBRip x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E03 VOSTFR 1080p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E04 VOSTFR 1080p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E05 VOSTFR 1080p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E06 VOSTFR 1080p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E07 VOSTFR 1080p WEBRip DD5 1 x264-LTL 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E07 FRENCH 720p WEBRip DD5 1 H264-LiBERTY 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange Is The New Black S03E08 FRENCH 720p WEBRip DD5 1 H264-LiBERTY 
2015-11-11 08:46:08 DEBUG    SEARCHQUEUE-BACKLOG-248682 :: [Libertalia] :: Found result: Orange is the New Black S03 FRENCH WEBRip x264-AZR 

````

**Comment by adaur** [comment]
I don't understand what you mean. All I know is that I can't get a single torrent to be found in LTL since this 'fix'.

Can you test my regex to make sure it works with your installation too?

**Comment by maxcore** [comment]
![capture d ecran 2015-11-11 09 08 17](https://cloud.githubusercontent.com/assets/4043787/11092783/dc164d02-8853-11e5-933e-6c4ef6a29132.png)

i get this error when i go to config

**Comment by duramato** [comment]
@maxcore did you applied the fix to your own SR or installed new? Set your locale as utf-8

**Comment by adaur** [comment]
It doesn't have anything to do with my modification.

**Comment by maxcore** [comment]
@duramato new install on my mac , i dont touch to my master on my nas
