### ISSUE TITLE
Show List sorting wrong

### ISSUE THREAD

**Issue by rmbleeker** [SiCKRAGETV/sickrage-issues#3547]
I have my Show List page sorted by *Next Episode*, with the *Show Name* as secondary sorting criteria. This morning I noticed that a show that aired yesterday evening is still on top of the list. For some reason the Next Episode date hasn't progressed to the next unaired episode. 
![screenshot from 2015-11-03 10 26 24](https://cloud.githubusercontent.com/assets/4312801/10904921/f6fdb698-8216-11e5-888d-11d5ff77b7cb.png)

I performed a full refresh of the show but that didn't help. The show is correctly pushed to the end of the *Schedule* however. The show in question is Scorpion, which airs at 21:00 EST on mondays.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by rmbleeker** [comment]
Removing the show from SickRage and then adding it again has had no effect, SR still thinks the next episode of Scorpion will air November 2nd even though that has passed.

**Comment by miigotu** [comment]
Please read what the bot said. It is there for a reason.

**Comment by rmbleeker** [comment]
A restart of SickRage (needed because of #3402) seems to have fixed the issue. Might have been a fluke or a cache issue, so closing this for now.

@miigotu I was still editing this issue, sorry for not adding branch and stuff like that right away.

**Comment by miigotu** [comment]
Sorry, Im just on an issue catching/fixing/closing binge =P I tend to be quicker than expected it at times

**Comment by rmbleeker** [comment]
Today Marvel's Agents of S.H.I.E.L.D, the Flash and the Muppets were all still at the top of the Show List even though their episodes aired last night. I removed the following things to hopefully clear this up:
```
cache/sessions/
cache/mako/
cache.db
```

**Comment by miigotu** [comment]
there was a caching issue that was resolved and hotfixed today, make sure you are updated

**Comment by rmbleeker** [comment]
I restarted SR a few times today already due to the post-processor crashing (see #3554) and it updates on start, so I should be up-to-date. I'll find out tomorrow if the issue is resolved :-)

**Comment by rmbleeker** [comment]
Just adding a comment to confirm the issue seems to be resolved.
