### ISSUE TITLE
All new episodes since commit yesterday marked as not downloaded.

### ISSUE THREAD

**Issue by doczong** [SiCKRAGETV/sickrage-issues#3549]
.. On the main start page... Even though they are downloaded and marked as such.
Adventure Time shows as snatched, but it is downloaded (and marked/processed)
Gotham and Fargo show as not even snatched, but they are downloaded (and marked/processed)

This happened after updating after yesterdays commit (Nov 2nd).

So it looks like all shows are snatching and downloading on the individual show page but the main page shows that they have not been.

I am not sure what part of the logs to look at.  There aren't even any errors or warnings indicated either.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Please follow the guidelines for reporting an issue. 
https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md

I have just checked my own installation, and no problems at all. Downloaded 3 episodes last night.
Try : Shutting down SickRage and removing the cache/mako & cache/sessions folders.

**Comment by LauwS** [comment]
I had the same problem, and i can verify that deleting mako and sessions workaround worked for me.
Now the main page looks correct again :-)

**Comment by doczong** [comment]
As a note, the one that was "snatched" was a stuck point in time from when I inadvertently restarted/auto-updated SR, then it downloaded and stayed snatched.  The other two were in "wanted" mode before I went to bed, and this morning were in the same state although they had indeed downloaded and processed properly.

As noted, the logs do not show any warnings or errors, so I would not know what to look for.

I did notice upon update just now that there was another large commit from overnight (last 12 hours).

@LauwS - stopping. deleting cache/mako and restarting did work.  All if fine now.  (for now?)

**Comment by neoatomic** [comment]
Sometimes the cache gets bad. Simply removing it generally solved those issues. :)

**Comment by LauwS** [comment]
Well... a restart might have been enough.
Now i just played a bit with it, and seems i have to restart each time i change something in my shows.
And this is after latest update.

I have The Tonight Show Starring Jimmy Fallon where i have 75/359.
But if i open the show and select the 284 episodes and change them to ignored.
Nothing is updated on main page.
After restart the Downloads look correct.

So i would say there is an issue still.

Gonna grab some logs for ya in a moment.

**Comment by doczong** [comment]
@LauwS @neoatomic 

As an FYI, I restarted last night to try and clear the stuck front page, that did not work.

I even went so far as to nuke Alaska The Last Frontier (the one which was stuck snatched) from the database (using Mass Update/Remove) and then added it back.  When it got added back, it STILL showed the 199+1/200 on the front page, and the show page itself was fine.

So yeah, it looks like nuking the cache.mako is the only way to resolve that.

I don't think the restart this morning had anything to do with it unless there was another Mako patch distributed.

**Comment by LauwS** [comment]
![2](https://cloud.githubusercontent.com/assets/11090754/10909835/fed15b5c-823b-11e5-8891-0782ec03c547.png)
![1](https://cloud.githubusercontent.com/assets/11090754/10909834/fece49a8-823b-11e5-9eab-d798ef8ab141.png)
Now i changed them back to skipped, and main page shows only 75 episodes.

Can´t quite figure out how to attach my logfile, but a small snip is this:
2015-11-03 14:58:48 DEBUG    CHECKVERSION :: git fetch origin : returned successful
2015-11-03 14:58:48 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickrage
2015-11-03 14:58:48 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2015-11-03 14:58:48 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickrage
2015-11-03 14:58:49 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2015-11-03 14:58:49 DEBUG    CHECKVERSION :: cur_commit = 57b043be95f462fa39296de970e0070d6307455d, newest_commit = 57b043be95f462fa39296de970e0070d6307455d, num_commits_behind = 0, num_commits_ahead = 0
2015-11-03 14:58:49 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2015-11-03 14:58:49 DEBUG    MAIN :: Transaction with 2270 queries executed
2015-11-03 15:00:05 DEBUG    Thread-24 :: Attempting to set status on episode 2x173 to 5
2015-11-03 15:00:08 DEBUG    Thread-24 :: 270261: Loading episode details from DB for episode The Tonight Show Starring Jimmy Fallon S01E03
2015-11-03 15:00:09 DEBUG    Thread-24 :: Transaction with 284 queries executed

**Comment by neoatomic** [comment]
Let me reopen this for now. We have a hot-fix waiting to be pushed out for a date/time issue.
Got the feeling this might be related to that. 

https://github.com/SiCKRAGETV/SickRage/pull/3066

**Comment by LauwS** [comment]
@neoatomic Ossum :-) And yes i use SABnzbd.

**Comment by doczong** [comment]
In my case all from last nights pull to this mornings pull were downloaded via SABnzbd yes.

**Comment by neoatomic** [comment]
@doczong That looks more like you tried to manually PP the walking death? Otherwise i cant explain the 8 entry's. Sickrage did recognize the file otherwise it wouldn't be added to the history. 
Its hard to say without extensive logging and knowing your settings etc.
But if its a one time accordance than just ignore it.

(My install downloaded that same episode fine last night without any problems.)

**Comment by doczong** [comment]
@neoatomic nope... that was all automatic.  No manual intervention there.

I did not think anything of it until you mentioned there might be a SABnzbd issue.  That was snatched automatically as a Proper, and then marked as downloaded several times by SickRage.  Where SR processed it correctly... and it is marked as downloaded / processed and the proper is in fact sitting in my media library.

Yesterday morning (before auto-updating after a restart) was the only time I had seen this, and have not seen it since.

I would consider it a once off - perhaps already fixed.  I normally restart every day and it auto-pulls from GIT so at any given time I could be running some in between code that has fixes already in place.

**Comment by miigotu** [comment]
This is a caching issue. Ironing out stuff that was hidden when the mako cache was not working at all, which is not generated dynamically.

**Comment by LauwS** [comment]
This seems to have been fixed on my system now.
No idea if there has been an update since my last comment.
