### ISSUE TITLE
Send torrents to Synology DSM 6 Beta doesn't work

### ISSUE THREAD

**Issue by Rafkat** [SiCKRAGETV/sickrage-issues#3558]
SR Version: 	BRANCH: (master) / COMMIT: (78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc)
Python Version:	2.7.10 (default, Oct 15 2015, 15:13:32) [GCC 5.2.0]
OS: Alpine Linux 3.2.3

Error: DownloadStation Connection Error (Search Settings-Torrent Search)

It seems that Synology has changed something in DSM 6 Download Station so SickRage not able to connect any more.

Thank you.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@Rafkat For now just use the black hole method.

Could you check the Synology forums if anything has changed with download station.? 
That would help solving this. :)

**Comment by Rafkat** [comment]
@neoatomic Thx for the reply.
Yes, I will raise this issue with Synology and will post update here once I've got more details.

**Comment by abetancort** [comment]
@Rafkat It works but you have to remember to log at least once using DSM interface with the user you plan to use in SickRage and open Download Station. It seems that the scripts that fully enable the user in the Download Station are run when this one it's opened for the first time in DSM 6. 

It also drove me crazy... as it worked before and was not working now... Until by chance I decided to try changing the default folder for the downloads for that user in Download Station and it suddenly started working.

**Comment by Rafkat** [comment]
Thx @abetancort - this helped after logging out and logging in back into DSM. Though strange as I was already logged in before. Perhaps, cookies should've been updated...
