### ISSUE TITLE
One Piece anime / Kaerizaki-Fansub: ignored result / not a valid episode

### ISSUE THREAD

**Issue by massiliattak** [SiCKRAGETV/sickrage-issues#3562]
OS: Linux omv-vm 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux
Python version: 2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]
SR Version:	BRANCH: (master) / COMMIT: (78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc) 
GIT reset: done
Shutdown SickRage and remove the cache.db file: done

Hello,
I'm experiencing an issue with the automated/manual backlog search function for the One Piece show.
 I've set two required words (vostfr,10bits), but as you can see in the <a href="https://gist.github.com/massiliattak/2d52e67548be8c9fd718#file-sickrage-log-one-piece">sickrage.log</a>, when I start a manual backlog search, no release is found.
Well, in the debug log, it seems that somehow the episode is found but ignored:
"2015-11-04 15:50:41 DEBUG    SEARCHQUEUE-BACKLOG-81797 :: [T411] :: The result [Kaerizaki.Fansub].One.Piece.716.VOSTFR.Version.HD.10Bits doesn't seem to be a valid episode that we are trying to snatch, ignoring"

Well, the latest episode (716) with required words exists on the following websites:
- <a href="http://www.t411.in/torrents/search/?name=one+piece+vostfr+10bits&description=&file=&user=&cat=&search=%40name+one+piece+716+vostfr+10bits+&submit=Recherche">T411</a>
- <a href="http://www.nyaa.se/?page=search&cats=0_0&filter=0&term=one+piece+vostfr+10bits">NyaTorrents</a>
- <a href="https://kat.cr/usearch/one%20piece%20vostfr%2010bits/">KickassTorrents</a>

I've tried with and without required words, adding/removing Kaerizaki-Fansub in the whitelist from the Avalailable Groups section: same problem.

The problem doesn't exist in my other anime series (<a href="https://gist.github.com/massiliattak/2d52e67548be8c9fd718#file-sickrage-log-gintama">e.g. Gintama - see this log</a>).

It seems that the issue #2834 is in some way linked to this problem.

Thank you for you help.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by duramato** [comment]
@massiliattak debug log -.-

**Comment by massiliattak** [comment]
Sorry, log updated.

**Comment by miigotu** [comment]
Because there is no quality there that SR understands.

**Comment by miigotu** [comment]
At least it will match the show right now, and tell you about the quality.
