### ISSUE TITLE
Thousands of error messages: Unknown exception in getURL http://sickragetv.{...}/network_timezones.txt Error: 'Error -5 while decompressing data: incomplete or truncated stream'

### ISSUE THREAD

**Issue by doopeldedoo** [SiCKRAGETV/sickrage-issues#3579]
Sickrage has been slow for the last few days. It fails catching the network-timezones.txt and therefore spams the Warning log and slows my machine down:
https://monosnap.com/file/MMh1KGcclI1e6FT1izyIqC1UuiSVXI

EDIT: Here's more info: http://take.ms/cQvhw
http://take.ms/BiK2v

Origin Branch, Ubuntu 14.04 LTS

Here is one error message. They keep repeating in the thousands: 
http://pastebin.com/84d30fsE

Things I've tried:
-downloading the txt file manually
-setting the permissions

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by duramato** [comment]
what about giving more info?

**Comment by neoatomic** [comment]
@doopeldedoo Please follow the guidelines. https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md
We need more info.

**Comment by doopeldedoo** [comment]
Sorry. I updated my initial post.

**Comment by duramato** [comment]
@doopeldedoo what OS?

**Comment by doopeldedoo** [comment]
Ubuntu 14.04 LTS

**Comment by neoatomic** [comment]
Its a connection problem. Could be DNS/Proxy etc.
But first try to : Shutting down SickRage and removing the cache/mako & cache/sessions folders.

**Comment by miigotu** [comment]
@neoatomic no need to ever remove cache/mako anymore =P

**Comment by doopeldedoo** [comment]
It worked and fixed my problems. Thanks neoatomic!
