### ISSUE TITLE
"Sickbeard failed to post process. sickbeard did not respond"

### ISSUE THREAD

**Issue by wigwam12** [SiCKRAGETV/sickrage-issues#3582]
Appreciate some help please.
Switched to nzbtomedia for scripting as per advice bit I have yet to manage to get Sabnzbd to manage to do it.
After stepping through lots of tweaks I thought I had got everything right but tried new snatched and for each one I get the error as per title. The log of the error is below and I will also post up my nzbtomedia file in the hope for a solution please.
```
[01:29:21] [INFO]::MAIN: Loading config from [/volume1/@appstore/sickrage/var/SickRage/contrib/nzbToMedia/autoProcessMedia.cfg]
 [01:29:21] [INFO]::MAIN: Checking database structure...
 [01:29:21] [INFO]::MAIN: Checking if source needs an update
 /volume1/@appstore/sickrage/var/SickRage/contrib/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
 InsecureRequestWarning)
 [01:29:22] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
 [01:29:22] [INFO]::MAIN: nzbToMedia Version:10.12 Branch:master (Linux 3.10.35)
 [01:29:22] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
 [01:29:22] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
 [01:29:22] [ERROR]::MAIN: Failed to connect to Transmission
 [01:29:22] [INFO]::MAIN: #########################################################
 [01:29:22] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
 [01:29:22] [INFO]::MAIN: #########################################################
 [01:29:22] [INFO]::MAIN: Script triggered from SABnzbd
 [01:29:22] [ERROR]::MAIN: Unable to open URL
 [01:29:23] [INFO]::MAIN: Auto-detected SECTION:SickBeard
 [01:29:23] [INFO]::MAIN: Calling SickBeard:tv to post-process:(name of show).nzb
 [01:29:23] [ERROR]::SICKBEARD: Server did not respond. Exiting
 [01:29:23] [ERROR]::MAIN: A problem was reported in the /usr/local/sickrage/var/SickRage/contrib/nzbToMedia/nzbToSickBeard.py script.
 SickBeard: Failed to post-process - SickBeard did not respond.!
```
And my script:
```
[SickBeard]
 #### autoProcessing for TV Series
 #### tv - category that gets called for post-processing with SB
 [[tv]]
 enabled = 1
 host = Http://192.168.0.20
 port = 8899
 username = wigwam12
 password = ****
 ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
 web_root =
 ssl = 0
 fork = auto
 delete_failed = 0
 # Enable/Disable linking for Torrents
 Torrent_NoLink = 0
 process_method =
 # force processing of already processed content when running a manual scan.
 force = 0
 extract = 1
 nzbExtractionBy = Downloader
 # Set this to minimum required size to consider a media file valid (in MB)
 minSize = 0
 # Enable/Disable deleteing ignored files (samples and invalid media files)
 delete_ignored = 0
 ##### Enable if SickBeard is on a remote server for this category
 remote_path = 0
 ##### Set to path where download client places completed downloads locally for this category
 watch_dir = /volume1/Downloads/complete/tv
[Nzb]
 ###### clientAgent - Supported clients: sabnzbd, nzbget
 clientAgent = sabnzbd
 ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
 sabnzbd_host = http://192.168.0.20
 sabnzbd_port = 8080
 sabnzbd_apikey = API_Key
 sabnzbd_username= wigwam12
 sabnzbd_password= ****
 ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
 default_downloadDirectory = /volume1/Downloads/complete/tv
```

I have even changed the "fork" from auto to "sickrage" and it has made no difference whatsoever

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by wigwam12** [comment]
This is on a HP Gen8 microserver running Xpenology 5.2

**Comment by neoatomic** [comment]
Seems like you are using https.? Try to disable for testing.

(Probably need to change `ssl = 0` to `ssl = 1` ?)

**Comment by wigwam12** [comment]
I log into sickrage on http://192.168.0.20 ie not https.

**Comment by neoatomic** [comment]
Only clear error i see is `[01:29:22] [ERROR]::MAIN: Unable to open URL` So looks to be connection related.  Try'd localhost instead of ip.? 

Otherwise i'm out of ideas. Best to ask at the nzbtomedia Repo, they probbebly are able to troubleshoot this with you. : https://github.com/clinton-hall/nzbToMedia
