### ISSUE TITLE
DVD Rips getting named incorrectly using %SQN

### ISSUE THREAD

**Issue by Quiksmage** [SiCKRAGETV/sickrage-issues#3584]
BRANCH: (master) / COMMIT: (5f496885827bf88e4b24a4c94dc163dd016b2bca) 
Python Version:	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Windows Server 2012

Using a file named 
Show Title - S01E01 - Episode Title SD DVD x264.mkv

If I use 
Season %S [%QN]/%SN - S%0SE%0E - %EN [%QN]
I correctly get
Season 01 [SD DVD]\Show Title - S01E01 - Episode Title [SD DVD].mkv

if I use
Season %S [%SQN]/%SN - S%0SE%0E - %EN [%SQN]
I get
Season 01 []\Show Title - S01E01 - Episode Title [].mkv
when it should be
Season 01 [SD DVD x264]\Show Title - S01E01 - Episode Title [SD DVD x264].mkv

I wanted to use SQN so that I could specify encoding x264 h.264 xvid etc on my archive. It seems to work fine on my other qualities for the most part. I see some not getting the x264 etc on other rips, but I think the original file must have lacked it in its name.

Is this %SQN a new option for renaming?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
You cant put the quality in the folder name....

**Comment by Quiksmage** [comment]
I don't understand what you mean as I do so and have done so before. %SQN
in either file or folder case are not working for dvdrips.

**Comment by medariox** [comment]
@Quiksmage 
I actually didn't know you could use a FILE quality for a season folder name. Doesn't make that much sense to me, as you can have different episode qualities in one season and that would cause trouble (I guess). Wouldn't it try to create a new season folder, for all different episode qualities it finds?

Anyway, I'll try to solve this somehow. Can you please tell me an example naming you are trying to process (you can strip the real show name)?

**Comment by Quiksmage** [comment]
Yes, it does create a separate folder for each quality per season. This is
helpful for me when I'm looking visually of what I have in a season. For
instance, when there's 50+ episodes in a season and only a few are sdtv or
dvd, I can quickly see which ones are there. Again, it doesn't matter too
much, as I believe if the file naming is fixed, the folder naming will
start to work as well.

The sample file name I used at the beginning should work. Any file that
gets caught with the quality "SD DVD", which should be itself SD DVD,
DVDrip, etc, comes out with no quality in the file using %SQN. %QN works
fine.

Sample files
Show.name.s00.e01.title.x264.dvdrip.mkv
Show name s01e01 title h.264 SD DVD.mkv
Real Sample
Jekyll.S01E01.PAL.DVD.AC3.x264-h264iRMU

**Comment by medariox** [comment]
First of all, sorry for the late reply.

I quote myself from a previous post of mine, to explain what "scene naming pattern" actually is about:
> The naming pattern tries to map the file name to a scene complaint name. This means it tries to add the video resolution (e.g. 1080p), the video source (e.g. HDTV, DVDRip) and the encoder/codec, depending which one is required (e.g. hevc is not permitted in the name, so it will be mapped to h265). All this parameters together make the "scene quality" preset.

If you have a file with "SD DVD" in the name, it must have come from a BDRip/mux or DVDRip/mux - since the scene naming requires it to be either tagged as BDRip or DVDRip for standard definition DVD/BRD content, the file will be correctly tagged with either DVDRip or BDRip. What I can do is adding DVD as valid keyword for DVDRip, so e.g. if you have "Show Title - S01E01 - Episode Title SD DVD x264.mkv", you will get [DVDRip x264] as folder name. Same goes with BDRip. Does it sound good for you? I won't be adding tags like "SD DVD" or just "DVD" for SD content from disk, as it would break all the logic behind a naming pattern that aims to resemble scene naming.

As for the file named "Jekyll.S01E01.PAL.DVD.AC3.x264-h264iRMU", it gets incorrectly tagged as h264, because of the group name I suppose, I will also get that fixed asap. Thanks for reporting that!

**Comment by Quiksmage** [comment]
That sounds perfect to me. Thanks!!

**Comment by medariox** [comment]
Both things done here: https://github.com/SiCKRAGETV/SickRage/pull/3159

**Comment by Quiksmage** [comment]
Can you tell me what is specifically needed for %SQN to grab the encoding off of the file name?
Is a release group required?
Is spacing allowed?
I ask this because sometimes files are named incorrectly, and I need to rename them for them to be properly processed by sickrage.

I had a file named the following that wouldn't scrape the encoding/codec until I added a release group.

For instance,
flhd-dollhouses02e01.mkv
didn't properly process.

I renamed it to Dollhouse - S02E01 - Vows [1080p BluRay x264]
and it didn't pull the x264 from the post-process
I then renamed it to Dollhouse - S02E01 - Vows [1080p.Bluray.x264]
and it didn't work as well
Once I did the following, it worked
Dollhouse - S02E01 - Vows 1080p.BluRay.x264-FLHD

I guess, I'm trying to figure out what naming scheme is appropriate so that if I were to ever have to re-build my database, it could be retrieved from the file name.

I'm now using 
%SN - S%0SE%0E - %EN [%SQN] -%RG

If I were to delete my show and then re-add it, would it be able to correctly process this file name using %SQN? If not, what naming convention would I need to take if I didn't want to use periods in the file name?

**Comment by medariox** [comment]
@Quiksmage 
Yes, unfortunately you need a group in the file name to properly process it. This is a known bug that is not strictly related to %SQN. Of course you can use spaces, points, etc. Only one limitation: if you wish to re-add your files at some point, you will have to make sure that %RG is attached to the quality with "-", otherwise SR won't be able to recognize the group (another regex bug). In the end you can safely use this naming pattern:
```
%SN - S%0SE%0E - %EN [%SQN]-%RG
```
(note the removed space before -%RG, it's important!)

**Comment by Quiksmage** [comment]
Thanks for taking the time to clear that up for me. It is greatly appreciated. :)
