### ISSUE TITLE
[Develop] Can no longer start SickRage

### ISSUE THREAD

**Issue by NilsNojje** [SiCKRAGETV/sickrage-issues#3586]
It's been running great for long now, but today the UI was not responding correctly, so I rebooted my VM. After this SickRage no longer starts.

I've cleared cache and did a GIT reset, but no luck.

I've got it running in Ubuntu 14.04.3 LTS.
SickRage set to autoupdate, so I should be at the latest commit.

Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 555, in <module>
    SickRage().start()
  File "SickBeard.py", line 308, in start
    sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE)
  File "/opt/sickrage/lib/configobj.py", line 1219, in __init__
    self._load(infile, configspec)
  File "/opt/sickrage/lib/configobj.py", line 1302, in _load
    raise error
configobj.ParseError: Invalid line at line "830".

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
There seems to be an issue with the Develop branch currently. We are working on that...

**Comment by fernandog** [comment]
Merging without test. Too bad

**Comment by mrkake** [comment]
any news? rollback to last commit? revert the broken code? some info about what actually went wrong?

**Comment by fernandog** [comment]
Stop SR
git reset --hard HEAD~5
Start SR

**Comment by OmgImAlexis** [comment]
Closing this as you shouldn't be expecting any support while on develop. If you want a stable install then use master.

**Comment by NilsNojje** [comment]
@OmgImAlexis I'm on master, never said anything about devel.

**Comment by OmgImAlexis** [comment]
"[Develop] Can no longer start SickRage" <-- Title

**Comment by NilsNojje** [comment]
@OmgImAlexis I don't know what that title came from, but the original issue is .,.
I'm on master and I can't start SickRage any more.

I have done a GIT reset according to this guide -> https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ's-and-Fixes#update-problems-try-this

But it still doesn't work.
Sorry for the confusion, but I didn't include [Develop] in the title of my original post.

**Comment by neoatomic** [comment]
I added the develop to the title as its only effecting the Develop branch.

Just to be sure i did an fresh install of Master on Windows 10 and its running fine.: 
`SR Version:  BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b) `

**Comment by NilsNojje** [comment]
@neoatomic Ok, worked for me also.
It must have been a corrupt .db or something, because a fresh installe worked, but not if I restored the DB or settings.

**Comment by miigotu** [comment]
@NilsNojje did you try just restoring the db and not the config.ini ?

**Comment by NilsNojje** [comment]
@miigotu I did both at the same time and also both separate, but no go.
It took me a while now, but now everyting is set up the way it was before.
