### ISSUE TITLE
unrar issue OSX El Capitan

### ISSUE THREAD

**Issue by sirelewop14** [SiCKRAGETV/sickrage-issues#3594]
First off, thanks for all you guys do, this software is wonderful.

I recently upgraded my server from OSX10.10 to OSX10.11.1

SR Version:	BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b) 
SR User:	root
SR Locale:	(None, None)
SR Config:	/Applications/SickRage/config.ini
SR Database:	/Applications/SickRage/sickbeard.db
SR Cache Dir:	/Applications/SickRage/cache
SR Log Dir:	/Applications/SickRage/Logs
SR Arguments:	['-q']
Python Version:	2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]

After upgrading my SR started throwing errors about not being able to unrar files.

I have checked by $PATH
jeeves:rar rhys$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
jeeves:rar rhys$ 

I have uninstalled and reinstalled unrar several times, through pip and brew, and finally manually.

jeeves:rar rhys$ which unrar
/usr/local/bin/unrar
jeeves:rar rhys$ ls -l /usr/local/bin/unrar 
-rwxr-xr-x  1 rhys  admin  318380 Nov  8 19:19 /usr/local/bin/unrar
jeeves:rar rhys$ 

My SR is fully up to date, and unrar worked flawlessly before the upgrade. 

Hopefully I am not submitting this poorly or in the wrong section. 

Thanks in advance,
Rhys

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
SickRage is not ran as that user. The $PATH you are seeing as that user is different than the user SR runs as has.

Use the search function, this has been explained multiple times and has solutions. Just search all issues for el capitan

**Comment by sirelewop14** [comment]
Thanks for the feedback, after disabling the plist I used to launch SR, I was able to run it manually from the command line. SR then showed that it was ran as "rhys" my username instead of root. At that point the unrar began working again. So now, I just have to find a way to run SR as myself instead of root.

Thanks,
Rhys
