### ISSUE TITLE
All shows list empty columns misaligned.

### ISSUE THREAD

**Issue by danielmason30** [SiCKRAGETV/sickrage-issues#3595]
See version info at the end. Screen shot below been like this for at least a month:

![image](https://cloud.githubusercontent.com/assets/11175151/11024156/33e32d1c-8682-11e5-9f5d-5ca9adcedc73.png)

SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
SR User:	DAN$
SR Locale:	('en_GB', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]

---
OS: Windows 10.
Browser: Chrome Version 46.0.2490.80 m

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
ctrl+f5 or clear browser cache

**Comment by danielmason30** [comment]
Already tried this ..... why close and not wait for feedback?!

**Comment by duramato** [comment]
try and delete mako cache

**Comment by danielmason30** [comment]
Nope still getting same issue..

**Comment by miigotu** [comment]
@danielmason30 It doesnt need to be open to get feedback, thats why.

**Comment by OmgImAlexis** [comment]
This issue isn't present on the latest master, either you've got a mako cache issue or your browser has it. If it's still broken try opening SickRage in incognito mode on chrome. If it's still broken then you probably have a problem with the js file or mako files downloading incorrectly when you updated.
