### ISSUE TITLE
Zoneinfo can not be downloaded due to permissions

### ISSUE THREAD

**Issue by HyperBaton** [SiCKRAGETV/sickrage-issues#3617]
I run Sickrage under my own user, so not user 'sickrage'. Sickrage is installed under /opt/sickrage. Zoneinfo wants to be downloaded in this folder but of course the permissions do not allow this.

Log file entries:
````
2015-11-09 20:01:05 SHOWUPDATER :: Problem setting permissions or writing file to: /opt/sickrage/lib/dateutil/zoneinfo/zoneinfo-2015g.tmp
2015-11-09 20:01:05 SHOWUPDATER :: Download of /opt/sickrage/lib/dateutil/zoneinfo/zoneinfo-2015g.tmp failed.
````
Maybe this should be downloaded into the user folder to avoid the issue?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
That makes no sense? Why wouldn't you let SickRage have permission to write to it's own directory?

**Comment by HyperBaton** [comment]
If Sickrage were to run as 'sickrage' user, then yes, it would have permission. But Sickrage does not run as user 'sickrage', it runs as my main desktop user account. If it would run as 'sickrage', it wouldn't have access to my downloads and data. Sickrage stores its configuration and database under /home/<user>/.sickrage, so it seems like it would make sense to store any downloaded files there as well.

**Comment by OmgImAlexis** [comment]
Sickrage should be running as the user that owns the files of SICKRAGE... you're making no sense.
If it's installed in `/opt/sickrage/` then it should be able to read and write the anything within that directory including the `/opt/sickrage/lib/dateutil/zoneinfo/zoneinfo-2015g.tmp` file.

**Comment by HyperBaton** [comment]
It seems counterintuitive to me. Why have support for saving all configuration and database in custom folders in the first place then? An application like chrome installs into /opt as well, but it would never require you to run the application as the owner of those files.

**Comment by OmgImAlexis** [comment]
You're not making any sense. @miigotu try to explain it to them?

**Comment by miigotu** [comment]
Can just `chmod 777 /opt/sickrage/lib/dateutil/zoneinfo`
