### ISSUE TITLE
Missing flags in subtitles history

### ISSUE THREAD

**Issue by Heisenberg74** [SiCKRAGETV/sickrage-issues#386]
Hello team ;)

Here is my problem

- Branch : master
- Commit hash : 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
- Your operating system and python version : Last Sinology DSM version - Python version 2.7.8
- What you did : viewing history
- What happened : in the history, flags for downloaded subtitles, the flag image is not found. I think this problem is linked with the subtitle name because i unticked "Subtitles Multi-Language" option which remove the language "-fr" / "-en" in the subtitle name. 
- What you expected : correct flag displayed

Thank you for your great work !!!!

**Comment by fernandog** [comment]
@Heisenberg74 full logs, print screen?

**Comment by Heisenberg74** [comment]
![Uploading Capture_d’écran_2015-01-12_à_17_59_09.jpg . . .]()
![Uploading Capture_d’écran_2015-01-12_à_17_59_25.jpg . . .]()

**Comment by Heisenberg74** [comment]
![Uploading Capture_d’écran_2015-01-12_à_17_59_09.jpg . . .]()

**Comment by Heisenberg74** [comment]
![a](https://cloud.githubusercontent.com/assets/8171300/5706983/585865ca-9a85-11e4-87c3-11dd16ac1d66.jpg)
![b](https://cloud.githubusercontent.com/assets/8171300/5706985/5bcde798-9a85-11e4-897c-8d829b5c407c.jpg)

**Comment by Heisenberg74** [comment]
You can see on the first screenshot, i unstick "Subtitles Multi-Language".
I think the problem is because SickRage is looking for the last two letters in the subtitle file because when it's a LOL release, it displays : 
<img width="16" height="11" style="vertical-align:middle;" src="/images/flags/OL.png">

When it's a DIMENSION release :
<img width="16" height="11" style="vertical-align:middle;" src="/images/flags/ON.png">

**Comment by fernandog** [comment]
@Heisenberg74 what if you enable "Subtitles Multi-Language"?

**Comment by Heisenberg74** [comment]
If i enable "Subtitles Multi-Language" it works fine. Flags are correctly displayed and subtitles filename are ended with "-fr". But i don't want it append "-fr" at the end of the filename.

Thx

**Comment by fernandog** [comment]
There's no logic displaying subtitles:

<img width="16" height="11" style="vertical-align:middle;" src="$sbRoot/images/flags/<%= hItem["resource"][len(hItem["resource"])-6:len(hItem["resource"])-4]+'.png'%>">
https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/history.tmpl#L134

It does not check if "Subtitles Multi-Language" is enabled
Don't know if this info is available in the DB, otherwise it can't be fixed.

**Comment by fernandog** [comment]
@Tagforce do you know if PP store this variable too?

**Comment by TagForce** [comment]
@Heisenberg74 @fernandog Subtitle downloading is not a direct part of PP. It does check for a subtitle file in the completed downloads folder and copies that along with the videofile, I think. It should store the language of the subtitle file, if it can find one, in the subtitle field in the tv_episode table.

**Comment by TagForce** [comment]
@fernandog @Heisenberg74 
This is the problem: <%= hItem["resource"][len(hItem["resource"])-6:len(hItem["resource"])-4]+'.png'%>
It takes the resource name (which you see when you hover over the Action text (SUBTITLED), and tells it to take the part in between the length of the string -6 and the length of the string -4... Which in the case of not using language add-ons returns the last 2 characters before the extension.

So Gotham - S01E13 - Whatever it's name was.LOL.nl.srt would return everything starting from the N (6th from the end) to the character immediately preceding the '.' (4th letter from the end).
This works if you add the language to the filename. If you don't, then things mess up.
Gotham - S01E13 - Whatever its name was.LOL.srt would return everything from the 6th letter from the end to the 4th letter from the end, which would return OL.

The problem, however, is that I cannot think of a way to fix that without changing the db. That is something I will leave to @echel0n because the history table doesn't store the language code of the language that was downloaded. It only saves the filename of the resulting subtitle file. It could show the value that it finds in the tv_episode subtitle field, but it has no way of knowing which of the languages was downloaded at that time, causing it to possibly display false information.

This is something that was overlooked when the subtitle function was added.

**Comment by fernandog** [comment]
@TagForce we should wait develop/master stabilizes to make changes in the DB.

**Comment by TagForce** [comment]
@fernandog Yes, definitely. I'd rather not make changes to the DB myself. I'd rather let @echel0n fix this. He's changed the DB before, so he knows what to change and where (like the db version, etc). It's not a really big change, but still. We should wait for @echel0n te get back.

**Comment by fernandog** [comment]
@TagForce what if we get the first subtitle language from "Subtitle languages" settings and use it on the file to show the flag?
The premiss is the first language is the main language for subtitle. I don't see an user adding more than one language to the list

**Comment by TagForce** [comment]
@fernandog That introduces a rather big error margin. That solution would be a bandaid, at best. The point is that you CAN set more than one language, so it should handle that properly. I don't think the problem is urgent enough to warrant doing it this way. It doesn't break SR, nor is it impeding anyone. It's purely cosmetic, so I'd rather just wait and fix it the right way at once.

**Comment by neoatomic** [comment]
As those 2 issues are not mentioned here before. :

https://github.com/SiCKRAGETV/sickrage-issues/issues/88
https://github.com/SiCKRAGETV/sickrage-issues/issues/96

Looks to be related/same as this.

**Comment by TagForce** [comment]
@fernandog First one is the same issue.
Second one is seemingly unrelated (actual wrong flag being displayed)

**Comment by fernandog** [comment]
@Heisenberg74  develop updated. please test and report back

**Comment by Heisenberg74** [comment]
No, sadly :(

**Comment by fernandog** [comment]
@Heisenberg74 please read this:

https://github.com/SiCKRAGETV/sickrage-issues/issues/88#issuecomment-74513875

**Comment by Heisenberg74** [comment]
It's ok in Show view :-)  but not in the history :/

**Comment by TagForce** [comment]
@Heisenberg74 That is expected. The language code is not saved in the history database, so SR has no way of knowing which language the subs are in. The only way for it to know it is when you save them with the country code added.

For the history to work, we need to create a new field in the history table that saves the language of the downloaded subtitles. Until that happens, your history will show unknown (which is better than the empty or wrong flag it used to be).

**Comment by Heisenberg74** [comment]
OK, but in the history, SR doesn't show the unknown flag but OL.png for LOL release. :/

**Comment by abeloin** [comment]
@Heisenberg74 My guess is that you have multi language subtitle enabled
