### ISSUE TITLE
Backlog search ignoring "require/irgnore words"

### ISSUE THREAD

**Issue by WebBuddha** [SiCKRAGETV/sickrage-issues#397]
It seems that Sickrage is ignoring the "require/irgnore words" filter if the backlog search runs.
The daily search engine works like it should.
http://pastebin.com/z3vXHKDn

My ignore words: french,core2hd,dutch,swedish,reenc,MrLss,BRAVERY,DEMAND,SHORTBREHD,REWARD,DIMENSION
My reguired word: german

I'm using the master branch and the fork of cytec https://github.com/cytec/SickRage

Regards
WebBuddha

**Comment by CtrlAltDefeat94** [comment]
Let me get one thing straight.. You are asking for support on a fork this one has nothing to do with?
Wow, just wow..

I advise you post on their support page

**Comment by cytec** [comment]
doesn't make any difference which fork he is useing in this particular case.
even the original SickRage fork has the same problem. I just had a quick look and it seems like the function which is reasonable for accepting/denying releases based on ignore/required words (filter_release_name) is not called when running backlog searches. at least for multi ep results.

**Comment by fernandog** [comment]
@cytec can you try to fix it?

**Comment by CtrlAltDefeat94** [comment]
@cytec If I have a problem with my TV should I be asking about it on a forum dedicated to refrigerators? Because yeah.. It's gotta be fixed anyway so it doesn't matter, right?

I know it must be fixed, but that doesn't change the fact that this is the wrong place to report it.
If the issue is here as well and it gets fixed here, what would that be to @WebBuddha? As he doesn't use this fork, his issue will still not be resolved for him(unless you copy the commit to your fork).

Perhaps in this case it's good that it's reported here, but that's not always the case.

**Comment by fernandog** [comment]
@CtrlAltDefeat94 dev is away for a while. so let's wait. =)

**Comment by cytec** [comment]
@fernandog not really much time atm... if i get some spare time i'll definitively try to fix it

@CtrlAltDefeat94 yeah i'm with you on that, but in this case i told @WebBuddha to report it here, cause I currently don't have the time to look into it by myself and also thought others have the same problem too. so in my opinion it makes sense fixing it here and i merge the fix over ;)

or the other way around if i got some time :)
