### ISSUE TITLE
Force overwrite with mediaToSickBeard.py

### ISSUE THREAD

**Issue by Rouzax** [SiCKRAGETV/sickrage-issues#422]
If I download an episode with SickRage I import them with mediaToSickBeard.py and that works great.
The thing is when I retry a search for an episode sometime there is no other file like proper or internal and it will just redownload the same original episode.
When the downloads finishes and mediaToSickBeard.py is kicked off it will drop the episode because it is the same but form then on the episode in SickRage will have the status of Snatched.

Would it be possible to have a force overwrite option in the post processing?

**Comment by fernandog** [comment]
@Rouzax in develop branch this retry won't download the same file again. Otherwise if you set as wanted
There's no point downloading the same file again. If you manually search, you want a better quality or proper, right?

I don't see any advantages re-postprocess the same file/quality.

https://github.com/SiCKRAGETV/sickrage-issues/issues/206

**Comment by Rouzax** [comment]
It would make more sense not to download it again.
:smile:

**Comment by fernandog** [comment]
are you using the latest master o develop?

**Comment by Rouzax** [comment]
Master

**Comment by fernandog** [comment]
develop has fixed this. will close the issue.
