### ISSUE TITLE
Feature Request - Stop Deleting ".sync" Directory for BTSync

### ISSUE THREAD

**Issue by ryan-pederson** [SiCKRAGETV/sickrage-issues#429]
When SickRage finishes post-processing my directories, it deleted the ".sync" directory responsible for managing the details of the Bittorrent Sync partnership.
Soon after this folder is deleted, the BTSync partnership fails. "Cannot identify the destination folder."

Log:
2015-01-16 14:10:48 INFO     POSTPROCESSER :: Deleting folder: /share/MD0_DATA/Download/sickbeard/completed/.sync
2015-01-16 14:10:48 INFO     POSTPROCESSER :: Deleting folder: /share/MD0_DATA/Download/sickbeard/completed/.sync/Archive

BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 

This is all the information I could think to dig up. Let me know if anything else would help.

**Comment by heymoe** [comment]
Instead of having the developers of SR code a work around a one-off issue like this, a possible work around you can implement with your BTSync setup would be to sync the sickbeard directory instead. The completed directory will still get synced as a sub-directory of sickbeard and the .sync directory would exist in the sickbeard directory and not the completed directory thus not getting removed when stuff in the completed directory gets post-processed. If there are other sub-directories of the sickbeard directory or files that live in that directory you don't want to sync, you can add them to the BTSync's ignore list for that synced directory.

**Comment by ryan-pederson** [comment]
I will certainly try this workaround. It sounds like it should work well.
But, I'm still surprised that this issue seems unique to me.
I will report back with how well the workaround works.

**Comment by ryan-pederson** [comment]
Seems to be working fine. I appreciate the feedback.
