### ISSUE TITLE
postprocessing should ignore hidden folders

### ISSUE THREAD

**Issue by sukosevato** [SiCKRAGETV/sickrage-issues#554]
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)  (latest as of ticket creation date)
Python Version:	2.7.9 (default, Jan 8 2015, 21:47:19) [GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)]
Freebsd 10.1 jail. 

Sickrage is a bit too ambitious when looking at the "TV Download Dir" of Post-Processing. I have a script that uses Rsync to upload files to this folder so that sickrage can move them once the upload is completed. The way rsync works is by uploading to a hidden folder, so /incomingfolder/.Torrentname/.zGAkja/ and when it finishes uploading it renames it to the actual file name. All other applications ignore hidden folders as they should because the file is still being uploaded. But sickrage will see the folder, try to process it and then delete it thus interupting the rsync upload.

Could you make the post processing ignore hidden folders so that it doesn't interupt rsync uploads?

**Comment by TagForce** [comment]
I'll have a look if I can add this check to PP. Basically if folder is hidden, then just skip it.
Hopefully have some time to do this tonight. I'll make this option configurable, just in case someone doesn't want it to.

**Comment by fernandog** [comment]
thanks!

**Comment by TagForce** [comment]
@fernandog It already checks if a folder is hidden. If it is it should skip it.
I noticed 2 things:
1. It fails the check if a hidden folder is actually a folder, which causes it to return false (not hidden).
2. It only checks for a leading '.', so this check only works for linux derivatives.

I'm going to need some time, but I'll get that fixed so that it actually skips hidden folders.

**Comment by fernandog** [comment]
@Tagforce Thanks!

**Comment by TagForce** [comment]
@sukosevato @fernandog 
Ok, so this is turning out to be more of a nightmare than I thought.
Apparently there's no default way to get file attributes in Windows without using some kind of external module. I don't want to do that, because that would mean that Windows users would either be limited to PyWin32 (which has it included) or that users install the Win32api module from PyWin32 into their own Python setups.
Other option would be using ctypes library but that just crashes and returns -1 (false), so that doesn't work either.

I'm not done looking for an answer, but I'm starting to understand why SR only checks for leading '.''s now.

**Comment by fernandog** [comment]
Why dont you read the attrib using 
os.system('attrib foldername')

**Comment by fernandog** [comment]
```
>>> import os
>>> hidden=os.system("cd $PP_PATH &dir /a:h-a-s /b")
AppData
pip
>>>
```

**Comment by TagForce** [comment]
Because I don't want to run any commands outside of SR. This is always a security risk.
No matter how little of a security risk it is.

**Comment by fernandog** [comment]
I see.

**Comment by TagForce** [comment]
@sukosevato @fernandog 
Fixed it :)
I was being dense... It needs the full path to check for attributes, and I gave it the foldername only.

Please test https://github.com/SiCKRAGETV/SickRage/pull/1309 if you can. It should now always skip hidden folders, regardless of OS.

**Comment by fernandog** [comment]
Nice. Thanks!

**Comment by fernandog** [comment]
@sukosevato develop updated. please test and report back

**Comment by sukosevato** [comment]
I've checked out develop but have not been able to reproduce it yet. (It only happened infrequently) I will let it run for a while to see if I notice any other episodes being mangled. I still think it will be an issue however. Only if a file like "The.Walking.Dead.S05E10.720p.HDTV.x264-KILLERS.mkv" is being uploaded by rsync this fix will solve it. Since rsync would upload that as: ".The.Walking.Dead.S05E10.720p.HDTV.x264-KILLERS.mkv.2SD0e" leaving it hidden untill the entire .mkv is complete. However there are some other edge cases that I don't think are addressed so far.

If that file is inside a folder you would get the following with rsync:

"The.Walking.Dead.S05E10.720p.HDTV.x264-KILLERS/.The.Walking.Dead.S05E10.720p.HDTV.x264-KILLERS.mkv.2SD0e"

Sickrage would see the completed folder with nothing inside it (since it ignores the hidden incomplete file) and will decide to throw away the 'empty folder'? Are there any checks in place to prevent this from happening? Say not throwing away empty folders with hidden files in them?

Something along those lines would also prevent issues with uploads of files that are rarred into multiple files. For example if Rsync uploads the following:

The.Walking.Dead.S05E10.720p.HDTV.x264-KILLERS
-rw-------  1 root  921  39845888 Feb 16 17:05 .the.walking.dead.s05e10.720p.hdtv.x264-killers.r32.0Q6oDs
-rw-r--r--  1 root  921  50000000 Feb 16 05:00 the.walking.dead.s05e10.720p.hdtv.x264-killers.r31

The way I understand that sickrage currently works, it would still screw up uploads like this. It will ignore the single .rar file that has not been finished uploading yet because it starts with a dot and is hidden. But it will still try to process the folder or files in the folder because they are not hidden because rsync succesfully uploaded those individual files. Maybe add a check that prevents processing of folders if there are some files in there that are hidden?

Or I could also modify my upload script to upload to a different directory and have it run a 'mv' command after the upload completes so that it instantly appears in the watch folder of sickrage. That way sickrage never has to deal with partially complete files.

**Comment by TagForce** [comment]
@sukosevato SR currently does not check for hidden files. Only hidden folders.
I think I could add a check for hidden files inside or after the check for sync files when I change that to only skip that particular folder instead of completely stop PP.

I'll have to think about doing it that way. And we're currently concentrating on fixing bugs, rather than introduce new features, so it may take a little while for this to be completed.
