### ISSUE TITLE
Feature Request - Custom Torrent Client Destination Directory for every Show

### ISSUE THREAD

**Issue by seqastian** [SiCKRAGETV/sickrage-issues#558]
Flexget has this rather nice option to set a custom destination dir for every show.
path: /something/tv/{{series_name}}

That way you don't have to post process at all and save a ton of IO.
(if have a player that can handle rars or use rar2fs) 
And you can keep the torrents in the torrent client and manage(delete/reseed) them from there or via the torrent client API. 

All the big name torrent clients support this feature via their APIs. 

Example:
http://flexget.com/wiki/Plugins/transmission 
(the Flexget page is dead right now but Google has it cached)

PS.: They also have a ton of renaming after the torrent finished things. I don't really see any need for that myself.

**Comment by fernandog** [comment]
@TagForce what do you think? can PP be disabled with a feature like this? SR already have the directory

**Comment by TagForce** [comment]
@fernandog That means SR would need to rescan each show multiple times a day to determine what new eps there are. And fail because it can't deal with rarred files without unpacking them. PP is there so that SR can make sure that only files that we expect are put in the show dir. This won't eliminate the need for PP, it would just change the folder it happens in.

So, the idea is a good one, but I think it would not be used by enough people to justify the effort that needs to be put into it. It would require an almost complete rewrite of everything in SR that has anything to do with episode recognition or PP.

If someone wants to try, go ahead, but I don't think we should do this ourselves anytime soon.
