### ISSUE TITLE
How to set specific hour to start search?

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#6]
<a href="https://github.com/vzoltan"><img src="https://avatars.githubusercontent.com/u/2751780?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vzoltan](https://github.com/vzoltan)**
_Thursday Nov 20, 2014 at 10:09 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/922 (2 comment(s))_

----

Hi, i need a config where i can set, when to start the episod search every day. how can i set this?

like every day at 13:00 (01:00pm).

thank you

**Comment by TagForce** [comment]
There are 2 different search schedules.
One schedule is for actually searching episodes.
The other is for when SR updates its show information (ie, new episodes, aired status, etc).
I see no harm in having the time at which SR updates its show information configurable. A lot of people turn off their rigs for the night, so SR never updates show information (unless its set to do it at startup).

Being able to change the time at which it does this from 3am to something like 12pm would be a welcome addition. In fact, it will be beneficial to the providers as well, because EVERYBODY in a certain timezone will now update that information simultaneously, causing a lot of load on the providers for a little while. Having it configurable spreads the requests around.

I've created a PR that does that.
https://github.com/SiCKRAGETV/SickRage/pull/1286

**Comment by cwallen19803** [comment]
I use the Windows Task Scheduler to wake my machine from hibernation and reboot.  That starts everything, including SR.  If you configure SR to update when it starts, then you can control it that way, at least until it becomes a configurable item.

**Comment by fernandog** [comment]
@TagForce as soon you PR this, can you add this issue to it?

**Comment by abeloin** [comment]
Pull request merged in develop.

**Comment by fernandog** [comment]
@vzoltan please update and report back

**Comment by vzoltan** [comment]
Ok i will report back tomorrow

Thank you

**Comment by vzoltan** [comment]
i cant open config/general/ after update to develop

**Comment by abeloin** [comment]
What is the error message

**Comment by vzoltan** [comment]
Now updated from develop.zip (overwrite the files) and it started, i have the new option for 
"When to update shows" in general config / misc.

for today i have all my media downloaded, 
how can i test it right now (set the time for eg. 17 hours (here is 16:45) to see if it works or not?
if i change todays media to wanted, it will snach it immediately

**Comment by TagForce** [comment]
@vzoltan Change the time and restart SR. Schedules are set on startup.

**Comment by vzoltan** [comment]
Time is set to 17
But it snached an episode in the early morning.

Inwas expecting todays episode to be snached at or after 17 today.

**Comment by TagForce** [comment]
@vzoltan did you restart SR after changing the schedule?
BTW this change does not change when SR searches for episodes, just when it updates its show information with new episodes/epinfo/airdates etc.
Check your log for UPDATESHOW messages.

**Comment by vzoltan** [comment]
im lost in this, 
i stick to my cron to stop at midnight SR and start at noon SR.
that is what works for me as i like it to be.

**Comment by fernandog** [comment]
@vzoltan develop updated
