### ISSUE TITLE
Feature Request: Add two-step verification to GITHUB settings

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#630]
Branch: Master
Commit hash: SiCKRAGETV/SickRage@93f0f0ad1fa278afb17f73d47c099b82a766dede
OS: Ubuntu 14.04
Python: 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

Every time I get an error and try clicking the submit error button all that happens is the page refreshes, I've checked the logs and nothing about it comes up at all.

**Comment by fernandog** [comment]
did you enter your github user and password in SR settings? you must disable two-factor auth.

**Comment by OmgImAlexis** [comment]
I actually never noticed that setting, maybe there should be a alert message or something instead of just silently failing if you haven't entered your account details. Also I have 2-step and I really don't want to remove it. Should I mark this as closed?

**Comment by fernandog** [comment]
would mark as feature request to add warning and 2-step

**Comment by fernandog** [comment]
we should disable the button with javascript if the git user/pass are blank.

**Comment by Weggy** [comment]
I really want this feature to. I don't want to compromise the security of my NAS. Hope we get it soon :)

**Comment by abeloin** [comment]
@Weggy How can SR compromise your NAS security if you deactivate your GitHub 2-steps auth?

I would venture to guess you meant the security of your GitHub account, if not please provide the details.

**Comment by fernandog** [comment]
@Weggy @abeloin github needs to update its module. We can't do anything

**Comment by abeloin** [comment]
@fernandog That won't happen soon as the main guy is currently stepping down.

**Comment by fernandog** [comment]
Maybe someone like you appear there ! =)

**Comment by Weggy** [comment]
@abeloin If I need to disable 2-step auth in order to make SR function with Download Station. Then by doing the SR would be compromising my NAS security, as I'd need to make it less secure to make SR function.

I don't want to have to make the trade if possible. I think 2--step auth is a valid method of security and if SR could support it then it ideally should.

However I have no idea how easy or hard that would be.

**Comment by abeloin** [comment]
@Weggy This feature request as nothing to do with download station, we're talking about submitting issue(bug) to github via SR. I think you didn't understand the OP feature request.

The OP asked for 2 factor auth support when submitting issue to https://github.com/SiCKRAGETV/sickrage-issues via SR interface(submit error button). In order to submit on your behalf SR need to connect to github as you hence the need for credential. There is 2 way to connect to GitHub user/pass or user/pass/token. We currently support the first and later we will support the 2nd when the functionality is implemented in the upstream lib. 

If you are not comfortable providing your github user/pass to SR, then you will have to submit issue manually. This is hardly a security compromise.

**Comment by Thraxis** [comment]
There is nothing special that needs to be done to support 2-factor from github.  You can generate an Application Authentication Token to use in place of your password for sickrage to use.

https://github.com/settings/applications 

The permissions are very fine grained and you can revoke the token and see when it was last used at any time.

![image](https://cloud.githubusercontent.com/assets/1131905/7100920/999fdbf6-dff1-11e4-9978-f037fd924e72.png)

![image](https://cloud.githubusercontent.com/assets/1131905/7100925/a195e594-dff1-11e4-8d39-7e1325a769cc.png)

**Comment by neoatomic** [comment]
As Thraxis states a token can be generated as secure login.
