### ISSUE TITLE
Backlog: failed parsing AlphaRatio Traceback

### ISSUE THREAD

**Issue by DcR-NL** [SiCKRAGETV/sickrage-issues#654]
**Branch**
Develop

**Commit hash**
e0204d048e2cfdf6ba27ee6f0a2800b8e942a1f0

**Your operating system and python version**
Linux (Synology - x86) - Python 2.7.8 (default, Dec 12 2014, 21:20:40) [GCC 4.7.3 20130102 (prerelease)]

**What you did**
Force backlog search with (only) AlphaRatio enabled. Settings:
```[ALPHARATIO]
alpharatio = 1
alpharatio_username = MYUSERNAME
alpharatio_password = MYPASSWORD
alpharatio_ratio = 55
alpharatio_minseed = 1
alpharatio_minleech = 0
alpharatio_proxy = 0
alpharatio_proxy_url = http://proxite.eu/
alpharatio_search_mode = sponly
alpharatio_search_fallback = 1
alpharatio_enable_daily = 1
alpharatio_enable_backlog = 1
```

**What happened**
Failed parsing AlphaRatio Traceback:
http://pastebin.com/X76qLtXp

**What you expected**
No traceback (/error).

@BillNasty

**Comment by fernandog** [comment]
@BillNasty could you check please?

**Comment by BillNasty** [comment]
I'll take a look into it and see if i can figure out whats going on

**Comment by fernandog** [comment]
@BillNasty any lucky?

**Comment by BillNasty** [comment]
Haven't been able to reproduce the error on my end yet.  I'm currently having issues with my internet so I'm not getting much time to test yet.  I'll keep looking into it when I can

**Comment by DcR-NL** [comment]
OK, well, take your time. :) I'm no python hero, but I will try to debug this as well when I find the time (later today or tomorrow).

**Comment by BillNasty** [comment]
@DcR-NL What I've figured out so far is the issue is in the html parsing.  It seems like you may be getting a different torrent_table than I am.  In your AR profile settings do you have grouping turned on?

**Comment by DcR-NL** [comment]
@BillNasty Yes I have it enabled, I'm using the default AR settings. Quick screenshots while on the road: http://imgur.com/yuNzFrm

**Comment by BillNasty** [comment]
@DcR-NL  Those are the same settings as I'm using for mine so that shouldn't be the issue.  I've changed up the HTML parse a little bit hopefully fixing it and pushed the commit to [my repository](https://github.com/BillNasty/SickRage) in the branch provider AR fix.  I haven't spent much time on github and am unsure of the best way to send you the commit for testing

**Comment by DcR-NL** [comment]
@BillNasty I've looked at the current implementation and changing line 187 to 
```Python
link = cells[2].find('a', attrs={'title': 'Download'})
```
And line 192 to
```Python
link = cells[2].find('a', attrs={'title': 'Download'})
```
seems to fix it form me.

I will try and take a look at your new implementation.

**Comment by BillNasty** [comment]
That's how I had them set up when I first made the file.  There was a blank cell on the left of the table which just disappeared for me one day.  The problem is that now the seeder and leecher cell numbers will have to be adjusted too(lines 195&196).  My commit should work for both cases as its now searching the whole row rather than individual cells.  Let me know how it works for you

**Comment by DcR-NL** [comment]
@BillNasty You're right, your new implementation works great, good work and thank you! :)

**Comment by BillNasty** [comment]
No problem, thanks for the help with debugging the code

**Comment by abeloin** [comment]
@fernandog PR Merged

**Comment by fernandog** [comment]
please update and report back.

**Comment by DcR-NL** [comment]
:+1: Fixed in develop. Thanks again.
