### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/TV/Downloads/complete/about.a.boy.214.hdtv-lol.mp4'

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#659]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@e1ea0135441662fae914b7579aaa6485e6df806d
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@krash1220 Please provide a log. Thank You

**Comment by fernandog** [comment]
@abeloin is strange that the auto-submit didn't create a gist with the log.

**Comment by fernandog** [comment]
@TagForce is this happens when user select a bad directory at PP settings?

**Comment by TagForce** [comment]
@fernandog No, it should catch bad folders and give a descriptive message back, not an exception.
It can happen when a file is deleted while doing a PP run, so the file is in the file list of files to Post Process but is gone by the time it gets to it. I've seen a couple of instances where this happened because for some reason the files get deleted by SR before they're copied.

@krash1220 Can you provide a full log of the PP run, and tell us what your Post Process folders and Process settings are? I have a feeling this only happens when Process Method is 'copy'. No evidence to back that claim up yet, though.

**Comment by fernandog** [comment]
@TagForce LOL. yesterday my wife went to work (holiday) and I had to take care of the baby until 22:00 Couldn't do much.

**Comment by TagForce** [comment]
@fernandog Yours is a baby, mine is almost 3 and is set to go to bed in 15 minutes :)

**Comment by fernandog** [comment]
@TagForce is this a thread problem? the delete thread runs together with the move thread (slow copy)

**Comment by fernandog** [comment]
@krash1220 Can you provide a full log of the PP run

**Comment by krash1220** [comment]
sorry, it was a problem on my end.

**Comment by fernandog** [comment]
@krash1220 can I close issue?

**Comment by krash1220** [comment]
Yes

**Comment by fernandog** [comment]
@krash1220 can you tell the problem so others user can learn too?

**Comment by krash1220** [comment]
I deleted the file too soon even though it had already been processed.
