### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#728]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b2790f920e879714836f05053eff9f815d0867c7
### ERROR
```
FINDPROPERS :: [SceneAccess] :: Error while searching SceneAccess, skipping: error HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@fernandog @TagForce I think theses lines should be warning instead of error:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L481
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/properFinder.py#L90
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/tvcache.py#L136

As these will be retried later on.

**Comment by fernandog** [comment]
Url error codes (500, etc) should be warning. Pure exception dont know. Maybe ERROR.

**Comment by fernandog** [comment]
@ThePieMan it's just a timeout not a SR error
