### ISSUE TITLE
[APP SUBMITTED]: could not import gobject (could not find _PyGObject_API object)

### ISSUE THREAD

**Issue by danfreedom23** [SiCKRAGETV/sickrage-issues#733]
### INFO
Python Version: **2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1]**
Operating System: **Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.10-utopic**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/4a22f76938ab7f596bb3
### ERROR
```
POSTPROCESSER :: Unable to import pynotify. libnotify notifications won't work.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
ssh and run: 
sudo apt-get install python-notify

**Comment by 3flex** [comment]
@fernandog please reopen. I have this same issue and I have python-notify installed.

The issue was introduced by https://github.com/SiCKRAGETV/SickRage/commit/ef4470bd789da13878d1a8db328b08374f501f63

This is apparently because pynotify was written to use pygtk, but you can't mix the old pygtk method and the new gobject introspection together in a single application. http://askubuntu.com/a/156228
