### ISSUE TITLE
Loads of different errors while using nginx proxy

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#764]

**Comment by joq3** [comment]
Great, hope we can solve this together.
First off, i too get this error:
2015-02-25 12:32:16 Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
....

And with the same type of config for CouchPotato, I get this problem too http://i.imgur.com/Qdhbsy3.png
As soon as I access the webui with /couch instead of portno :5050 the images are gone. CouchPotato works fine, as SickRage does, when it comes to its function to download movies/series.
If i rightclick the missing image in CouchPotato and click open image in new tab, the image works great.
I think there is something missing in the redirect that keeps something from getting redirected.

**Comment by joq3** [comment]
This is my redirect:

<code>location /couch/ {
        proxy_pass http://localhost:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
}
</code>
Same thing for SickRage

**Comment by Hellowlol** [comment]
@joq3 Please note what settings you have set in sickrage regarding reverse proxy aswell

**Comment by joq3** [comment]
location /sick/ {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
}

It's the same settings, also set both SickRage and Couchpotato to Url Base /sick and /couch (in the webui settings)

**Comment by Hellowlol** [comment]
Well there are some option about reverse proxy headers etc in sickrage gui/ini file. I meant those.

**Comment by joq3** [comment]
@Hellowlol 
Do you mean this:

<script src="https://gist.github.com/joq3/d16d5802b42dbb4f91f6.js"></script>

**Comment by Hellowlol** [comment]
Yes, thank you.

**Comment by Hellowlol** [comment]
@joq3 I just remember that i have hidden everything behind a HTPC-Manger... But ill play around some tonight and see if i reproduce your issues

**Comment by abeloin** [comment]
Can you try this PR: SiCKRAGETV/SickRage#1419 ?

**Comment by OmgImAlexis** [comment]
Everything's been working for me since the merge of SiCKRAGETV/SickRage#1419.
