### ISSUE TITLE
Logs stop writing to log file

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#820]
BRANCH: (develop) / COMMIT: (68cd0fa18e3ae75a368728aeaaae7913caf13db4) 

I've been having this issue for a while and I'm not sure when it started because I only check the logs when I have a problem.  I go to view my logs and they are weeks behind.  I check the log file and it seems the sickrage just stopped writing to the log file.  I restart sickrage and it doesn't write to the log file.  I have to manually delete my log files and then it will start writing to them again.  I'm not even sure where to start to troubleshoot this.  I've uploaded the logs that were present when they froze last time but I don't see any indication of what caused the lock up.

https://drive.google.com/file/d/0B5289cPZgwEiSEFUMmZGWk1UNGs/view?usp=sharing
https://drive.google.com/file/d/0B5289cPZgwEiLS1hc21xWE0ybGc/view?usp=sharing

**Comment by abeloin** [comment]
That is usually an indication that a program other than sickrage is locking the log files so when it try to rotate the files it stop.

**Comment by copekyle** [comment]
That would make sense, any idea how to find which program is causing this? This is on a media server, so I have too many programs to just check each one individually. It's also happens randomly.

**Comment by copekyle** [comment]
This might also be an indicator, I get a random error that says " unable to update show, the show is already being updated"... Also random and never gives any indication of why it's throwing the error...

**Comment by abeloin** [comment]
In the console, you would see an error like this:
```
Logged from file views.py, line 1561
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
```

**Comment by abeloin** [comment]
Can you check the open handle on sickrage.log

Use one of the tools used in the q/a here http://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows

* Process explorer
* handle
* openfiles
* unlocker

**Comment by abeloin** [comment]
> unable to update show, the show is already being updated"

That simply mean, another thread is updating the data so don't update it.

**Comment by ripper1967** [comment]
Windows 8.1 pro
SR Version:  BRANCH: (develop) / COMMIT: (68cd0fa18e3ae75a368728aeaaae7913caf13db4)
2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]


I am also get  this error, http://pastebin.com/TPqpGgHJ ,do you have a recommendation to correct?

**Comment by fernandog** [comment]
@abeloin I think this happens when the 03:00AM update is running and SickRage try to rotate the log.

**Comment by ripper1967** [comment]
yes I am running windows,, no fernandog, it happens very random but usually  just restarting it can cause it ,because I believe it is doing a search and I try restart

**Comment by fernandog** [comment]
@ripper1967 do you have "update shows at startup" enabled?

**Comment by ripper1967** [comment]
yes both are enabled so I take it disable both?

**Comment by fernandog** [comment]
that's why! if you keep SR on 24/7 you can disable it. Because this does a massive update and it takes a long time! Imagine that you started SR at 23:00, the "update shows at startup" started to run. if finishes but at 03:00 another update will be started (SR don't need to update again)

@TagForce shouldn't we check the last time shows were updated and block if is less than 24 hours for example? Your new PR helps change the update hour but this "update shows at startup" can conflict with the scheduled update. Thoughts?

**Comment by ripper1967** [comment]
mine stays on 24/7 

 and yes I have a large collection
 312 Shows (241 Active) | 5851 (+33 snatched) / 10919 Episodes Downloaded | Daily Search: 5:59:47 | Backlog Search: 3/8/2015

**Comment by ripper1967** [comment]
and yes that did fix the error I was having..

**Comment by fernandog** [comment]
Wasnt an error. But a configuration setting

**Comment by ripper1967** [comment]
True, thanks again.

**Comment by copekyle** [comment]
I'm using Windows also... I'll disable both of those and see what happens. Thanks

**Comment by fernandog** [comment]
@abeloin @TagForce  we still need to figure out how to not rotate log when another thread is pushing data to it (maybe windows only)

**Comment by TagForce** [comment]
@fernandog Nothing we can do about that, really... Logging is handled by the Python Logging module.
It does have issues on Windows, it seems.

@copekyle @ripper1967 Have you guys enabled debug logging in the config.ini?
Can you disable it if you have?

**Comment by copekyle** [comment]
@TagForce I do not have debug logging enabled.  I also have disabled both daily and backlog search on startup.  

It makes sense that the processes were running over each other because my log was always "frozen" at times between 3am and 3:30am.  I was going crazy looking for any outside processes that started around those times that would "lock" the log file (i.e. virus scan) but could not find anything.  I'll see how things go now that I have all my settings correct for a 24/7 machine.

**Comment by TagForce** [comment]
@copekyle Disabling those settings is a workout (that will work, most likely). The underlying problem is within Python itself. Even if the processes are running over eachother (which they shouldn't by the way, I'll have to look into that, if there's a show-update running it shouldn't start another one), it still should be able to rotate the logs just fine. Something in the logging module in Python is messing up on Windows. If you google the error message, there's tons of people that have this problem on a lot of different programs.

**Comment by bitzorro** [comment]
@fernandog 
Changing these settings doesnt help! Ive had the same prolem since around christmas. The only thing that makes logs running is a clean install of SickRage, but the logs will stop again!

**Comment by copekyle** [comment]
@bitzorro  A Clean install?  Shoot, I'm glad that my problem wasn't as bad as yours.  I found that I could shutdown sickrage and just delete the existing log files and things would start working again.  If I had to do clean installs every time I wanted to see my logs, I would have probably given up on the logs by now!

**Comment by bitzorro** [comment]
@fernandog 
originally i installed python for running PlexConnect and now i allso use it for sickrage, can there be a connflict there maybe?

**Comment by fernandog** [comment]
When you restart SR, the update stops and you can have outdate show information for example an aired episode showing as unaired

**Comment by copekyle** [comment]
@fernandog You are answering all of the weird problems I've been having that I just accepted as a part of SickRage.  I didn't bother to ask because they were so small.  Now I'm finding out that it was all related.

**Comment by bitzorro** [comment]
@copekyle 
i may have done that allso, cant really remember.
i have made 3 different clean installs since december for some different reasons and the logs allways have stoped after a couple of days.

**Comment by TagForce** [comment]
@bitzorro What you can try is to set Number of Logfiles to 0. This should effectively disable logrotation. I haven't tested this, but it appears that the logging problems occurs when it wants to rotate the logfile, and then can't because it doesn't handle it properly on windows.
Setting Logfiles to 0 should simply change it so that the logfile is deleted instead of moved to a different name.

**Comment by fernandog** [comment]
@bitzorro or set to 1 and set to a very large size

**Comment by bitzorro** [comment]
@fernandog @TagForce @copekyle 
ive just set it to 0 and the logs started writing again. 
I will try to set  it to 1 later.

**Comment by abeloin** [comment]
@bitzorro Leave it to 0, from python doc:
>  if either of maxBytes or backupCount is zero, rollover never occurs.

Ref: https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/743

**Comment by mmazur519** [comment]
Mine on windows just seems to lose some of the detail. I could find the error that was thrown in the log but when I went back to investigate what was throwing the error. Even on ubuntu if SR is pushing a large amount of data to log file which mine was when it went to rotate I lost about 4 minutes of Data. Not a big issue most of the time because if it is an error in the code and not just a blip in processing it will occur again and usually with the same file. But I am going to try some of the stuff listed here and see if I can keep more Data in the log file.

**Comment by fernandog** [comment]
can you post both logs ? rotated and the new one ? - pastebin please

**Comment by fernandog** [comment]
@mmazur519 please reply
