### ISSUE TITLE
Post Processing Failing to take into account scene exception downloads

### ISSUE THREAD

**Issue by mmazur519** [SiCKRAGETV/sickrage-issues#864]
Branch: Master

The exception is for Brandi and Jarrod but show is listed as Brandi & Jarrod
```
2015-03-05 16:47:46 DEBUG    POSTPROCESSER :: Parsed Brandi.and.Jarrod-Married.to.the.Job.S01E07.Gumball.Empire.HDTV.x264-W4F into Brandi and Jarrod-Married to the Job - S1E7 [ANIME VER: -1] [GROUP: W4F] [ABD: False] [ANIME: False] [whichReg: ['standard']]
```

**Comment by fernandog** [comment]
what is the error?!

**Comment by TagForce** [comment]
@mmazur519 Post Processing indeed does not use scene exceptions as the method for getting the show is completely reversed from searching from downloads.
When you download a show, you only have a showname, season and episode number to get the files you need. This means that SR can only search using the showname. However, filenames may be (slightly) different to what SR thinks the show name is. That's where scene exceptions come in.

When Post Processing, SR has a filename, and it can parse a showname from that. That showname is looked up in the cache, and if it doesn't find it there, it will look for it on thetvdb and tvrage. It then gets a list of possible shows back, and will match the show IDs for those shows to a show that's in your database. If it finds a match it will then use that show for Post Processing.

The chances of matching a show in Post Processing are much higher (in the range of 99+%) than matching a show in downloads. Of course, if it fails to find a show either way, we could still look up all the scene exceptions in the database as a fallback method. However, that usually is not needed, which is why it's not implemented.

Getting back to your issue: I fail to see where it goes wrong. Brandi and Jarrod or Brandi & Jarrod should both match a show on the indexers. I think it may fail because it believes the showname is Brandi and Jarrod-Married to the Job, which may indeed fail, but scene exceptions won't fix that. Every episode name will be different, so that's impossible to catch.

**Comment by TagForce** [comment]
I've decided to include scene exceptions in the post processing run. If it fails to get a show from the cache or from an indexer, it will try to look it up in the scene exceptions last.

https://github.com/SiCKRAGETV/SickRage/pull/1494

**Comment by mmazur519** [comment]
The issue in the end is likely the tvdb or SickRage because at times whenadding shows ddepending on how written may or may not send results.  Yesterday secrets and lies would only show  UK in results had to specifically enter (us)  to get upcoming us version of show from tvdb.  So not sure if short coming in Sr code or tvdb.
