### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by markfaine** [SiCKRAGETV/sickrage-issues#866]
Develop Branch
88e1f2e65adf1946b7f8fffc0c2532aa44ea7d64
Synology DSM 5, Python 2.7.8-11

I'm seeing poor performance.  Page loads are very slow.  I've tried both branches.  Of course, today as I finally get around to compiling the information and submitting an issue, it works much faster, but it's still slow, just not as slow as most days.  Disabled HTTPS because it's so slow as to be unusable with it enabled.

http://pastebin.com/tsdMs6dA

**Comment by neoatomic** [comment]
All runs fine on my Synology, actually its running faster and more stable then ever before.
So this must be a local problem with your Synology. Check your settings and otherwise reinstall Sickrage. 
Also best to switch to Master as there will be some major code changes that could make Develop unstable.

**Comment by fernandog** [comment]
On running on a raspebberry pi (512 ram). Fast loading
