### ISSUE TITLE
Name parsing problem: prioritize normal regex instead of anime

### ISSUE THREAD

**Issue by grrr2** [SiCKRAGETV/sickrage-issues#946]
SR Version: 	BRANCH: (master) / COMMIT: (2b9adc3324c9985e77fc3204e2693e3ab08a744e) 
Python 2.7.9 (default, Jan 28 2015, 05:37:45)
[GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)] on freebsd10

Hi,

A possible bug or misbehavior ( not necessarily due to Sickrage) I came across.

Got a torrent file name "Showname.2000.S01.Season.1.Complete.1080p.WEB-DL.x264-[release-group]". It matches against season_only and  anime_codec_crc regexp as well.

Season_only is parsed in to:
series_name	`Showname.2000`
season_num	`06`
extra_info		`Season.1.Complete.1080p.WEB-DL.x264`
release_group	`[release-group]`

Anime_codec_crc is parsed in to:
series_name	`Showname`
ep_ab_num	`200`
codec	`release-group`

Due to season_only starting from score -8 ending -4, and anime_codec_crc starting from -6 ending -3 the latter is selected as best parse result. Which is wrong primarily to me because season number info is missing (and secondly because it is not an anime), that resulting incorrect setup of download path (ie. Showname\Season will fail).

Thanks

**Comment by TagForce** [comment]
@grrr2 I noticed the same thing for some releases... I'll see if I can add a check when looking for the best result and simply remove any match on anime regexes when the show it parsed is not anime, so it will simply return the first non-anime regex result that comes out as best.

**Comment by fernandog** [comment]
@TagForce should we post pone this to next milestone?

**Comment by TagForce** [comment]
@fernandog Yeah, I'll have this done after the weekend, so won't make it for sunday's merge.

**Comment by fernandog** [comment]
@TagForce but regex for anime are separate from normal regex isn't?

I think we only use anime regex IF the show is set as anime, otherwise only use normal regex

normal
https://github.com/abeloin/SickRage/blob/develop/sickbeard/name_parser/regexes.py#L21
anime
https://github.com/abeloin/SickRage/blob/develop/sickbeard/name_parser/regexes.py#L200

**Comment by TagForce** [comment]
@fernandog No, when it says "using ALL regexes" in the log... It's using ALL regexes...
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/name_parser/parser.py#L107

The problem is that NameParser gets called to figure out the show, season, and episode we're post processing... But NameParser can only use anime only or normal only regexes if it already knows what show it is (which we don't since we're trying to figure that out by calling nameparser).

So, on searching we know which show we're searching, so we can check if show.is_anime is true...
On Post Processing we have no clue what show a file is for, so we need to use all regexes to get the showname and therefor the show.

It's basically the same problem we faced when implementing scene_exceptions on Post Processing... When searching we have a show, and we want to find the most results so we try different shownames (scene exceptions). On Post Processing we only have a filename to go on, so we don't know what scene_exceptions to use. Which is why the Post Processing scene exceptions simply queries the database to get the indexerID for the scene_exception that is in the name. (Searching and PP have the information provided in reverse. show, season, episode -> filename versus filename -> show, season, episode)

**Comment by fernandog** [comment]
@TagForce why don't we compare the filename with HISTORY (nzb filename or torrentname) first ?

**Comment by TagForce** [comment]
@fernandog Which history? NZB or torrentnames may not be the same as the resulting filenames...
And what if you download a season pack? 1 torrent filename contains 20+ videofiles...

**Comment by fernandog** [comment]
@TagForce I see. Sorry

**Comment by grrr2** [comment]
Hi,

What if checking databade if we have any anime series at all? If not just use normal regexp. Or globally allow/disallow anime parsing. There's already a page for anime support db, that variable can be used to control if anime parsing may be a valid choice.

**Comment by TagForce** [comment]
@fernandog Why are you sorry? You're thinking with me, which is greatly appreciated. :)

https://github.com/TagForce/SickRage/commit/d50f365a256519e4f9bbfa02274c4e6aa79783f6 should simply check if the bestResult returned was actually gotten from the correct set of regexes.

This is completely untested... Not even sure if all the variables are accessible at that point. But it shows what I'm trying to accomplish.

**Comment by fernandog** [comment]
@grrr2 nice ideia IMO! Not all users uses anime! =)

**Comment by TagForce** [comment]
@grrr2 @fernandog We could do that, but that won't help those that have anime and non-anime shows... I think.

**Comment by grrr2** [comment]
Sure but this how it works now. Not ideal i admit but at least if user surely not seeing anime it will work correctly.

**Comment by fernandog** [comment]
@TagForce we can't do both. check if there is any anime, if don't we uses the best non-anime regex as you said

**Comment by fernandog** [comment]
@TagForce any update on this?

**Comment by TagForce** [comment]
@fernandog Right now, I have it so that it will only accept a bestResult if it finds a show, and that show is an anime found with anime regex, or not anime with a normal regex... However, if it doesn't find a show, it just keeps throwing away bestResults... Need to fix that, then it's ready for testing/merging.

**Comment by fernandog** [comment]
@TagForce keep current milestone or move to next one?

**Comment by fernandog** [comment]
@TagForce any news on this one? thanks!

**Comment by fernandog** [comment]
@TagForce any news on this one? thanks!

**Comment by TagForce** [comment]
@fernandog No, it's not quite working as I expected... I'll need to work around some things so that it will at least return a valid value.
