### ISSUE TITLE
[Feature Request] Add min/max size for episodes downloads

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#95]
<a href="https://github.com/BenjV"><img src="https://avatars.githubusercontent.com/u/7405528?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BenjV](https://github.com/BenjV)**
_Sunday Dec 14, 2014 at 10:22 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/1133 (1 comment(s))_

----

Lately I got a lot of torrentg videos with only a audio stream in the .mkv
It would be a nice feature to be able to set a minimum size(in Kbytes) as search criteria for downloading.

**Comment by alaorath** [comment]
I would also like to see this feature added!  Although my vision was slightly different.... more like how CouchPotato allows you to tune the quality/size settings.

I envisioned an additional size setting as part of the per show quality option.  For example, I could set 720P and >800mb for a one hour show.
Understanding that magnets may not include size information, this value would be used during post-processing, and the episode would be left as "wanted" (and somehow flag that provider/magnet as "bad") so that it tries the next provider in the list on the next scan.  

For now I've re-ordered my providers in hopes of weeding out the handful of tiny 720p (175meg for a 1hour show?! wtf) rips which are terribly lossy, pixelated, and don't play on my TV due to super high encoding rate.

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
