### ISSUE TITLE
[Feature Request] Search by episode name only

### ISSUE THREAD

**Issue by MrsAngelD** [SiCKRAGETV/sickrage-issues#965]
This specifically refers to things like National Geographic documentary's which are not released with either an air by date or episode number, but instead by episode name. Would it be possible to get the option to search by episode name in scene exception?

Thanks,
Angel

**Comment by fernandog** [comment]
@MrsAngelD can you post some examples?

**Comment by MrsAngelD** [comment]
Examples of what exactly? The TVDB lists each episode of Nation Geographic documentarys by season (ie 2015x8) however episodes are being released without these they are instead released by the name of the episode.

For example the first episode of National Geographic Documentaries for the most recent season is listed on tvdb as

Season: 2015
Episode: 01
Title: The Raising of The Costa Concordia 

However a search for National Geographic Documentaries s2015e01 won't return any results because the episodes aren't being released with season/episode numbers. Instead in order to find the episode you have to search for the title in this case it would be "The Raising of The Costa Concordia" Which sickrage does not do. Therefor in order to get episodes I have to manually search for them by name, else no results are ever returned.

**Comment by SeNtReX** [comment]
Exactly same issue. 
Every week I need to download BBC's Horizon series manually, if there would be an option in the show settings to use episode title as search string instead of numbering it would fix it. Would love to contribute but i am unable to program :(

Examples:
BBC Horizon 2014 Inside the Dark Web 720p x264
BBC Horizon 2014 Man on Mars Mission to the Red Planet 720p x264
BBC Horizon 2015 Are Video Games Really That Bad 720p HDTV x264 AAC mkv
etc

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
