### ISSUE TITLE
Odd logging hiccups

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#974]
Python Version: 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
Operating System: Windows-7-6.1.7601-SP1
Branch: master
Commit: SiCKRAGETV/SickRage@3b399f1

Though the error logging appears to work just fine no matter what, the main logs (DB / Debug / etc.) appear to stop logging after an update is processed.  That means when I've updated and then have an error thrown, I can't get any more then the most basic one-liner detail about what's happened, because the primary logs have stopped rolling through hours (or days) beforehand.

The situation is resolved when SR is fully Shut Down and restarted.  It is not resolved if SR is just Restarted.

**Comment by fernandog** [comment]
@ThePieMan send all logs you have so we can confirm the hiccpups

**Comment by TagForce** [comment]
@ThePieMan Please update to the latest master... A fix for logfiles not rotating on Windows properly when restarting SR has been pushed to it. The problem is that SR would keep the logfile open when restarting, and closing the old instance after starting a new instance would keep an exclusive lock on the file open, causing it to not be able to be renamed/deleted. This would cause logrotation to fail, and as a result logging to be throwing errors on the console (error 32: file already in use by a different program). The fix will shutdown logging at the last possible moment before either starting the new instance, or exiting to the system. This was tested on Windows and Linux machines, and the exclusive lock will now be freed properly and logrotation will work.

**Comment by fernandog** [comment]
@ThePieMan please report if error still happens after last yesterday update

**Comment by ThePieMan** [comment]
I was wondering if something had changed, because I've been monitoring after all those updates that were pushed yesterday, and the problem has not duplicated itself. Closing the issue. I'll revisit if I see it happening again. Thanks @fernandog

**Comment by fernandog** [comment]
@ThePieMan, thank @TagForce ! he did the fix!
